### ISSUE TITLE
Daily updates of Zammad OS packages

### ISSUE THREAD

**Issue by MDXDave** [zammad/zammad#1000]
I am using zammad on Debian using the stable packager repository. Why there are so many -
nearly daily - updates? 

Normally, stable packages will be updated not more than once per week - except there are security fixes.

**Comment by martini** [comment]
Hi @MDXDave 

congratulation to issue #1000 ! 👍 

For packaging we use http://packager.io which is a service to build os independent packages with application dependencies included. By the way, many thanks to the people of packager.io, it's a fantastic service!

The service allows to build a release on every commit, this means if a bugfix has been pushed to stable a new version will be build automatically after ci pipeline was successful (currently we have about 70 ci jobs including parallel testing with 32 concurrent browser instance - it takes about 45 minutes to get whole Zammad tested).

So the advantage is to deliver fixes short time after the fix is pushed & tested.

In the beginning I was suspect to me, but after 6 months I (and also issue reporters) really love to get a fast deployment of tested fixes within hours.

However, any feedback is welcome!

 -Martin

**Comment by martini** [comment]
Just reopen on feedback.
