### ISSUE TITLE
Let's Encrypt not working due to 404 creation by Zammad

### ISSUE THREAD

**Issue by Hildi1978** [zammad/zammad#1024]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: apg-get package
* Operating system: Ubuntu 16.04
* Browser + version: any

### Expected behavior:

After having installed Let's Encrypt, certificate requests are being processed by generating content in a folder /.well-known which is checked for existence by the issuing certificate authority. The CA can access the subfolder with the request token and delivers the certificate

### Actual behavior:

when calling websites unknown to Zammad, the system generates a generic 404 error. The Lets Encrypt CA cannot access the token and the cert request fails

### Steps to reproduce the behavior:

install LE and try to request a certificate

I know that from the security perspective, this is expected behavior. So maybe a feature request could be made to habe an option to allow the usage of Lets Encrypt which allows access to the /.well-known url?

Regards 

Jens

**Comment by MartinBorg** [comment]
I'm using zammad with letsencrypt on Debian without problems. IMHO, zammad should not provide any functions for letsencrypt, because this is not necessary. Either your frontend web server, such as nginx, handles this for you, or you run letsencrypt in standalone mode (i.e. shutting down nginx for the cert update). If you do not yet run nginx (or Apache or whatever) in front of zammad, please do so now! :~)

**Comment by martini** [comment]
I agree with @MartinBorg letsencrypt (at least all https config) is part of nginx/apache. It's not a topic here to discuss.
