### ISSUE TITLE
notification messages bounce on tickets if email address belonging to agent account does not exist

### ISSUE THREAD

**Issue by markum** [zammad/zammad#1026]
### Infos:

* Used Zammad version: Version 1.4.x

One of our admins created an agent account for an email address that did not exist. This lead to a bounces loop between the notification-email-address and the not existing email address on the ticket. So for every new notification the agent received a new bounce loop was created. Luckily we noticed this early but were able to fix it by creating that email address which did not exist in the beginning.

To avoid this upon account creation a user email address should be verified before coming active or at least before sending out further emails. But there could be also a scenario where an agent email address could be deleted at a later because we does not work for the company anymore and it is forgotten to delete the agent account. Either way bounces of an agent account should not create an entry on the ticket, they should create a notification on the admin accounts and after say three or five bounces the email notifications of an agent account should be turned of. Further there should be also a scenario if email notifications of an admin bounce.

**Comment by rolfschmidt** [comment]
Hi @markum ,
looks like @martini already fixed your issue in develop. He added some code to prevent bouncing to invalid user email addresses by blocking them for 2 months if the address is not reachable.

https://github.com/zammad/zammad/commit/48e3da57ee06227c9b57f96a5afb56f132325aa1

Should be fixed in develop.

Best regards,
Rolf
