### ISSUE TITLE
LDAP - Import certain groups

### ISSUE THREAD

**Issue by maysv** [zammad/zammad#1068]
Hello,

first of all - good job - the design looks very nice! :)

I have a question about the LDAP integration.

I don't want to integrate the whole AD, only two groups (users and admins) is it possible that I can make that work? Is there a way to configure that?

Greetings

**Comment by thorsteneckel** [comment]
Hi @maysv - Thanks for the feedback ☺️

With the latest stable version (since today 🤡) you can! Just configure as:

<img width="801" alt="bildschirmfoto 2017-05-10 um 14 47 28" src="https://cloud.githubusercontent.com/assets/3873515/25899310/acc76fdc-358f-11e7-81fd-4e8e339fb0ad.png">

This means that only users get synced that have an assignment to the configured roles. Users without a matching assignment are skipped and won't get imported.

🚀

**Comment by maysv** [comment]
Hello @thorsteneckel,

thx for the quick response. Can I still update my version (1.5.x) now? Or must I just wait for it?
Because I don't have the "Expert" config

**Comment by thorsteneckel** [comment]
Yes! Just update your zammad package via your OS package manager to the latest version (4 hours ago): https://packager.io/gh/zammad/zammad#stable

**Comment by maysv** [comment]
Got it! Thank you! 😃 🚀

**Comment by maysv** [comment]
The update works - Now I have another problem. In our AD we have a piece of users with two accounts.
for example max.mustermann and admin.max.mustermann - both have the same mailaddress - only one user has been imported. I thought when I change the mailadress at the admin user - both user were imported, but it's only one of them. Have you any idea how I can fix that? Thx

**Comment by thorsteneckel** [comment]
Hi @maysv - since this is (as you stated) another problem please create a new issue for this. Thanks!

**Comment by maysv** [comment]
=> new issue
https://github.com/zammad/zammad/issues/1069
