### ISSUE TITLE
Time accounting not tracked for agents and not showing on dashboard

### ISSUE THREAD

**Issue by sthag** [zammad/zammad#1071]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: deb package
* Operating system: Ubuntu 16.04
* Browser + version: Firefox 52.0.2 (32bit)

### Expected behavior:

* Time is measured for every agent working on a ticket.
* could be displayed as total time and specific agent time if multiple agents are working on the same ticket
* Time accounting in admin section shows times for agents in overview (export)
* ticket section in overview shows all agents which worked on a ticket

* dashboard displays time in the corresponding box

```
∅ Waiting time today
My handling time: 0 minutes
Average: 0 minutes
```

### Actual behavior:

* time is measured per ticket, I guess
* if the ticket owner changes the new time is added up to the current ticket time
* there is no differentiation between agents
* only the first owner of a ticket is shown in time accounting overview
* there is no way to show/get specific agent times?!

* the dashboard doesn't show any time progress in the stopwatch section

### Steps to reproduce the behavior:

* work on tickets and measure the time
* switch ownership of the tickets

I think it could be a feature, to be able to measure actual working times for agents and not only tickets or customers.

**Comment by sthag** [comment]
I also noted that the time is not always recorded. The dialog asking for a time value is missing sometimes. Even if the ticket is changed from an open state and an agent is assigned to it.

**Comment by sthag** [comment]
I want to report further on the time topic.

We have many tickets which do not necessarily get info from customers in the process of solving.
During the processing of tickets we noticed that the time is not always asked for.
That's why we started to stop making internal notes on the tickets and except only make phone notes so that the system thinks there was a real contact.
However the time is not captured on every ticket.

Maybe there is a possibility to have the time dialog on a dedicated button to always have the possibility to record times for every kind of ticket.

**Comment by KoJie** [comment]
> I also noticed that the time is not always recorded. The dialog asking for a time value is missing sometimes. Even if the ticket is changed from an open state and an agent is assigned to it.

This topic is slightly related, but we would ask you to open this as a separate issue. 
Your problem also sounds more like a bug, in case it's really not working. But I suggest to please check first the settings for which the accounted time is set. Because you can enable conditions for it in Admin > Manage > Time Accounting

**Comment by KoJie** [comment]
As these are more topics I like to give feedback on it first:

> ### Expected behavior:
> * Time is measured for every agent working on a ticket.
> * could be displayed as total time and specific agent time if multiple agents are working on the same ticket
> * Time accounting in admin section shows times for agents in overview (export)

This is already possible by downloading the accounted time "by activity"

> * ticket section in overview shows all agents which worked on a ticket

This could lead to a huge overview that is not really usable when you have for example 10 agents that worked on one ticket. But I would be interested in the reason why you would need that for?

> * dashboard displays time in the corresponding box

Since the waiting time shows a different time/background than your request, I would be interested in your usecase here as well, or your goal of what is to be achieved. 

-------

Due to the various topics here, I will close the issue for now. If there is feedback or still interest on the two open once, I would ask you to create a feature request in our [community](https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6) and describe the use cases here. We will then be happy to consider the proposal. Thank you
