### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by maysv** [zammad/zammad#1074]
Is it planned (or possible) to create own formulars as a ticket?

So the customer as the opportunity to open a new ticket or a new form.

Or maybe to create templates for specific conditions - like a information collection for new hire?
A kind of a list where the applicant must fill out the custom fields and this list become a new ticket.

**Comment by hanneshal** [comment]
Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


regards
Johannes

https://community.zammad.org/t/custom-forms-for-ticket-creation/59
