### ISSUE TITLE
High CPU usage and freeze zammad when user logging in

### ISSUE THREAD

**Issue by Ruyuk** [zammad/zammad#1112]
- Infos
Used Zammad version: 1.5.0-1494609142.a96442f
Used elasticsearch version: 5.4.0
Used Zammad installation source: DEB
Operating system: Ubuntu 16.04
CPU: 4 Cores
RAM: 16 GB 
Database: PostgreSQL 9.5
Zammad users: < 100
Tickets < 500
Browser + version: Not relevant

- Problem Description

High CPU usage by puma 3.60 and scheduler.rb process when user logging in to zammad. This causes freeze zammad for 5-20 sec.
Cause seems to be BackgroundJobSearchIndex. Rebooting the processes or the server does not solve the problem.

Log included 
[log zammad.txt](https://github.com/zammad/zammad/files/1009924/log.zammad.txt)

**Comment by martini** [comment]
Hi @Ruyuk 

the log file looks good so far. I can't reproduce it. Is remote login possible?

 -Martin

**Comment by Ruyuk** [comment]
Not possible at this moment. Is there a better way to find problem ? How can i help  ? The problem started when the number of users exceeded 30 and groups 15 (at this moment is 38 groups)

**Comment by Ruyuk** [comment]
any ideas ?

**Comment by martini** [comment]
It's expensive to debug by remote hands. Anyway, let's try. One more question:

> High CPU usage by puma 3.60 and scheduler.rb process when user logging in to zammad. This causes freeze zammad for 5-20 sec.

Can you tell me, what is freezing? The browser or the server process?

PS: The BackgroundJobSearchIndex log entries look good so fare, any time a ticket got touched the search backend need to get updated (which usually has not performance issues and is not generating high load on server - because it's a background job).

 -Martin

**Comment by hanneshal** [comment]
Closed.
Please reopen when this issue still exists in 2.0.
