### ISSUE TITLE
Add new object field: tree selection

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#1126]
It should be possible to handle more complex structure via tree selection field.

![treeview-example1-1](https://cloud.githubusercontent.com/assets/5445062/26353284/f925f684-3fbf-11e7-985e-fd7e763ea24b.png)

Ticket#104445

**Comment by mrflix** [comment]
I think we already have a UI Widget for this use case: 
![screen shot 2017-05-28 at 20 15 55](https://cloud.githubusercontent.com/assets/60777/26531114/8f324238-43e2-11e7-8066-2d54d0b8a4d6.png)
I'm not sure if it is already prepared for general content with multiple depths because I think we only use it for the user selector so far. But I'd say this could work great. What do you think @martini?

Usability wise we have to make sure that it remembers the scroll position in each depth.

**Comment by martini** [comment]
@mrflix thanks for feedback. That looks good. I see to things:

1) Info: Tree selection should have only one selectable value (so it makes it easier).

2) UX: It would be nice to have more tree oriented visibility (to keep showing level of tree). The rest (with auto completion is a good idea!)
 -=> @mrflix What do you mean?

**Comment by mrflix** [comment]
My focus is not on the autocomplete but on the rows with the arrows. You can click on it and go a level deeper, seeing the users in the organisation. I think we could use this existing UI for this feature. I wouldn't want to invent something new.

**Comment by martini** [comment]
It's implemented in develop + master.
