### ISSUE TITLE
chat_disabled when trying to open a chat windows

### ISSUE THREAD

**Issue by protheusfr** [zammad/zammad#1129]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: (source, package, ...) : Docker
* Operating system: Ubuntu
* Browser + version: Chome 58, Safari 10.1

### Expected behavior:

* On click to chat windows on my site, the windows must open and allow chat.

### Actual behavior:

* Nothing append, on Browser JavaScript console I get a "chat_disabled" notice despite 1/ the chat is enabled on admin console, 2/ a chat subject has been created and activated, 3/ an agent is connected and accepting conversation.
* I get the same issue on agent dashboard -> Chat client.

### Steps to reproduce the behavior:

* Just trying to open chat windows either from agent dashboard or from a site integration.
<img width="365" alt="capture d ecran 2017-05-24 a 09 08 35" src="https://cloud.githubusercontent.com/assets/1698825/26390928/f5fcb0a0-4060-11e7-926f-58f19270819e.png"> 
<img width="502" alt="capture d ecran 2017-05-24 a 09 12 39" src="https://cloud.githubusercontent.com/assets/1698825/26391040/5728ef38-4061-11e7-8137-c3f490032aa4.png">
<img width="714" alt="capture d ecran 2017-05-24 a 09 12 50" src="https://cloud.githubusercontent.com/assets/1698825/26391045/5ae51192-4061-11e7-8582-196dd3a33b6f.png">

**Comment by rolfschmidt** [comment]
Hi @protheusfr ,

i tried to reproduce the problem but im not able to reproduce it. We also using the chat on multiple website successfullly.

- I activated the chat functionality in the admin interface

**Comment by rolfschmidt** [comment]
Hi @protheusfr ,

i tried to reproduce the problem but i was not able to to it. We also using the chat on multiple websites successfullly.

- I activated the chat functionality in the admin interface

![grafik](https://user-images.githubusercontent.com/5445062/27481912-7789376c-581f-11e7-8021-c14497d008ee.png)

- Activated the chat for my logged agent

![grafik](https://user-images.githubusercontent.com/5445062/27481926-8781861a-581f-11e7-8fc3-35d67aec8372.png)

- Open a page where the chat ist integrated for testing:

http://localhost:3000/assets/chat/index.html

This example page only works with host localhost. Otherwise you need to replace the host in the file **public/assets/chat/index.html** if you want to use it for tests.

Worked fine for me. 

Please reopen the issue if you have more information to reproduce the problem.

Best regards,

Rolf
