### ISSUE TITLE
Duplicate/clone User/Organization/Overview/Trigger/Macro

### ISSUE THREAD

**Issue by bruskiza** [zammad/zammad#1133]
(First time poster, no offense intended :peace_symbol:)
In order to better control responses when dealing with multiple channels such as:
* specific triggers per group
* specific triggers per communications channel

it would be really great if we could have a "duplicate trigger" option from the 
* admin -> triggers menu

p.s. thanks for a great platform so far!

**Comment by thorsteneckel** [comment]
@martini - as discussed. Your WIP clone feature will solve this ❤️

**Comment by moellert** [comment]
@martini its a nice feature and thanks for your work on this.
But I have to say that it doesn't work in this 2.4.0-1522215250.d5263470.centos7 Zammad version.

When I try to copy an trigger/role/group this windows appears and nothing happens when I press submit.
![clone](https://user-images.githubusercontent.com/30858921/38014399-f2fa1870-3268-11e8-8ed8-ccf79022803e.png)

**Comment by martini** [comment]
@moellert which branch is that?

**Comment by moellert** [comment]
@martini the newest development

**Comment by martini** [comment]
@moellert thanks for the hint. Can you update to latest and verify it again? Thanks!

**Comment by moellert** [comment]
@martini now it works perfect.

**Comment by martini** [comment]
@moellert thanks for reporting.
