### ISSUE TITLE
Unprocessable Mail - uninitialized constant

### ISSUE THREAD

**Issue by calatrave** [zammad/zammad#1146]
### Infos:

* Used Zammad version: 1.5.0
* Used Zammad installation source: DEB package
* Operating system: Ubuntu 16.04 Xenial 64bits
* Browser + version: Google Chrome 58.0.3029.110 (64-bit)

### Expected behavior:

* Processing E-Mails

### Actual behavior:

* Incoming messages will be fetched from the providers account, but will not be processed by ZAMMAD.

[2017_05_29_production.log.txt](https://github.com/zammad/zammad/files/1035862/2017_05_29_production.log.txt)

### Steps to reproduce the behavior:

* Resend Mail / using another account

**Comment by martini** [comment]
Hi @calatrave 

after some research I saw the error message "uninitialized constant Channel::Filter::FollowUpMerged (NameError)" in your production log.

You have installed Zammad 1.5 (on other words "stable"). The issue is, Channel::Filter::FollowUpMerged is only on develop and master branch.

So it seems the problem is that you upgraded (maybe temporary) to develop/master and moved back to stable. In this case Zammad still tries to use Channel::Filter::FollowUpMerged.

Can this be?

In case of removing "Channel::Filter::FollowUpMerged" in stable again just execute the following:

`zammad run rails r "Setting.where(state: 'Channel::Filter::FollowUpMerged').destroy"`

Feedback is welcome.

 -Martin

**Comment by martini** [comment]
Please reopen on feedback.
