### ISSUE TITLE
Group and User filter detection for freeIPA LDAP fails

### ISSUE THREAD

**Issue by soccermitchy** [zammad/zammad#1155]
### Infos:

* Used Zammad version: 1.5
* Used Zammad installation source: Debian package
* Operating system: Debian
* Browser + version: Vivaldi 1.9.818.49
* LDAP Server: FreeIPA (not sure what LDAP server it uses)

### Expected behavior:
* LDAP would bind without issues like I can everywhere else with the same creds/base DN

### Actual behavior:
* LDAP doesn't bind, saying 'Invalid credentials'

### Steps to reproduce the behavior:
* Set up a FreeIPA server
* In Zammad, try to bind to it. The base DN it uses is `cn=users,cn=accounts,dc=mydomain,dc=com`
* No matter what credentials you enter, it will always return 'Invalid credentials'

Logs from production.log:
```
I, [2017-05-31T22:37:42.466783 #1302]  INFO -- :   Parameters: {"base_dn"=>"cn=users,cn=accounts,dc=example,dc=com", "bind_user"=>"mitchell", "bind_pw"=>"[FILTERED]", "host_url"=>"ldap://10.0.0.7", "ldap"=>{"base_dn"=>"cn=users,cn=accounts,dc=example,dc=com", "bind_user"=>"mitchell", "bind_pw"=>"[FILTERED]", "host_url"=>"ldap://10.0.0.7"}}
E, [2017-05-31T22:37:42.642106 #1302] ERROR -- : Can't connect to '10.0.0.7' on port '389', Can't bind to '10.0.0.7', 49, Invalid Credentials (Exceptions::UnprocessableEntity)
/opt/zammad/lib/ldap.rb:140:in `rescue in binded_connection'
/opt/zammad/lib/ldap.rb:128:in `binded_connection'
/opt/zammad/lib/ldap.rb:122:in `connect'
```

**Comment by thorsteneckel** [comment]
Hi @soccermitchy - Thanks for giving a hint to support freeIPA as well. I managed to get the login working with the [public demo server](http://www.freeipa.org/page/Demo). The following credentials worked for me:

```
ldaps://ipa.demo1.freeipa.org
uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org
Secret123
```

You can change admin to any other user that is listed on the site. However you need to bind with the full DN of the user as I did above. Otherwise you'll get the reported error.

After the bind you will get another error 🤓 The fix for this is done with the commits above. Please wait ~30 minutes before updating your Zammad to the latest 1.5 version via your package manager. Feedback would be great!

**Comment by soccermitchy** [comment]
Just tried to upgrade Zammad from the apt repository, but I got a message saying something along the lines of there being no available updates (I tried this about 4 hours ago, don't remember the exact message, but it was along those lines)

**Comment by thorsteneckel** [comment]
Damn, this might have something to do with #1156.
