### ISSUE TITLE
Packager.io - partial failure

### ISSUE THREAD

**Issue by maysv** [zammad/zammad#1156]
Is there a problem with packager.io? I can't update zammad on debian-8.
Only the debian-8 Update wouldn't work - for the other OS - zammad can be updated..

Thank's!

![image](https://cloud.githubusercontent.com/assets/28597483/26668034/2bc8875c-46a8-11e7-81e6-4d95ed9b8a39.png)

**Comment by monotek** [comment]
Hmmm... Seems its some OpenSSL problem:  https://packager.io/gh/zammad/zammad/build_runs/2101#96932

I'll dive into it later...

**Comment by monotek** [comment]
@martini
The problem seems to be some incompatibility between ruby 2.3 and debians openssl version.

Can we switch to ruby 2.4?

**Comment by monotek** [comment]
After some experiments with pkgr in docker and Debian Jessie it turned out that openssl needs to be installed from jessie-backports to get ruby compilation fixed. 

@crohr implemented it in packager.io now and Debian build works again for all packager.io projects :-)

New debian package for Zammad is already available :-)

**Comment by martini** [comment]
@monotek Thanks! I checkout out to upgrade to ruby 2.4... but I still need some time for it.
