### ISSUE TITLE
Some ticket states disappear after import

### ISSUE THREAD

**Issue by KirkBushman** [zammad/zammad#1167]
### Infos:

* Used Zammad version: 1.5
* Operating system: CentOS
* Browser + version: Chrome 58

When we try to import data from otrs 5, and we want to create a new ticket we notice that the ticket states available are different from a fresh start, and some of them (like pending_reminder), are missing.

We tried a second time updating everything we can to the latest version to date (june 6) but the problem is still there.

This is what we have on a fresh start of Zammad, when we create a new ticket:
![before_import_otrs_2017-06-06](https://cloud.githubusercontent.com/assets/20772090/26826047/c90c355a-4ab7-11e7-9de4-c35def6fe3d4.png)

... pending reminder is an available option.

This is what we have when we try to import the data we already have from OTRS 5:
![after_import_otrs_2017-06-06](https://cloud.githubusercontent.com/assets/20772090/26826093/0e507c70-4ab8-11e7-9bfc-4045fac94856.png)

... and now pending reminder is not there anymore.

Are we doing something wrong? while searching I found that there were some problems with the import, that will be fixed in ver. 1.6, is this related somehow? 
 
Thanks in advance

**Comment by thorsteneckel** [comment]
Hi @KirkBushman - yes, there were some issues which Are resolved as stated in #890. Unfortunately this doesn't resolve it in 1.5 due to some technical aspects. As a workaround you can use the current `develop` branch for your system and switch back to stable after the release next week. Otherwise you have to wait till next week.
