### ISSUE TITLE
Filename of images (c&p) downloaded via lightbox is invalid

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#1246]
### Infos:

* Used Zammad version: latest
* Used Zammad installation source: source
* Operating system: CentOS
* Browser + version: Chrome macOS

### Expected behavior:

* I paste an image from clipboard to Zammad. Then I want to download it later and expect the file to have a valid file name.

### Actual behavior:

* it has a cryptic file name + domain of the Zammad system, which is also missing the extension (jpg, png...) 48.964342269@ptool.zammad.com

### Steps to reproduce the behavior:

*

**Comment by thorsteneckel** [comment]
Information I gathered about the process while looking into it:

Handling the pasting of clipboard data is handled here:
https://github.com/zammad/zammad/blob/20e0784c344ffcd3bd3d4b8212de9cef671b15a0/app/assets/javascripts/app/lib/base/jquery.contenteditable.js#L312

Image extraction is done here:
https://github.com/zammad/zammad/blob/757f0ac9bddaf348a6929bcf7d43d1180ea106f4/app/controllers/concerns/creates_ticket_articles.rb#L52

Generation of filename is done here:
https://github.com/zammad/zammad/blob/0c917e13aa9507ecaa487a5c805589c47e212a1e/lib/html_sanitizer.rb#L418

Since there is no information on filename and extensions is and can't be provided via the browser clipboard API and can't guess these there is no solution possible for this.

I'm closing now. Feel free to provide information on how this can be fixed.

**Comment by martini** [comment]
It's fixed in stable now. Please let me know if it's not working as expected.

@hanneshal it's also deployed on ptool.
