### ISSUE TITLE
Trigger Layout and Placeholder Documentation

### ISSUE THREAD

**Issue by semaf** [zammad/zammad#1270]
I could not find anywhere Documentation about the Trigger "Placeholders" and "Layout".

- (#{config.ticket_hook}#{ticket.number})
- #{config.http_type}://#{config.fqdn}/#ticket/zoom/#{ticket.id}
- etc..

How about HTML Layouts for Emails to Customers? At the backend is not possible to create.
And E-Mail Layouts to Agents.

**Comment by hanneshal** [comment]
Ho @semaf,

we don't document placeholders for trigger and text templates because they are mutable and based upon your config. So we came up with another solution:

just enter "::" in the text where you want to use the tags. And, like a magic trick... the possible tags appear. 
![helpdesk_-_triggers](https://user-images.githubusercontent.com/804939/28370046-9a7b9e0c-6c99-11e7-9e05-1888f2191acd.png)

At the moment we don't support HTML Formatting at this point. So this is not possible at the moment. 

regards
Johannes

**Comment by patmuc** [comment]
Hi. When will you support HTML in triggers? I think this is a helpfull and usefull function. Thanks in advance for your reply. Best, Patrick

**Comment by Shra25** [comment]
Must feature for zammad, which will definitely increase the product value.
Please allow to customize templates for triggers also

**Comment by MrGeneration** [comment]
Please stop recycling already closed issues, this does not help.
