### ISSUE TITLE
no multi language for objects->tickets-> attribute (no translation possible)

### ISSUE THREAD

**Issue by thomas-vahrson** [zammad/zammad#1282]
### Infos:

* Used Zammad version: V1.5
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: all browser

### Expected behavior:

I would like to see an function "like "inline translation" or something else to translate the attributes.
the problem is that we have customers world wide. But how I can create a form with customer attributes in different languages? 

### Actual behavior:

*  no multi language for objects->tickets-> attributes
* Actually only the system Text's are multilinugal. All other points are static
* 

### Steps to reproduce the behavior:

*

**Comment by penzoiders** [comment]
+1 on this!

**Comment by MrGeneration** [comment]
Locking conversation to prevent `+1` comments.
Please use the emote function for this.

**Comment by MrGeneration** [comment]
I'll be closing this issue, because this is already possible.
I see inline translation critical, because you would have to workaround the selection field behavior of Browsers which I see as a super bad idea.

However, you can add translations for any language Zammad supports via command line, as long as you have the exact same string. :-)

See: https://docs.zammad.org/en/latest/console/other-usefull-commands.html#add-translation
