### ISSUE TITLE
Question: Testing OAuth2 with Office365

### ISSUE THREAD

**Issue by passboltUser** [zammad/zammad#1304]
I saw that you recently implemented https://github.com/zammad/zammad/issues/1177 and was wondering if I can test it by pulling master? Or do still some features need to be implemented before one can test this feature?

**Comment by martini** [comment]
Hi @passboltUser 

your can pulling the master for testing. But currently you can not go back to develop (because of database changes and new settings).

So can do it on your current Zammad test system, just pull the master an test it.

PS: For questions (not issue) it would be nice if you could use our lists: https://zammad.org/participate ->  zammad-users mailing list - Thanks!

 -Martin

**Comment by passboltUser** [comment]
Ok, thanks.

**Comment by passboltUser** [comment]
Too bad the mailing list requires a Google account. Any other sites where one can ask a question?

**Comment by martini** [comment]
Unfortunately not right now. Working on other forums be done after next Zammad release...

**Comment by passboltUser** [comment]
Good to know.
Is there an upgrader or something for upgrading zammad 1.5.x to 2.0 (master)?

**Comment by martini** [comment]
For upgrading rails behaviour is used.

If you upgrade via package, you do not need to do anything (in background "zammad run rake db:migrate" is executed which is performing all upgrade tasks).

-=> So finally just a package upgrade is needed.

There is one limitation right now, if you upgraded to master you will not be able to downgrade to 1.5 again (because of database and setting changes).

So in case just upgrade your Zammad test system to master for testing (not production).

**Comment by passboltUser** [comment]
Thanks. That the downgrade is not possible is due to running master or will a downgrade also not be possible with the final release? I know that packages can be `remove`d or `purge`d but now I wonder how that works when the database has been changed?

**Comment by martini** [comment]
The downgrade will work until the database can be downgraded (e. g. if the new release only brings additional fields). So Zammad it self (the application) can be downgraded anytime (currently you just need to restore the matching database for it).

After Zammad 2 is release it's possible again to switch between master/develop/stable on the fly again.

**Comment by passboltUser** [comment]
Ok, so when DB schema changes happen like with a major release, a downgrade to a previous version (in this case 1.5) is not possible, even though it is package format, ok then. Yes indeed, I assume downgrades between the same version are of course possible because same DB schema. Ok, thanks.
