### ISSUE TITLE
Can't add attributes manually to LDAP sync

### ISSUE THREAD

**Issue by gwingend** [zammad/zammad#1326]
### Infos:

* Used Zammad version: 1.6.1
* Used Zammad installation source: (source, package, ...)
* Operating system: 
* Browser + version: 

### Expected behavior:
All or at least more ldap attributes should be able to sync with zammad objects.

usecase:
We want so give the agent as most as possible of the needed information about the enduser in zammad.
The need for using other tools should be minimized.

Informations like
- department with site and building
- room number for onsite support,
- manager of the enduser
- information about the enduser computername
and many other informations could be pulled out of directory service (ldap) with a one time configuration effort.

### Actual behavior:
only a subset of all given ldap attributes could be synced with zammad objects.
 

### Steps to reproduce the behavior:
setup ldap source and start attribute mapping

**Comment by hanneshal** [comment]
@gwingend 
So just to be clear, are you missing attributes from your LDAP or do you miss user attributes to map your existing LDAP attributes to?

If you you are missing user attributes, please extend using the objects for users, then you can map your existing LDAP attributes to the newly created user attributes.

**Comment by gwingend** [comment]
@hanneshal 
I´m missing attributes from my LDAP.
Zammad is showing only a small subset of all available LDAP attributes

**Comment by thorsteneckel** [comment]
Hi @gwingend. How many users are affected by the Zammad LDAP sync?

Zammad uses a special logic to determine the available LDAP attributes with example values for users. It starts a search with the User filter and checks each entry for new attributes. If there are [more than 50](https://github.com/zammad/zammad/blob/b04f56faedf298fe5e4dbfbc2dbf74f64687acc0/lib/ldap/user.rb#L136) entries in a row without new attributes it will stop the probing. If after lets say 20 entries a new attribute is found [the 50 counter gets reset](https://github.com/zammad/zammad/blob/b04f56faedf298fe5e4dbfbc2dbf74f64687acc0/lib/ldap/user.rb#L152) and will start looking for up to the next 50 entries.

So it might be that the attributes in your case are missing because of this logic. The first 50 entries may not have any of those.

**Comment by gwingend** [comment]
@thorsteneckel 
Why is zammad doing the filter? 
Won´t it be faster just showing all attributes?

So you could do the mapping also for ldap fields, that have to be filled in the future.


But the functionality you described could be the cause. 
There might be some users which have some fields empty.

I will check that.

**Comment by martini** [comment]
As discussed with @gwingend, it would be nice to keep the actually behaviour + add possibility to enter fields via UI which are not in autocompletion.

Currently if I enter "some_field_name_which_is_not_in_autocompletion" it's not stored in config.

**Comment by vbustamante** [comment]
Do you have any updates on this Issue?
