### ISSUE TITLE
Change the default state when answering a ticket

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#1367]
### Infos:

* Used Zammad version: 1.5.x
* Used Zammad installation source: package
* Operating system: Debian Jessie
* Browser + version: Mozilla Firefox 55.0.2

### Expected behavior:
No other status can be selected, which is applied by default when answered.
* 

### Actual behavior:
When I answer a ticket, the status "open" is selected by default.
* 

### Steps to reproduce the behavior:
Update / reply a ticket
*

**Comment by zabarabab** [comment]
Hi Linus,
do you know you can press Shift+Ctrl+c to send your answer and close the ticket in one step?

Unfortunately Strg+Shift+w is still broken, so there is no shortcut to close the ticket-tab.

**Comment by hanneshal** [comment]
Note to future me: If we implement this, a default state per group would be useful.

**Comment by gwingend** [comment]
Maybe the following workaround would work:
Create a new state which you want answered tickets set to.
You can find a howto in issue #574.

Then use the trigger to set the ticket to the new state.

Or create a macro which sets the ticket to the new state when updating the ticket.

**Comment by martini** [comment]
> Or create a macro which sets the ticket to the new state when updating the ticket.

For me the macro sounds the best way. 🚀 You also can combine it with setting the owner to the user which is executing the action. Also other attributes could be also set within one action.

 -=> It is very flexible.

**Comment by thorsteneckel** [comment]
Agreeing with @martini that using a macro would be the best solution here. Feel free to take the discussion over to our [community board](http://community.zammad.org/) if needed.

**Comment by martinvonwittich** [comment]
I didn't like the suggested macro solution, so I came up with a trigger instead. We had configured our old ticket system Kayako so that it would automatically suggest "closed" as the new state when replying. At this point, our agents are probably very used to this behavior, and always having to click on the arrow button -> reply & close seemed rather annoying. The trigger I came up is this:

conditions:
- State is not: closed
- Action is: updated
- Sender is: Agent
- Type is: email

execute:
- State: closed

The only disadvantage is that when the agent doesn't want the ticket to be closed, he has to manually reopen it after sending a reply. This was slightly better in Kayako because there the agent could change the suggested new state before replying, but IMO it's close enough.
