### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by HLFH** [zammad/zammad#1378]
### Infos:

* Used Zammad version: stable branch
* Used Zammad installation source: github repo
* Operating system: Windows 10
* Browser + version: Chrome x64 last version

### Expected behavior:

* A systemd service fully working for websocket-server.rb and scheduler.rb

### Actual behavior:

* I have an ArchLinux server running with the last Nginx.
I have to run manually websocket-server.rb and scheduler.rb.
I need to use it via systemd to use zammad in production.

### Steps to reproduce the behavior:

* Launch manually websocket-server.rb and scheduler.rb.
Cry.

cc @martini @mrflix @thorsteneckel

**Comment by mrflix** [comment]
Hi HLFH. Please don't flat out cc developers. I for example have no clue about systemd. My bread and butter is frontend code (css, html, js). Your issue will get categorised and assigned if there is the capacity and relevance to work on it.

Since you seem to know what you're talking about: do you think that adding this to Zammad would help a lot of people? Do you think you can add the support for systemd support? This is an Open Source project never the less, not the make a wish foundation.

**Comment by chocochrispi** [comment]
Great addition, thanks

**Comment by mrflix** [comment]
Now that escalated quickly. Thanks for your enthusiasm @HLFH and for assigning pull request reviewers @thorsteneckel.

**Comment by monotek** [comment]
Fixed in: https://github.com/zammad/zammad/commit/7c24141cdf18971b8d7624b08d950c014ffd0160
