### ISSUE TITLE
DEB / RPM packages to big because Ruby 2.3.0 & 2.4.1 are packaged

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#1438]
The vendor dir of our DEB & RPM packages contains 2 Ruby versions (2.3.0 & 2.4.1). 
Seems to be a bug in pkgr / apckager.io

Bugreport @ pkgr: https://github.com/crohr/pkgr/issues/132

**Comment by monotek** [comment]
Temporary fixed in Zammad with: https://github.com/zammad/zammad/commit/78c8fc48790f6c97bbda644082192e608bb7290f

**Comment by hamzehmohammadnia** [comment]
Hi,
i have installed your latest version of zammad, and based on my changes on database file, I need to run "run rake" command but:
zammad run rake db:migrate
rake aborted!
Mysql2::Error: Access denied for user 'zammad'@'localhost' (using password: YES)
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.6/lib/mysql2/client.rb:89:in `connect'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.6/lib/mysql2/client.rb:89:in `initialize'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/composite_primary_keys-8.1.6/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:51:in `retrieve_connection'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/composite_primary_keys-8.1.6/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:33:in `connection'
/opt/zammad/config/initializers/db_preferences_mysql.rb:9:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:166:in `instrument'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:615:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `each'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
/opt/zammad/config/environment.rb:5:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/application.rb:328:in `require_environment!'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/railties-4.2.9/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/opt/zammad/bin/bundle:3:in `load'
/opt/zammad/bin/bundle:3:in `<main>'
Tasks: TOP => db:migrate => environment

im using Centos 7, and when check version of Ruby it shows:
#ruby -v
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
Can I ask you what I missed here? since I could user rake in previous version without making any changes...

Best,

**Comment by NeverMin** [comment]
> Mysql2::Error: Access denied for user 'zammad'@'localhost' (using password: YES)
did you upgrade MySQL ?

**Comment by hamzehmohammadnia** [comment]
No, everything is same as previous installation structure for Zammad 1.5
I just updated zammad repository to install the latest version.

**Comment by NeverMin** [comment]
using CLI check your DB config: `/opt/zammad/config/database.yml`
e.g.: `mysql -u root -p` and input password from `database.yml`

**Comment by NeverMin** [comment]
@hamzehmohammadnia Great !

**Comment by monotek** [comment]
@hamzehmohammadnia 
Please don't post youz problems to random issues which does not have any relation to your problem.

Open an new issue instead.
