### ISSUE TITLE
Icinga/Nagios Integration: No longer accepts regex in "Sender"

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#1439]
### Infos:

* Used Zammad version: 2.0
* Used Zammad installation source: package
* Operating system: Ubuntu 16.04

### Expected behavior:

If I use nagios@.* it should work for mails from nagios@customer**A**.com and nagios@customer**B**.com

It worked very well in 1.5. 

### Actual behavior:

In 2.0 it only works for exact matches.

The 1.5 "feature" was very useful for us. If regex is not possible we need the ability to enter more than one sender e-mail address.

**Comment by natseg** [comment]
Hi,

Is this issue not resolved by simply using the wildcard alone? 
<img width="531" alt="screen shot 2017-09-19 at 16 00 19" src="https://user-images.githubusercontent.com/6449818/30599263-d4040b10-9d53-11e7-80f0-8d3364773515.png">
` nagios@*` instead of `nagios@.*`

**Comment by martini** [comment]
@natseg in Zammad under Admin -> Channel -> E-Mail -> Filter (or also for integrations -> icinga or nagios) your can use regular expressions too. 

For Zammad 1.5 and below is was enabled by default. It looked like:

<img width="651" alt="screen shot 2017-09-19 at 18 51 15" src="https://user-images.githubusercontent.com/110226/30604839-47ae4ac2-9d6c-11e7-8d98-5147830fa0d9.png">

The only problem was, many people used simple * for a wildcard. But technically it was used for a regex which was broken then (because with regex you need to use .*).

Anyway, for Zammad 2.0 and higher we changed the syntax it support * as wildcard per default (95% of the users will expect it). If you still want to use regular expressions you need to prefix it with **regex:** in the search field:

<img width="642" alt="screen shot 2017-09-19 at 18 51 45" src="https://user-images.githubusercontent.com/110226/30604984-c9d9fe42-9d6c-11e7-81ef-ef5344e920a8.png">

@hiaz for icinga and nagios integration we missed the support of "regex:" prefix. -> Fix is on the way.

**Comment by martini** [comment]
@hiaz now it's fixed for Zammad 2.0 (just update the package). You can use regex again just enter `regex:nagios@(customerA.com|customerB.com)`

**Comment by hiaz** [comment]
@martini Just did the update. Seems to work fine! Thank you.

**Comment by martini** [comment]
@hiaz Thanks for feedback!
