### ISSUE TITLE
amounts of results REST-Requests

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1458]
Hi,

I have a problem with my REST-requests.
As soon as I make a request which should return more then 12 results, I only get 12 results.
I'm sure, I'm completely stumped 😳 
What I've about elasticsearch to that topic, you just can at the "size" parameter, which in my case doesn't work 😞 

Here is a sample of my request:
/api/v1/tickets/search?query=created_at:%3Enow-310d&size=2

**Comment by martini** [comment]
Hi @MamoulianDelacroix 

try `limit=20`. The maximum is 100. Then you need to use `page` and `per_page` params.

See also https://docs.zammad.org/en/latest/api-intro.html

 -Martin

**Comment by MamoulianDelacroix** [comment]
@martini 
thanks a lot! 👍 
I just found that as well.
Is there the possibility to change the maximum from 100 something else?

**Comment by martini** [comment]
> Is there the possibility to change the maximum from 100 something else?

Currently it's fixed in source code. In case we can create a system wide setting for it.

https://github.com/zammad/zammad/blob/develop/app/controllers/tickets_controller.rb#L388
https://github.com/zammad/zammad/blob/develop/app/controllers/users_controller.rb#L362
https://github.com/zammad/zammad/blob/develop/app/controllers/organizations_controller.rb#L236

Just feel free to create a PR (I'll review it).

PS: Just to make sure, the result of more of 100 ticket can get huge.

 -Martin

**Comment by martini** [comment]
I'm closing because the question is answered. Just reopen if needed.
