### ISSUE TITLE
Feature Request - Google OAuth2 utilize HD (Hosted Domain)

### ISSUE THREAD

**Issue by MelonSmasher** [zammad/zammad#1474]
It would be nice to allow only specific domains to log in via Google OAuth. This would prevent users from logging in with their personal Google accounts and force them to use their GSuite account.

I've done this in Laravel before, but I am not proficient with Rails, so I have no idea where to begin.

At a high level it would involve: 

- A section in the admin panel to whitelist specific domains.
- Sending the [HD parameter](https://developers.google.com/identity/protocols/OpenIDConnect#hd-param) to Google with the OAuth request.
- Validating the callback information on the server to verify that the OAuth parameters were not tampered with.
- An error displayed in the view if someone attempts to log in with a non whitelisted domain.

Please feel free to point me in the direction of how to implement this.

**Comment by muhammadn** [comment]
@MelonSmasher This is possible because we are using this gem: https://github.com/zquestz/omniauth-google-oauth2

If you read the documentation, there is HD option for hosted domain. Implementing it is quite straight-forward since most of the configuration is stored in Zammad's database.

example:
https://github.com/zquestz/omniauth-google-oauth2/blob/master/examples/omni_auth.rb

Above is the example to set the HD parameters for the following files:

https://github.com/zammad/zammad/blob/develop/config/initializers/omniauth.rb
https://github.com/zammad/zammad/blob/develop/vendor/lib/google_oauth2_database.rb

You could add in omniauth.rb an extra third dummy parameter and in google_oauth2_database.rb the `hd: %{domain.foo.bar, example.com}` parameter for the allowed domains. Usually these settings are stored in database, that is why you see `Setting.get('data')` in google_oauth2_database.rb

don't forget to restart your rails app after making changes (because of the initializer files loads only when rails is started)

**Comment by vishnus** [comment]
Hi @muhammadn , Can you guide on how to get hosted domain work with a sample code? I'm new to ruby, so would appreciate it if you can explain this little more details.

Thanks

**Comment by thorsteneckel** [comment]
Please refer to our http://community.zammad.org/ board for technical questions. Thanks!

**Comment by prashant-shahi** [comment]
Continuing the solution in this thread, as it could be a helpful reference for others to look at.

In file `omniauth.rb`, comment out or remove the provider configuration for `google_oauth2_database`. And, add the following one :
```ruby
provider :google_oauth2, ENV['GOOGLE_KEY'], ENV['GOOGLE_SECRET'], {
    hd: 'your-domain.com'
}
```

Set the **GOOGLE_KEY** and **GOOGLE_SECRET** environment before running it. Alternatively, add it to `.bash_rc`.
```sh
export GOOGLE_KEY=your-google-key
export GOOGLE_SECRET=your-google-secret
```
