### ISSUE TITLE
create automaticly an ticket based on a phone call via sipate api for Time Accounting

### ISSUE THREAD

**Issue by thomas-vahrson** [zammad/zammad#1505]
actually you can't do nothing on the caller page. It would be great if you can create automaticly an ticket for the time accounting based on the phone call start/end time.

If you want to make the bill to the customer depends of the investigated time you need an overview of the investigated time on the phone and so on.

**Comment by thomas-vahrson** [comment]
actually you can't do nothing on the caller page. It would be great if you can create automaticly an ticket for the time accounting based on the phone call start/end time.

If you want to make the bill to the customer depends of the investigated time you need an overview of the investigated time on the phone and so on.

**Comment by hanneshal** [comment]
Hi @thomas-vahrson,

this is a rather special use case. In a scenario where you get multiple calls within a short amount of time, you need some time to work on tickets, or just leave them open to handle them later. So the automatic time counter would not work. I think we wont implement such a feature for all Zammad users, because of the limited usage. You can open a ticket if you get a call, and if the user is found it will pre-filled. 

It would be possible to develop this as custom development. Feel free to contact us.

regards

Johannes

**Comment by Megachip** [comment]
Hmm, I think creating tickets for missed calls is a very useful feature.

**Comment by MrGeneration** [comment]
Please don't hijack closed issues.
Limiting conversation to contributors only.
