### ISSUE TITLE
Some doubts in Zammad's configuration

### ISSUE THREAD

**Issue by gueeme** [zammad/zammad#1576]
### Infos:

* Used Zammad version: 2.0.x
* Used Zammad installation source: (source, package, ...) Package
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Chrome 62.0

I have some doubts about Zammad's management:

1- Is it possible to modify and delete the ticket status?
2- Can I create sub groups to separate the services that will be served?
3 - Automatically assign the call to the agent that modifies the state of it?
4- Disable the option to create client in the opening of the call?
5- Change colors of the backuground and logo next to the search field?
6- Remove the Received Call, Outbound Call, Send Mail, and leave only one default fields?

I am very grateful if you can clarify these doubts.

Thanks and congratulations for the excellent system.

**Comment by babakkazemi** [comment]
@gueeme 
1) yes
2) yes
3) yes
4) needs customization
5) needs customization
6) needs customization

**Comment by gueeme** [comment]
Does it exist any manual or can you give me a hint on how to make these changes from questions 1, 2 and 3?
Can you tell me the code of which files should I change to modify questions 4, 5 and 6?

Thanks for your attention

**Comment by babakkazemi** [comment]
@gueeme have you looked at zammad yet? There's also a manual at https://docs.zammad.org/en/latest/
1) dropdown menu inside the ticket with ticket status. If you want to add a new ticket status, see #574 
2) sorry got you wrong there - no nested groups possible.
3) create a trigger. condition: "state = changed". action: "owner = current user"
4,5,6 I can't help you with, maybe someone else. Otherwise, read the source and you'll see :)
