### ISSUE TITLE
No localised time displayed in trigger (autoreply/slack/...) notifications

### ISSUE THREAD

**Issue by em-ex** [zammad/zammad#1589]
### Infos:

* Used Zammad version: 2.0.0 from source

Is there an option to set proper local timezone for notifications (mail and Slack in particular)? They all come through in UTC, while I'd like them to be UTC+3 (even though reminders and triggers do trigger at right, local time).

I had some success by altering localized mail and Slack notification templates - adding `.localtime` to the time-related variables does force it to output the right time - but this can't be the best solution.

Not sure if this is meaningful, but in console I see this:
![image](https://user-images.githubusercontent.com/29741946/32083249-13ccbd1c-baca-11e7-9339-3de486ee9eed.png)

Thanks.

**Comment by svnr-dvnkln** [comment]
Is this going to be implemented in a future release or do we have to do this by ourself everytime we upgrade zammad?

**Comment by svnr-dvnkln** [comment]
Yes. By default it's UTC so the agents will receive notifications about tickets that will escalate at the wrong time (or timezone). 

By adding `.localtime` to `#{ticket.escalation_at}` it will transform it into the right timezone.

**Comment by martini** [comment]
Thanks for feedback. In case, would it be better to use the agent based time zone (which is used in web interface anyway)?

**Comment by svnr-dvnkln** [comment]
IMHO the agent based time zone would be better. 
If you have agents working for you from different countries this would be the way to go, since it wouldn't depend on the server time zone.

**Comment by svnr-dvnkln** [comment]
One little thing that came into my mind..

We're already choosing a time zone in the calendar section and we're furthermore choosing these calendars for defining the SLAs.

So the "right" way to do this would be that the notifications look up the time zone defined in the calendars?

**Comment by chesty** [comment]
I'm seeing time zone issues in other areas that might be related. server running on UTC, browser running on +10.

The graph on the reports are 9 hours out of the time displayed on the tickets. (9 hours doesn't make any sense, 10 makes sense)
https://community.zammad.org/t/report-timezone-issue/826

Also the pending reminders seem to be UTC.

**Comment by MrGeneration** [comment]
#2169 might be a slight overlap: @mantas could you let me know the branch this has been adressed in? I might be able to verify it's function then, maybe the other issue got adressed too.

**Comment by mantas** [comment]
@MrGeneration it's in `private-mm_timezones`

**Comment by bnalpay** [comment]
adding .localtime solves this issue for mail and slack notifications but still it's manual and must be redone on every update, anyone with automatic workaround for this ?

**Comment by Anagastes** [comment]
Sorry, guys, but I have this behavior, too.

How exactly can I add ".localtime" so that the time is really correct?

I have this in automation, for example. I must set 19:30 to have the execution at 20:30.

![screenshot_20190112_205021](https://user-images.githubusercontent.com/17494592/51077829-dfb65d00-16ab-11e9-91c1-5261a20fdf67.png)
![screenshot_20190112_205048](https://user-images.githubusercontent.com/17494592/51077835-f492f080-16ab-11e9-8872-3a965d75727c.png)

**Comment by thorsteneckel** [comment]
Hi @Anagastes - this issue is still open and not resolved yet. You can see what issues we're working on and their progress over [here](https://github.com/zammad/zammad/projects/3). You can add an 👍 reaction to each comment you're interested in to get fixed. We're focus on the issues reported by our paying customers and the ones with the most 👍 reactions. JFI: Adding comments and asking when things are done will only slow us down.

**Comment by martini** [comment]
Update: With Zammad 2.9 we introduce a system wide default time zone. It's set by the admin at initial setup, on updated instances at first login if an admin user or manual via Admin -> Settings -> Branding.

This system wide default time zone is also used for localised time displayed in trigger (autoreply/slack/...) notifications.

Note: Right now we do not support a user based timezone setting (but maybe in future).

If you feel there are other timezone issues which is not covered by this issue, please create a separate issue for it. Thanks!
