### ISSUE TITLE
feature request - change customer on entrys forwarded by email

### ISSUE THREAD

**Issue by chrklo** [zammad/zammad#1640]
### Infos:

* Used Zammad version: 2.1.6
* Used Zammad installation source: package
* Operating system: linux
* Browser + version: Chrome 61

### Expected behavior:

* I would like to be able to change the customer of an entry added by email.
Like its possible for the ticket itself.

the ticket would be more readable if the source could be associated to the customer, and not the forwarder.

### Actual behavior:

* forwarded (customer) mails to the ticket looks like its an input from myself.
If you reply on such an entry the own mail adress is suggested.

### Steps to reproduce the behavior:

*
1) create ticket
2) forward an email to this ticket

**Comment by hanneshal** [comment]
Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals

regards
Johannes

https://community.zammad.org/t/change-customer-on-entrys-forwarded-by/23
