### ISSUE TITLE
Allow users to delete and edit "Notes"

### ISSUE THREAD

**Issue by zabarabab** [zammad/zammad#169]
In github it's possible to edit comments of issues. For "Notzen" (articles?) that would be nice to have in zammed, too.

**Comment by zabarabab** [comment]
Thank you for adding this feature: there is now a button "delete". 

But it does not work here:
https://linuxhotel.zammad.com/#ticket/zoom/775

**Comment by urfin78** [comment]
We have the same problem here. Note dissapears only (after click on delete button and click on yes) on manual reload of page.

**Comment by thorsteneckel** [comment]
Seems like this issue was never closed. Deletion of notes was already added quite some time ago. There will be a change in the near future to allow the deletion only in a time frame of 10 minutes after creation.
However, it's not planned to add an "edit" functionality.

Therefore I'll close this issue.
