### ISSUE TITLE
LDAP sync huge issue

### ISSUE THREAD

**Issue by ToubieObie** [zammad/zammad#1694]
### Infos:

* Used Zammad version: 2.1
* Used Zammad installation source: DEB
* Operating system: Debian
* Browser + version: Not relevnt

### Expected behavior:

* LDAP Syncs users every X minute

### Actual behavior:

* Today I had the issue that if i add a userrole and map that to a AD group. All "lokal" Users become disables and my account (admin, Agent) and the admin account got disables! Now I canot access the Ticket System!! 

### Steps to reproduce the behavior:

* Interagte Zammad in a Active Direcory, sync the users, add AD group to zammad that has Zammad admin and agent rights, add a AD group for all "customers", -> All local users become disabled and my agent, admin account too... (Thinking of deleting Zammad and changing to another system!!)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by ToubieObie** [comment]
The issue happens, if a AD user is in both groups: 1 group with admin right and in a group with customer rights

**Comment by thorsteneckel** [comment]
Hi @ToubieObie - Thanks for filling an issue. There is no need for dramatizing. If you need support for your self hosted installation you can check out [our plans](https://zammad.com/pricing#selfhosted). If you have the need to use another system we can't and won't stop you from that.

As you write:
> The issue happens, if a AD user is in both groups: 1 group with admin right and in a group with customer rights.

An Administrator can't be a Customer at the same time (currently). This is not possible due to a logical restriction. So you have to change this in your LDAP / configuration.

You can re-activate any user you want by running the following code in your [Rails console](https://docs.zammad.org/en/latest/admin-console.html#start-zammad-s-rails-console): `User.find_by(email: 'admin@yourtld.com').update!(active: true)`

You can disable the LDAP import via: `Setting.get("#ldap_integration", false)`

The Zammad issue I see is that it should not be possible to disable (all) Administrator accounts. There is already a check that prevents deleting all Administrator accounts. I'll create a new issue for this and close this issue here.

**Comment by ToubieObie** [comment]
Ok Thank you. 
Yes the problem was, that I assigned the Zammad customer group to a AD group where I was a member.
It was my mistake ^^

I fixed it and now is all fine. 
It would be nice that in this case the customer group will be ignored and a massage "A Admin/Agent cannot be a customer at the same time!" will be shown. Also if the assigment is set via ActiveDirecory/LDAP.

**Comment by thorsteneckel** [comment]
Thanks for your reply. Glad it worked out for you. I'll have a look what I can do 👍
