### ISSUE TITLE
LDAP User uid attribute is not reliable

### ISSUE THREAD

**Issue by JakobTewes** [zammad/zammad#1709]
As were using MS ActiveDirectory, were in need for a solid and feature-complete LDAP integration.
For us the following things are missing and we think, that the integration will help quite some organisations using ActiveDirectory

- Recursive group membership: As we like to have permissions assigned inside zammad, we´d love to have the possibility, to add users via "group in group" via LDAP. Thatfor a ldap-filter memberOf:1.2.840.113556.1.4.1941:=CN=group,DC=netways,DC=de needs to be set (https://blog.netways.de/2012/11/28/ldap-filter-fur-autorisierung-bei-rekursiven-gruppen/)

- Use a UID in zammad as user uid instead of a changing account name (SamAccountName). That for we´d love to use the attribute "objectguid". This attribute is currently blacklisted in ./lib/ldap/user.rb

Thanks a lot - if we can help (unfortunately we got no developers, that can fix this - so we have to kindly ask for the optimisation), please let us know.

Regards,

Jakob

**Comment by thorsteneckel** [comment]
Hi @JakobTewes - thanks for your suggestions. We discussed your second point already and came to the conclusion that you're right and we need to change that. We will prepend `objectGUID` and `entryUUID` to the list of uid_attributes. This will need a migration which we will integrate in our LDAP refactoring which is currently going on. This be part of Zammad 2.3 or 2.4 - depending on the workload.

Your other point `Recursive group membership` is not clear to me. Can you please create a new topic in our [board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals) where we can discuss this more in detail? I don't want to mix things up here in this issue and this is more a feature request than a real issue/bug if you know what I mean.

🚀

**Comment by thorsteneckel** [comment]
Hi @JakobTewes - We fixed the issue with commit above. We added an automatic migration to avoid manual work.
So after you update your Zammad installation to latest develop or 2.3 (later) you'll (probably) see in your admin LDAP view that the configuration has changed to `objectGUID` instead of `samaccountname` as an identifier. Some others might see a change to `entryUUID` as described above. If those are not available `samaccountname` remains.

The next sync run will then perform the needed changes.

Closing for now. Would be great to get some feedback 👍
