### ISSUE TITLE
Zammad does not accept specific imap folders

### ISSUE THREAD

**Issue by flome00** [zammad/zammad#1820]
### Infos:

* Used Zammad version: 2.3.x 
* Installation method (source, package, ..): package on CentOS
* Browser + version: Firefox / Edge

### Expected behavior:

* When adding an Email Account (Zammad should fetch only a given folder) Zammad should accept this folder and continue.

### Actual behavior:

*Zammad says when giving the any existng mailbox name: Mailbox does not exist, or must be subscribed to. (except when using inbox - this works). Referring to thunderbird, the folders are like this:
inbox
inbox/zammad
inbox/sent
inbox/XYZ
Zammad is accepting only the inbox folder. I tried several notations: "zammad", "inbox/zammad", etc

Thanks flome

**Comment by flome00** [comment]
Hey,

I found a silly solution (for somebody who is having the same trouble):

IMAP-Folder notation is not inbox/zammad but inbox.zammad !!

Please close this issue - Sorry for the inconvenience....

**Comment by muhammadn** [comment]
Okay. closing.

**Comment by ICT-Eurotrol** [comment]
Used Zammad version: 2.9.x

If you are using Zammad version: 2.9.x and you want to make use of folders, you need to verify that the folder has received the test email message from your Zammad server.
As soon as you are verifiying your mail setup on the Zammad server, move the received mail message to the folder you want to synchronize, otherwise the verification will fail.(most of the time with a login error)

The IMAP-Folder notation is  /Inbox/Zammad(or whatever you named it) -> It is capital sensitive!!
