### ISSUE TITLE
Popup showing new API Token closes, when pressing [cmd] key on mac

### ISSUE THREAD

**Issue by chrisblech** [zammad/zammad#1839]
### Infos:

* Used Zammad version: 2.3.x
* Installation method (source, package, ..): deb package
* Operating system: debian 9.3
* Database + version: bundeled
* Elasticsearch version: 5.6
* Browser + version: chrome latest stable (mac)

### Expected behavior:

* agent can copy newly generated token, by pressing [cmd] - [c]

### Actual behavior:

* popup closes (and token can never be shown again) unexpected on pressing left [cmd] key.

### Steps to reproduce the behavior:

* click Personal avatar (lower left corner) - Profil - Tokens
* green button: new token
* click some checkboxes, then OK
* double-click token (to select it)
* press [cmd]

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
@chrisblech thanks for the issue.

It's already fixed in develop. Now also in stable. https://github.com/zammad/zammad/commit/69357d1d4fe369edf24f449bdc340175b9c473d7 Just update your Zammad package and you can test it (build will be finished in about 20 minutes https://packager.io/gh/zammad/zammad/refs/stable).

Feedback is welcome!
