### ISSUE TITLE
Two minor user interface/documentation issues

### ISSUE THREAD

**Issue by lpar** [zammad/zammad#1867]
- There are settings for date and time format under Translations, but I can't work out what the format specification is and it appears to be undocumented. (It's not standard Ruby/Rails.)

 - The Description help text for the Organizations management section appears to me in German.

**Comment by thorsteneckel** [comment]
Hi @lpar - could you please move this over to the http://community.zammad.org/ since it's a technical question. Would be great if you could provide some more context (maybe screenshots?) because currently I don't fully get it.
Regarding the german text: This is a deeper issue and was (party) addressed in the linked PR above.

I'm closing this one here now.
