### ISSUE TITLE
Escalation ignores public notes

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#1880]
### Expected behavior:

* escalation for an update is based on the contact agent's last timestamp. Public notes should be counted as an update (info to the customer) to suspend escalations.

### Actual behavior:

* the last contact agent timestamp ignores "notes" to customers, even if they are public. This causes tickets to escalate even though a public note has been added to the ticket.

### Infos:

* Used Zammad version: 2.3 (hosted)
* Browser + version: Google Chrome, Version 64.0.3282.186

**Comment by martini** [comment]
Just as remark: External notes are not sent to the customer per default. If you use Zammad the Zendesk way, you can create an trigger to send external notes to the customer of a ticket. In this case the external note should be considered for escalations. But only if this trigger exists.

**Comment by MrGeneration** [comment]
Personally I believe that this works as designed and should not be changed.
Instead, if needed, I believe we should set the `communication: true` flag.

Attention: This causes private notes to count for SLA as well.
Imho this is, because we currently can't differ from that.

@thorsteneckel  what do you think?

**Comment by dennykorsukewitz** [comment]
In my opinion, a note should not be counted as communication. Because we only write a note on the ticket and don't necessarily want to inform the customer. 

At the moment, however, it is expected that a note will count as communication because the customer can view it at Zammad as a customer.

**For this we should use the ArticleType 'web'**.

----

Or we differentiate between internal and external notes.

**- External note counts as communication.**
**- Internal does not count as communication.**

**Comment by MrGeneration** [comment]
I like the approach to automatically switch to "Web" when using a public note better.
This will also disallow the agent to delete the note and will make it clearer that this e.g. has been public earlier.

**Comment by MrGeneration** [comment]
This is already possible within Zammad, but requires an update on the Article-Type `note`:

```
Ticket::Article::Type.find_by(name:'note').update!(communication: true)
```

With the above, Zammad will recognize **public** notes as communication.
Please note that this does not send E-Mails to the customer, if you want your customer to receive what you typed in the note, ensure to set up a Trigger. ;)

Also note that notes are, by default, `communication = false`.


### Technical Background

For those who want to dig deeper, the following two blocks are responsible for that magic:

https://github.com/zammad/zammad/blob/37687e32a114d0d62bbcef1092d09184ec81b835/app/models/observer/ticket/article_changes.rb#L59-L82

https://github.com/zammad/zammad/blob/37687e32a114d0d62bbcef1092d09184ec81b835/app/models/observer/ticket/article_changes.rb#L97-L155

**Comment by danieleades** [comment]
i have an additional question here-
the vast majority of our clients communicate exclusively via email, hence we do not wish to differentiate between email communications and public notes- hence we use the above instructions to set communication=true on these events and trigger the SLA.

Then we need to set up triggers so that a public note triggers an email to the client, but we don't want the agent to be notified, since they posted the ticket. similarly, the customer doesn't need to be notified if they've just sent an email, or posted a note.

We're having trouble finding a way to do this using the triggers.

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question, please head over to the Community: https://commnunity.zammad.org

This is most likely a workflow issue.

**Comment by danieleades** [comment]
Hi, thanks for the quick response. I guess what I'm saying is that it *is* a workflow problem- specifically that the "SLA communication hack" doesn't solve any problems *in isolation*. If the intent is to use the public notes as a communication, you also need to be able to notify the client when you create one. But I can see no way to solve that second problem using the available triggers. There is a catch-all "on ticket update" trigger, but it becomes incredibly noisy.
Given that, what is the use case for this hack? With this in place it will reset the SLA without notifying the client, which seems like a worse outcome than spamming the agents for using notes instead of emails.

**Comment by MrGeneration** [comment]
Please head over to the community.
This is not a bug - you're hijacking a closed issue for a bug that has been solved about a year ago.

I'm limitting th conversation to contributors only to reduce the noise on this issue.
Please don't get me wrong, I don't want to be inpolite, but please create a Post at the Community: https://community.zammad.org.
