### ISSUE TITLE
View into merged tickets

### ISSUE THREAD

**Issue by MamoulianDelacroix** [zammad/zammad#1904]
Hihi 👋

### Infos:
* Used Zammad version: 2.3.0-1520582300.fdc0abbe.xenial
* Installation method (source, package, ..): package
* Operating system: Ubuntu LTS 16.04
* Database + version: psql (PostgreSQL) 9.5.10
* Elasticsearch version: 5.5.1

I'm not quiet sure, if this really is a bug or just a missinterpretation.
Starting point:
Organisation: ACME
Shared: False

User 1
Organisation: ACME

User 2
Organisation: ACME

User 1 creats ticket#0001, User 2 creats ticket#0002. Each user can correctly only see his own tickets.
Now User 2 creats ticket#0003, which will be merged with ticket#0001. Now only User 1 can see the ticket and User 2 only get's a merged information. Shouldn't user 2 bee able to the ticket#0001, since his ticket got merged there?

Greetings

**Comment by thorsteneckel** [comment]
Hi @MamoulianDelacroix - No, this works as intended since your Organization does not share tickets and the customer of Ticket#0001 is User 1. So there is no cause for User 2 to have permissions on the Ticket. You have to be the customer or in the same (shared) Organization as the customer to get permissions.
Please refer to our [community board](https://community.zammad.org/) for technical questions.
