### ISSUE TITLE
Tickets gets reopened but is still showing state "pending reminder"

### ISSUE THREAD

**Issue by maggusf** [zammad/zammad#1946]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): package
* Operating system: CentOS
* Database + version: postgresql 9.2.23
* Elasticsearch version: 5.6.8
* Browser + version: Safari 11.1 (mac os)

### Expected behavior:

* website shows current state

### Actual behavior:

* website is showing old state, but history of ticket shows that it got re-opened

### Steps to reproduce the behavior:

1. create ticket by mail
2. set pending reminder 
3. send mail to answer this ticket to let it get re-opened

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by maggusf** [comment]
only to leave a screenie here .. 
![bildschirmfoto 2018-04-11 um 16 07 59](https://user-images.githubusercontent.com/35348993/38622356-4de41bec-3da3-11e8-912f-6a239193037f.png)

**Comment by muhammadn** [comment]
@maggusf I am unable to reproduce your problem.

From my end, what i can see is that, after replying the "pending reminder" ticket by email, that ticket state automatically sets to opened.

**Comment by muhammadn** [comment]
@maggusf Could you try it on our hosted zammad at https://zammad.com and try it out if you can reproduce this problem to make it easier for us to check it out?

Thanks!

**Comment by maggusf** [comment]
was not able to reproduce in testversion on zammad.com ...

**Comment by mbpws** [comment]
@maggusf Do not doubt yourself. I have the same, identical problem. When setting a reminder, there's no e-mail sent, the status stays on reminder, instead of open or so. 

In the meantime, I've tried to try and solve it with manually set triggers, but unfortunately that did not offer a solution either.

What I noticed is that as soon as you set up the reminder for the first time a notification is given in Zammad (web GUI), but not by mail. After that, the reminder does not work any more.
