### ISSUE TITLE
Customer cannot change and see his notification settings

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#1959]
### Infos:

* Used Zammad version: 2.3 & 2.4
* Installation method (source, package, ..): package (both)
* Operating system: Ubuntu 16.04 (2.3) & openSuse 43.2 (2.4)
* Database + version: unknown (2.3) & postgreSQL 9.6-1.1 (2.4)
* Elasticsearch version: unknown (2.3) & 5.6.6 (2.4)
* Browser + version: current Edge and Firefox (2.3) & Google Chrome 65.0.3325.181 (2.4)

### Expected behavior:

When setting "notification"-Setting for role "Customers" is set the customer should be able to edit his notification settings under profile.

### Actual behavior:

When setting "notification"-Setting for role "Customers" is set the customer is not able to change nor see his notification settings.

### Steps to reproduce the behavior:

* Go to Settings -> Roles and edit Role "Customers"
* Give the customer the right to edit his notification settings
* login as customer and see that you cannot see the settings

Setting is set:
![image](https://user-images.githubusercontent.com/6549061/38929534-e8816218-430c-11e8-9fbc-69a92aa7781e.png)

Customer sees the following options logged in as customer:
![image](https://user-images.githubusercontent.com/6549061/38929666-5d9d3586-430d-11e8-88d7-734ad9526d3a.png)

Same goes for admins taking a look at zammad as customer:
![image](https://user-images.githubusercontent.com/6549061/38929698-79ce3f0c-430d-11e8-9dbf-2d4c274a8b1c.png)

This Bug/Feature has been postet by xp8it on https://community.zammad.org/t/web-notification-for-customer-role/559

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by SummerStorm** [comment]
After discussions with the team, we decided that customers should not be able to view or change their own notification settings. The reason is that there is only a very limited number of options that they can choose from, and that there aren't many useful use cases where a customer would want to change any of these settings.

Certain settings are not applicable to the Customer role, like the notification setting from this issue, and also out_of_office. In the future, we plan to gray out these settings in the Customer Role edit screen to minimize the confusion about whether a setting is applicable or not. But this is a very low priority feature.  

![sdfsdf](https://user-images.githubusercontent.com/7030950/45610315-1d083680-ba8e-11e8-92ae-a82b349d37bf.png)

**Comment by andreaci** [comment]
How can we change those settings on ALREADY EXISTING USERS?
I know how to edit the settings file with default; but how can I change already existing customers?

**Comment by 3wherrmann** [comment]
Hello, with Zammad 6.3 its still not grayed out. I did spend some time to figure out why the setting is not working.

**Comment by MrGeneration** [comment]
> Hello, with Zammad 6.3 its still not grayed out. I did spend some time to figure out why the setting is not working.

This issue is 5 years old and closed as 'wont fix' and thus, from product perspective works as designed. Please post feature requests and technical questions on our community: https://community.zammad.org

![image](https://github.com/zammad/zammad/assets/6549061/00ea957b-bc4e-4c4e-a764-3979f10b163d)
