### ISSUE TITLE
Display of Twitter Messages

### ISSUE THREAD

**Issue by GreXXL** [zammad/zammad#1967]
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): rpm
* Operating system: ubuntu
* Database + version: 9.5.12
* Elasticsearch version: 5.6.9
* Browser + version: Chrome 65.0.3325.181

### Expected behavior:

* Complete Twitter messages displayed within Zammad / not only a short version with link

### Actual behavior:

* Only a excerpt is shown and you have to click t.co link within nearly every tweet (see screenshot). I am opening this issue as it seems that in #912 you mentioned that it should not be like this?

<img width="848" alt="bildschirmfoto 2018-04-21 um 14 40 03" src="https://user-images.githubusercontent.com/1630413/39084278-47707850-4573-11e8-8a47-a6a4f6ffd9a6.png">

### Steps to reproduce the behavior:

* Any tweet above aprox. 110 characters

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Happens above 140 characters :)

![image](https://user-images.githubusercontent.com/6549061/39085276-926fae86-4580-11e8-93d2-3b661230f3f5.png)

Conversation zammad used/displays: https://twitter.com/i/web/status/987683918366363650

**Comment by derN3rd** [comment]
Seems like the issue I had with direct messages.
I don't know if you can add a `full_text: 'true'` in https://github.com/zammad/zammad/blob/master/app/models/channel/driver/twitter.rb#L323 . If not you have to fetch `extended_tweet` instead of a classic one and then you could use the `full_text` prop on the response.
This is due the twitter changes with longer tweets https://developer.twitter.com/en/docs/tweets/tweet-updates#overview

I'm afraid I don't have time to look into this, but maybe this helps some of the core devs from zammad :)

**Comment by thorsteneckel** [comment]
A solution for this is currently not that easy because the used [twitter gem](https://github.com/sferik/twitter) doesn't support [the `tweet_mode: 'extended'`](https://github.com/sferik/twitter/issues/905) properly. However, there is a workaround to extract [the content](https://github.com/sferik/twitter/pull/848#issuecomment-329425006) which looks rather hackish to me.
I think we will wait till [twitter shuts down some of its APIs](http://apps-of-a-feather.com/) and [replaces them with new endpoints](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets). We probably need to change more then anyway.

**Comment by MrGeneration** [comment]
With 2.8 and the Twitter changes we applied, I didn't see this Problem any more.

@GreXXL Can you check if it's solved for you as well?

**Comment by MrGeneration** [comment]
We've received no further Feedback which why I suspect it has been fixed with 2.8. :-)
Closing now.
