### ISSUE TITLE
unprocessable mails

### ISSUE THREAD

**Issue by juergenp83** [zammad/zammad#1970]
### Infos:

* Used Zammad version: 2.4.x
* Installation method (source, package, ..): .deb
* Operating system: ubuntu 16.04
* Database + version: mysql 5.7.21
* Elasticsearch version: 5.6
* Browser + version: not related

### Expected behavior:
process regular customer emails
*

### Actual behavior:
zammad can't process very few emails;
max attachment size in setup is 100 mb
*

### Steps to reproduce the behavior:
no idea, that's my problem

sent two unprocessable emails + logs to support@zammad.com (EDIT @thorsteneckel: Ticket# 1018077 )
*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @juergenp83 - I just reviewed your files. I was able to import them without any errors. Then I looked into the logfiles. Those stated that your Zammad scheduler lost the connection to your MySQL server while processing the mail with the MessageID `058EDCCF2559FF4D93C54AF4577D5FB401EBDD85`. It probably has something to do with the (size?) of the attachment of the mail.
However, since the MySQL "stopped working" you have to check out the log file of the database. It is no Zammad issue in general or more of a related technical question. Feel free to open a topic over at our community board: http://community.zammad.org/

**Comment by juergenp83** [comment]
Hi Thorsten, thank you very much. The "max_allowed_packet" of mysql was way
too low. It's working now.

regards,
Jürgen

Thorsten <notifications@github.com> schrieb am Di., 24. Apr. 2018 um
16:49 Uhr:

**Comment by hamzehmohammadnia** [comment]
Hi,

I have faced a similar issue, and have set the "max_allowed_packet" to 104857600. However, I have seen many emails are not processed while their size is less than 3MB or sometimes around 25MB. I dont see the spamming probability since they are from valid DNS. Is there any reason for this?

**Comment by martini** [comment]
@hamzehmohammadnia 

there are usually 2 reasons for not being able to process email.

1) A temporally issue - e. g. database connection lost or something like that. In this case you can execute the following command to execute alle mail in tmp/unprocessable_mail/*.eml again:

`zammad run rails r 'Channel::EmailParser.process_unprocessable_mails'`

If mails are processed then, the issue was not with Zammad.

2) Permanently not processed
If the email are permanently not processed, there my be an issue which is Zammad. In this case we need to get the email which was not able to process to get the issue reproduced (and then solved).

 -Martin
