### ISSUE TITLE
Is it possible to add a new ticket state?

### ISSUE THREAD

**Issue by Guevarabrik** [zammad/zammad#1982]
Hi, 
I am having a problem with adding a new ticket state over the UI because the state value is not editable. 
I want to add 2 new states: waitingOnCustomer and waitingOnVendor. 
Is there any way to add those states over the UI? or over the souurce code?

thx

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

This issue was/is already addressed in other issues and community posts. You should be able to find them quite easy via the search functions.
