### ISSUE TITLE
Can't configure LDAP and "Counting entries" never ends

### ISSUE THREAD

**Issue by Wardrop** [zammad/zammad#2005]
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): Source
* Operating system: macOS 10.13.4
* Database + version: MySQL 5.7.19
* Elasticsearch version: N/A
* Browser + version: Chrome (latest)

### Expected behavior:
LDAP "configure" button should be enabled to allow configuration, and " Counting entries. This may take a while." shouldn't take forever.

### Actual behavior:
The "Configure" button on the LDAP settings screen remained "Disabled". If I edit the HTML in dev tools and remove the disabled attribute, I can configure LDAP, but then it never gets past "Counting entries. This may take a while.". I've left it overnight and the same thing.

### Steps to reproduce the behavior:
Clean install on macOS from source.

![screen shot 2018-05-09 at 10 22 42 am](https://user-images.githubusercontent.com/201442/39789409-04a8b1e6-5373-11e8-9b90-7c25d00453b2.png)

**Comment by thorsteneckel** [comment]
Hi @Wardrop - So you are saying that the configure button was always disabled and you were never able to click it?
Could you please reload the Zammad tab and have a look at your browser console. If there is an error, please provide a screenshot. Otherwise please provide your `log/production.log` file.

**Comment by Wardrop** [comment]
Correct. The "Configure" button is always greyed out as shown in that screenshot.

Here's a screenshot of the console.

![screen shot 2018-05-10 at 8 20 02 am](https://user-images.githubusercontent.com/201442/39842721-f995e054-542a-11e8-8319-b2148d4e2a6d.png)

I'm running Zammad using `rails s -p 3000`

**Comment by uli-heller** [comment]
I did a similar installation just a couple of days ago but on ubuntu. For me, the LDAP configuration worked really fine. By looking at the screenshot, I see these differences:

1. LDAP was deactivated on my installation (the switch right to the left of the headline LDAP)
2. I was able to configure LDAP while it was deactivated
3. I activated it after the configuration

Maybe you clicked on the activation switch before trying to configure it?

Best regards, Uli

**Comment by thorsteneckel** [comment]
I'm pretty sure this is caused by [not starting all Zammad services](https://docs.zammad.org/en/latest/install-source.html#start-zammad). Zammad will run much faster, send and receive messages etc. after you started  those. 
Please use our [community board](http://community.zammad.org/) for technical questions. Thanks!

**Comment by Wardrop** [comment]
I believe this is correct. I'm just re-installing zammad now, and will be sure to start all services this time.
