### ISSUE TITLE
Translation error - English: "from/to", German: "von/bis" should be "von/nach" at some places

### ISSUE THREAD

**Issue by uli-heller** [zammad/zammad#2008]
### Infos:

* Used Zammad version: 2.4.0
* Installation method (source, package, ..): source
* Operating system: ubuntu 18.04
* Database + version: mysql
* Elasticsearch version: 5.6.x
* Browser + version: Chrome

### Expected behavior:

* For example in ticket history, show "von ... nach ..."

### Actual behavior:

* "von ... bis ..."

![auswahl_203](https://user-images.githubusercontent.com/1677414/39855896-01f3948c-542e-11e8-984d-faad2d72d5cb.png)

### Steps to reproduce the behavior:

* Use German language
* Create a ticket
* Assign the ticket to a person
* Look at the ticket history

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @uli-heller this is caused by the decision to use english as a base language. This causes issues like this because of differing contextual meaning of a single word. This can't be changed that easy. I'll label this post as `refactoring` but don't expect to get a solution soon 😞 Thanks for reporting anyway.

**Comment by dominikklein** [comment]
History was improved and the output is like that: `updated Ticket Owner from '-' → 'Agent 1 Test'`
