### ISSUE TITLE
Telephone notify not clearing on leftside, the number of open calls are froozen

### ISSUE THREAD

**Issue by Newan** [zammad/zammad#2017]
### Infos:

* Used Zammad version: 2.4
* Installation method (source, package, ..): package deb
* Operating system: ubuntu 16.04
* Database + version: postgresql
* Elasticsearch version: n/a
* Browser + version: chrome

### Expected behavior:

* the number of calls in the left menu are the same as the open calls in the caller log

### Actual behavior:

* the number of open calls are froozen
![image](https://user-images.githubusercontent.com/3693094/39997032-c0bd88f4-5781-11e8-8086-24fea49bb75a.png)

### Steps to reproduce the behavior:

* Make an call to the caller log and clear the call with the checkbox

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
How to reproduce:

1) Enable sipgate.io via admin interface and press submit at the end of the page
2) Execute `curl http://localhost:3000/api/v1/sipgate/in -X POST -F 'event=newCall' -F 'direction=in' -F 'from=491715000000' -F 'to=4930600000000' -F 'callId=4991155921769858278-2'` to show an incoming call
3) Execute `curl http://localhost:3000/api/v1/sipgate/in -X POST -F 'event=hangup' -F 'direction=in' -F 'from=491715000000' -F 'to=4930600000000' -F 'callId=4991155921769858278-2' -F 'cause=busy'
` to reject because of busy
4) In the caller log an open call is shown. 

![cit_counter](https://user-images.githubusercontent.com/110226/40163460-1fdbb1d0-59b7-11e8-8819-7c00c919ef43.gif)
