### ISSUE TITLE
Incorrect reset after deleting single object-selection

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad#2020]
### Infos:

* Used Zammad version: 2.4 (SaaS)
* Browser + version: Google Chrome Version 66.0.3359.139

### Expected behavior:

* When deleting a selection option (format: select), the selection of existing tickets should be set to "zero".

### Actual behavior:

* The selection of existing tickets categorized with the selection to be deleted is set to any other selection after deletion. 

### Steps to reproduce the behavior:

- Create an object with format: Select (e.g.: Language: English, German, Spanish)
- Now define "Spanish" for a ticket
- Delete the selection "Spanish" in the object
- In the tickets "German" is now defined as language

**Comment by tkovs** [comment]
This only affects the tickets? This behaviour can be dangerous in the Zammad while a big system. I think that is important to check the scope of this behaviour. Someone can explains me the current situation?

**Comment by SummerStorm** [comment]
@tkovs This is caused by the lack of a default "null" option for select attributes. If you have a select attributes with two options, English and German, the drop down menu will automatically choose English even if you don't click, and Zammad will mistakenly think you have chosen English. 

I've written a fix for it and I'll discuss with the team on what changes I need to make before merging it. 

In the meanwhile an easy workaround would be to put a "None" option at the beginning of each select attributes, e.g. None, English, German.

**Comment by tkovs** [comment]
The point is that should not be possible to remove used elements from a list of objects, but the Zammad's team knows what is better.
