### ISSUE TITLE
"Body - Search for follow up also in Body" - greps wrong reference which results in wrong follow up (internal #1019027)

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#2038]
### Infos:

* Used Zammad version: latest 2.5 (dev)
* Installation method (source, package, ..): source
* Operating system: macOS
* Database + version: MariaDB
* Elasticsearch version: 5.6
* Browser + version: Safari

### Expected behavior:

* Zammad should search for exact ticket numbers only and not for every reference which CONTAINS the ticket number.

### Actual behavior:

* a given CSS value **"bgcolor=3D"#17346c"** matches ticket number **17346**

### Steps to reproduce the behavior:

* Create a new ticket and send a new HTML mail ticket to Zammad. This new ticket should use the new ticket number as a HTML element - value in the body. For examlpe

```HTML
<table  width=3D"610" class=3D"c100" border=3D"0" cellpadding=3D"0" cellspa=
cing=3D"0" align=3D"center" bgcolor=3D"#17346c" style=3D"margin:0 auto;"  >
            <tr>
              <td width=3D"610" class=3D"c100" height=3D"39" ><table width=
=3D"570" align=3D"center" class=3D"c95" cellpadding=3D"0" cellspacing=3D"0"=
 border=3D"0" ><tr><td style=3D"font-size:20px; color:#ffffff;
font-family:ArialMT, Arial, Helvetica, sans-serif;" align=3D"left" class=3D=
"font-size-14px">
=20
</td></tr></table></td>
  </tr>
</table>
```
Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rlue** [comment]
I'm only partially able to reproduce this issue. Here is what I found in my own testing:

* The entire string `"Ticket#nnnnn"` must be present in the subject (or body or whatever text is to be searched for the follow-up string) to update a ticket rather than create a new one. Partial/similar matches (_e.g.,_ `"Ticket #nnnnn"` or `"#nnnnn"`) are not recognized, and simply create a new ticket.
* Matches within HTML tags _are_ recognized (_e.g.,_ `"<a href="https://google.com/s?q=Ticket#nnnnn">Click me!</a>"`.
* Matches are not word-boundary sensitive (_i.e.,_ `"xTicket#nnnnnx"` updates an existing ticket rather than creating a new one).

I will get to work on points 2 and 3. If I'm incorrect or missing anything regarding point 1 (I'm looking at you @hanneshal), please let me know.

**Comment by thorsteneckel** [comment]
Hi @hanneshal @rlue 

Thanks to your analysis @rlue I was able to track the issue down on the customer instance. The configured value of the Setting `ticket_hook` is just `#` - not `Ticket#` (default). Therefore Zammad correctly matches the CSS color as a ticket number. Changing the behavior would lead to a unexpected behavior in other (more) valid cases.
Having a only `#` as the `ticket_hook` is IMHO not practical and should get changed instead.

Therefore I will close this issue as wontfix - no further actions needed @rlue 

@hanneshal can you please notify the customer?

**Comment by rlue** [comment]
@hanneshal, what value do you have stored for `Setting.get('ticket_hook')`?

**Comment by martini** [comment]
@thorsteneckel @rlue it's common to only use `#` as `ticket_hook`.  How about to perform followup search only on text and not html documents (in this case a simple htm.html2text)?
