### ISSUE TITLE
FYI its not possible to thumbs up a locked issue

### ISSUE THREAD

**Issue by lucaspottersky** [zammad/zammad#2109]
Hi,

just for your information,

its impossible to add a reaction to a [locked issue](https://github.com/zammad/zammad/issues/223), as asked by @thorsteneckel on [this comment](https://github.com/zammad/zammad/issues/223#issuecomment-344281684) 

sorry for creating an issue to point that out.

**Comment by thorsteneckel** [comment]
Hi, thanks for pointing that out. We currently have no better option than that. Otherwise people will create comments which result in hundreds of send emails for the repository watchers. Which is really distracting. Additionally the informational value is pretty low for this comments which is sad.
However, I made a mental +1 on that for you 👍
