### ISSUE TITLE
Telegram is not generating new Tickets

### ISSUE THREAD

**Issue by dcapape** [zammad/zammad#2116]
### Infos:

* Used Zammad version: 2.5.x
* Installation method (source, package, ..): package
* Operating system: Debian 8.10
* Database + version: 9.4.15
* Elasticsearch version: 6.3.0
* Browser + version: Chrome 67

### Expected behavior:

A new ticket to be opened

### Actual behavior:

The ticket is not opened. Elasticsearch is running, but there is a Delayed job trying to run recursively
`irb(main):038:0* Delayed::Job.all
=> #<ActiveRecord::Relation [#<Delayed::Backend::ActiveRecord::Job id: 11808, priority: 0, attempts: 3, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "Unable to process POST request to elasticsearch UR...", run_at: "2018-07-05 23:58:29", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2018-07-05 23:56:20", updated_at: "2018-07-05 23:57:03">, #<Delayed::Backend::ActiveRecord::Job id: 11806, priority: 0, attempts: 3, handler: "--- !ruby/object:BackgroundJobSearchIndex\nobject: ...", last_error: "Unable to process POST request to elasticsearch UR...", run_at: "2018-07-05 23:58:28", locked_at: nil, failed_at: nil, locked_by: nil, queue: nil, created_at: "2018-07-05 23:56:19", updated_at: "2018-07-05 23:57:02">]>

[log.txt](https://github.com/zammad/zammad/files/2168606/log.txt)

### Steps to reproduce the behavior:

* To set Telegram API
* To set Twitter API
* To delete Twitter API because is parsing as crazy random Tweets
* To delete Delayed Jobs Delayed::Job.delete_all
* To unset Telegram API
* To generate a new bot
* To set a Telegram API again

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @dcapape - this looks more like a list of different issues with your installation. So these are technical questions but Zammad issues. You can ask technical questions over at the [community board](http://community.zammad.org/). You can mention me and I'll see what I can do.

However, it seems that there is an issue with the Elasticsearch connection. Please run `Delayed::Job.where.not(last_error: nil).take&.last_error` on your Zammad console and post the output in your community board thread.
Please make sure to add your `log/production.log` file so we can reason about the Telegram issue.

To speed things up you can use the [commercial service](https://www.zammad.com/pricing).

**Comment by msickl** [comment]
Please help. I have the same problem here. The webhook is working but it doesn't show up any ticket inside zammad.

/opt/zammad/vendor/bundle/ruby/2.5.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
I, [2020-02-14T22:59:56.041949 #1452-47412973927260]  INFO -- :   Rendering inline template
I, [2020-02-14T22:59:56.042488 #1452-47412973927260]  INFO -- :   Rendered inline template (0.5ms)
I, [2020-02-14T22:59:56.042622 #1452-47412973927260]  INFO -- : Completed 422 Unprocessable Entity in 44ms (Views: 0.8ms | ActiveRecord: 10.4ms)
I, [2020-02-14T23:00:00.086526 #1452-47412973928140]  INFO -- : Started POST "/api/v1/channels_telegram_webhook/b9_Hvf9mhImqKA?bid=939119377" for 91.108.6.83 at 2020-02-14 23:00:00 +0100
I, [2020-02-14T23:00:00.094440 #1452-47412973928140]  INFO -- : Processing by ChannelsTelegramController#webhook as HTML
I, [2020-02-14T23:00:00.094571 #1452-47412973928140]  INFO -- :   Parameters: {"update_id"=>391543455, "message"=>{"message_id"=>43, "from"=>{"id"=>783717520, "is_bot"=>false, "first_name"=>"Martin", "last_name"=>"Sickl", "username"=>"m_sickl", "language_code"=>"de"}, "chat"=>{"id"=>783717520, "first_name"=>"Martin$
I, [2020-02-14T23:00:00.133830 #1452-47412973928140]  INFO -- : Enqueued SearchIndexJob (Job ID: cb5df845-acca-45cb-9e40-62b4eeb6afc8) to DelayedJob(default) with arguments: "User", 142
I, [2020-02-14T23:00:00.139199 #1452-47412973928140]  INFO -- : Won't enqueue SearchIndexJob (Job ID: c551e34b-d054-435e-a79e-07a695798061) because of already existing job with lock key 'SearchIndexJob/User/142'.
I, [2020-02-14T23:00:00.139308 #1452-47412973928140]  INFO -- : Enqueued SearchIndexJob (Job ID: c551e34b-d054-435e-a79e-07a695798061) to DelayedJob(default) with arguments: "User", 142
W, [2020-02-14T23:00:00.140278 #1452-47412973928140]  WARN -- : Scoped order is ignored, it's forced to be batch order.
E, [2020-02-14T23:00:00.147638 #1452-47412973928140] ERROR -- : Validation failed: Type is required but missing. (ActiveRecord::RecordInvalid)
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:80:in `raise_validation_error'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:52:in `save!'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `block in save!'
/opt/zammad/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:387:in `block in with_transaction_return
