### ISSUE TITLE
xml: [Errno 14] HTTPS Error 500 - Internal Server Error

### ISSUE THREAD

**Issue by iccamilo** [zammad/zammad#2119]
adding the repo skips the next error:

failure: repodata/repomd.xml from zammad: [Errno 256] No more mirrors to try.
https://dl.packager.io/srv/rpm/zammad/zammad/stable/el/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 500 - Internal Server Error

Site: https://docs.zammad.org/en/latest/install-centos.html

**Comment by thorsteneckel** [comment]
Hi @iccamilo - this is an issue with our packaging service packager.io. The builds for the `stable` branch [are all green](https://packager.io/gh/zammad/zammad/builds/3220/install/centos-7). However, this is usually a hickup and resolved within a few hours. If the error persists please create a topic over at [community board](http://community.zammad.org/) because we handle only Zammad (application code) specific issues over here on the issue tracker. Thanks!
