### ISSUE TITLE
LDAP: paging

### ISSUE THREAD

**Issue by merlinnot** [zammad/zammad#2122]
Hello, I've been looking around a little and I've not found any documentation about paging LDAP results. Is there such option or is it a feature request? :)

https://msdn.microsoft.com/en-us/library/aa367011(v=vs.85).aspx

**Comment by thorsteneckel** [comment]
Hi @merlinnot - We're tracking only issues here on the issue tracker (as stated in the initial issue text you removed). Please ask technical questions over at the [community board](http://community.zammad.org/).

Regarding your question: It seems like the the [support of paged results is still an open issue (sice 2011) for the gem we are using](https://github.com/ruby-ldap/ruby-net-ldap/issues/12). But when searching the code of that gem for `paged` you find different information about it and even some [special logic to handle the quirks of different LDAP servers](https://github.com/ruby-ldap/ruby-net-ldap/blob/36815b51581435af68c2a995e02d102159a17666/lib/net/ldap/connection.rb#L362).
However, there is not possibility for us to support paging since the gem we are using doesn't support it.

**Comment by merlinnot** [comment]
Thanks.
