### ISSUE TITLE
CTI: Unknown number matched to random users

### ISSUE THREAD

**Issue by raphaelm** [zammad/zammad#2143]
### Infos:

* Used Zammad version: 2.5.x (2.5.0-1531824466.f897e164.stretch from 07/17/2018)
* Installation method (source, package, ..): debian package
* Operating system: Debian
* Database + version: PostgreSQL
* Browser + version: Chromium 65

### Expected behavior:

* Unknown number is recognized as unknown and allows me to create a new user

### Actual behavior:

* Unknown number is matched to five random customers

See also: https://community.zammad.org/t/ticket-creation-from-cti-sipgate-view/1011/6

![2018-07-24-115056_1629x151_scrot](https://user-images.githubusercontent.com/64280/43133400-ed20213c-8f3e-11e8-8fcf-52cebc021940.png)

**Comment by martini** [comment]
@raphaelm thanks! Can add the information what Zammad Debian package version it exactly is? Because there was a change the last days. Thanks!

**Comment by raphaelm** [comment]
Version: 2.5.0-1531824466.f897e164.stretch

**Comment by martini** [comment]
@raphaelm thanks for feedback.

To clarify the feature first, Zammad has some logic to also discover articles (e. g. emails) or also user attributes like note and extract possible numbers. So in this case it seems that the number "+49 176 38..." has some associations with the people listed under "maybe/vielleicht". 

Can you verify that nobody of this users wrote an email to Zammad where the number "+49 176 38..." was listed in content or as user/organization attribute of the user?

PS: If there is a direct association with the phone number (because a user has stored in under "phone") then the "maybe" associations are not longer shown.

Thanks for feedback!

**Comment by raphaelm** [comment]
> Can you verify that nobody of this users wrote an email to Zammad where the number "+49 176 38..." was listed in content or as user/organization attribute of the user?

It's my personal cellphone number and in fact it's all people who at some point forwarded an email from myself to Zammad which contained it. This explains the selection.

Still, would be great to have a way to say "no, it's none of the suggested, but it is X or it is a new customer"

**Comment by martini** [comment]
>> Can you verify that nobody of this users wrote an email to Zammad where the number "+49 176 38..." was listed in content or as user/organization attribute of the user?
>
> It's my personal cellphone number and in fact it's all people who at some point forwarded an email from myself to Zammad which contained it. This explains the selection.

Thanks for that feedback! Here also a reference to an issue which would set the sender of and emails which got forwarded by an agent https://github.com/zammad/zammad/issues/1596 - this would work her to not show/identify your forwarded emails as your own "content" to associate with your user.


> Still, would be great to have a way to say "no, it's none of the suggested, but it is X or it is a new customer"

That's true. Currently this two possibilities are not implemented. But would be good to have it!

**Comment by martini** [comment]
I just created a new issue as FR https://github.com/zammad/zammad/issues/2144 and let this one untouched for documentation reasons.
