### ISSUE TITLE
2 Zammad Servers with 1 DB Server

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#2156]
Hi Support Team,

I was deployed two Zammad servers with one DB Server and it working.

But I confuse that, when the customer opencase/comment on Zammad-01, it didn't show  on Zammad-02. After I start new session on Zammad-02, I can see that opencase/comment from customer.

I don't know why.
Could you help me explain it and how to fix it ?

Thank You and Best Regards
Dat

**Comment by thorsteneckel** [comment]
Hi @tiendatdtvt - Zammad is currently [not stateless](https://github.com/zammad/zammad/issues/1601) it relies on the filesystem for the queueing of the Websocket data and has some internal memory cache which won't get invalidated. You can share the FS to get around most of the issues but the memory cache sticks. That's why it's currently not recommended to run multiple application servers. However, we're planning to resolve these issues soon. For further questions please refer to the [community board](http://community.zammad.org/) - otherwise more than 100 people will receive mails about each comment. Thanks for your understanding. Closing now.

**Comment by ghost** [comment]
Hi Zammad Team,

Thank you for you update information.

Best Regards,
dat
