### ISSUE TITLE
OTRS Migration Plugin unavailable

### ISSUE THREAD

**Issue by octomike** [zammad/zammad#218]
The installer directs a user to a download site for the Migration Plugin.

Unfortunately the link is dead, returning:

`{"error":"Package_contentlease contact http://znuny.com! 99983"}`

**Comment by thorsteneckel** [comment]
Hi @octomike - thanks for your feedback. The migrator can get downloaded via:

OTRS 5:
https://portal.znuny.com/api/addon_repos/public/617/latest

OTRS 4:
https://portal.znuny.com/api/addon_repos/public/383/latest

OTRS 3.1 - 3.3:
https://portal.znuny.com/api/addon_repos/public/287/latest

We will update the link in the migrator view ( https://github.com/zammad/zammad/blob/f2d0eca3da4d922b8ac4f741af30cacd0f39acd4/app/assets/javascripts/app/views/import/otrs.jst.eco#L10 ) as soon as possible.

**Comment by derboehsevincent** [comment]
So how long does this migraton takes? I only see 
![image](https://cloud.githubusercontent.com/assets/1434798/19553266/c5e03d80-96b3-11e6-873e-fc64c9e16557.png) this, (since 30minutes)

**Comment by octomike** [comment]
Thanks for the quick response regarding the otrs package.

Unfortunately we're stuck at the same step, after around 25 Users the migration simply stopped.

Where should I start looking for logs regarding the import/migration ?

**Comment by derboehsevincent** [comment]
The Debugwindows is showing this (App server startet with rails s -p 3000 -b IP), with changing values:
![image](https://cloud.githubusercontent.com/assets/1434798/19554216/e5b47a82-96b7-11e6-854d-f421e345e311.png)

Is this part of the migration process?

**Comment by monotek** [comment]
its also possible to do it from the comand line but i dont know how.
@martini could you provide the commands please?

**Comment by Julian0o** [comment]
I will try to migrate when i have a ldap connection. We have no users inside otrs but about 20k in our ldap/active directory.

But if there is a way to migrate some kind of manually, this would be the way i go i think.

**Comment by thorsteneckel** [comment]
Manual import is described here https://github.com/zammad/zammad/issues/238#issuecomment-255134136

If the import is still not working some logs from the `log/` dir would be great to get some track where we have to search.

**Comment by Julian0o** [comment]
@thorsteneckel But this will import everything i think. Or is there a way to choose what you want to import?

Just tried to install the Znuny repro. I think i will get a problem because i have Kix4OTRS running. 

`Can't install/upgrade package, file var/httpd/htdocs/js/Core.UI.InputFields.js already used in package KIX4OTRS-8.0.5!`

I think i first have to get rid of kix4otrs to test a migration. For this i first have to get another test machine with the same database and no kix removed.

**Comment by thorsteneckel** [comment]
Hi @Julian0o - Znuny4OTRS-Packages are not compatible with KIX(4OTRS), see https://github.com/znuny/Znuny4OTRS-Repo/issues/13
Since we can't rely on the KIX internal API as to the one of OTRS on which we rely heavily.

I don't think that we will provide an import for KIX. What we can do is to open source the importer and an open source hero can migrate it to KIX.

Currently it's not possible to import what you want since there are cross references (User -> Group -> Queue etc.) that are not that easy to split up.

**Comment by Julian0o** [comment]
@thorsteneckel if we will do the switch - we should give zammad several month to grow up - than it would be no problem to get rid of kix. 

We were thinking about the switch from OTRS 5 to KixDesk in the next year. The release of Zammad made the decision for us ;)

**Comment by monotek** [comment]
What should work is: 

Copy you KIX DB
Install a fresh OTRS 5.0.13.
Change Config.pm to point to your copied  KIX DB.
Restart Apache.
Check, if Apache starts and you can access OTRS.

On the commandline of OTRS machine:
/opt/otrs/bin/otrs.Console.pl Admin::Package::Install --force /tmp/Znuny4OTRS-Repo-5.0.13.opm
/opt/otrs/bin/otrs.Console.pl Admin::Package::Install --force /tmp/Znuny4OTRS-ZammadMigrator-1.2.1.opm 

On the commandline of Zammad machine:
Follow: https://zammad.org/documentation/migration/otrs

**Comment by thorsteneckel** [comment]
Download works now, too. See commit above. Closing this issue. Feel free to open new in any case.
