### ISSUE TITLE
Search with id:123 does not work anymore

### ISSUE THREAD

**Issue by membero** [zammad/zammad#2195]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): Debian Package
* Operating system: Debian 9
* Database + version: PostgreSQL 9.6
* Elasticsearch version: 5.6.10
* Browser + version: any

### Expected behavior:

* A search with id:123 will show objects with id 123.

### Actual behavior:

* A search with id:123 produces elasticsearch errors.
* A search with id:"123" works correct.

### Steps to reproduce the behavior:

* Search for id:123 in UI or use any API search request.

We upgraded from 2.4, no problems with that version.

Here is a snipped from the production.log:

Payload size: 0M
E, [2018-08-17T17:33:26.947875 #7020] ERROR -- : Unable to process GET request to elasticsearch URL 'http://127.0.0.1:9200/zammad_production/Ticket/_search'. Check the response and payload for detailed information:

Response:
#<UserAgent::Result:0x00007f2934d01a38 @success=false, @body="{\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\":\"Can only use prefix queries on keyword and text fields - not on [id] which is of type [long]\",\"index_uuid\":\"xxx\",\"index\":\"zammad_production\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"zammad_production\",\"node\":\"xxx\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"Can only use prefix queries on keyword and text fields - not on [id] which is of type [long]\",\"index_uuid\":\"xxx\",\"index\":\"zammad_production\"}}]},\"status\":400}", @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">

Payload:
{"from"=>0, "size"=>"10", "sort"=>[{:active=>{:order=>"desc"}}, {"updated_at"=>{:order=>"desc"}}, "_score"], "query"=>{"bool"=>{"must"=>[{"query_string"=>{"default_field"=>"group_id", "query"=>"\"1\" OR \"2\""}}, {"query_string"=>{"query"=>"id:123*", "default_operator"=>"AND"}}]}}} @data=nil, @code="400", @content_type=nil, @error="Client Error: #<Net::HTTPBadRequest 400 Bad Request readbody=true>!">

Yes I think this is a bug. It is no feature request or a general question.

**Comment by SummerStorm** [comment]
Hi there, thanks for the bug report. A fix for this will be available in the next version. 

In the meanwhile, if you need a triage you can replace `/opt/zammad/lib/search_index_backend.rb` with [this fixed version](https://gist.github.com/SummerStorm/b64c2c46fbd9257ccc48f125b449dba2).


## Detailed explanation

Before 597cd01b5a2a88f3b869d64c68ecd0d6f7c43874:
1. Elasticsearch creates indexes on the fly, and this automatic index was fairly "lax" 

2. `id:123` is considered a simple query so we append * to it.

3. `id:123*` is stilled considered a valid query by Elasticsearch since there was no restriction on the type of `id`

After 597cd01b5a2a88f3b869d64c68ecd0d6f7c43874:
1. 597cd01b5a2a88f3b869d64c68ecd0d6f7c43874 creates an index at Elasticsearch index creation time, locking down the type of `id` as integer

2. `id:123*` is no longer a valid query because wildcards cannot be used on integer indices

The solution is to consider all queries operating on numeric attributes (id, article_count, first_response_in_min, close_in_min) as complex queries and do not append * at the end. A fix is available at internal branch `private-bz_2195_search_with_id_fails`.

**Comment by SummerStorm** [comment]
Please note that starting with Zammad 2.7 the search behaviour will change slightly:

1. Any search query containing a `:` character will be considered a complex query and no wildcards will be appended at the end. Searching for `number:10` will only find tickets with that exact ticket number. `number:10*` will find tickets starting with 10.

2. Search queries without `:` will have the `*` wildcard appended at the end. Searching for `10` will yield all tickets starting with 10.
