### ISSUE TITLE
Unable to Close a specific Ticket

### ISSUE THREAD

**Issue by Noertward** [zammad/zammad#2212]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): Ubuntu via DEB
* Operating system: Ubuntu 16.04
* Elasticsearch version: 5.6.10
* Browser + version: Google Chrome 68.0.3440.106 (also checked with FF at another Computer)

### Expected behavior:

*I want to close a Ticket with the "State" Option, so im setting it to Closed

### Actual behavior:

*As soon i want to save the State, its changing to Closed and then back to open again.
The Ticket Event History dont even show, that the Ticket state has changed to Closed.

Ticketlogs:
- gerade eben
erstellt Artikel
aktualisierte Ticket state von 'closed' bis 'open'
aktualisierte Ticket last_owner_update_at '2018-08-28 08:32:26 UTC'

We also tried to merge the Ticket and maybe the error will be fixed, but instead there are 2 bugged Tickets .
### Steps to reproduce the behavior:

*Untill now i wasnt able to reproduce the Bug. New genereted Tickets are not effected by the Bug. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
This is most likely a misconfigured trigger. Please check your triggers. If the issue still persists please open a topic over at the [community board](http://community.zammad.org/). We/the community will find a solution. Closing now because every comment will send more that 100 emails to the watchers of this repository. Thanks for your understanding.
