### ISSUE TITLE
Supporter gets notification for own tickets in groups he doesn't have access to

### ISSUE THREAD

**Issue by SimJoSt** [zammad/zammad#2215]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): Docker?
* Operating system: Linux
* Database + version: 
* Elasticsearch version: 
* Browser + version: Google Chrome 68.0.3440.106 64bit

### Status
I use our Zammad setup as a customer, for internal tickets, as well as a supporter.
The tickets I create as a customer, belong to a group (accounting) I don't have access too as a supporter. And tickets in accounting are not accessible to customers.

### Expected behavior:

* I cannot see ANY tickets in the accounting group
* I don't get ANY notifications for tickets in the accounting group

### Actual behavior:

* I got a notification for one of the tickets I created via email in accounting.
* In the sidebar the ticket shows as `» Unauthorized «`
* When I click on it, no details are shown, but `X Opps.. I'm sorry, but you have insufficient rights to open this Ticket.`

### Steps to reproduce the behavior:

* Create at least two groups
* Create a user with access to one of those groups
* Restrict the other group, so no customers can see ticket details
* Open a ticket in the restricted group, via the same email address used for the created user

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @SimJoSt - Welcome to the community and thanks for your comprehensive write up. This is one side effect of #967. Your use case is currently not possible. I'll close this issue now but it's linked to the original one and we will cover the issue you described, too. Feel free to subscribe to the other issue to get notifications on our progress. Sadly there is no concrete timeline yet because it's a fundamental change where we have to change/test/validate a lot of use-cases and side-effects.
