### ISSUE TITLE
Office 365 SMTP

### ISSUE THREAD

**Issue by J44LKS** [zammad/zammad#2240]
Hi

I've looked through the other posts on this and I saw that it now states Zammad now works with Office 365 out of the box.  I've gone through those posts and nothing in there solves the issue.  I'm pretty technical on the network side of things and have some understanding of development (but nothing on the Ruby side).  

Things I've tried:

- Letting it try to connect automatically (out of the box)
- Manually putting in the settings
- Connecting to Office 365 via an SMTP relay (yes I have set this up correctly in Office admin)

I know user name / password are correct and I'm pretty sure it should just work with one of the above.

Below are the errors I get. (I've tried port 25 too).  Basically I'm just using standard configurations, nothing fancy.  I know Office 365 no longer supports older versions of TLS, so I'm starting to think it's that.  Any other ideas?

![image](https://user-images.githubusercontent.com/8283811/45742589-417d2380-bbf2-11e8-86de-b2dcdfe7bcea.png)
![image](https://user-images.githubusercontent.com/8283811/45742733-899c4600-bbf2-11e8-902d-b0c5b8c1807b.png)

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

**Comment by patstew** [comment]
FWIW, the answer to this is:
- Set up SMTP relay in 365 with your Zammad instance's public IP in the connector settings
- Address is YourCustomDomain-com.mail.protection.outlook.com
- Use a blank user and password
- Use port 25
- Most importantly and least obviously, in the Channel->Email->Settings tab change the from address for notifications to be noreply@domain.com instead of noreply@support.domain.com (or whatever subdomain you have zammad on). You must do this before attempting to add the SMTP server at all, or you'll get a misleading error message.
