### ISSUE TITLE
Notification in Zammad for Customer not shown

### ISSUE THREAD

**Issue by nk-Zammad** [zammad/zammad#2247]
### Infos:

* Used Zammad version: 2.6
* Installation method (source, package, ..): -
* Operating system: -
* Database + version: -
* Elasticsearch version: -
* Browser + version: Safari Version 11.1 (13605.1.33.1.2)

### Expected behavior:

*The customer opens a ticket. The agent receives the ticket and writes a public note in the ticket. 
  The customer receives a notification at Zammad bird.

### Actual behavior:

* The customer should receive a notification in his interface on the bird when the agent has publicly       updated something in the ticket.

### Steps to reproduce the behavior:

* Customer creates a ticket. Agent gets a notification at the bird and goes on the ticket. The agent writes a public note about the ticket and updates it.
The customer does not receive a notification on the bird that the ticket has been update

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by SummerStorm** [comment]
#1880 is related to this. Both are caused by public notes not being considered a ticket update.

**Comment by SummerStorm** [comment]
Hi, there. Customers do not receive notifications for public notes and this is by design. The reason is that the vast majority of customers receive updates via email only, and only log into Zammad to open new tickets. If we bombard the customers with notifications on each ticket update, then there will be lots of "unread" notifications the next time they log in, when in fact each of those notes have been sent to their email already. So these duplicate and outdated notifications will cause unnecessary confusion for the customer.
