### ISSUE TITLE
Login always redirected to dashboard after third party / OAuth2 login (e.g. Google)

### ISSUE THREAD

**Issue by SimJoSt** [zammad/zammad#2266]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): Docker?
* Operating system: Linux
* Database + version:
* Elasticsearch version:
* Browser + version: Google Chrome 68.0.3440.106 64bit
* Ticket #1083688

### Expected behavior:

* being logged out
* opening a direct link to a ticket
* login with Google
* see ticket

### Actual behavior:

* being logged out
* opening a direct link to a ticket
* login with Google
* see homepage

### Steps to reproduce the behavior:

* be logged out
* open direct link to ticket
* get redirected to login page
* login with Google

The ticket opens properly when login in via the normal credentials.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi @SimJoSt - I think this is a general problem with the OAuth2 flow (which is the base of the Google authentication). As far as I know it's possible to configure one (or more) valid redirect URLs in the Google OAuth2 application registration. These have to be hard coded URLs - usually the root path of the application. However, Zammad can't send the Ticket-URL to the Google OAuth2 application as the redirect URL because it won't be registered as a valid URL and an error will be thrown. Please correct me if I'm wrong.

It might be possible to use cookies to store the requested URL and redirect to it after a successful login.  We have to check this.

Anyway, this "works as designed" and is therefore an enhancement and no bug. (But maybe an usability bug ;)

**Comment by KervyN** [comment]
Hi, will there be a 'fix' any time soon?
It is super annoying to click on an email, login and the sit on the dashboard.

And gitlab show that this is possible.
