### ISSUE TITLE
Any user can be set as a replacement for out of office

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#2293]
### Infos:

* Used Zammad version: develop
* Installation method (source, package, ..): source
* Operating system: CentOS 7 
* Database + version: PostgreSQL 9.5
* Elasticsearch version: 5
* Browser + version: n.a.
* Ticket#: 1050074, 1081054 

### Expected behavior:

* Selecting another agent as a replacement when out of office.

### Actual behavior:

* Any user in the is offered and can be set as a replacement.

### Steps to reproduce the behavior:

* Go to preferences, select Out of Office and search for any user.

If this behavior is on purpose I suggest to show only agents to agents and customer of the same organizations to customer.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by maysam** [comment]
@thorsteneckel 
Customers don't have out of office preferences. Are we trying to limit agents to use other agents from their own organization?

**Comment by thorsteneckel** [comment]
@maysam  Nice catch! Agents should be able to select from all available agents without a limitation.

**Comment by maysam** [comment]
@thorsteneckel so there is not much to do, is there? customer don't have 'out of office' preferences

**Comment by thorsteneckel** [comment]
It's currently possible for an agent to chose a customer as an OOO replacement. That's what @rkaldung meant with "any user".

**Comment by maysam** [comment]
Right, agents only choose agents, should there be a limitation on admin users or that doesn't matter much?

**Comment by thorsteneckel** [comment]
As you already pointed out earlier this view is only available to a subset of users. This subset should be available in the selection.

**Comment by martinvonwittich** [comment]
I thought I'd take a shot at this. This is what I've found:

- `app/assets/javascripts/app/controllers/_profile/out_of_office.coffee` builds the out of office user interface; it uses a `user_autocompletion` UI element for the user selection
- `app/assets/javascripts/app/controllers/_ui_element/user_autocompletion.coffee` - uses `App.UserOrganizationAutocompletion` to render the user selection
- `app/assets/javascripts/app/lib/app_post/_object_organization_autocompletion.coffee` does the actual work

It takes the term the user entered and submits it to ElasticSearch, by default to `#{@apiPath}/search/user-organization`.

That just seems to be the generic search API that is also used by the search box on the upper left of Zammad. The `user-organization` limits the results to users and organizations. The way it currently works there seems to be no way to limit the results to agents.

I decided that the proper way to fix this is to modify the search query immediately before it is passed to ElasticSearch. This is what I've come up with:

``` diff
zammad@martin ~ (develop) % git diff -w
diff --git a/app/assets/javascripts/app/controllers/_profile/out_of_office.coffee b/app/assets/javascripts/app/controllers/_profile/out_of_office.coffee
index 8f796f715..5bd3385f7 100644
--- a/app/assets/javascripts/app/controllers/_profile/out_of_office.coffee
+++ b/app/assets/javascripts/app/controllers/_profile/out_of_office.coffee
@@ -75,6 +75,8 @@ class Index extends App.ControllerSubContent
             translate: false
             disableCreateObject: true
             value: @localData
+            source: "#{@apiPath}/search/user"
+            mangle_query_callback: (query) -> "permissions:ticket.agent #{query}*"
           ]
       noFieldset: true
       params: @localData
diff --git a/app/assets/javascripts/app/lib/app_post/_object_organization_autocompletion.coffee b/app/assets/javascripts/app/lib/app_post/_object_organization_autocompletion.coffee
index 58e941f65..ec7f4bd18 100644
--- a/app/assets/javascripts/app/lib/app_post/_object_organization_autocompletion.coffee
+++ b/app/assets/javascripts/app/lib/app_post/_object_organization_autocompletion.coffee
@@ -345,6 +345,8 @@ class App.ObjectOrganizationAutocompletion extends App.Controller
       @lazySearch(query)

   searchObject: (query) =>
+    if @attribute.mangle_query_callback?
+      query = @attribute.mangle_query_callback(query)
     @ajax(
       id:    "searchObject#{@key}"
       type:  'GET'
```

- The `source: "#{@apiPath}/search/user"` ensures that it won't match organizations anymore.
- The `mangle_query_callback` callback allows the controller to mangle the query just before it is passed to ElasticSearch, and I use it here to prepend the search query with `permissions:ticket.agent` so that it only matches agents. I also have to append `*` to the query then because `append_wildcard_to_simple_query` will only do this automatically as long as the query doesn't contain `:`.

It works, but I'm not sure if this is proper way to fix it. Any thoughts?
