### ISSUE TITLE
Search result sort order is wrong

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2298]
### Infos:

* Used Zammad version: 2.6.x
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: n/a
* Ticket-ID: #1026240

### Expected behavior:

* When searching for tickets (no matter if the result is two or more) the search is ordered by last update of the ticket itself.

### Actual behavior:

* When searching for tickets (no matter if the result is two or more) the search is ordered by last update of the organization get's updated, the ticket gets touched too. This will result in a wrong sort order.

### Steps to reproduce the behavior:

* Create at least two customers with each having their own organization
* Get some tickets that have been created on different times (by randomly of those two users) (it's easier when you've got atleast an hour between the tickets, or you just rock the rails c :)
  Ideally your sort order will randomly show both organizations in the result
* Search for both organization with an OR (in my case AniMaCo and MMC - MMC was rather below AniMaCo)
* Now update one organization (in my case MMC) [a note is enough!]
* do the same search query again.
  => All tickets of that updated organization will be above the other

![image](https://user-images.githubusercontent.com/6549061/47210888-723cae00-d394-11e8-91b6-1b731d65b481.png)

![image](https://user-images.githubusercontent.com/6549061/47210895-77016200-d394-11e8-8f55-701e12f4db99.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by SummerStorm** [comment]
@martini and I had a discussion over this. Currently whenever an organization is updated, all associated tickets are updated as well, thus causing this "incorrect" search result. 

All associated tickets are currently updated as a band-aid fix to another issue (let's call it issue B): if you have an overview open with the Organization column visible, an update to the organization isn't reflected in the overview. The band-aid fix touches all associated tickets, and thus forces all rows to re-render, so that the Organization column is correctly updated.

Since the current band-aid fix for issue B is causing confusion in other areas, and is effectively trashing `updated_at` of tickets unnecessarily, we are looking at a more proper solution:

**Proposal 1**
Since organizational changes are relatively infrequent compared to other objects, a lightweight solution is to broadcast a message to all currently connected clients saying: "Organization X has been updated, please refresh your browser for the latest data." This avoids having adding an event listener for each row of each overview. 

Advantages: 
- Lightweight, minimal code changes
- No database changes

Disadvantage:
- Slight user inconvenience
- This makes Organizations a special case, requiring a manual browser refresh, whether as all other objects update automatically and silently

**Proposal 2**
Since the `updated_at` attribute of tickets is being used for another purpose, we added a new column `last_update` to the Ticket table to mirror ticket updates. All Activerecord changes are reflected `last_update` except for those ones from an Organization update. This way `last_update` keeps track of only the "true" ticket updates and thus will sort correctly.

Advantages: 
- No manual browser refreshes required by the user, better user experience

Disadvantage:
- Adds a new column to the Ticket table
- Lots of backend changes required

**Comment by SummerStorm** [comment]
Just a quick update: @martini and I decided to go with Proposal 1. 

Currently, updates to User, Organization, and Ticket triggers updates to neighborhood objects. We're limiting Proposal 1 to only changing the update behavior of User and Organization.

The update behavior of Tickets will stay the same, i.e. updates to a Ticket will touch its neighborhood User and Organization objects. We found this behavior desirable, because when you search organizations, we want list the organizations with which we had the most recent contact first, and this "recent contact" is closely captured by ticket updates.

**Comment by rolfschmidt** [comment]
Hi,
the root issue of this problem is the following issue: https://github.com/zammad/zammad/issues/2911

In the future the associated data will not get touched anymore and this will correct the search result order hopefully. The update of associated data will only update the elastic search index and have no related database changes or touches.

Best regards,
Rolf
