### ISSUE TITLE
Rights management

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#231]
At the moment I miss roles which enables me to add users to multiple groups at once.

It would also be helpful to have rights like rw, ro, note, move and so on...

**Comment by dynamicman36** [comment]
+1
And also an Overview where you can tick these rights. So that you don't have to switch to every user and give them permissions. If you have 200+ users, it would be very hard to do so for every user.
A main user permission overview would be great with these rw ro, etc. rights to check (like in otrs)

**Comment by monotek** [comment]
Available in 2.0
