### ISSUE TITLE
Status Code 422 on viewing tickets, new install

### ISSUE THREAD

**Issue by unquietwiki** [zammad/zammad#2314]
Status Code: 422. {"error":"PG::UndefinedTable: ERROR: missing FROM-clause entry for table \"groups\"\nLINE 1: ... $2 AND (\"groupsusers\".\"access\") IN ($3, $4) AND \"groups\".\"...\n ^\n: SELECT 1 AS one FROM \"groupsusers\" WHERE \"groupsusers\".\"userid\" = $1 AND \"groupsusers\".\"groupid\" = $2 AND (\"groups_users\".\"access\") IN ($3, $4) AND \"groups\".\"active\" = $5 LIMIT $6"}

Using Zammad 2.8, with [Ruby 2.5](https://community.zammad.org/t/ruby-2-5-preparation/1490) & PostgreSQL 9.6. Everything is nice & slick, so it seems. But creating the database, I had to create an empty one manually; then use db:migrate, since db:create wouldn't work against an existing database (and the system wouldn't create a database otherwise). Either one of the tables didn't populate, or the query is defective (groupsusers vs groups_users vs groups).

**Comment by thorsteneckel** [comment]
Please read our intro text before creating issues. This is not an issue but a technical question. You can ask questions over at https://community.zammad.org/ - Closing now.

**Comment by unquietwiki** [comment]
@thorsteneckel per #2313 & this, I forked the code; cleaned it up; made sure the database created correctly (best as able); and still running into that error message. If you think it's of your interest, I'd like you or someone to give it a spin & see if it's just Google Cloud being silly. I've got another associate pushing me to use Samanage, so getting some version of this working would be useful. Thanks!

- https://community.zammad.org/t/ruby-2-5-preparation/1490/2
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422

**Comment by thorsteneckel** [comment]
Dear @unquietwiki ,

first of all, many thanks for your participation on the Zammad open source project.

Not usual as with proprietary software, we finance Zammad through service. We're happy to help where we can but setup issues for self hosted installations without a support contract are out of our scope. Because it's less money we have at our disposal to push Zammad.

If you would like to support Zammad, you can do so via Zammad Support: https://zammad.com/pricing#selfhosted

We're currently not working on Ruby 2.5, Rails 5.2 and Elasticsearch 6 support but will somewhere soon. However, please (once again) please use our [community board](http://community.zammad.org/) for questions because comments on the issue tracker will send emails to more than 100 people.

Thank you for your understanding.
