### ISSUE TITLE
Agent sends email to another group gets assigned the wrong customer name

### ISSUE THREAD

**Issue by KINGRULZ** [zammad/zammad#2322]
Infos:
Used Zammad version: 2.8
Used Zammad installation source: (source, package, ...)
Operating system: Ubuntu Server 18.04 lts
Browser + version: Chrome
Expected behavior:
incoming mails should be associated to correct customer

Actual behavior:
I set up a mailbox (e.g. Helpdesk@mycompanyname.com) in our internal mail system.
zammad is catching the emails from the inbox of helpdesk with imap and creates a ticket in group helpdesk.
That works as expected!

If an external user (i.e. testuser@googlemail.com) sends a email to helpdesk (helpdesk@mycompanyname.com) everything if fine.
zammad is pulling the mail out of the inbox of "helpdesk" and creates a ticket.
This ticket is correctly created for customer "testuser@googlemail.com".

But if an internal user (user@mycompanyname.com) sends an email to this mailbox "helpdesk@mycompanyname.com", something is going wrong!

zammad is correctly pulling the email out of the inbox of "helpdesk" and creates a ticket.

But this ticket is not created for user@mycompanyname.com!
Instead zammad created the ticket for "helpdesk@mycompanyname.com".

This means every ticket of internal users get assigned to customer "helpdesk" instead of the individual internal users.

Do the described setup.

Additional Info

i have seen this issue in version 1.6  but was resolved i believe but am now getting it in a newer version

**Comment by thorsteneckel** [comment]
Hi @KINGRULZ - please provide a RAW email file so we can reproduce it. You can download the file from below the article itself. Do I understand you correctly that this worked as expected before Zammad 2.7 and just changed after the update?

**Comment by KINGRULZ** [comment]
Hi @thorsteneckel 

actually i found this issue https://github.com/zammad/zammad/issues/1351

this ticket says it was resolved in an update 

but have the same problem 
[test 2.txt](https://github.com/zammad/zammad/files/2528521/test.2.txt)

**Comment by thorsteneckel** [comment]
Hi @KINGRULZ - this looks more like a technical question to me. Could you please create a topic over at the [community board](http://community.zammad.org/) and provide the real email. Your example is broken (there are not To and From addresses). Please try to reproduce the issue in one of our [free hosted instances](https://www.zammad.com/getting-started) and make sure to provide the name of the instance in the community board topic. We can create/update this issue after we know for sure how to reproduce it. Otherwise each comment here will send an email to over 100 people. If you need [commercial support](https://www.zammad.com/pricing#selfhosted) please let us know. Closing now.
