### ISSUE TITLE
Role-Filter shows inactive Roles

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2332]
### Infos:

* Used Zammad version: 2.7
* Installation method (source, package, ..): n/a
* Operating system: n/a
* Database + version: n/a
* Elasticsearch version: n/a
* Browser + version: Google Chrome 70, Firefox 62

### Expected behavior:

* When setting a role to inactive, the role filter inside the users GUI won't be shown for that role.

### Actual behavior:

* When setting a role to inactive, the role filter inside the users GUI will be shown for that role.

### Steps to reproduce the behavior:

* Create a test role and set it to inactive
* go to users and see that the role will be shown as filter

![image](https://user-images.githubusercontent.com/6549061/48021263-655fde80-e138-11e8-97d9-2db8346c275c.png)

![image](https://user-images.githubusercontent.com/6549061/48021278-6f81dd00-e138-11e8-835f-03013bbfbe84.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Charburner** [comment]
I would like to add an idea to improve the UI:

If you are working with many different roles in your Zammad instance, the "manage users" view will be kind of awkward since there is no linebreak. So you will always have to scroll to the right manually to be able to click those last roles.

It would be better to either add linebreaks or switch to something like a dropdown list with multiselect.

**Comment by thorsteneckel** [comment]
Hi @Charburner - Thanks for pointing this out. However, this is a different UI issue. Would you mind creating a new issue and provide a screenshot so we can have a visual impression of the case. Thanks. My UI colleagues will then find a proper solution 👍
