### ISSUE TITLE
Exchange Integration Folder access

### ISSUE THREAD

**Issue by Chritzz** [zammad/zammad#2338]
### Infos:
Used Zammad version: 2.7.0
Used Zammad installation source: DEB
Operating system: Ubuntu 16.04 LTS
Browser + version: Firefox

### Actual behavior:

Zammad can not access Exchange 2010.
Credentials checked multiple times.
EWS interface to Exchange checked.

![zammad](https://user-images.githubusercontent.com/44860414/48183971-d79b1380-e330-11e8-82ee-31441eeebfb8.PNG)

production.log

I, [2018-11-08T08:03:55.183741 #973]  INFO -- : Started POST "/api/v1/integration/exchange/folders" for 127.0.0.1 at 2018-11-08 08:03:55 +0100
I, [2018-11-08T08:03:55.193851 #973]  INFO -- : Processing by Integration::ExchangeController#folders as JSON
I, [2018-11-08T08:03:55.193930 #973]  INFO -- :   Parameters: {"endpoint"=>"https://***********.de/EWS/Exchange.asmx", "user"=>"edv@****.de", "password"=>"[FILTERED]"}
W, [2018-11-08T08:03:55.471810 #973]  WARN -- : Could not retrieve folders. ErrorAccessDenied: Der Zugriff wird verweigert. Überprüfen Sie die Anmeldeinformationen, und versuchen Sie es dann erneut. (Viewpo$
/opt/zammad/vendor/bundle/ruby/2.4.0/gems/viewpoint-1.1.0/lib/ews/folder_accessors.rb:167:in `find_folders_parser' ...

Checked by:
https://testconnectivity.microsoft.com

![exchange](https://user-images.githubusercontent.com/44860414/48183771-21372e80-e330-11e8-9df2-bab0406e2c07.PNG)

**Comment by thorsteneckel** [comment]
Hi @Chritzz - This is rather a technical question than a problem on the Zammad side. You can ask technical questions over at the [community board](http://community.zammad.org/). Closing now.

The message in the log file only states that there is (at least) one folder for which the user has no access. It's just a warning, no error. The error however states that there was an internal server error on the Exchange side. So you have to check the logs of the Exchange server rather than the one of Zammad. This is out of our scope.
