### ISSUE TITLE
Error mail reply

### ISSUE THREAD

**Issue by bmaurizio** [zammad/zammad#2387]
Used Zammad version: 2.7.x
Operating system: Ubuntu 16.04

Hi community,
The account email in zammad doesn’t work for me,
first I thought it was a mail problem but when I tried with another email the problem has not changed.
Essentially when I receive an email, zammad places it in the system, but when I answer or change the status of the ticket, zammad does not send email to the user’s mail.
When the user create a ticket zammad send the creation email to agent but not to user, when the ticket is updated zammad does not send the mail to the user and also to the agent with the change made (example: reply)
HELP ME please

**Comment by thorsteneckel** [comment]
Hi @bmaurizio - I already saw [your post](https://community.zammad.org/t/account-email-sender-not-work/1661/5) in the [community board](http://community.zammad.org/). Please respect the time of other people. We're giving our best to get the most value for all of the Zammad users out there from the time we have.
If your problem is as urgent as it seems consider our [commercial support](https://zammad.com/pricing).
