### ISSUE TITLE
TLS/SSL for SMTP with exchange 

### ISSUE THREAD

**Issue by derboehsevincent** [zammad/zammad#240]
Where are the settings for TLS/SSL? I can't connect to my exchange:
504 5.7.4 Unrecognized authentication type.

**Comment by MDXDave** [comment]
![image](https://cloud.githubusercontent.com/assets/6099976/19564111/bba6708a-96e2-11e6-8445-d55fab6c9f30.png)

**Comment by thorsteneckel** [comment]
Hi @derboehsevincent - could you please provide further information about your setup? Which server do you wan't to reach, what is the auth type, where is this log message from, is a stacktrace or further log output available?

**Comment by cice** [comment]
I have the save problem. 
The form should be extended to allow configuration of port (different than 25) and starttls true/false. 
Exchange / Office 365 only accepts TLS connections, and only on port 587, but without the possibility to configure it, Zammad would always try port 25.

**Comment by cice** [comment]
It basically works like this: https://github.com/kayoom/zammad/commit/ffda858be71d20344f570b4a19395954940eca34
where i put our authentication domain into "Domain", set "Port" to 587, and "Authentication" to "Login"

**Comment by martini** [comment]
@cice wow!

**Comment by thorsteneckel** [comment]
@cice nice! Thats why I love the open source community so much. Could you create a pull request for this?

**Comment by cice** [comment]
Yes, i'll try to get a grip of the tests structure at the weekend and then prepare a PR. cheers!

**Comment by cice** [comment]
i cant get any of the tests to run. is there some documentation about prerequisites for running the tests? i dont know, if my changes break any tests, and i would like to extend the tests to cover my changes.

**Comment by martini** [comment]
@cice Thanks for the really good preparation. I'll try to improve the wizard to detect the needed authentication, domain and so on automatically too.

**Comment by martini** [comment]
@cice We improved the email wizard to detect possible auth types from smtp server and use one working. So it's easier for normal users to integration (because the do not need to select authentication type).

I'm just not sure about "port" and "domain".

Port: I tested against Office356. There is no need to change the port (because TLS is possible via port 25)

Domain: IMO domain is also not needed to be changeable (the domain is used for SMTP helo command, we changed it to fqdn of Zammad installation).

**Feedback from your side if the port needed to be changeable would be fine.**

**Comment by martini** [comment]
We also created a pull request for Net::SMTP https://github.com/ruby/ruby/pull/1474

**Comment by martini** [comment]
Fix for exchange SMTP issues https://github.com/zammad/zammad/commit/db2b32933162ef6098d9249750283c6003c765ff - works with Office365 out of the box now.

**Comment by cice** [comment]
Thanks, i'll test it on our end. Since we had problems getting Office365 to work with Rails / Ruby before, i just "ported" the settings from our own apps, that i know would work.
If port 25 works, thats good; But i would keep the port option anyway, so users with an exotic mail server configuration won't be locked out.

**Comment by jacotec** [comment]
No issues here with Zimbra and Kerio as mail servers ... but I know that at least some public services need to be connected on port 587 for customer's SMTP auth. I'd keep a configurable port option or the FQDN format "smtp.mailserver.de:587" in my mind ;-)

**Comment by babakkazemi** [comment]
Works fine in "Accounts" section, but in "Notifications" i can't enter a port number for SMTP
