### ISSUE TITLE
E-mail content can't be access (winmail.dat)

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#2403]
### Infos:

* Used Zammad version: develop
* Installation method (source, package, ..): source
* Operating system: CentOS 7
* Database + version: PostgreSQL 9.5
* Elasticsearch version: 5
* Browser + version: any
* Ticket-ID: #1057853, #1078916, #10156723

### Expected behavior:

* The complete e-mail content can be read.

### Actual behavior:

* In some e-mails, usually from MS Outlook, the content is only available in an attachment, named winmail.dat, and can be processed inside Zammad.

### Steps to reproduce the behavior:

* Send an e-mail from MS Outlook with inline screenshots.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by monotek** [comment]
Sounds familiar to me :D
https://bugs.otrs.org/show_bug.cgi?id=4639

**Comment by kevin-olbrich** [comment]
I have hit this problem once or twice on our prod instance.
Actually only outlook users can open RTF mail. For example, in germany there is also "Tobit David" which is rather popular (I don't like it) and does not support RTF either. Most large email providers here just display the message exactly as you described.

I think it's worth fixing this but people who send RTF emails instead of text or text+html will always limit the clients who are able to process such emails.

With Exchange 2016 + Outlook 2016 I am unable to reproduce your problem. Do you use the "Snipping Tool"? If I use it and press the "send via email"-button, I get a new message and it is sent with inline images using HTML. The display is also correct in the new article.

**Comment by maxxer** [comment]
All mails from Outlook users we receive are missing attachments :(

**Comment by MrGeneration** [comment]
@maxxer please don't hijack other issues.
Your issue rather sounds like a technical question, please post technical questions over at the Community: https://community.zammad.org


If we later discover that you're experiencing a bug, we'll post an Issue here. :-)


I'm locking the conversation to contributors only, because this issue hasn't had any further Feedback within several month. Please don't get me wrong, this is to keep the noise of this repository as low as possible. :-)

**Comment by YetAnotherGerrit** [comment]
> Messages sent from incorrectly configured Microsoft Outlook/Exchange email clients may contain a file attachment called winmail.dat. This attached file contains formatting information for messages that use Microsoft's proprietary TNEF standard, plus any attachments sent with the original message. The TNEF file is not recognized by other email clients, so any attachments sent with the original message are not displayed in Thunderbird's message pane.

Source: https://support.mozilla.org/en-US/kb/what-winmaildat-attachment

We will follow the example of Thunderbird and almost all other e-mail clients and will not support Microsoft's proprietary TNEF format. Please ask the sender to fix their e-mail client/server settings.
