### ISSUE TITLE
Print dialog does not show article visbility

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2430]
### Infos:

* Used Zammad version: 2.8 + develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Google Chrome and Firefox

### Expected behavior:

* When printing a ticket (for whatever reason), Zammad will show all needed article information. An important information might be, the type of visibility at that moment (e.g. public or private).

### Actual behavior:

* When printing a ticket dialogue, the visibility information is being lost.

### Steps to reproduce the behavior:

* create a new ticket
* add at least one private and public article (type does not matter)
* try to print the ticket

![image](https://user-images.githubusercontent.com/6549061/51121796-97687d80-1818-11e9-9485-cc5d4ff14124.png)

![image](https://user-images.githubusercontent.com/6549061/51121806-9afc0480-1818-11e9-90c6-5b13947aa266.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martinvonwittich** [comment]
While you're at it - it would be fantastic if staff agents had the choice between including internal comments in the print view, or excluding them. At the moment Zammad doesn't support forwarding complete tickets with all postings (it's only possible to foward single postings), and a print view without internal comments might be a useful workaround.

**Comment by mrflix** [comment]
The simplest technique would be to add our internal border:

![image](https://user-images.githubusercontent.com/60777/59850145-d2438400-9369-11e9-8b13-1b98ff54e64d.png)

Do you think that would be good enough?

The option to hide internal comments for printing would require UI, so it has to determined if that's relevant enough for a big user group so that its worth the effort. A button to toggle showing internal comments could be interesting outside the print content and if its built for that the print css could honor that setting and toggle the internal comments as well.

**Comment by martini** [comment]
> The simplest technique would be to add our internal border:

I like this!

**Comment by MrGeneration** [comment]
I like that approach as well. You can clearly see a visual difference which is actually the same as in the UI itself (well.. except for colors ;) )
