### ISSUE TITLE
Hosting zammad on Amazon Web Services AWS

### ISSUE THREAD

**Issue by manuelfink** [zammad/zammad#2457]
Has anyone experiences on hosting Zammad on Amazon Web Services?
Is any installation recommended?

My idea is to have it highly available hosted:

- App: Elastic Beanstalk or Docker
- MySQL DB: Aurora serverless as DB 
- Elastic Search through elastic cache
- S3 as file storage #660 - not yet implemented
- [EFS](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/services-efs.html) as alternativ to S3

This also can be seen as a feature request. A cloud formation script would be amazing ;-)

**Comment by monotek** [comment]
Hi there - thanks for filing an issue. Please ensure the following things before creating an issue - thank you! 🤓

Since november 15th we handle all requests, except real bugs, at our community board.
Full explanation: https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21

Please post:
- Feature requests
- Development questions
- Technical questions

on the board -> https://community.zammad.org !
