### ISSUE TITLE
Uploading attachments >50 MB in web interface does not work and does not throw error

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2477]
### Infos:

* Used Zammad version: 2.8.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version:
* Elasticsearch version:
* Browser + version: Latest Firefox

### Expected behavior:

* Error message when trying to upload file larger than currently set max file size limit.
Also if possible being able to edit max file size limit. If I understood correctly this is currently not possible and hard cap seems to be around 50 MB.

### Actual behavior:

* Agents and users try to upload attachment >50 MB. Upload progress bar shows 100 % immediately without any error message:
![image](https://user-images.githubusercontent.com/44224243/52847104-98d4e080-310b-11e9-9fff-e0e9aef23d29.png)
Also Ticket Update field is greyed out and no discard changes field showing so to get a working interface again browser side must be refreshed.
When uploading the attachment via drag and drop it is not greyed out and you get at least the option to discard changes without need to refresh the browser. However with drag and drop same 100% progress bar without error message.

### Steps to reproduce the behavior:

* Create ticket
Try to upload attachment via web interface smaller than 50 MB-> works
Try upload attachment smaller than 50 MB-> shows behaviour described above.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by ghost** [comment]
Hi @SEGGER-NV did you try to increase the default limit in nginx configuration?

/etc/nginx/conf.d/zammad.conf
client_max_body_size 50M;

**Comment by SEGGER-NV** [comment]
Hello,

Thank you for the hint. We have not tried editing that value yet.
But our issue is not that it has a fixed limit. The issue is that web interface users get no information when it fails and e.g. customers assume the upload was successful and wonder why the attachment is not in the ticket. So error information for the users is missing here.

**Comment by MrGeneration** [comment]
Right now I'm not really sure if this is really a bug...
It's working fine with apache (so it's rather a problem in combination with the webserver)

![image](https://user-images.githubusercontent.com/6549061/52896132-c7ae8d80-31c3-11e9-9d3d-cfc33e4a4779.png)


I've raised my upload limit to 150MB which should be enough to. The upload does not finish after being at 100% for over 15minutes. My IO/Disk wait exploded on all cores and the machine came nearly unresponsive. As this did not happen with apache, I suspect this is a problem with nginx.

![image](https://user-images.githubusercontent.com/6549061/52896279-c41c0600-31c5-11e9-88c6-822ca38c2b7c.png)

I will discuss this within our team on monday, as I'm not sure regarding this.

**Comment by SEGGER-NV** [comment]
Hi,

Good to see that it is reproducible. Really weird that it works with Apache instead. Do you get an error when you try to upload a file with Apache that is over the set file size limit?
Or was this already the case in your setup and the upload still worked?

**Comment by tmswr** [comment]
I'm seeing this issue with attachments of ~1mb. Max upload is set to 150mb on nginx. I get a POST 413 on ticket_attachment_upload (Request Entity Too Large)

![image](https://user-images.githubusercontent.com/44615905/52968547-2e25de00-3373-11e9-81fe-0825141a0cd4.png)

**Comment by alexandresouza** [comment]
This issue remains

**Comment by MrGeneration** [comment]
## Entity Too Large

This is mainly a nginx error (with a too big attachment being uploaded), but Zammad fails to intepret it correctly.

`2019/05/31 18:58:00 [error] 713#713: *389 client intended to send too large body: 99112562 bytes, client: 192.168.2.122, server: 172.16.16.3, request: "POST /api/v1/upload_caches/321778948 HTTP/1.1", host: "172.16.16.3", referrer: "http://172.16.16.3/"` is logged by nginx and should be interpreted by Zammad correctly (throw error and remove "uploading process".

Browser-Console logs:
![image](https://user-images.githubusercontent.com/6549061/58721866-3f50a300-83d6-11e9-9c6a-d87f87f36b81.png)

## Upload size limits in general

I set `client_max_body_size 200M;` inside the zammad.conf of nginx and could successfully upload a 195 MB file. Here comes the but: Even on SSD storage with 4 cores (and nothing else running on the system) it took a fair time to finish the file operations and giving back a "success". After that the scheduler and elasticsearch went berserk for about 5-10 minutes (which is proberbly because I didn't optimize anything).

Before questiosn rise: I tested this on database and filesystem based attachment storage, filesystem was a way better in my tests.


## Conclusion:
I only partly agree with this issue as it's a configurational question inside of nginx.
What I agree on is that Zammad should throw an error when nginx does give feedback "file too big".

**Comment by MrGeneration** [comment]
@tmswr sorry, but this is more a technical question that wants to live on our Community: https://community.zammad.org - the error message clearly comes from your nginx. please also provide the config of your nginx on the community.
