### ISSUE TITLE
Zammad with Davmail

### ISSUE THREAD

**Issue by ocerecedo** [zammad/zammad#2488]
Hello, I have an exchange account that I want to use with zammad, I could not natively because my exchange server does not support pop, imap, smtp. I was able to configure Davmail to use exchange but the emails are not downloaded from the exchange server to zammad, they could support me by telling me where the error might be.

Centos 7
Zammad 2.9
Davmail

Thank you !.

**Comment by MrGeneration** [comment]
Hello and welcome to Zammad!

This is a technical question, please head over to our Community ( https://community.zammad.org/ ).
This is a tracker for Issues only.

Please note that Zammad relies on POP3/IMAP and SMTP - other Protocolls like e.g. ActiveSync are not possible. When posting to the community, please also include your production log `/opt/zammad/log/production.log` as otherwise it's impossible to help you.

Thank you, have a nice weekend!
