### ISSUE TITLE
Feature Request: Tag Cloud

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#250]
My Idea: 

Manage everything with tags. You could create an overview for tag:Servers and one with tag:Network.

If you have an issue wich belongs to servers and network, the server and network guys will see the ticket. So you could work with only a few groups and organize the rest by tags. 

On the right tags area you should see the most recent tags in an small tag cloud.

What do you mean? 

By the way: You do so much nice perfect work. Go on with it. I love you 💌
When you used several years OTRS - Zammad is a giant step from 56k to VDSL100 😄

**Comment by thorsteneckel** [comment]
Hi @Julian0o - thanks for the proposal and the warm words. That motivates a lot! 🚂  Some functions might be described in the issue #245 too.

**Comment by MartinBorg** [comment]
+1 for tag cloud

**Comment by hanneshal** [comment]
Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals

regards
Johannes
