### ISSUE TITLE
smooch.io integration

### ISSUE THREAD

**Issue by skolarianer** [zammad/zammad#252]
Would love to see smooch integration:
https://smooch.io/integrations/

**Comment by hanneshal** [comment]
Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals

regards
Johannes
