### ISSUE TITLE
users_controller.rb: search: pagination broken

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#2539]
### Infos:

* Used Zammad version: dev
* Installation method (source, package, ..): git
* Operating system: Debian
* Database + version: doesn't matter
* Elasticsearch version: doesn't matter
* Browser + version: doesn't matter

As discussed in the [community](https://community.zammad.org/t/api-v1-users-search-cant-get-pagination-to-work/2376).

This probably broke in cf1626494047f27d8fe094a7b954e04fef0f182b; removing the `# do pagination if needed` block fixes it.

### Expected behavior:

* `/api/v1/users/search?query=*&per_page=10&page=n` should return results for n > 1

### Actual behavior:

* `/api/v1/users/search?query=*&per_page=10&page=n` does not return results for n > 1

### Steps to reproduce the behavior:

* Manually query with `curl`:

	```
	curl -s -H "Authorization: Token token=x" 'http://zammad:3000/api/v1/users/search?query=*&per_page=1&page=2'
	```
	
	Note that no results are returned for page > 1.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by SummerStorm** [comment]
Hi @martinvonwittich, thanks a lot for the really detailed bug report + fix. We have an internal branch based off your contributions undergoing the QA process now so you don't need to submit a PR anymore. Just giving you a heads up since you mentioned that you were preparing a PR in the [community thread](https://community.zammad.org/t/api-v1-users-search-cant-get-pagination-to-work/2376/2).
