### ISSUE TITLE
Error with case-sensitivity and uniqueness of email addresses

### ISSUE THREAD

**Issue by raphaelm** [zammad/zammad#2558]
### Infos:

* Used Zammad version: 2.9.0-1554805410.8c7abf98.stretch
* Installation method (source, package, ..): Debian package
* Operating system: Debian stretch
* Database + version: MariaDB 10.2.23
* Elasticsearch version: 5.6.16
* Browser + version: irrelevant

### Expected behavior:

* When saving a users with an email address that does not clash with another users email address, I expect to be able to modify and save the user under any circumstances.

### Actual behavior:

* In our database, we had a user with a ``login`` field of, say, ``john.doe@example.org`` and an ``email`` field of ``John.Doe@example.org``. I don't know how that happened, it just did. The user sent their first support request in 2015, so this dataset might have been created through our OTRS import many years back.

* Modifying this user is impossible, it always leads to "Email address is already used for other user."

* Of course, as soon as the user opens a ticket, ``TicketUserTicketCounterJob`` starts failing due to the same validation error and triggers a monitoring alert.

* Changing the value of the ``email`` field inside the database to lowercase resolves the problem.

### Suggestion to resolve:

* I would recommend excluding the currently modified object from the validation check for duplicate email addresses.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Hey,

thanks for your contribution!

This has been fixed with #893 

This should affect very few instances, as this is adressed. That's why, we will not supply a migration with a Zammad-Update and instead incourage our users to run the following code on a Zammad-Console to fix the issue "on the fly".

**Attention:** This can be veeryyy ressource expensive, depending on the number of users you have. You might want to run this within a maintenance window. This might also create a ton of search index updates, depending on the number of affected users.

```
list=""
User.all.pluck(:id).each {|user_id|
  next if user_id == 1
  user = User.find(user_id)
  next if user.email.blank?
  next if user.email !~ /[A-Z]/
  user.email = user.email.downcase
  user.save!
  list += "Affected User: #{user.login}/#{user.email}/#{user.id} has #{Ticket.where(customer_id: user.id).count} tickets (as Customer) \n"
  list += " -> new email: #{user.email.downcase} \n"
}
puts list
```

Bests

Edit: We optimized above code, enabling `import_mode` is no longer needed and has been a problem with my local test system.
