### ISSUE TITLE
Permanently add SSO readiness

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2576]
### Infos:

* Used Zammad version: 2.9
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any 
* Browser + version: any (Firefox needs fiddling)
* Ticket-IDs: #1041777, #1040804

This partially plays into #1192 (which is more of a documentary part by now, so this is the clean version for a developer to do magic on :) )

### Requirenments:

In order to have this feature working, you need the following:

* Apache2 (nginx does currently not work and is not supported by us)
* Somewhat LDAPish (Active Directory or even a Kerberos-Server)
* Kerberos-Client on the Zammad-System (and correctly configured)
* An valid Keytab-File you generated

### Expected behavior:

Logging in with accessing the Zammad WebApp works without file changes (expecting configs to be fine already). It does not matter if the logged in user logged in with a not completely lower case loginname (e.g. `User.Name` will be seen by Zammad as `user.name`).

### Actual behavior:

At the moment it's needed to adjust Zammads source code ( `/opt/zammad/app/controllers/sessions_controller.rb` ):

```ruby
ENV['HTTP_REMOTE_USER']=request.env['HTTP_REMOTE_USER'] || request.headers['X-Forwarded-User']
```

The above has still one downside: It does take any username format which will work as long as the supplied username is all lower case. That's why, Zammad should lower case the username to ensure compatibility. Beside the Apache2 config, everything is working fine as soon as this is ensured.

**Comment by thorsteneckel** [comment]
**ATTENTION**: We have to warn you to use the SSO implementation in any way described in this or other issues. The changes provided here contain a serious security vulnerability. This vulnerability will persist sessions created via SSO for not authenticated users. This means that it's possible for non authenticated users to take over the previously created SSO session for a user (in Zammad context).

**We strongly recommend to disable SSO until this issue is resolved.**

This issue is no longer relevant since the current implementation is broken. We need to dig deeper.
