### ISSUE TITLE
Double-click timeout in ticket zoom too short

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#2586]
As discussed in the community: https://community.zammad.org/t/selecting-text-in-an-article-via-double-click-triggers-detail-view/2527/1

### Infos:

* Used Zammad version: 2.9.x
* Installation method (source, package, ..): docker-compose
* Operating system: Debian 9
* Database + version: docker-compose
* Elasticsearch version: docker-compose
* Browser + version: Chrome 74

### Expected behavior:

* Zammad should correctly detect and ignore double-clicks in the ticket zoom so that users can use double-clicks to select whole words. It should only expand the detail view that shows to/from/subject on single clicks.

### Actual behavior:

* Zammad does have a double-click detection:

	https://github.com/zammad/zammad/blob/master/app/assets/javascripts/app/controllers/ticket_zoom/article_view.coffee#L291-L300
	
	```
	  toggleMetaWithDelay: (e) =>
		# allow double click select
		# by adding a delay to the toggle
		delay = 120

		if @lastClick and +new Date - @lastClick < delay
		  clearTimeout(@toggleMetaTimeout)
		else
		  @toggleMetaTimeout = setTimeout(@toggleMeta, delay, e)
		  @lastClick = +new Date
	```

	But IMO the timeout of 120ms is too short. I've added a bit debug code to show how long my double clicks take, and they're all longer than 120ms:
	
	```
	application.js:42910 toggleMetaWithDelay - diff: 146
	application.js:42910 toggleMetaWithDelay - diff: 136
	application.js:42910 toggleMetaWithDelay - diff: 128
	application.js:42910 toggleMetaWithDelay - diff: 141
	application.js:42910 toggleMetaWithDelay - diff: 136
	application.js:42910 toggleMetaWithDelay - diff: 161
	application.js:42910 toggleMetaWithDelay - diff: 144
	application.js:42910 toggleMetaWithDelay - diff: 126
	```

	I propose raising to e.g. 300ms. That improves the double-click detection significantly for me. although it also means that the expandable detail view takes a bit longer to respond.

### Steps to reproduce the behavior:

* Attempt to double-click on a word in the article zoom.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
Hi Martin, nice to read from you. I encountered that myself in my daily support work. So thanks for digging into it. Your solution sounds reasonable to me. @martini - what do you think?

**Comment by martini** [comment]
It was hard to me to see what the issue is. After I played a little bit I was able to reproduce it. But I needed 3 clicks (one to set focus and then two clicks to select the word(s)).

With 120ms:
![behavior_with_120ms_and_3_clicks_to_select](https://user-images.githubusercontent.com/110226/58330291-e1044d00-7e36-11e9-918e-2c4b809f018d.gif)


With 300ms:
![behavior_with_300ms_and_3_clicks_to_select](https://user-images.githubusercontent.com/110226/58329961-25431d80-7e36-11e9-8770-f719448def94.gif)

So the change to 300ms is ok for me.

But I found something else which is more annoying to me. If I want to "deselect" the selected word(s) by one click the meta area is expanded. So it would be nice to check if the click was on a selected range. And if it is so, do not toggle the meta real.

![do_not_toogle_if_text_is_selected_on_click](https://user-images.githubusercontent.com/110226/58330020-43a91900-7e36-11e9-9e80-4f5050ebac13.gif)
