### ISSUE TITLE
Feature Request: RegEx for Attributes

### ISSUE THREAD

**Issue by Julian0o** [zammad/zammad#260]
Would be nice to define some RegEx for attributes.

**Comment by hanneshal** [comment]
Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


regards
Johannes
