### ISSUE TITLE
Knowledge base not redirecting properly from docker instance

### ISSUE THREAD

**Issue by Ekultek** [zammad/zammad#2621]
### Infos:

* Used Zammad version: `2.10.x `
* Installation method (source, package, ..): `docker`
* Operating system: `Ubuntu 16.04`
* Database + version: whatever version is processed with this Dockerfile https://hub.docker.com/r/zammad/zammad/dockerfile
* Elasticsearch version: Same as above
* Browser + version: `Firefox Quantum 60.7.2esr (64-bit)`

### Expected behavior:

* Redirect with the open port as expected, such as `http://10.0.1.1:9099/help`

### Actual behavior:

* Redirects straight to `/help` without the port being assigned, instead redirects straight to URL without open port: EG `http://10.0.1.1/help`

### Steps to reproduce the behavior:

* Dockerize Zammad instance, and run with a forward facing port other than 80. 
* Create a KB article, sign in as a customer.
* Click on KB link.

Yes I'm sure this is a bug and no feature request or a general question.

Examples:

![firstExample](https://user-images.githubusercontent.com/14183473/60040294-3de56400-967e-11e9-9603-699be6de3c9a.png)

![secondExample](https://user-images.githubusercontent.com/14183473/60040300-42aa1800-967e-11e9-8ba7-698323f6b3cb.png)

![thirdExample](https://user-images.githubusercontent.com/14183473/60040308-45a50880-967e-11e9-98d3-134d1e208602.png)

**Comment by MrGeneration** [comment]
Hey,

thanks for the write up.
Sorry, but I can't reproduce this on univention system (which is based on docker compose with a custom port).

That makes me believe that this is actually a technical questions, which should be on our community for the next time (please. :-) ).

To solve your problem, go to Admin-Settings ->System (Settings) and ensure your FQDN does contain your custom port. If it doesn't add it.
![image](https://user-images.githubusercontent.com/6549061/60041751-6e4bf300-96bc-11e9-9b9a-215c3a1142dc.png)

While you're at that, go to E-Mail (Channel) and then the Settings-Tab and ensure your Notification-Sender does not contain the FQDN-Variable. If so, set it to whatever you need to be.
(Background: If you add a custom port to your FQDN, this can give you a hard time on other places, especially in terms of sending mail).
![image](https://user-images.githubusercontent.com/6549061/60041871-aeab7100-96bc-11e9-810e-5994a128c6d8.png)

If my guess is correct, your notification mails you get (if you ever got any because the docker compose does not have or use sendmail), they will also contain a wrong link (without the custom port).

🚀

**Comment by Ekultek** [comment]
cool thank you
