### ISSUE TITLE
Full quote shows "<agent> wrote:" instead of "<customer> wrote" when agent toggled article visibility

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad#2629]
### Infos:

* Used Zammad version: 3.0.x
* Installation method (source, package, ..): docker-compose
* Operating system: Debian 9
* Database + version: postgres
* Elasticsearch version: doesn't matter
* Browser + version: Chrome
* Ticket-ID: #1060389

### Expected behavior:

* When an agent toggles "set to internal"/"set to public" of an article of a ticket (for example accidentally), and then another agent (or the same one, doesn't matter) replies to this article, the full quote should be introduced with "On Wednesday, June 26, 2019, 8:57:55 AM, <Customer's name> wrote:".

### Actual behavior:

* When an agent toggles "set to internal"/"set to public" of an article of a ticket (for example accidentally), and then another agent (or the same one, doesn't matter) replies to this article, the full quote is introduced with "On Wednesday, June 26, 2019, 8:57:55 AM, <Agent's name> wrote:".

### Steps to reproduce the behavior:

* As a customer, create a ticket (for example by sending a mail into Zammad). Or as an agent, create it manually as a phone ticket and choose a customer.
* Ensure that the options "Email - full quote" and "Email - quote header" are both enabled.
* As an agent, click on reply. Note that the full quote is introduced as "<Customer> wrote:", as it should be. Discard your changes.
* As an agent, toggle the visibility of the article by clicking on "set to internal"/"set to public".
* As an agent, click on reply again. Note that the full quote is now introduced as "<Your agent name> wrote:", which is wrong.

### Further analysis

The bug is caused by:

1. [app/assets/javascripts/app/controllers/ticket_zoom/article_action/email_reply.coffee](https://github.com/zammad/zammad/blob/develop/app/assets/javascripts/app/controllers/ticket_zoom/article_action/email_reply.coffee#L151..L157) uses `article.updated_by` to determine the name. We don't use the customer frontend, but I suspect customers may edit their own ticket articles, and therefore it could be relevant which customer edited the article last?

1. When an agent toggles the visibility of an article, _he_ becomes the user who last updated the article.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please note that this doesn't only affect customer articles, but also happens if you reference text from an agent article by pressing "reply" on a customers article.

That's a bit unexpected. To help understand the second issue (from my end) better, here's a screencast. It consists of two parts which on the second part will also proove what Martin has described.

![issue-2629_quoting-customers](https://user-images.githubusercontent.com/6549061/73538291-ee90be80-442a-11ea-93c6-8e5cda881cd2.gif)

**Comment by romitgithub** [comment]
After what I read here and checked in the code, Shouldn't we use **USER**(created_by) who created the comment when replying to a particular item rather than using the **USER**(updated_by) who updated the article last?

@mantas @MrGeneration thoughts??

**Comment by mantas** [comment]
There's another related issue that if ticket was created by agent on behalf of customer (e.g. incoming phone call), quote metadata will also show `agent` instead of `customer`.

@romitgithub there's also `origin_by_id` property which is used for tickets created on behalf of someone else. Best solution would be `USER(origin_by || created_by)`. See above scenario to check it out in action.

**Comment by romitgithub** [comment]
@mantas Got it, so where do we get this data(origin_by) for the customer for whom the ticket is created?
