### ISSUE TITLE
Keeps saying "Host Unreachable"

### ISSUE THREAD

**Issue by matthew119427** [zammad/zammad#2652]
### Infos:

* Used Zammad version: latest
* Installation method (source, package, ..): Debian 9 Installation Instructions 
* Operating system: Debian 9
* Database + version: MySQL 10.1
* Elasticsearch version: 5.5
* Browser + version: Mozilla Firefox Quantum 67.0.4

### Expected behavior:

* IMAP to work successfully

### Actual behavior:

* Says hostname unreachable, even though I can ping the host through my machine and send emails through the support address through Thunderbird.

Logs are below:
*It also appears to be trying to send emails from noreply@support.libraryofcode.us* when it's supposed to come from support@staff.libraryofcode.us*
```
Jul  6 15:34:20 staff dovecot: master: Warning: Time moved backwards by 1 seconds, waiting for 2 secs until new services are launched again.
Jul  6 15:34:20 staff dovecot: log: Warning: Time moved backwards by 1 seconds.
Jul  6 15:34:23 staff postfix/qmgr[62249]: 04C1A233EE: from=<noreply@support.libraryofcode.us>, size=1027, nrcpt=1 (queue active)
Jul  6 15:34:54 staff postfix/smtp[18164]: 04C1A233EE: to=<emailtrytest@znuny.com>, relay=arber.znuny.com[88.198.51.81]:25, delay=428, delays=397/0.04/1.5/29, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as CC88260608)
Jul  6 15:34:54 staff postfix/qmgr[62249]: 04C1A233EE: removed
```

### Steps to reproduce the behavior:

* 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by matthew119427** [comment]
Update:
Changing the host to the IP address works, however I would still expect it work if you provided the domain name.

**Comment by MrGeneration** [comment]
Sorry but I do believe that this is a technical question that should live in our community: https://community.zammad.org

We have tons of hosted customers and community users that do not experience this problem.
Ensure that your host can lookup the mail server host without any problem.

The used mail addresses don't have to do anything with that directly.

Closing now. (If you need to discuss this because you believe this is wrong, please do so in the community by referencing this issue, if we see this to be a valid `bug`, we'll reopen this issue)
