### ISSUE TITLE
Last line in note is not selectable

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#2654]
### Infos:

* Used Zammad version: 3.0
* Installation method (source, package, ..): package
* Operating system: macOS
* Database + version: Postgres
* Elasticsearch version: 5.6
* Browser + version: Safari latest/Chrome/Firefox

### Expected behavior:

* If I expand a note, I want to copy the last line, right above the "show less"

### Actual behavior:

* The last line is not selectable

### Steps to reproduce the behavior:

* Create a long note
* Expand the text using "show more"
* Try to select the last line (for copy and paste)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by hanneshal** [comment]
![screencast 2019-07-08 19-36-05](https://user-images.githubusercontent.com/804939/60830604-dec43b00-a1b7-11e9-9aa4-ab416d8c910b.gif)

**Comment by dennykorsukewitz** [comment]
This problem is the `.textBubble-overflowContainer:before`.
@mrflix could you please check this.

```
<div class="textBubble-overflowContainer is-open">
            <div class="btn btn--text js-toggleFold">weniger anzeigen</div>
</div>
```

```
.textBubble-overflowContainer:before {
    content: "";
    position: absolute;
    left: 0;
    right: 0;
    top: -30px;
    height: 30px;
    background: linear-gradient(rgba(255, 255, 255, 0), white);
    transition: opacity 300ms;
}
```

**Comment by mrflix** [comment]
I'm fading out the gradient when animating from the closed to the open state. So once it's open the gradient layer is still there, just invisible. Animating from visible to invisible is easy with css. Animating from visible to not rendered is tricky, that's why its still there. I realize however that this animation is not need and removing it all together might even improve the general fold-out animation performance.

Additionally there is a new css property since > IE10 called `pointer-events: none` that makes elements ignore mouse clicks. So using this we can make it possible to start a text selection in the last row of text even when its closed and overlaid by the gradient.
