### ISSUE TITLE
Profile out of office toasters untranslatable

### ISSUE THREAD

**Issue by maxxer** [zammad/zammad#2666]
Zammad 3.0.x

When setting out of office in user profile toaster messages may appear, like *user is required* (or something like that) and *Successfully!*. Both those messages aren't listed in the translations page

**Comment by MrGeneration** [comment]
This can be found here:
https://github.com/zammad/zammad/blob/a70153106ab9c47f298e187b2c293a4878871c70/app/assets/javascripts/app/controllers/_profile/out_of_office.coffee#L127

I think we should change this from `Successfully!` to `Successfully!`, because I think it's nearly the same (at least in german the same result will be translated ;) ).

What do you think, @dennybresch  ? :)

**Comment by maxxer** [comment]
The word itself is not really meaningful... Something like *Settings stored* would be slightly better, isn't it?

**Comment by dennykorsukewitz** [comment]
Hi @maxxer @MrGeneration ,

`Successfully!`and `Successful!` are already present on the i18n.
First of all we should check why they are not displayed in the translation overview.

If we change this notice, we should use a general wording so that it can be used more often in user preferences and admin area AND to keep the number of translations small.

`Update successful!` already exists and could be used directly.

**Comment by MrGeneration** [comment]
I'd like to vote for `Update successful` and `Settings stored successful` :-P

**Comment by maxxer** [comment]
*Update successful* is fine to me. *Settings stored successful* should be *lly* :)

**Comment by mgruner** [comment]
This will be fixed with the upcoming migration to Weblate in Zammad 5.1.
