### ISSUE TITLE
Limit on copy and paste in note box for new articles

### ISSUE THREAD

**Issue by hanneshal** [zammad/zammad#2696]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): package
* Operating system: CentOS
* Database + version: Postgresql
* Elasticsearch version: 5.6
* Browser + version: Safari/Chrome
* T#1051055

### Expected behavior:

* There should be no limit when pasting text into the text box for article content

### Actual behavior:

* There is a limit around 19k Characters
* After pasting the text a red border around the article shows up

### Steps to reproduce the behavior:

* Create a large string (+19k) using http://www.loremipsum.de
* Paste text to Zammad Article Box
* Red border appears

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
It's about the user note field or for new articles?

**Comment by martini** [comment]
Additional note, we have this behavior (by the way, the red border show that the maximum limit has reached) on two places:

1) For note fields of users & organizations we have a size limit (because of database field limitation).

2) For new articles we have also this behavior - which is currently as designed. I never expected to write answers with more as 19k characters.

What limit is a suitable limit here? 

Technical background: If we allow unlimited size for new articles the browser will slow down because of resource limits on client/browser.

**Comment by sstonemen** [comment]
Normal mails work easy with 500000 characters.
I would recomend prefer at least 50 000 characters.

I run in this limit several times with zammad. Eg by copy a technical description or a faq or something else in a mail.

**Comment by martini** [comment]
@sstonemen thanks for feedback. We increased the limit 3 times (from `50000` to `150000` it's the sting length including html tags). So if you have the same html structure to past in you now can past about 60k chars formated in html.
