### ISSUE TITLE
Backup script does not work as zammad user when DB is Postgresql

### ISSUE THREAD

**Issue by abeluck** [zammad/zammad#2705]
## background

This issue is related to https://github.com/zammad/zammad/issues/2508, however while that issue is about running as root, this one is about running as the `zammad` user.

In fact it seems people are running the Zammad backup script as root in their cron jobs specifically because of this issue ([ref](https://github.com/zammad/zammad/issues/2508#issuecomment-470526180)). Monotek also noticed this ([ref](https://github.com/zammad/zammad/issues/2508#issuecomment-470527571)), however there is no open issue for it, hence this one.

## reproduction

1. Use postgresql with zammad
2. Run the backup script as the zammad user

```console
root@host:/opt/zammad/contrib/backup# su zammad
zammad@host:/opt/zammad/contrib/backup$ /opt/zammad/contrib/backup/zammad_backup.sh

# Zammad backup started - Fri Aug 16 08:08:14 UTC 2019!

creating file backup...
creating postgresql backup...
Password:  <pressed enter>
su: Authentication failure
mv: cannot stat '/tmp/20190816080814_zammad_db.psql.gz': No such file or directory

# Zammad backuped successfully - Fri Aug 16 08:12:39 UTC 2019!
```

When no tty is available during cron mode, the script fails similarly.

## the problem
The [backup_db function in the backup functions](https://github.com/zammad/zammad/blob/develop/contrib/backup/functions#L54) uses `su` to run `pg_dump`. 

So, the backup scripts cannot complete as the `zammad` user.

Also note another minor issue, that the script reports it completed successfully when in fact it didn't.

## potential solutions

1. explicitly document that when using postgresql the backup should be run as root
2. make the scripts use the provided credentials  in `../../config/database.yml` (relative to the backup script) to connect to the database

**Comment by MrGeneration** [comment]
One thing beforehand:
- Please use the issue template, especially the "Info" section is mandatory 


Note while fiddling:
As I think it's enough to change the following line in your case (`contrib/backup/functions` line 54):
`su -c "pg_dump -c ${DB_NAME} | gzip > /tmp/${TIMESTAMP}_zammad_db.psql.gz" postgres`
TO
`pg_dump -c ${DB_NAME} | gzip > /tmp/${TIMESTAMP}_zammad_db.psql.gz`

In my field tests this worked.


Now I don't see this as a technical question, as this is rather a configuration issue.
The password prompt you're receiving is **not** the database, but from `su` (for changing to the postgres user).

Note: Changing the user as "normal" user (which `zammad` is) especially when change ownering to `postgres` that this is a potential security issue. 
Reason: If you can change to a superuser account for a webservice account, this can lead to great problems. Imho, you never - ever - want that to happen.


If we really want to change something in that context, then we'd rather want to check for the user and dump an alternative way. (maybe that's the better approach than globally changing, because if we'd change it directly, it will break existing and working backups.

Another side note: This might be a documentation issue that we might need to enhance.

**Comment by AleBitlam** [comment]
Hi,
what is Zammad's default password? do I have to set it?
Thanks

**Comment by MrGeneration** [comment]
Please do not hijack closed issues.
Please also note that technical questions better should live within the Zammad Community (https://community.zammad.org) - this is to reduce noise on this repository.

Zammad and it's installation doesn't come with default credentials in any way.
