### ISSUE TITLE
Failing HTML-Processing denies user to access the mail

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2706]
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1051620, #1056801, #1072848, #1086963, #1086950, # 10104953, #10108800, #10113609, #10114725, #10109416, #10117639, #10118442, #10122133

### Expected behavior:

If Zammad can't reliably process HTML content (with sanitizing and stuff), it will create a note at the ticket with the raw mail attached (what you originally received or typed [depending on the direction the message goes to]).

### Actual behavior:

If Zammad can't process HTML content (e.g. because the system is too busy at that moment or processing takes too long for other reasons), it will create a note that the message could not be processed and you shall check the RAW message.

For incoming, this is no problem, you can download the raw eml and view the content.

For outgoing mails (what your agent typed and sent), Zammad will include the same error message inside the eml as well. This will cause Zammad to loose the articles content.

Note: For both directions, the limit currently is too low (or not robust enough if you have a pretty busy system) and thus needs fiddling. Especially for outgoing mail, this needs fiddling so that the content doesn't get lost.

Message of article is:
```
This message cannot be displayed due to HTML processing issues. Download the raw message below and open it via an Email client if you still wish to view it.
```

### Steps to reproduce the behavior:

* make your system busy as hell
* pump mails into Zammad (this one is a bit tricky to enforce ;), you basically can simply lower the processing limit dramatically to enforce it)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rlue** [comment]
Looked into this yesterday. Posting my notes for whoever comes to this issue next. Be warned—it's a doozy!

### My understanding

#### Background

We use `HtmlSanitizer.strict` to sanitize HTML in various parts of the application (_e.g.,_ to protect against [XSS attacks](https://en.wikipedia.org/wiki/Cross-site_scripting)). It can be quite slow, though: for `test/data/mail/mail047.box` (3800+ lines), `.strict` can take almost a full second on my development machine. If a server is congested with a lot of other tasks, this method may become very slow indeed.

As slow as this method is, **sometimes it just has to be called in the foreground** (we'll get to why in a second). So, to protect the user from a hanging and totally unresponsive application, `.strict` wraps all of its logic into a timeout (default 20s), and if this timeout is exceeded, then it abandons the task and returns an error message instead.

So the underlying problem is that **sometimes we want to sanitize some HTML before saving it to the database, but if it takes too long, then we just end up discarding the HTML and saving an error message in its place**.

#### What specifically is going wrong?

Whenever an agent sends an outgoing email, Zammad starts by creating a new ticket article. The body of the article is [passed through the HTML sanitizer in a `before_create` callback](https://github.com/zammad/zammad/blob/develop/app/models/concerns/checks_html_sanitized.rb#L20):

```ruby
article.body = HtmlSanitizer.strict(article.body)
```

Thus, if an outgoing email takes too long to sanitize, `article.body` is replaced with an error message, which leads to two problems:

1. the original content of the message is lost, and
2. an outgoing email is dispatched to the customer that says nothing but:

   > This message cannot be displayed due to HTML processing issues. Download the raw message below and open it via an Email client if you still wish to view it.

(Zammad also sanitizes incoming emails, and this problem can occur there, too—but it's not such a big deal, since users can always download the raw email content and inspect it manually.)

#### Why does it have to be called in the foreground?

Well, for example, the text of an outgoing email will become the `#body` of a new `Ticket::Article`—if we sanitized in a bg job, we'd have to create the article first, wait for the job to finish, and then update the article with the safe, sanitized `#body` afterwards. In the meantime, what value should we set for `#body`? an empty string? the unsanitized, potentially XSS-injected original? Or what happens if the sanitization job fails? How do we alert the user that something has gone wrong?

Maybe there is a better way, but I haven't come up with one yet. So, to my knowledge, it must be run in the foreground.

#### So what do we do?

Not sure. Finding a faster way to sanitize the HTML would help, but there are limits to that. I imagine that saving unsanitized HTML to the database is not acceptable. Maybe a background job _is_ the way. ¯\\\_(ツ)\_/¯

### Question

If our sanitization logic is too slow, would it be acceptable to use a faster/dirtier sanitization method as a fallback instead? (Loofah's ["whitewash"](https://github.com/flavorjones/loofah#features) strategy is almost 4x faster, in my benchmarks.)

**Comment by MrGeneration** [comment]
FYI: Ticket#1086963 contains a sample raw that might help pinning this done. It seems like especially rather long quotations cause this effect to appear more likely.

**Comment by lug-gh** [comment]
Is it more or less safe to increase the timeout from 20 to, say, 60 seconds?
I know that the change will be overwritten with the next update.
I have already given Zammad a lot of resources (WEB_CONCURRENCY=4 with around 20 agents), yet it still times out on very very large mails (200k+ characters).

**Comment by MrGeneration** [comment]
@lug-gh this repository is the wrong place for technical questions. Please don't post them here.

**Comment by rolfschmidt** [comment]
Another small workaround for now might be to reduce the load by ticket overviews. If you do `htop` and there the most processes dominating your screen are puma's and not background workers then you could try to reduce the mail processing errors by limiting ticket overviews:

https://github.com/zammad/zammad/blob/c0546af0e6265b583292f88c9630182a3269932c/app/models/ticket/overviews.rb#L131

reduce the limit to 400 -> `.limit(400)` and restart zammad services.

Watch `htop` again. If your load decreases much then it also might have positive impact on your mail processing performance.

Another finding we had in a customer session yesterday was a performance issue for article sanitization in the assets which we could cache to reduce load as well in general. I will work on that.

We will keep you up if we find any new hints to solve the situation.

## EDIT:

This workaround can now be also done by setting. Update your zammad to latest stable and then:

```
root> zammad run rails r "Setting.set('ui_ticket_overview_ticket_limit', 400)"
root> zammad run rails r "Setting.set('html_sanitizer_processing_timeout', 60)"
```

**Comment by rolfschmidt** [comment]
You can increase the processing timeout (default 20 seconds) now after updating to latest stable to 60 seconds with:

```
root> zammad run rails r "Setting.set('html_sanitizer_processing_timeout', 60)"
```

We also prepared a couple of improvements last week which will be merged with the next major version and increase the performance by like 30% for now. The performance is very different based on your hardware. On our notebooks we are able to parse 500kb HTML mail files 10 times in like 6-12 sec where other customer systems take like 80 seconds for. This makes it very hard to improve it.
