### ISSUE TITLE
Roles and Users selection in Overview administration UI ambiguous

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#2714]
### Infos:

* Used Zammad version: 3.1.x
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: -
* Elasticsearch version: -
* Browser + version: -

### Expected behavior:

* When setting the availability of an overview one can set it for a role and/or individuals.
When setting both a role and an individual the overview should be visible to everyone that has the role and to the individual.

### Actual behavior:

* Instead the two availability settings seem to operate as a logical "and" when both are set. So  if you set both the overview will only be visible if the individual has also the role. The role group itself will lose the overview completely. Even worse if the individual does not have the role, then neither the other role members nor the individual user will see the overview.

If the options would be evaluated as an logical "or" it would work as expected.
As a simple switch to "or" would probably break backwards compatibility the fix proposal would be to add a switch to switch between both modes.

### Steps to reproduce the behavior:

* Create new role
* Give two users new role
* Create new overview where overview availability settings are new role and user1
* Log into user2, now you don't see the overview, only user1 can see it

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
That's unexpected. Thanks for your report!

Documentation states:
`With these settings you can choose whether to make the overviews available to an entire group of people (by selecting the role) or to specific users. The entries in both fields apply. This means that you can also select individual users in addition to sharing the overview for all role members.`

(https://admin-docs.zammad.org/en/latest/manage-overviews.html)

So we should address this :)

**Comment by thorsteneckel** [comment]
Hey there. @mantas @martini and I had a discussion about what the current implementation is and what is expected. We found out that the difference those two is the root cause of this issue: The UI is misleading and the documentation states a different behavior than what the implementation actually does. 

# Overview

## What is expected (Case 1)
An Overview can be configured to be available for a List of Roles **or** Users. The Role and User selections are optional on their own but at least a selection in one of them is required. This behavior is called **additive** as a technical term: Users that are not already covered in one of the possibly selected Roles will be added. This translates in the following variations:

- All Users of the selected Roles will see the Overview.
- All selected Users of the Users list will see the Overview.

Caveat: There is no way to limit the Users of the selected Roles. Each User has to be added manually via the Users list selection or a new Role has to be created.

## What is implemented (Case 2)
An Overview has to be configured to be available for a List of Roles. The availability can be **reduced** to an optional list of Users. The Roles selection is required while the Users selection is optional. This translates in the following variations:

- All Users of the selected Roles will see the Overview if there is no selection in the Users list.
- Users of the selected Roles that are also listed in the Users selection will see the Overview.
- Users of the selected Roles that are not listed in the Users selection will not see the Overview.
- Users that are not in one of the selected Roles are ignored. 

Caveat: There is no way to add single Users. Instead a new Role has to be created to make the Overview available for them.

# Conclusion 

Case 1 and 2 both are a shorthand to limit the amount or Roles required for making Overviews available to Users. Case 1 does this by adding single Users. Case 2 does this by removing single Users. They are in contrast of each other but achieve the same goal.

However, Case 1 comes with two downsides that Case 1 does not.

## Higher UI state/UX complexity

It's harder to check and transport to the User that at least one of two fields is required. You can't add a `*` (required sign) to both or none of them. This results in workarounds on a UI/UX and technically form validation level.

## Current implementation

That's kind of an unfair one but Case 2 is already implemented and Case 1 is not. This means that there is an undefined number of Zammad installations out there that are using the Case 2 implementation (aka the status quo). If we change the behavior we will break their use case and Overview configurations. We could add technical migrations for it at some level but would never achieve full migrate-ability. This will make people unhappy. We don't want that.

# How to proceed

After we talked about this and took all in consideration we decided to stick with Case 1 – the current implementation. This leads to two tasks:

## Make the UI clearer

The `AVAILABLE FOR USER` label of the Users selection is misleading and should state clearly that the selection reduces the availability to the selected Users of the Roles instead of adding them to it.

- [ ] We can use this issue here as a reference.

## Sync the documentation

The author of the documentation section was mislead by the UI as many others. Now that things are clear we should bring the documentation back in sync with the actual implementation.

- [x] We need a new issue for that.

# Disagree?

In case you disagree please create a thread over at the [community board](http://community.zammad.org/) and refer to me. I'm happy to elaborate my point in more detail. We should keep our issues focused on concrete facts and keep the noise low to those that are watching this repository. Thanks ✌️ 

🚀

**Comment by SEGGER-NV** [comment]
Makes sense to me. A clear documentation and UI should already help most people so they do not waste time trying to implement something that is not intended to work that way.

**Comment by MrGeneration** [comment]
Added documentation issue https://github.com/zammad/zammad-admin-documentation/issues/47
