### ISSUE TITLE
Triggered note with variables do not replace variable with content

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#2716]
### Infos:

* Used Zammad version: 3.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: tested on Google Chrome (latest)

### Expected behavior:

When adding variables with `::` to a trigger that creates a note (with any visibility), it will replace the variables placed with the content they should hold. (Just like an triggered notification mail would)

### Actual behavior:

When adding variables with `::` to a trigger that creates a note (with any visibility), it will not replace the variables content and instead just post the "raw" content.

### Screen:
![image](https://user-images.githubusercontent.com/6549061/63530749-63201280-c507-11e9-9bf1-3bd13b8c426a.png)

### Steps to reproduce the behavior:

* create a trigger with a note containing variables that `::` provides
* save the trigger
* do the thing that triggers your trigger
* check the content

Example: 
![image](https://user-images.githubusercontent.com/6549061/63530944-c0b45f00-c507-11e9-9d8a-a171bc87514e.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by AnnemarieBecher** [comment]
Is there already a plan for the implementation of a solution?

**Comment by MrGeneration** [comment]
Sorry but we can't provide any time estimations. We will update this issue as soon as something moves in any direction.

**Comment by rosscdh** [comment]
+1 limits integration possibilities

**Comment by rosscdh** [comment]
somewhere in here: https://github.com/zammad/zammad/blob/develop/app/models/ticket.rb#L1104 
and https://github.com/zammad/zammad/blob/develop/app/models/ticket.rb#L900

looks like here https://github.com/zammad/zammad/blob/develop/app/models/ticket.rb#L1031

a "serializer" needs to be created that injects/sanitises and renders the body so that the variables can safely be rendered into the content

should all really pop out into its own lib as this model is getting tubby

```
ActionController::Renderer.render plain: values[:body], locals: { **relevantfields }
```

would also be awesome to have the article.id in there, as the api only lets you get by article.id not number afaik
