### ISSUE TITLE
zammad3.1.x 加入LDAP 报错

### ISSUE THREAD

**Issue by omaidb** [zammad/zammad#2756]
操作系统 ubuntu16.04
zammad 3.1.x
在设置-集成-LDAP中加入LDAP时报错
![image](https://user-images.githubusercontent.com/18365223/65568057-ff1bbe80-df8a-11e9-8bc0-2f59359b040d.png)
确认了很多遍，参数是正确的，但是它就是无法加入LDAP，谁能帮助我解决这个问题

**Comment by omaidb** [comment]
Operating system ubuntu16.04
Zammad 3.1.x
Adding LDAP in the settings-integrated LDAP error is confirmed many times, the parameters are correct, but it is unable to join LDAP, who can help me solve this problem

**Comment by NeverMin** [comment]
First, many thanks for your choosing Zammad open source project.
But, this repository is the wrong place for technical questions, 
because comments on the issue tracker will send emails to more than 100 people.
please use the Community(English only):
https://community.zammad.org

首先非常感谢你选择 Zammad 开源项目, 但这里不是张粘技术问题的地方, 会对超过 100 多名开发者造成干扰, 请你使用社区讨论技术问题(使用英文):
https://community.zammad.org
