### ISSUE TITLE
No attachment with templates

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#281]
Attachments were ignored while saving a form as a template.

**Comment by hanneshal** [comment]
Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


regards
Johannes
