### ISSUE TITLE
Assets Error 

### ISSUE THREAD

**Issue by lrjbrual** [zammad/zammad#2816]
### Infos:

* Used Zammad version:  Zammad version 3.1.x
* Installation method (source, package, ..): https://docs.zammad.org/en/latest/install-source.html#install-from-source-debian-7-8-ubuntu-16-04-ubuntu-18-04
* Operating system:  Ubuntu 18.04.3 (LTS) x64
* Database + version: postgresql pg', '~> 0.21.0
* Elasticsearch version: 5.0-5.5
* Browser + version: Chrome 

### Expected behavior:

* The assets and layouts correctly and I can configure and the admin side and that we can include in one page that the client can log a ticket. 

### Actual behavior:

* I got multiple error from assets, although the assets compiled correctly. 
* I successfully assets:precompile the assets not sure why the actual behavior still like cannot find all the assets. 

### Steps to reproduce the behavior:
* 1. during registration for admin I got the error cannot find the image. 
2. The assets (SCSS / Images) are not working properly
Here are the screenshot: 
![image](https://user-images.githubusercontent.com/9385561/69227842-d1b25200-0b82-11ea-8ada-bbd28e28994e.png)
![image](https://user-images.githubusercontent.com/9385561/69227884-e68ee580-0b82-11ea-86f5-52a6d4a1aa79.png)
![image](https://user-images.githubusercontent.com/9385561/69227903-f1e21100-0b82-11ea-8e9f-9d795249096b.png)

cannot find any error on the logs:
![image](https://user-images.githubusercontent.com/9385561/69228354-500af600-0b7b-11ea-92b3-4edb50b22d21.png)

I also follow this issue log: [https://github.com/zammad/zammad/issues/234](https://github.com/zammad/zammad/issues/234 ) using export RAILS_SERVE_STATIC_FILES=tru

**Comment by MrGeneration** [comment]
Sorry but this seems to be a rather technical question instead of a bug, plus, it's not clear what you've done.
Please open a thread over at the Zammad community (https://community.zammad.org) and also note what's so special about your installation.

This means:
We want logfiles and especially your webserver configurations, as you seem to have skipped steps or did something different.


Closing for now.
If the above statement of mine is an mistake and the community thread shows I was wrong, I'll gladly reopen the issue.
