### ISSUE TITLE
CSRF token verification failed

### ISSUE THREAD

**Issue by Hermut** [zammad/zammad#2829]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): YUM
* Operating system: Centos 7
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

Upgraded to Zammad 3.2. and I get error message csrf token verification failed. Cannot log in. Newer before seen this error message.

### Actual behavior:

Cannot log in. Linux setup is stayed same. 

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this is technically not a bug, but a technical question.
This has to do with your webserver configuration.

Please see the following community thread:
https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080

Closing now.

**Comment by MrGeneration** [comment]
In the mean time it has shown that I was incorrect about the technical question partly.
I am sorry for that.

I'm reopening this issue and will use it for referencing as soon as I finished the  configuration QA.
The configuration will be helping other users to see what kind of configuration they'll need, apart from the docker container.

Again, sorry for the fuss.

**Comment by thorsteneckel** [comment]
Hey there! Let me share some background information, summarise the current state and describe on what we will do next about it:

This issue was introduced by https://github.com/zammad/zammad/commit/68c56c7b8714918e9ad0d8201c532c803f90016b to enable the `secure` Cookie flag for HTTPS connections for making the usage of Zammad more secure. It basically enforces the behaviour to send/consider Cookies only over secure HTTPS connections but not over/from regular HTTP connections. This is a good thing to do and best practice.
However, it has the side effect that in a more advanced scenario where the SSL connection is not terminated by the NGINX itself (as we assume in the [NGINX example configurations](https://github.com/zammad/zammad/tree/develop/contrib/nginx)) but e.g. by a load balancer the NGINX is not aware of the HTTPS connection and therefore Zammad neither. Therefore Zammad won't know that it actually initially was a HTTPS connection and won't consider the Cookie. This leads to the CSRF validation issue you face down the road because the Cooke and CSRF token are coupled.

Since the initial change and impact I haven't seen or found a solution that resolves the issue in both setups (direct NGINX / load balancer NGINX) – unfortunately.

We will stick to the current example which expects that the SSL connection is terminated at the NGINX and not on a previous level. However, we will extend the documentation on what to do in more advanced setups and place references to it where people will end up when facing the issue (this issue, the linked PRs https://github.com/zammad/zammad/pull/2863 https://github.com/zammad/zammad-docker-compose/pull/166 and issue(s) https://github.com/zammad/zammad/issues/3049 https://github.com/zammad/zammad-docker-compose/issues/161 https://github.com/zammad/zammad-docker-compose/issues/120 https://github.com/zammad/zammad-docker-compose/issues/131 https://github.com/zammad/zammad-docker-compose/issues/157 https://github.com/zammad/zammad-docker-compose/issues/168, the [community](https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080) and probably as a remark on the installation guide). It might take some time so please be patient. If you (the lovely reader) find the time to make a contribution in this direction that would be highly appreciated.

Our philosophy is to make the installation and usage of Zammad as easy as possible for both users of the application and administrators  who do the heavy lifting behind the curtains. We take special consideration for those who are not that technical versatile or have other priorities.
It's annoying for us whenever we can't keep that bar up and need to require manual work. This is one of those situations again and we're open to any contributions that help to remove this manual step again. Just let us know, preferably over at the [community board](http://community.zammad.org/).

**Comment by benbucksch** [comment]
> We will stick to the current example which expects that the SSL connection is terminated at the NGINX and not on a previous level

Can you at least fix the docker config, please?

These days, esp. since Let's Encrypt, automatic deployment of SSL certificates is normal, and normally done with SSL terminators or traefik. Nobody wants to manually find the place in each package where the SSL certificate is configured, for every different piece of software, and manually update it all the time for each of them.

(Actually, I'd argue that this configuration hassle was the main reason why we didn't have HTTPS for most sites in the past. HTTPS is ubiquious now _only_ thanks to SSL terminators and software like traefic. Otherwise it's practically unmaintainable, if you have lots of different servers to run.)

It's even worse when things appear to work fine and then suddenly fail. Even more so when it's due to an update.

So, whatever you do, can you please ensure that the *Docker images work out of the box*, with an SSL terminator or traefik? The entire purpose of Docker is that the admin does *not* have to manually configure all the settings, but just pulls the image, adapts 5 values for hostname and root password, and it works. The last thing you want is things failing like this.

**Comment by monotek** [comment]
The docker compose image is already configurable to work like you want. Check the available env vars:

See: https://github.com/zammad/zammad-docker-compose/blob/master/containers/zammad/docker-entrypoint.sh

**Comment by benbucksch** [comment]
That requires that the admin knows about this bug. Who would? That defeats the point. Docker images need to be working out of the box. Otherwise I could install it manually.

At the very least, the necessary variables need to be right in the `docker-compose.yml` file, as concrete values, with a comment when they are needed. Right in that file. Other documents will be missed and are irrelevant.

FWIW, despite knowing about this bug, and even after reading all this, I still wouldn't know which exact variable to set to what. Do I set it to `https` (because that's what the user enters) or to `http` (because that's how it arrives at nginx)? Do I have to set the hostname or just the scheme? That's why it's important to have the exact values already in the file.

**Comment by thorsteneckel** [comment]
The docker compose image has grown much in functionality, configuration and adaption. I think that's fantastic.
I also think it's time spend well to provide some more information and documentation on how to use it. As we're currently pretty busy it would be awesome to receive some community contributions for this.
However, please do it in consultation with @MrGeneration (who has the overview of the documentation(s) and knows the next steps/directions) to avoid walking in the wrong direction.

**Comment by benbucksch** [comment]
@thorsteneckel 
> Therefore Zammad won't know that it actually initially was a HTTPS connection

I think it's fair to assume that any public server these days - esp. one that offers password login like Zammad - is on `https:`. Chrome and Firefox don't even allow anything else, and warn and disable the password manager, if it's on `http`. Can you just assume that the public server is `https:`? If the setup is insecure for people running `http:` on public servers, that's not a surprise to anyone, because the browsers explicitly warn about it.  Would that help this issue?

@monotek:
FWIW, despite knowing about this bug, and even after reading all this, I still wouldn't know which exact variable to set to what. Do I set it to https (because that's what the user enters) or to http (because that's how it arrives at nginx)? Do I have to set the hostname or just the scheme? That's why it's important to have the exact values already pre-configured.

**Comment by thorsteneckel** [comment]
> Can you just assume that the public server is https:? If the setup is insecure for people running http: on public servers, that's not a surprise to anyone, because the browsers explicitly warn about it. Would that help this issue?

We will consider it. Thanks for the food for thought!

**Comment by 7tobias** [comment]
It took my some hours to debug this CSRF token verfication failed error message in combination with traefik as reverse proxy. Here's what it make it work in my place...
in my docker-compose.override.yml i added the following:

[...]
  zammad-nginx:
    environment:
       - RAILS_TRUSTED_PROXIES=['127.0.0.1', '::1', 'traefik']
       - NGINX_SERVER_SCHEME=https
[...]

I attach my full docker-compose.override.yml that works for me to bring zammad to life in combination with traefik. I hope it saves someone some hours of searching... i attached traefik.yml (which is my docker-compose.yml file for traefik also)
[docker-compose.override.yml.txt](https://github.com/zammad/zammad/files/6032258/docker-compose.override.yml.txt)
[traefik.yml.txt](https://github.com/zammad/zammad/files/6032260/traefik.yml.txt)

**Comment by linucksrox** [comment]
@7tobias Thank you! I just applied those environment variables and that solved it for me as well. Luckily I also run Traefik as my reverse proxy and the service name happens to be 'traefik' so I believe that would need to be adjusted if your reverse proxy had a different service name.

**Comment by thalion0** [comment]
Solved my issue too. Thanks a lot @7tobias

**Comment by MrGeneration** [comment]
The new system docs were merged yesterday evening.
They now reflect help on the CSRF topic both in general and for docker-compose stacks:

   * https://docs.zammad.org/en/latest/getting-started/configure-webserver.html
   * https://docs.zammad.org/en/latest/install/docker-compose/environment.html

These pages should provide enough help for future users stumbling upon this.
Closing.
