### ISSUE TITLE
Allow create ticket only by existing customer

### ISSUE THREAD

**Issue by maxper75** [zammad/zammad#2832]
Hi,
my company uses zammad as a support ticketing system, that seems to be a goot UC.
This is nice, up til the moment in which we use the inbound email feature, where even with 30 and more filters, when a spam email comes in a ticket gets generated (this will be matter for another issue). The best would be to let only an existing customer email be converted in a ticket. This way we can generate the customers' info table and use that to create tickets.
This would help us keeping the customers list shorter and less polluted.
The way to reproduce this issue  is simple as sending an email from d.trump@whitehouse.gov :D.
Thank you so much for the awesome product anyway!
Regards, Massimiliano

**Comment by MrGeneration** [comment]
Sorry but this sounds rather like a technical question or enhancement request.
Those kind of posts are better for the Zammad Community (https://community.zammad.org) instead of this repository.

Please use the community. This helps you to find dedicated help and us to keep an proper overview. :-)

Closing now.
