### ISSUE TITLE
Auto-Complete on Typing for Tags is hidden behind Pop-Up Windows

### ISSUE THREAD

**Issue by duesterTechnology** [zammad/zammad#2890]
### Infos:

* Used Zammad version: 3.2.x
* Installation method (source, package, ..): docker
* Operating system: Ubuntu 18.04
* Database + version: N.A.
* Elasticsearch version: N.A.
* Browser + version: Chrome  79.0 and IE 11.0 and Firefox 72

### Expected behavior:

* The Auto-Complete list (for tags) will be shown IN FRONT of the Pop-Up Window

### Actual behavior:

* The Auto-Complete list (for tags) is shown BEHIND the Pop-Up Window. I can still select them using the Arrow-Keys but am not able to read the hints. I also cannot select them using the mouse-curser 

### Steps to reproduce the behavior:

* Start to fill in Tags in e.g. Trigger-Formular as condition and wait for the list to be shown (See screenshot)
![2020-01-14 12_09_43-](https://user-images.githubusercontent.com/30858793/72340894-4ad4ae00-36c9-11ea-9709-da473b8d76be.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by PhilippRedel** [comment]
I can reproduce the issue.
The z-index of the Jquery UI Autocomplete class is below the z-index of the bootstrap modal.

Im not exactly sure which z-index is needed to be above the modal but this worked for me:

(in zammad.scss)
```
.ui-autocomplete.ui-widget-content {
  z-index: 1111 !important;
}
```

I can not make a pull request at the Moment because im on vacation.
But i hope this helps fixing the issue.
