### ISSUE TITLE
Authentication with O365 - User accounts get created despite option being disabled (including reset password functionality)

### ISSUE THREAD

**Issue by wucherpfennig** [zammad/zammad#2912]
### Infos:

* Used Zammad version: 3.2
* Installation method (source, package, ..): source
* Operating system: Debian 10.2
* Database + version: default
* Elasticsearch version: 7.5
* Browser + version: Chrome, latest

### Expected behavior:

* If user creation is disabled no user accounts should be created even if the user uses the authentication method O365.

### Actual behavior:

* if the option is disabled (together with the "reset password" function) and a visitor authenticates via o365 a new user will be generated by the system.
* Issue is related to: #2503

### Steps to reproduce the behavior:

* enable o365 authentication
* disable user registration
* disable reset password function

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I'm not sure about this.
I understand your approach, however, I'd like to hear @thorsteneckel 's feedback before deciding how to tag this. :)

**Comment by thorsteneckel** [comment]
Zammad provides many ways auf authenticate users. I agree that we should have a functionality that prevents the creation of new accounts consistently. However, I'd like to have one issue that covers all this cases instead of one issue for each one of them. This might lead to a situation where we overlook some way.
Could you please bring #2503 in shape to list the relevant parts in one place in a way that we won't overlook them?

**Comment by MrGeneration** [comment]
I reworked the first article of issue #2503 it should now cover both cases.
