### ISSUE TITLE
External Customer Db

### ISSUE THREAD

**Issue by morphxle** [zammad/zammad#292]
Hi, is it possible to set a view to a external customer db? Like MS-SQL?l

**Comment by thorsteneckel** [comment]
Hi @morphxle - Not yet! I'll put it on our list.

**Comment by urksle** [comment]
Hello 
I have the same problem here, I need to add our existing customers from our system into the ticketing system. It does not make sense to add all those by hand. When can we expect this funtion ?

Kindest Regards
 Steffen

**Comment by morphxle** [comment]
hi @thorsteneckel please close this issue, now we use the api 👍

**Comment by RAD-X** [comment]
Solved same way - imorting users using own sync script. But connection to external user DB will be a nice feature.

**Comment by morphxle** [comment]
@RAD-X do you have your customer in the ldap?

**Comment by RAD-X** [comment]
Nope. Only some kind of mysql user table for ISP internal purposes.
BTW Why? :-)

**Comment by morphxle** [comment]
@RAD-X with the LDAP integration you able to import user via LDAP

**Comment by hanneshal** [comment]
Closed on request.


Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals

regards
Johannes
