### ISSUE TITLE
Attribute "integer" in organization: -1 not allowed

### ISSUE THREAD

**Issue by tobiasKaminsky** [zammad/zammad#2938]
Hello,

we used to have an integer parameter in our organization, that could be -1, 0, and up to 99.999.
Since quite some time we are now not allowed to use "-1".
It is also said in the edit parameter dialog.

Is there a reason for such a change? 
Is there a way to get the old behaviour back and allow -1? E.g. via a different type?

**Comment by MrGeneration** [comment]
Sorry but this rather sounds like a technical question - please post technical questions over at the community https://community.zammad.org .

If this turns out to be a bug and not intended, we'll gladly open this issue backup up.
Please also don't forget to not delete the requested information of your installation, as this is mandatory information.

Closing now.
