### ISSUE TITLE
Can not create first admin account #getting_started/admin

### ISSUE THREAD

**Issue by Herbstweiss** [zammad/zammad#2945]
Hello,

we try to implement the ticket system Zammad in our company.
Unfortunately it always fails when trying to create the "first" admin account. We always get the message "can't create".
We have installed the server several times according to the instructions and have always followed the instructions.
No matter whether from Zammad himself or from other websites, no installation went better.
So far we have used Debian10, CentOS7 and Ubuntu 18.04 for the Linux distributions.
Also had no influence on the result.
this is the current system which has the error again.

18.04.4 LTS (GNU/Linux 4.15.0-88-generic x86_64)
postgres (PostgreSQL) 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)
3.2.0-1583078335.fd84f3a1.bionic

I am grateful for any information and advice

**Comment by Herbstweiss** [comment]
![grafik](https://user-images.githubusercontent.com/61696262/75684919-0366a900-5c9a-11ea-9a01-b7a0ac479091.png)

**Comment by MrGeneration** [comment]
Please provide your production.log.

**Comment by Herbstweiss** [comment]
[production.log](https://github.com/zammad/zammad/files/4275978/production.log)

**Comment by Herbstweiss** [comment]
I once set the whole log as a file because the file has an extremely large number of lines

**Comment by MrGeneration** [comment]
Sorry but this is a technical questions and not a bug.
You're having issues with CSRF-Tokens which has been described here:
https://community.zammad.org/t/zammad-3-2-is-available/3656 (point2 important technical notes)

For the next time, please post technical questions within the Zammad Community, because for us the Github-Repository is for issues only. This helps us to focus on bugs.

With the above link you should be able to solve your issue - if not, we'll gladly assist you over there within a new thread to get you going. 💪 

Closing now.
