### ISSUE TITLE
Reply to ticket to and copy search account failed.

### ISSUE THREAD

**Issue by enryxgit** [zammad/zammad#2974]
### Infos:

* Used Zammad version: 3.3.0
* Installation method (source, package, ..): yum
* Operating system: Centos 7 v7.7.1908
* Database + version: PostgreSQL v9.2.24
* Elasticsearch version: v5.6.16
* Browser + version: v79.0.3945.88

### Expected behavior:

* After update to Zammad v3.3.0, e-mail address search pop-up is not visible in To and Cc field.
We have to add the e-mail address manually.

### Actual behavior:

* After update to Zammad v3.3.0, e-mail address search pop-up is not visible in To and Cc field.
We have to add the e-mail address manually.
LDAPS is enabled and sync perfectly.
Exchange Server 2016 is enabled and sync perfectly.

### Steps to reproduce the behavior:

* 1. Create a new ticket.
2. Reply to user and try to add To and Cc mail address, as you can see, account search popup will not be available.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry but this is rather a technical question.
Please ensure to re-index your elasticsearch searchindex as stated in the release notes.

This is a mandatory step after upgrading because of technical changes in Zammad.

If the issue persists, please ensure your elasticsearch is running and not crashing. Allow your installation to run the search (wait 5-10 seconds to be sure).

Please post technical questions over at the Community: https://community.zammad.org
If we prove me to be wrong and this to be a bug indeed, I'll gladly reopen this issue. :-)

**Comment by enryxgit** [comment]
Thank you MrGeneration!
Issue solved.

1 - Run this command successfully.
/usr/share/elasticsearch/bin/elasticsearch-plugin list displaying ingest-attachment

2 - Run reindex successfully
zammad run rake searchindex:rebuild

3 - Restart zampar service successfully
systemctl restart elasticsearch
 
I try to reply to a ticket open by a user, try to add To or Cc and now I can see pop user to add.

Thank you so much.
Close the ticket.
