### ISSUE TITLE
CSV Exports ignore related fields

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3002]
### Infos:

* Used Zammad version: 3,3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket-ID: #1061272

### Expected behavior:

When creating CSV Exports (e.g. via Time accounting or Reporting) Zammad uses existing related objects / relations to display their values.

### Actual behavior:

When creating CSV Exports (e.g. via Time accounting or Reporting) Zammad does not get values from existing related objects or relations. In some situations this causes Zammad to return IDs instead of names.

### Steps to reproduce the behavior:

* have a relation object
* fill it with relational data
* export a CSV

*Note*: This is more of a future use implementation.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Based on the ticket information i don't think this issue is valid anymore. There is some code already which does lookup relations (https://github.com/zammad/zammad/blob/275c32a35f254b6740c8209a2882d7f8ca66c4e6/lib/excel_sheet.rb#L118) and display the name of the object if possible. The related ticket issue has other reasons, here the relation at the object (belongs_to) is missing which relates to the missing display value.
