### ISSUE TITLE
Tree-Select is missing tooltip if required and not set

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3008]
### Infos:

* Used Zammad version: 3.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on Google Chrome (latest)
* Ticket-ID: #1068251

### Expected behavior:

When trying to update or create tickets with required attributes, Zammad will display an error tooltip indicating the field still needs to be filled with information.

### Actual behavior:

When setting a tree select attribute to mandatory, it will not indicate that it hasn't been set.
This causes confusion for the user, as "everything looks good to go", while it isn't.

### Screencast:

![ticket_1068251_bug-tree-select-no-tooltip-on-required](https://user-images.githubusercontent.com/6549061/78362612-b3da0c80-75ba-11ea-99f0-b91dff7c0226.gif)

### Steps to reproduce the behavior:

* create a custom tree-select object with mandatory setting (e.g. as agent)
* update or create a ticket and do not touch your tree-select
   * you won't be able to post your new changes

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
Looks like the issue came in with this commit:

https://github.com/zammad/zammad/commit/d68d867866

the left px result in a hover fly's around:

https://github.com/zammad/zammad/blob/7bfe6dac3149c751fe7d69970737d07f73766b6d/app/assets/stylesheets/zammad.scss#L9412

![grafik](https://user-images.githubusercontent.com/5445062/101494768-08aefd80-3968-11eb-9002-dfae91963420.png)

If i do `left: 0px` it works and looks good. 

@mrflix do you remember the reason for the left px absolute change maybe? What do you think would be a good fix for it?

**Comment by mrflix** [comment]
The `searchableSelect-shadow` is set to `-9999px` to hide from screen because it should never be visible. It has additional UI that's being interacted with. If it shows a faulty required notification I'd investigate why the additional UI doesn't fill out the shadow element.

**Comment by mantas** [comment]
@mrflix if interactive element is required but empty, it could generate the tooltip for shadow element and then position it to look as if it's for the interactive element.

For example search-select could have some text entered, but option from dropdown never selected. Effectively shadow element would be invalid. While interactive element technically would not be empty.

**Comment by mrflix** [comment]
@mantas I'm not sure if I understand the issue correctly. Please help me:

a) If the UI is filled but not the shadow we'll have to make sure that the shadow is filled too. They always have to be in sync. b) If the required tooltip is at the wrong position I'll have to fix that.

**Comment by romitgithub** [comment]
From my understanding from the comments here, the shadow element is used just to show tooltip. And @mrflix used left -999px to hide it from screen, but this can be achieved using **{position: absolute, left: 0px, z-index: -999}** since this will keep the shadow element always behind the interactive element and will show the tooltip as required.

@mantas Let me know if this sounds like a good approach. Thanks

**Comment by mantas** [comment]
@mrflix this is case B. The mechanics work fine. But tooltip is not shown because it is tied to shadow element.

What was the reason to move shadow element off screen? It looks like it is properly hidden by foreground input element .

**Comment by dominikklein** [comment]
In the current version is a visible identifier present, when the field is required and not filled:

<img width="320" alt="Bildschirmfoto 2023-02-09 um 17 53 19" src="https://user-images.githubusercontent.com/5445094/217883163-f4d0a434-92d6-4384-8495-3f11686bc1b9.png">
