### ISSUE TITLE
Zammad Wordpress Chat dont appear

### ISSUE THREAD

**Issue by ahmidosenadoro** [zammad/zammad#3010]
Hello @all,

i have the problem with the Zammad chat with Wordpress. I have connected the Wordpress-Site with Zammad and i see at the debugger that the site is connected. But when  i try to open the chat with the button on the wordpress website, the chat will not appearing. There is no errors in the logs or something. Do anyone have an idea what the problem is?

Thanks for your help

greet
ahmido

**Comment by MrGeneration** [comment]
Sorry but this looks like a technical question.
Please note that we strictly divide technical questions from bug reports, which is why this repository is the wrong place.

Please consult the Zammad Community at https://community.zammad.org and make sure to fill in the technical assistance form to help us to help you.

Thank you!

Closing.
