### ISSUE TITLE
Cannot give default role ticket.agent permissions (even though account creation is disabled)

### ISSUE THREAD

**Issue by Gittenburg** [zammad/zammad#3027]
### Infos:

* Used Zammad version: 3.3

The changes introduced in #1758 prevent a legitimate use case:

At my organization we have disabled account creation via the web interface and all users that use the web interface are ticket agents. Until now we created all accounts manually. Now we want to use Authentication via SAML, which works but inconveniently newly created accounts cannot have the ticket agent permission by default.

### Expected behavior:

* when New User Accounts is disabled you can give the default role ticket.agent permissions

### Actual behavior:

* you get an error message:
>Cannot set default at signup when role has admin or ticket.agent permissions.

### Steps to reproduce the behavior:
As an admin go to settings:
1. under Security disable new user accounts
2. under Roles try making a role with the ticket agent permissions the default

**Comment by MrGeneration** [comment]
Oh sorry for that.
Don't know why I didn't read the title correctly.

Default signup roles may not contain sensible permissions such as reporting, ticket.agent or even admin.
This is by design and it doesn't matter if you disabled the signup by anonymous users.

The reason:
Your agents can also create new users in case they can't find the customer within the database.
Other wise they can't create the ticket in question.

This would mean they'd create a new agent account, because by default they can't provide the correct permission.

This ends in you having data leaks.
This is a potential security risk and a **very** bad idea.

Thus closing as won't fix.

**Comment by Karlovsky120** [comment]
From what I can gather, the problem is that the setting is global, meaning that **every** created user has the set role(s). If you could differentiate created users by source (google oauth, internally by agent, web interface registration, etc.) it would be possible to allow all accounts created via google oauth to be agents, while others default to customers, avoiding the problem you presented.

I'm sure there are implementation details that have to be worked out, but it does seem doable.
Or am I missing something?

**Comment by MrGeneration** [comment]
Please don't hijack closed issues, if you have questions head over to the community: https://community.zammad.org
