### ISSUE TITLE
Newly created users are only shown in the admin interface after reload

### ISSUE THREAD

**Issue by Vogelkoje** [zammad/zammad#3050]
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Google Chrome, Internet Explorer, Firefox 
* Ticket-ID: #1075470 

### Expected behavior:

* When creating a user in the administration interface, the user list should be updated directly without the need for a reload.

### Actual behavior:

* After a user has been created in the admin settings, the new user object is not displayed directly. A reload must first be performed for the object to be displayed.

### Steps to reproduce the behavior:

* Login into web interface with admin permissions
* Go to settings > Users
* Create an new user via "new user"
* After the user is not displayed directly
* Reload must first be performed for the object to be displayed

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by gituser** [comment]
Having same issue in Zammad v3.6.0 (0157dc25f45e2cbc19f00faf5647ec1dcad31732) as well.

**Comment by MrGeneration** [comment]
Locking conversation to contributors only to reduce "me too" messages.

**Comment by romitgithub** [comment]
@MrGeneration Not able to reproduce this issue on stable. Users are automatically reloaded after adding

**Comment by MrGeneration** [comment]
Please ensure to have Elasticsearch enabled up and running. 
This does not work, because Elasticsearch indexing takes longer than we're waiting for the reload. 

This means the delayed job may not be done at that moment. 

See screen cast. It shows about 30 seconds *before* I fiddle around with the role filter which causes a reload on the list.
![issue-3050](https://user-images.githubusercontent.com/6549061/121511244-ba4aec00-c9e8-11eb-8ec3-d2ee3af3ff7e.gif)

The instance shown is a current stable 4.1 (pulled today morning)

**Comment by romitgithub** [comment]
Thanks for the additional info. Will look into it 👍🏼

**Comment by rolfschmidt** [comment]
approach to fix this

**app/models/user/search.rb**
```diff
diff --git a/app/models/user/search.rb b/app/models/user/search.rb
index 9cd136fca..1c8f470e7 100644
--- a/app/models/user/search.rb
+++ b/app/models/user/search.rb
@@ -99,7 +99,7 @@ returns
         end

         # try search index backend
-        if SearchIndexBackend.enabled?
+        if SearchIndexBackend.enabled? && query.present? && query != '*'
           query_extension = {}
           if params[:role_ids].present?
             query_extension['bool'] ||= {}
@@ -162,10 +162,12 @@ returns
                       end
         end

-        statement.where(
-          '(users.firstname LIKE ? OR users.lastname LIKE ? OR users.email LIKE ? OR users.login LIKE ?) AND users.id != 1', "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%"
-        )
-        .order(Arel.sql(order_sql))
+        if query.present?
+          statement.where(
+            '(users.firstname LIKE ? OR users.lastname LIKE ? OR users.email LIKE ? OR users.login LIKE ?) AND users.id != 1', "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%"
+          )
+        end
+        statement.order(Arel.sql(order_sql))
         .offset(offset)
         .limit(limit)
       end

```

We should only use the elastic search if a query is entered in the search field of the admin user interface. Otherwise use the rdbms. 

**Also** there is a change needed to empty the user search field after the user got created in the frontend.

The search field is then the only place where the elastic search is used and the admin has to wait until the new data is indexed correctly if he has some specific query. In all other cases it should be displayed then.
