### ISSUE TITLE
docker-entrypoint.sh: Permission denied

### ISSUE THREAD

**Issue by Suleman-Elahi** [zammad/zammad#3079]
### Infos:

* Used Zammad version: latest
* Installation method (source, package, ..): Docker
* Operating system: Xubuntu 18.04
* Database + version:
* Elasticsearch version:
* Browser + version: Chrome 84

### Expected behavior:

* After running the `docker run` command, it should start working on localhost.

### Actual behavior:

* It showing error:
`/bin/bash: /docker-entrypoint.sh: Permission denied`
![image](https://user-images.githubusercontent.com/24384996/84359160-dc4b3c00-abe5-11ea-96f3-9ac5c7f96b4e.png)

### Steps to reproduce the behavior:

* Run the Docker installation command given on the wiki.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sidenote from me: Please don't use version `latest` - we strongly encourage against doing so.

**Comment by Suleman-Elahi** [comment]
> Sidenote from me: Please don't use version `latest` - we strongly encourage against doing so.

There is no versioning for Docker images, right? or is there?

**Comment by MrGeneration** [comment]
There is:
https://hub.docker.com/r/zammad/zammad/tags

Oh and by the way - sorry for noticing so late.
You're in the wrong repo.
This is not application related, but an issue of either your docker installation or our scripts of docker.

The correct repository would be:
https://github.com/zammad/zammad-docker


Also, just for completness, as pointed out on our documentation (https://docs.zammad.org/en/latest/contributing/install-docker.html): The single docker image is not suitable for productive use - in case you're planning to do so, you should stick to the docker-compose version.

---

Closing because of wrong repo.
