### ISSUE TITLE
Deletion of communication article works for admins

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3086]
### Infos:

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: tested on Chrome
* Ticket-ID:  1076948 

Regression introduced by: https://github.com/zammad/zammad/commit/e037b6015eeb24050816a643156230d7bb9f7bac

### Expected behavior:

Administrators can't delete communication articles because.

### Actual behavior:

Administrators that have administrator rights are now able to delete all kinds of articles.

### Steps to reproduce the behavior:

* login as administrator
* take a look at any ticket (article type doesn't matter)
* successfully delete article

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by thorsteneckel** [comment]
This was possible since [4 years](https://github.com/zammad/zammad/commit/2078a079cd05c52bb3b9bd541e44067682fa32ab#diff-5bd5d4546d4924340722d82eb2daccc1R146-R150) via the REST API. @mantas removed the inconsistency and [just added the functionality to the UI](https://github.com/zammad/zammad/commit/222e8c0dd3e787762191c6b378fd5959ec482dd2#diff-4839de132a6830d0d6174f62efaa4d4b).

As discussed internally: We should remove the special Administrator capability because Administrators should use the Scheduler functionality to remove Tickets in the admin interface.
