### ISSUE TITLE
Thousands of emails sent to same address, system crashed after background tasks piling up as result

### ISSUE THREAD

**Issue by aartrost** [zammad/zammad#3103]
### Infos:

* Used Zammad version: 3.2.0
* Installation method (source, package, ..): package via zammad.repo
* Operating system: Amazon Linux 2 (CentOS 7-based)
* Database + version: PostgreSQL 9.2.24
* Elasticsearch version: 7.4.2
* Browser + version: n/a

### Expected behavior:

Don't crash Zammad on a 354 Go Ahead response from Gmail SMTP

### Actual behavior:

For some reason (we suspect the above) our system crashed because of SMTP issues. Our server re-sent the same email to the same person thousands of times over the course of 2 days. This caused all ticket replies after this one to be queued up till all the background caused a 100% CPU load crashing the system.

### Steps to reproduce the behavior:

n/a

-------

### What happened:

Last Friday our Zammad server experienced a quite spectacular breakdown. We found the server chugging at a constant 100% CPU load on our `mx5.large` instance. Upon checking our support system outbox we've found a single ticket reply email was re-sent thousands of times (2 day period with 20 second interval). All our other emails sent after that did not make it through, causing the background jobs to pile up to `10244 background jobs in queue` according to the healthcheck endpoint. This all happened over the aforementioned 2 day period.

### Our diagnosis:

From what we can see the problematic email went out `Tuesday, Jun 23 at 10:33 PM`, which is `2020-06-24T06:33:36` UTC. In our logs we find this:

```
E, [2020-06-24T06:33:36.277300 #8422-47047543409480] ERROR -- : Can't use Channel::Driver::Smtp: #<Net::SMTPUnknownError: 354  Go ahead r76sm2428933qka.30 - gsmtp
E, [2020-06-24T06:33:36.277359 #8422-47047543409480] ERROR -- : 354  Go ahead r76sm2428933qka.30 - gsmtp (Net::SMTPUnknownError)
```

This is bizarre because `354 Go ahead` is not an SMTP error code. Why is it marked as an error? The closest related bug report we can find this this one: https://bugs.ruby-lang.org/issues/2749. This issue should have been resolved 10 years ago in Ruby `1.9.2dev`. We run Ruby `2.5.5`. 

Regardless, we suspect the incorrect handling of gmail's `354 Go ahead` is causing the email to be sent whilst Zammad thinks the email did not make it there because of an error. Zammad keeps retrying and the email keeps going out. After this we find 256k errors originating from `Net::SMTP` and eventually our Gmail account started blocking our account due to too many login attempts.

Here is a pastebin link with the redacted source of the email in question in case it helps at all: https://pastebin.com/21G3xuz9. Our log file for that day is 1.04 GB in size, so I opted to not attach it. If there's anything from the logs that anyone needs, I'll gladly provide snippets.

**Comment by MrGeneration** [comment]
Before continueing in any direction I'd warmly recommend to upgrade to Zammad 3.4 like.. as fast as possible.
Zammad 3.2 is prune to security issues which you may want to solve before hand.

Note that ruby changes to 2.6.5 when using Zammad 3.4.

**Comment by gohai** [comment]
Thank you @MrGeneration - we'll be updating. However, I didn't see any changes in Ruby's `SMTP` handling recently - meaning that the issue likely still stands.

This happened out of the blue after a couple month of uptime, so any any consideration of this issue would be deeply appreciated.

**Comment by MrGeneration** [comment]
Please don't get me wrong with above comment.
I'm having a look soonish (tomorrow) - however, this issue technically should also affect other customers which doesn't seem to be true at this moment.

**Comment by MrGeneration** [comment]
I'm sorry for the delay, I'm afraid I can't reproduce this issue on either Zammad 3.2 and 3.4.
This might possibly a configuration issues on schedulers or triggers.

I've sent at least 12 mails per instance I've tried.
I ensures to always mail to the same user.

To ensure the issue doesn't appear on new tickets or doesn't because of references, I've created several independent new tickets.
All mails per instance have been sent out within 5 minutes.


The SMTP Error "354" is never appearing within the production log which is why I suspect this is not a direct Zammad or ruby issue. Especially when using google and "bombing" a single user with dozens of mails - ensure to not hit Googles sendout limits.

As I can't reproduce this issue, I'll have to close this issue.
If the problem consists with Zammad 3.4 please kindly create a post on the Zammad-Community (https://community.zammad.com) and reference this issue.

If we can proove me wrong there, I'll gladly reopen the ticket is required.
Thanks and have a nice weekend.
