### ISSUE TITLE
Unprocessed E-Mail

### ISSUE THREAD

**Issue by SEGGER-NV** [zammad/zammad#3114]
### Infos:

* Used Zammad version: 3.3.x
* Installation method (source, package, ..): package
* Operating system: Dabian 9
* Database + version: -
* Elasticsearch version: -
* Browser + version: Firefox latest

### Expected behavior:

*  When receiving an e-mail that e-mail should be processed by zammad and a ticket should be opened.

### Actual behavior:

*  The attached e-mail can't be processed by Zammad and it is not clear why.
* Is this an issue with the e-mail or Zammad?
[example.zip](https://github.com/zammad/zammad/files/4911722/example.zip)

### Steps to reproduce the behavior:

* Send the attached E-Mail to a Zammad inbox. It will be moved to the unprocessed e-mails folder.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
