### ISSUE TITLE
New email account expert view cannot be opened without filling in all fields

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#3137]
### Infos:

* Used Zammad version: 3.4, 4.1/stable
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* When adding a new email account, expert settings can be brought up right away

### Actual behavior:

* When adding a new email account, all form fields has to be filled in to be allowed into expert view

![Screenshot 2020-07-29 at 13 50 50](https://user-images.githubusercontent.com/36944/88791595-ab799300-d1a2-11ea-9293-2b4e50323733.png)

### Steps to reproduce the behavior:

* Go to Manage > Email and click "Add new"

* Click "Experts"

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
The reason for this is that when pressing on "Experts", the email field does change to "user".
This allows you to use an user account that is different from your email address. Just as a heads up!

**Comment by mantas** [comment]
Not-yet-filled-in email could be easily converted to empty user field :) Or not?

**Comment by MrGeneration** [comment]
In my humble opinion it's easier to require the email address first.
If you don't you have two uses cases:
* already filled in 
  - fill out the user field with the supplied mail address
  - in this use case it doesn't matter if you swap "email" with "user"
* not filled in email
  - you can't swap "email" with "user", because you then wouldn't be able to set your mail address

**Comment by mantas** [comment]
Oh boy. I thought that when in expert view I edit "User" field, it applies to where "Email" value would go to.
