### ISSUE TITLE
js-notificationsCounter can't over 100+

### ISSUE THREAD

**Issue by NeverMin** [zammad/zammad#315]
js-notificationsCounter can not over 100+, is a normality limit?

Zammad version = git

**Comment by martini** [comment]
Hi @NeverMin 

currently the limit is 200. It's only for performance reasons. We also can go up to 300. But IMO more as 100 makes no sense because the agent need to work/handle the work. For more then 100 it's not possible to get an overview of it's online notifications.

Any feedback is welcome!

 -Martin

**Comment by NeverMin** [comment]
Noted! you are right, good for me.

-Never
