### ISSUE TITLE
Backup script restoration order causes issues if version difference causes ruby version differences

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3160]
### Infos:

* Used Zammad version: 3.4 and earlier
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Restoration works, no matter which version you're restoring (or migrating) from.

### Actual behavior:

If your old Zammad version had a different ruby version from the one a fresh install provides you can't run Zammad commands.
The backup script currently restores all Zammad files **before** it works on database restoration.

As we're using Zammad commands for some operations, this task will fail if the restored Zammad installation actually has required different ruby version. This causes the database restoration to fail and cause issues and confusion.

This is because Zammad expects ruby in a version the system can't provide.

### Steps to reproduce the behavior:

* backup a fairly old Zammad version (e.g. Zammad v2.8)
* install a new host with a fresh Zammad 3.4
* try to restore your old 2.8 backup :D

### Workaround:

Manually import the dump *or* upgrade your old installation before migrating.
This causes environments to be available and solve these issues. Not perfect  though.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I prepared a commit on our private repo for this issue.
It will swap file and database restoration for package installations, but will remain the current behavior other installation types.

I believe that this is the best approach together with above mentioned PR no 140.
Admins or source code installations may want to restore right away without needing to install. 

This is not possible for package installations because of missing environments (this would actually raise manual tasks for admins)

**Comment by mgruner** [comment]
@thorsteneckel @MrGeneration @martini 

Referring to our discussion about the "atomic" restore from earlier today, I found this PR and related commit. It seems that the restore script is used for entirely different purposes (migrating to other systems, performing major updates). If that is true, then my proposed changes might not stand, because they are more restrictive. The current version seems to work even with another ruby version, if I understand @MrGeneration's changes correctly (Ruby from Zammad 3.4 would be used to drop/create the database.
Also, the current code has different treatment of package based and source based installations, with some inconsistencies.

Let's talk about this to agree on a way forward, please.

Best regards, Martin
