### ISSUE TITLE
Backslash "\" causes tree select to disappear during selection

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3162]
### Infos:

*This bug report originally comes from community user "vak" (https://community.zammad.org/t/bug-report-version-3-4-0-4/5152)**

* Used Zammad version: 3.4
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on latest Google Chrome

### Expected behavior:

The content of a tree select field doesn't matter. You can always select it's value. If you configure unsupported characters into one of your values, Zammad won't let you update the object.

### Actual behavior:

Entering "\" into any value of a tree select object causes the value selection to disappear as soon as you use such a value.

In my quick test I verified it on:
* overviews
* sla
* ticket detail view
* trigger

I guess it affects the complete UI.

### Steps to reproduce the behavior:

* create a tree select with "\" in at least one of your values
* update your database and restart Zammad
* go to any UI part that allows you to select tree select field values and try to set your value with backslash (or a level below it).

![issue_backslash-in-tree-selects](https://user-images.githubusercontent.com/6549061/91042305-d3c5a780-e611-11ea-9301-2756cea64b74.gif)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by bolah2009** [comment]
Hi @MrGeneration 

I am not sure I get the issue right or perhaps the issue has been solved.

Below is an example where the value selection still appears after selecting a value with `\`:


https://user-images.githubusercontent.com/36057474/107738919-f8b8ee80-6d07-11eb-8c59-451c4aaa5f8f.mov

**Comment by mantas** [comment]
@bolah2009 did you try it at Ticket view? As in Marcel's screencast. The conditions selector view was rewritten since then and uses a different widget.

**Comment by bolah2009** [comment]
Yes, @mantas I did. Maybe I don't under the issue. See screencast below:


https://user-images.githubusercontent.com/36057474/107739801-fb1c4800-6d09-11eb-8a58-e2080407468e.mov

**Comment by mantas** [comment]
@bolah2009 the issue is that if Tree Select item has backslash in it's name, you cannot select children items in it. It selects the item itself instead of opening it's children.

Currently this only happens in Ticket view.

**Comment by bolah2009** [comment]
Thanks, @mantas, the "children" items is where my confusion is.

**Comment by mantas** [comment]
Children as in sub-items. 

`Parent \ Item`

> `Children 1`
> `Children 2`

**Comment by bolah2009** [comment]
Got it!

**Comment by bolah2009** [comment]
After some investigation on the issue I found out that the `\` is escaped when it is used to query the element, that is, when the parent is `le \ test`, it queries `le  test` instead of `le \ test`.

I think there are some possible solution to these, not sure which approach would be preferred:
1. We disallow the use of backslash `\`
2. We escape such characters.

The approach in the screenshot below is (2), there's an existing utility function `App.Utils.escapeRegExp` that does this already, so using it gives the desired result. Since it will also escape other characters like `*`, `+` , `?`, etc, I tested the tree select with these characters too.


https://user-images.githubusercontent.com/36057474/107860297-e2fa1500-6e3e-11eb-92c7-96002fc9379b.mov
