### ISSUE TITLE
Microsoft Teams for notifications (with pre-defined Webhook)

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3218]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Note: This enhancement originally comes from one of several feature requests on our [community](https://community.zammad.org/t/integration-of-microsoft-teams/1409). Please don't use this issue for discussion.*
*  T#1083667

### Desired behavior:

It should easily be possible to add microsoft teams as a notification.

Push messages (mainly ticket information) depending on their state to a specific Teams channel.

More information regarding Slack can be found here:
https://admin-docs.zammad.org/en/latest/system/integrations/slack.html

![image](https://user-images.githubusercontent.com/6549061/94259410-b47eaa80-ff2e-11ea-9e93-0914310e78fb.png)

For this, we want to use the new pre-defined webhooks (like we do for Slack, Mattermost and RocketChat).

Example for Microsoft Teams:

![Image](https://user-images.githubusercontent.com/5445094/232788594-12273a3a-9cec-4bf7-a2c3-6266967b17ba.png)

### Actual behavior:

Currently, Zammad doesn't provide Microsoft Teams support for notifications.

**Comment by dominikklein** [comment]
@dvuckovic Feel free to add some example payload for the adaptive cards.

**Comment by dvuckovic** [comment]
Payload example with the new message card format (incl. color customization):

```json
{
  "@type": "MessageCard",
  "@context": "http://schema.org/extensions",
  "themeColor": "#cb2431",
  "summary": "summary text",
  "title": "title text",
  "text": "text text",
  "sections": [
    {
      "facts": [
        {
          "name": "fact name 1",
          "value": "fact value 1"
        },
        {
          "name": "fact name 2",
          "value": "fact value 2"
        },
        {
          "name": "fact name 3",
          "value": "fact value 3"
        }
      ]
    }
  ],
  "potentialAction": [
    {
      "targets": [
        {
          "os": "default",
          "uri": "https://example.com"
        }
      ],
      "@type": "OpenUri",
      "name": "Link name"
    }
  ]
}
```

Example screenshot:

![Screenshot-2021-07-07-at-09 47 51](https://user-images.githubusercontent.com/6049445/232410996-503c87c0-28ad-41d1-b31c-98da58a6ac83.jpg)


To enable incoming webhook in a Teams channel, follow the steps below (hopefully the UI didn't change too much in the past year or so):

1. Find a designated MS Teams channel for receiving of notifications.
2. Click on three dots next to the channel name in the sidebar (More options), and choose **Connectors**.
3. Find the **Incoming Webhook** connector in the list, and click on **Configure** button next to it.
4. Enter name of the webhook in the first text field, which will be used instead of a user.
5. Upload an image as the webhook avatar.
6. Click on **Create** button.
7. After few seconds copy the webhook **URL** to clipboard by clicking button next to it.
11. Use webhook URL as the endpoint.
