### ISSUE TITLE
Setup wizard should allow to invite colleagues when skipping email channel setup

### ISSUE THREAD

**Issue by mantas** [zammad/zammad#3237]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* When setting up a new system and skipping email channel, `Invite colleagues` screen should pop up

### Actual behavior:

* When setting up a new system and skipping email channel, `Invite colleagues` screen is not shown

### Steps to reproduce the behavior:

* Setup a fresh system
* Skip email channel setup

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
Closing as not fixable. Apparently can't send out invite while no email channel is configured! Whoops.

**Comment by MrGeneration** [comment]
Invitations should be sent out via the notification channel.
Zammad does force you to configure your notification channel - it's either SMTP or sendmail.

However, if you skip that part and leave it as is, it will be sendmail and thus requires you to have it configured already.
So this may also be the reason why it fails. 

I personally think it's enough to have it within the Dashboard. If you're still setting Zammad up, inviting people to early may be confusing instead of being usefull.
