### ISSUE TITLE
Sort_by and Order_by not working ticket search

### ISSUE THREAD

**Issue by cashwani** [zammad/zammad#3268]
I am trying to search ticket with sort option

### Infos:

* Used Zammad version: 3.4.x
* Installation method (source, package, ..): Install on Ubuntu via DEB
* Operating system: Ubuntu
* Database + version: PostgreSQL + 10.14
* Elasticsearch version: 7.9.1

### Expected & Actual behavior:

case 1:

https://domain.com/api/v1/tickets/search?query=(organization_id:3 AND owner_id:17 AND group_id:(1 OR 2 OR 3 OR 5))&page=1&per_page=10&**sort_by=id&order_by=desc**

**but I am getting an empty array**

case 2:

https://domain.ca/api/v1/tickets/search?query=(organization_id:3 AND owner_id:17 AND group_id:(1 OR 2 OR 3 OR 5))&page=1&per_page=10&**sort_by=created_at&order_by=desc**

**I get a result but look like it is not being sorted as expected.**

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
