### ISSUE TITLE
Rich Text Editor doesn't appear

### ISSUE THREAD

**Issue by tiagoIW** [zammad/zammad#3269]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): Docker
* Operating system: Ubuntu
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* Can edit knowledge base with Rich Text Editor

### Actual behavior:

* Rich Text Editor doesn't appear to Knowledge Base

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

Please note that Zammad does not have a dedicated "rich text editor".

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
