### ISSUE TITLE
SMIME - undefined method `n' for #<OpenSSL::PKey::EC:0x0000560dd2b31c68> 

### ISSUE THREAD

**Issue by Pisoko** [zammad/zammad#3285]
Hey Zammad

I'm trying to upload our CA Cert to Zammad to prepare the use of SMIME.
I get the following error trying to upload a base64 formatted cert.

**undefined method `n' for #<OpenSSL::PKey::EC:0x0000560dd2b31c68>**

![error_zammad](https://user-images.githubusercontent.com/11957656/99368329-4bc30700-28bb-11eb-927d-02aa46577d99.png)

The log is attached.

[production.log](https://github.com/zammad/zammad/files/5552241/production.log)

PS: There are a lot of **/n line breaks** in the log.

I, [2020-11-17T09:44:31.560851 #18851-47308676082980]  INFO -- :   Parameters: {"data"=>"-----BEGIN CERTIFICATE-----\r\nMIIDmjCCAvygAwIBAgITHgAAAAlys075AaGHjQAAAAAACTAKBggqhkjOPQQDBDAU\r\nMRIwEAYDVQQDEwlMSVNSb290Q0EwHhcNMTkwMjIxMTUxNTQxWhcNMjIwMjIxMTUy\r\nNTQxWjBCMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZFgNs\r\naXMxFDASBgNVBAMTC0xJU1NjaG9vbENBMIGbMBAGByqGSM49AgEGBSuBBAAjA4GG\r\nAAQBKxjNf0W1FV2hvWBVeWr0ewUJCxMferMM6dJEoNJI1MwzIIZBiqqHAWq4Xu4o\r\nggZ3nXh0schQSS71JeMfPP6/inAAgW+13czzJKA8ILWm9JJSUgo2MDpji2Aclc74\r\nI4kThKtWoEJxWF1WIGN14Qgh4YzAObGfwUFI3TLgoua5YoFT+6WjggG6MIIBtjAS\r\nBgkrBgEEAYI3FQEEBQIDAgACMCMGCSsGAQQBgjcVAgQWBBSRbnk1Crni+XgKz5Hi\r\nk/Oap7BFXzAdBgNVHQ4EFgQU9MN6SZHtPOXbRRXJHnJ/uxNrV5owGQYJKwYBBAGC\r**\n**NxQCBAweCgBTAHUAYg...

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

As per https://admin-docs.zammad.org/en/latest/system/integrations/smime.html#troubleshooting ensure you're using a clean PEM formatted certificate.
