### ISSUE TITLE
Upgrade to 3.6 throws error when logging into WebGUI

### ISSUE THREAD

**Issue by bastolino** [zammad/zammad#3286]
Error Message is as follows:
Mysql2::Error: Unknown column &#39;stats<u>stores.stats</u>storable<u>type&#39; in &#39;where clause&#39;: SELECT `stats</u>stores`.* FROM `stats<u>stores` WHERE `stats</u>stores`.`stats<u>storable</u>type` = &#39;User&#39; AND `stats<u>stores`.`stats</u>storable<u>id` = 3 AND `stats</u>stores`.`key` = &#39;dashboard&#39; LIMIT 1 

see https://community.zammad.org/t/zammad-crashed-after-3-6-update/5667/7
Downgrading to 3.5 makes it work again.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
