### ISSUE TITLE
Ticket Priority and states can be changed by customers via API

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3288]
### Infos:

* Used Zammad version: 3.5
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any 
* Browser + version: any

*Note: This is a breaking API change which causes ticket creation payloads for customers no longer to allow setting e.g. the ticket priority as customer.*

### Expected behavior:

If you're a customer, you can't set or change ticket states (for states the customer may not see) or ticket priorities.

### Actual behavior:

Currently customers can see all available ticket states via API and by knowing the correct ticket states also update the tickets state. This also applies to ticket priorities.

### Steps to reproduce the behavior:

Below steps have to be done via API.

* retreive a list of states available
* update tickets priority and state to a state you can't see within the UI as a customer
* check the ticket

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
### Status quo

The state is not changeable to a pending state for example because core workflow is restricting the values which can be set. So with core workflow you would be also able to restrict options of other select fields which are not shown in the UI for the API. In general there is no possibility yet to remove a field completely from the API.

- State can be changed to open, closed but not pending reminder (because of core workflow).
- Priority can be changed.

### Current concept

Current API behaviour does allow changing everything of the ticket, except a couple of blacklisted columns:

https://github.com/zammad/zammad/blob/084cbc0253d30ca0e9fe4b9347ff5e38d6d4f54f/app/controllers/tickets_controller.rb#L258-L262

### Meeting DK+RS (2023-11-22)

The API for zammad does not match the UI in most places and provides more possibilities. There is also no asset-limiting and in general for the ticket. So changing behaviour here would be breaking the current concept. Might change in the future, but currently there is no change planned for this. There would also be heavy specification needed for this.
