### ISSUE TITLE
js some api GET methods are different 

### ISSUE THREAD

**Issue by rlakis** [zammad/zammad#3298]
### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): package
* Operating system: CentOS Linux release 7.9.2009 (Core)
* Database + version: postgresql-server-9.2.24-4.el7_8.x86_64
* Elasticsearch version: elasticsearch-5.6.16-1.noarch
* Browser + version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0

### Expected behavior:
* working properly

### Actual behavior:

After upgrade to the latest version using the yum repository, some API URLs stopped working with 404
here is some detected from production.log

* Started GET "/api/v1/tags/add?object=Ticket&o_id=116356&item=abusive+ad&_=1606161457329" 
* Processing by ErrorsController#routing as JSON
* Parameters: {"object"=>"Ticket", "o_id"=>"116356", "item"=>"abusive ad", "_"=>"1606161457329", "a"=>"api/v1/tags/add"}
* No route matches [GET] /api/v1/tags/add (ActionController::RoutingError)

* Started DELETE "/api/v1/ticket_attachment_upload" 
* Processing by ErrorsController#routing as JSON
* Parameters: {"form_id"=>"163030266", "a"=>"api/v1/ticket_attachment_upload"}
* No route matches [DELETE] /api/v1/ticket_attachment_upload (ActionController::RoutingError)

* Started GET "/api/v1/ticket_related/116356?_=1606161457335" 
* Processing by TicketsController#ticket_related as JSON
* Parameters: {"_"=>"1606161457335", "ticket_id"=>"116356"}
* Completed 200 OK in 178ms (Views: 28.9ms | ActiveRecord: 32.4ms)
* Started GET "/api/v1/ticket_merge/116356/97116278?_=1606161457336"
* Processing by ErrorsController#routing as JSON
* Parameters: {"_"=>"1606161457336", "a"=>"api/v1/ticket_merge/116356/97116278"}
* No route matches [GET] /api/v1/ticket_merge/116356/97116278 (ActionController::RoutingError)

while zammad run rake routes result for those three methods:
PUT                         /api/v1/ticket_merge/:slave_ticket_id/:master_ticket_number(.:format) 
POST                        /api/v1/tags/add(.:format) 

### Steps to reproduce the behavior:
* No steps

Please note browser cache is deleted and also tested on other browsers

Thank you in advance

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
