### ISSUE TITLE
Seassion cleaup didnt work

### ISSUE THREAD

**Issue by Anagastes** [zammad/zammad#3301]
Evening boys,

I recently noticed that user sessions are not automatically deleted.

So I built a command based on this example. https://github.com/zammad/zammad/issues/98

It looks like this.

```ruby
zammad run rails r "Scheduler.create_or_update(:name => 'Cleanup expired sessions',:method => 'SessionHelper.cleanup_expired',:period => 60 * 60 * 24,:prio => 2,:active => true,:updated_by_id => 1,:created_by_id => 1,)
```

And in the production.log it appears successfully, but old sessions older than 24h are simply not deleted.

```log
/var/log/zammad/production.log.1:I, [2020-11-25T04:06:06.646459 #91363-47024942741540]  INFO -- : execute SessionHelper.cleanup_expired (try_count 0)...
/var/log/zammad/production.log.1:I, [2020-11-25T04:06:06.650392 #91363-47024942741540]  INFO -- : ended SessionHelper.cleanup_expired took: 0.010968723 seconds.
```

Any ieda why?

### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): package
* Operating system: Debian 9
* Database + version: PostgresQL 9
* Elasticsearch version: 5.6.16
* Browser + version: Firefox 83

### Expected behavior:

Cleanup sessions older than 24h

### Actual behavior:

No session cleanup available

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

Also see: https://docs.zammad.org/en/latest/appendix/privacy.html

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
