### ISSUE TITLE
PostgreSQL installation fails with standard RPM procedure from docs

### ISSUE THREAD

**Issue by TonyBostonTB** [zammad/zammad#3313]
### Infos:

* Used Zammad version: 3.6.0
* Installation method (source, package, ..): package
* Operating system: CentOS7
* Database + version: Postgresql 9.2.24
* Elasticsearch version: 7.10.0
* Browser + version: Safari 14.0.1

### Expected behavior:

* PostgreSQL database is being created 

### Actual behavior:

* Postgres database can't be setup/created

### Steps to reproduce the behavior:

* follow the setup procedure on https://docs.zammad.org/en/latest/install/centos.html

Yes I'm sure this is a bug and no feature request or a general question.

The install log tells what the problem is: 
```
# Creating zammad postgresql user
CREATE ROLE
# Creating zammad postgresql db
createdb: database creation failed: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)
HINT:  Use the same encoding as in the template database, or use template0 as template.
# Grant privileges to new postgresql user
ERROR:  database "zammad" does not exist
# Updating database.yml
rake aborted!
```

The install then finishes but nothing runs because there is no database.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by TonyBostonTB** [comment]
How is this technical? The official documentation for installing Zammad on CentOS7 errors out. This is a bug.

**Comment by MrGeneration** [comment]
I could also tag it "can't repdocue".
I've recently installed centos8 by following the docs, it does work.

Also, IF this is any issue, this is not a bug but a handling issue.
Again, this is a technical question, trust me.
