### ISSUE TITLE
Can't log in, must reset my password each time

### ISSUE THREAD

**Issue by pyrog** [zammad/zammad#3318]
### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): online version zammad.com

### Expected behavior:

* Log in with my email and password

### Actual behavior:

* Display _"Login failed. Have you double-checked your credentials and completed the email verification step?"_
* Must click on _"Forgot password?"_

### Additional information:

* I could log in with a GitHub account

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
I can't find any related error messages in your instance, please contact support via support [at] zammad [dot] com and let us know the time you tried that again.

Please also provide the configuration of your github app.

**Comment by MrGeneration** [comment]
Right now this seems to be more of a technical question.
We're continuing this topic within a ticket.

Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
