### ISSUE TITLE
Fresh install - Setup new system - no password field

### ISSUE THREAD

**Issue by FuxPCN** [zammad/zammad#3325]
I posted this on community forum too:

### Infos:

* Used Zammad version: 3.6
* Used Zammad installation source: source (http://ftp.zammad.com/zammad-latest.tar.gz)
* Operating system: Ubuntu
* DB: MariaDB 10.3
* Browser + version: Firefox + Chromium

### Expected behavior: 

* Ask for Password/Show password field in the form

### Actual behavior: 

* no password field but after clicking submit error message: 

Invalid password, it must contain at least 2 lowercase and 2 uppercase characters!

* no error in production.log

### Steps to reproduce the behavior:

* do a fresh install on ubuntu

![Bildschirmfoto vom 2020-12-04 10-19-31](https://user-images.githubusercontent.com/46864425/101148178-9e235800-361d-11eb-83a6-56d64d66af08.png)
![Bildschirmfoto vom 2020-12-04 10-20-08](https://user-images.githubusercontent.com/46864425/101148165-9b286780-361d-11eb-99b4-625e5df74906.png)

**Comment by MrGeneration** [comment]
Reference to 20 minute old community post is missing:
https://community.zammad.org/t/fresh-install-setup-new-system-no-password-field/5827

It's not nice to make people busy twice.

**Comment by FuxPCN** [comment]
First line of the above post:

I posted this on community forum too:

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
It works on my machine.™

![image](https://user-images.githubusercontent.com/6549061/101149991-f3f8ff80-361f-11eb-9da2-c5fb8deff90c.png)

---

Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
