### ISSUE TITLE
Setting up an email with a different port not possible

### ISSUE THREAD

**Issue by bm1-phillip** [zammad/zammad#3332]
I want to connect a Microsoft365 mailbox. But this is only possible if I specify in the setting.fqdn without a port.

`501 5.5.4 Invalid domain name [AM4PR07CA0001.eurprd07.prod.outlook.com]`

It should be possible to specify a different port separately and not for fqdn. Or it is removed for smtp helo.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by MrGeneration** [comment]
Also a possible duplicate of https://github.com/zammad/zammad/issues/2651
