### ISSUE TITLE
MISSING Mailbox header FROM mail

### ISSUE THREAD

**Issue by vdeville** [zammad/zammad#3349]
### Infos:

* Used Zammad version:3.6.0-20
* Installation method (source, package, ..): Docker
* Operating system: Debian 10
* Database + version: Postgresql from docker-compose file
* Elasticsearch version:from docker-compose file
* Browser + version: Chrome

Hello,
I'v set email setting like FROM parameter using external SMTP, but when i receive mail in my mailbox the FROM is: `
MISSING_MAILBOX@MISSING_DOMAIN`.

How to define mail settings properly ?

Thanks

<img width="834" alt="Capture d’écran 2020-12-27 à 14 44 36" src="https://user-images.githubusercontent.com/6104498/103172230-54abde80-4852-11eb-9b89-caa9aaf9c711.png">

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

--

The reason might also be your mail server.
If you search for above mentioned string you'll see that this is nowhere mentioned in our repo except this issue.
