### ISSUE TITLE
Audio/Video player for ticket attachments

### ISSUE THREAD

**Issue by alireza-salehi** [zammad/zammad#3351]
### Infos:

* Used Zammad version: Any
* Installation method (source, package, ..): Any
* Operating system: Any
* Database + version: Any
* Elasticsearch version: Any
* Browser + version: Any

### Expected behavior:

all users can play audio / video attachments inside browser

### Actual behavior:

users need to download audio/video attachments in order to view theme

### Steps to reproduce the behavior:

Attach an audio/video file to a ticket!

Yes I'm sure any web based solution has such player for audio/video files and it is simple to add this to zammad.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
