### ISSUE TITLE
Running Zammad in Docker without the docker-compose repo

### ISSUE THREAD

**Issue by Teascade** [zammad/zammad#3366]
Hey, I didn't see a discord of any kind where I could ask this, so I resorted to an issue. Is there **any** way to run zammad in production in docker, without using the docker-compose repo? I don't want most of the containers that come with it, for example the postgresql, the nginx or the memcached. I have those services already set-up elsewhere and differently. I just want zammad, in one container, and nothing else.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by gituser** [comment]
@Teascade check documentation - https://docs.zammad.org/en/latest/install/source.html it's all explained there.

Zammad is written in Ruby, so it's just another ruby software, you need to install rvm or rbenv or whatever and configure nginx / postgresql / etc if you don't want to run inside the docker.

Also you can use packages available for Debian / Ubuntu / CentOS / Suse.

**Comment by Teascade** [comment]
I do specifically want to run it on docker though, I just dont want to run postgres on docker.

**Comment by monotek** [comment]
You could use the [zammad container](https://hub.docker.com/layers/zammad/zammad-docker-compose/zammad-3.6.0-33/images/sha256-ce94353476c4dfdd487556d85e55a1fd1dd9dcb71840b79ec85a04b4ee6ce27a?context=repo) from the docker-compose repo but you would need to write your own entrypoint.
