### ISSUE TITLE
"canonical"-tag is missing in knowledge base

### ISSUE THREAD

**Issue by martini** [zammad/zammad#3370]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* For SEO reasons knowledge base should use "canonical"-tag for configured FQDN since knowledge base my be available via different fqdns.

### Actual behavior:

* No "canonical"-tag exists.

### Steps to reproduce the behavior:

* Have a look at e. g. https://support.zammad.com/help/en-us/3-faq/9-how-do-i-start-using-zammad

**Comment by thisconnect** [comment]
I believe we have the same issue, knowledge base in english and german, the link in the language switch from EN->DE points to a URL in english, but it would be great if it would point to the german url.

**Comment by mantas** [comment]
Hi @thisconnect 

This issue is about canonical HTTP header tag. A knowledge base with a custom subdomain can be reached at both custom subdomain and originaldomain.com/help. Thus canonical tag is needed to point search engines to correct primary URL.

Your issue seems different and likely is as-designed. Language switcher has a checkmark next to active language (so, EN when looking at EN content) and allows to pick other language (e.g. DE). If it works differently for you, please open a new issue. If you want to discuss this behaviour, please do so on our community forums https://community.zammad.org
