### ISSUE TITLE
No login possible in latest debian package

### ISSUE THREAD

**Issue by miterion** [zammad/zammad#3376]
### Infos:

* Used Zammad version: 3.6.0-1610965497.9c3d4389.buster
* Installation method (source, package, ..): debian package
* Operating system: Debian Buster
* Database + version: psql (PostgreSQL) 11.9 (Debian 11.9-0+deb10u1)
* Elasticsearch version: 5.6.16
* Browser + version:
  * Firefox 84.0.2
  * Google Chrome 87.0.4280.141

### Expected behavior:

* After being forwarded by the SAML provider the system logs in

### Actual behavior:

* The login site is shown again without any indication that something failed. An error is printed on the browser console:
`App.s(error)                   | route dashboard: No permission for *`
* No error message is printed in the backend logs

### Steps to reproduce the behavior:

* Upgrade to the newest version (from 3.6.0-1610965497.9c3d4389.buster)
* Try to log in

Yes I'm sure this is a bug and no feature request or a general question.

It seems that a similar issue was reported a few years ago (#1273) but seems to have been fixed in a newer version.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
