### ISSUE TITLE
Mails not sending by triggers

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#3383]
### Infos:

* Used Zammad version: 3.6.x (latest build)
* Installation method (source, package, ..): apt
* Operating system: Ubuntu 20.04
* Database + version: postgres
* Elasticsearch version: latest 7
* Browser + version: Microsoft Edge and Firefox

### Expected behavior:
sending mails by triggers
*

### Actual behavior:
mails not sending
*

### Steps to reproduce the behavior:
create a trigger with the option to send a mail. If I choose to write an note, it works. If I define to send a mail, nothing is sent.

I tried the folling simple test-trigger, but no mail is sent. I tested it with sendmail and my own E-Mail Account in the config. It doesnt work.
Other mails from the system (e.g. in my profile > notification) works. I receiver mails, if a new ticket is created for me or something else in my notification options. But I dont receiver mail from trigger. In my test installation the same problem...
*

Yes I'm sure this is a bug and no feature request or a general question.

![image001](https://user-images.githubusercontent.com/1473674/105395906-934d7280-5c1f-11eb-9753-4685ccd64b9d.png)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
