### ISSUE TITLE
Ticket iCal Abonnement with SAML Authentication

### ISSUE THREAD

**Issue by idominiki** [zammad/zammad#3390]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): Source via apt get
* Operating system: 18.04 Linux

### Expected behavior:
* I want to subscribe to my ticket calendar within macOS Calendar App and with the use of SAML Authentication

### Actual behavior:
* I got the error, permission denied

Can anyone help?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
