### ISSUE TITLE
CSRF token verfication failed after migrating from OTRS

### ISSUE THREAD

**Issue by Floaty-Pi** [zammad/zammad#3394]
### Infos:

* Used Zammad version:3.7
* Installation method: source
* Operating system: Ubuntu 20.04
* Database + version: mySQL 15.1

### Expected behavior:

* Log-in to the Zammad App to use after migrating Data from OTRS

### Actual behavior:

* Log-in fails with CSRF token verification failed error 

### Steps to reproduce the behavior:

* Install Zammad from source 
* Set-up system via the web-wizard 
* Start migration from the terminal following the steps on https://docs.zammad.org/en/latest/migration/otrs.html
* (Migration worker stops after 17820 tickets saying "no more work") 
* use Ctrl+C to get back into ruby console 
* Switch off import mode and set `system_init_done` back to `true`
*  Restart Zammad processes 
* Open Zammad in browser (tried with Microsoft Edge) 

Setting up nginx to use SSL has already been tried following this thread: https://community.zammad.org/t/fresh-install-3-2-x-csrf-token-verification-failed/3080/48 but to no avail 

What seems strange about this is that the error only pops up _**after**_ the migration. Before that the log-in has no issues at all and the service works just fine.

Also noteworthy is the fact that our system uses its own PKI, so the certificate we use is an internal one, not an external one, would that cause issues like this? If so, what additional steps need to be done to prevent these errors from happening? It's also weird Zammad isn't reachable over its assigned DNS name, but only via its direct IP, does this relate to this topic?

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by Floaty-Pi** [comment]
Update:
Sorry for the late response but after some trial and error we managed to set up nginx and Zammad in a way that both of them seem to run. However now I'm getting a 403 **Forbidden** error whenever I try to access the web app.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
