### ISSUE TITLE
LDAP Configure button disabled

### ISSUE THREAD

**Issue by agreif** [zammad/zammad#3412]
### Infos:

* Used Zammad version: current stable as of 16.2.2021
* Installation method (source, package, ..): source
* Operating system: centos 7
* Database + version: postgres 12
* Elasticsearch version: not installed
* Browser + version: Firefox 83.0

### Expected behavior:

* Menu Integrations > LDAP: "Configure" button is active and klickable

### Actual behavior:

* "Configure" button is disabled and not klickable

### Steps to reproduce the behavior:

* open Menu Integrations > LDAP

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
