### ISSUE TITLE
specific e-mail did not trigger a ticket creation

### ISSUE THREAD

**Issue by lug-gh** [zammad/zammad#3417]
### Infos:

* Used Zammad version: zammad/unknown 3.6.0-1613047982.332fdca8.xenial amd64 [upgradable from: 3.6.0-1611733683.51a3d218.xenial]
* Installation method (source, package, ..): package
* Operating system: ubuntu 16.04
* Database + version: psql (PostgreSQL) 9.5.24
* Elasticsearch version: 5.6.16
* Browser + version: -

### Expected behavior:

Recieved email will create a ticket

### Actual behavior:

it didn't, but only in one speicific case (as far as i know)

### Steps to reproduce the behavior:

After some searching, I'm pretty sure this is a bug, but I need your help to find the actual information you need.

I use the IMAP connector, every mail that is recieved on that mailbox will create a ticket, this worked fine for over 4000 tickets now. Today I got a call from a customer, who asked if he recieved the mail, because he didn't get any reply.
I checked in zammad, no ticket there. So I checked the mailserver log, maybe the mail got denied, but no, it was accepted.
So I went into the mailbox of the imap account I use for zammad, to check if the mail was declared as spam, but that wasn't also the case, its right there in the inbox between all the other mails, that did trigger a ticket creation.
So I checked production.log.1 (as it was yesterday), but nothing with ERROR or WARN in that timerange, so I searched for the customers e-mail-address, and parts of it. No success either. This is where I am completely lost.
I can't explain myself why this happened, except it's a bug.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
