### ISSUE TITLE
creating ticket article with API return  422 Unprocessable Entity error

### ISSUE THREAD

**Issue by MajidShafaee** [zammad/zammad#3438]
### Infos:

* Used Zammad version: 3.7
* Installation method (source, package, ..): source
* Operating system: ubuntu
* Database + version: 
* Elasticsearch version:
* Browser + version:

### Expected behavior:

Status: 201 Created

### Actual behavior:

Error: 422 Unprocessable Entity

### Steps to reproduce the behavior:

POST /api/v1/ticket_articles by bearer token

{
“ticket_id”: 3,
“subject”: “some subject”,
“body”: “some text”,
“content_type”: “text/plain”,
“type”: “note”,
“internal”: false,
“internal”: false,
“type”: “note”,
“sender”: “Customer”,
“sender_id”:36

}

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
