### ISSUE TITLE
How to install zammad as NONROOT user in private cloud

### ISSUE THREAD

**Issue by ajeetratnu** [zammad/zammad#3439]
### Infos:

* Used Zammad version: 3.6.0.20
* Installation method (source, package, ..): Using Helm Chart
* Operating system: On Company Kubernetes 
* Database + version: Same as in Helm Chart
* Elasticsearch version: Same as in Helm Chart
* Browser + version: NA

### Expected behavior:

* To be able to install zammad and make it up and running.

### Actual behavior:

* Zammad is developed as RootUser which are not allowed in private cloud for security reason.
* I couldn't find any guide for running zammad as NonRootUser.

### Steps to reproduce the behavior:

* I have tried to create new images from the current image and just adding USER 1000 to start as.
* My dockerfile has only two lines:
* FROM <Image name> 
* USER 1000

With this I can deploy but then get into lots of other issues as the user is NOT root user.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
