### ISSUE TITLE
htpp_log table is not create due to  Row size issue when using zammad with external mysql Ver 8.0.23

### ISSUE THREAD

**Issue by abhishek-tyagi87** [zammad/zammad#3443]
### Infos:

* Used Zammad version:  3.3.0
* Installation method (source, package, ..):  helm charts
* Operating system: ubuntu 18.04
* Database + version: mysql external mysql   Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu)
* Elasticsearch version: external elastic search
* Browser + version:

### Expected behavior:
zammad should create http_logs table table 

*

### Actual behavior:

mysql> CREATE TABLE `http_logs` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `direction` varchar(20) NOT NULL, `facility` varchar(100) NOT NULL, `method` varchar(100) NOT NULL, `url` varchar(255) NOT NULL, `status` varchar(20),
    -> `ip` varchar(50), `request` varchar(10000) NOT NULL, `response` varchar(10000) NOT NULL, `updated_by_id` int, `created_by_id` int, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL) ENGINE=InnoDB;
ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

*

### Steps to reproduce the behavior:
1. installed mysql external
2. create zammad image with installed package for mysql  and mysql2 adpator
3. change mysql2 adaptor in database.yaml
4.installed zammad with disable internal postgressql
5.mysql init container failed with below error.

 CREATE TABLE `http_logs` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `direction` varchar(20) NOT NULL, `facility` varchar(100) NOT NULL, `method` varchar(100) NOT NULL, `url` varchar(255) NOT NULL, `status` varchar(20),
    -> `ip` varchar(50), `request` varchar(10000) NOT NULL, `response` varchar(10000) NOT NULL, `updated_by_id` int, `created_by_id` int, `created_at` datetime(3) NOT NULL, `updated_at` datetime(3) NOT NULL) ENGINE=InnoDB;
ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
