### ISSUE TITLE
Change ticket status in Macro is not working.

### ISSUE THREAD

**Issue by FBEZ** [zammad/zammad#3447]
### Infos:

* Used Zammad version: 3.6.x
* Installation method (source, package, ..): hosted by zammand.com
* Operating system: 
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

After creating the macro (e.g. "mark as blocked") in which it's programmed a change of status from new to waiting for, to have the ticket changing the status to "waiting for".
![macrobugged](https://user-images.githubusercontent.com/19321724/110641716-9c37da80-81b2-11eb-83fc-39c0634b5b84.png)

### Actual behavior:

The status remains "new

". On the other hand macros which change the status to close works.

### Steps to reproduce the behavior:

* In the portal create macro with a name and the action status : waiting for
* Go to a ticket and click the macro name
* Nothing happens

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
