### ISSUE TITLE
Add Tags to Knowledgebase

### ISSUE THREAD

**Issue by winnidarks** [zammad/zammad#3474]
It would be helpful to have tags in the knowledgebase to help users to do easier searches..

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by mantas** [comment]
this is also a duplicate of #2612 ;)
