### ISSUE TITLE
501 Syntactically invalid HELO argument(s)

### ISSUE THREAD

**Issue by nicedevil007** [zammad/zammad#3485]
### Infos:

* Used Zammad version: latest docker image as of 31.03.2021
* Installation method (source, package, ..): docker-compose inside docker-swarm
* Operating system: docker
* Database + version: latest docker image as of 31.03.2021
* Elasticsearch version: latest docker image as of 31.03.2021
* Browser + version:  89.0.774.63 (64-Bit) (MS Edge)

### Expected behavior:

* I enter the SMTP Host without username and password and change the SMTP Port to 25 to be able setup zammad on first installation. This SMTP Host is just available in my network and not on WAN.

### Actual behavior:

* error is shown as titel says and I can't continue
![image](https://user-images.githubusercontent.com/17103076/113115513-cbb79100-920c-11eb-8d46-dc925e0cfe52.png)

### Steps to reproduce the behavior:

* install docker-compose images on docker-swarm by just replacing all the env variables with "normal" written ones and set the version up to 3.8

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
The same setting worked **before** updating or didn't you try earlier?

**Comment by nicedevil007** [comment]
This is my realy first attemp to get zammad up an working :)
But thank you for that fast reply!

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

You may want to check the documentation on this regard, as you should be able to find your answer there:
https://docs.zammad.org/en/latest/getting-started/first-steps.html

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
