### ISSUE TITLE
Zammad with external Postgresql DB

### ISSUE THREAD

**Issue by dimuit86** [zammad/zammad#3491]
Hi Guys,

I'm planning to deploy Zammad on Kubernetes with separate postgresql database. Can anyone guide me to how can I customize zammad for external DB?

Is there any option to pass DB connection string as an argument to the helm install? 

Or any other options welcome ☺

Thanks,

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by monotek** [comment]
https://github.com/zammad/zammad-helm/blob/master/zammad/values.yaml#L56
