### ISSUE TITLE
Is there anyway to run Zammad with exsisting postgres database ?

### ISSUE THREAD

**Issue by dimuit86** [zammad/zammad#3496]
### Infos:

* Used Zammad version: 3.6.0
* Installation method (source, package, ..): APT packages
* Operating system: ubuntu
* Database + version: postgresql

### Expected behavior:

* Run Zammad with exsiting postgres DB, without creating a new DB. Connecting to existing DB 
* Can anyone guide me one this...

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
