### ISSUE TITLE
Cannot install Zammad without Elasticsearch getting the Elasticsearch package

### ISSUE THREAD

**Issue by YWatchman** [zammad/zammad#3498]
### Infos:

* Used Zammad version: 4.0.0-1617381062.0fb1b17c.bionic
* Installation method (source, package, ..): Package (apt)
* Operating system: Ubuntu Bionic (18.04)
* Database + version: PostgreSQL
* Elasticsearch version: 7.12.0

### Expected behavior:

* Install Zammad

### Actual behavior:

* Install Zammad and Elasticsearch

### Steps to reproduce the behavior:

* apt install zammad

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
