### ISSUE TITLE
Reporting Error - StatusCode: 500

### ISSUE THREAD

**Issue by ivan0s** [zammad/zammad#3502]
After Upgrading vom 3.6.x to 4.0 i have this error when i try to open the reporting module.

StatusCode: 500

{"error":"Unable to process GET request to elasticsearch URL 'http://localhost:9200/zammad_production_ticket/_doc/_search'. Elasticsearch is not reachable, probably because it's not running or even installed.\n\nResponse:\n#\u003cUserAgent::Result:0x00007f6abc880990 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error=\"#\u003cErrno::ECONNREFUSED: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for \\\"localhost\\\" port 9200)\u003e\"\u003e\n\nPayload:\n{\"query\":{\"bool\":{\"must\":[{\"range\":{\"created_at\":{\"from\":\"2021-03-31T22:00:00Z\",\"to\":\"2021-04-30T21:59:59Z\"}}}],\"must_not\":[{\"term\":{\"state.name.keyword\":\"merged\"}}]}},\"size\":0,\"aggs\":{\"time_buckets\":{\"date_histogram\":{\"field\":\"created_at\",\"interval\":\"day\",\"time_zone\":\"Europe/Berlin\"}}},\"sort\":[{\"updated_at\":{\"order\":\"desc\"}},\"_score\"]}\n\nPayload size: 0M"}

can anybody help me? :) 

thanks in advance

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
