### ISSUE TITLE
Zammad Upgrade failes from 2.9 to 3.6

### ISSUE THREAD

**Issue by alexbippus** [zammad/zammad#3505]
Hello There, 

i am new here in Github and i am searching for help to Upgrade Zammad. 

I am not an expert in coding, only a little bit experienced in installing linux/zammad. 

The main Problem is the Login after a Zammad Upgrade. It shows an "ID Error" for my all my users. 

### Infos:

* Used Zammad version: 2.9.0 -> 3.6.0
* Installation method (source, package, ..): source
* Update Method: package 
* Operating system: ubuntu 18.04
* Database + version: postgresql
* Elasticsearch version: elasticsearch 5.6.16
* Browser + version: Firefox 87.0, Edge 89.0.774.75, Chrome 89.0.4389.114

### Expected behavior:

Updating via source from 2.9.0 to 3.6.0 should be possible.

### Actual behavior:

Upgrade doesn't work due to new dependencies

After Update, Login is not possible 

![grafik](https://user-images.githubusercontent.com/82373074/114381369-54c6b480-9b8b-11eb-98fc-c60985233160.png)

grep "Error ID" /var/log/zammad/production.log

![grafik](https://user-images.githubusercontent.com/82373074/114381646-a3744e80-9b8b-11eb-8a50-fd42d30fefdd.png)

### Steps to reproduce the behavior:

Following the Update Documentation
https://docs.zammad.org/en/latest/install/update.html

I Also tried to install a new Ubuntu 20.04 and backup the Database from Zammad 2.9.0 
https://kifarunix.com/install-zammad-ticketing-system-on-ubuntu/

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
