### ISSUE TITLE
Advanced search for `state` and `state_id` is broken

### ISSUE THREAD

**Issue by mrohnstock** [zammad/zammad#3510]
### Infos:

* Used Zammad version: 4.4.0-20
* Installation method (source, package, ..): docker
* Operating system: archlinux
* Database + version: ? (docker version)
* Elasticsearch version: ? (docker version)
* Browser + version: Vivaldi 3.7.2218.52

### Expected behavior:

(as listed in [user-docs](https://user-docs.zammad.org/en/latest/advanced/search.html) searching for `state:open` do get replaced with `state.name:open` with zammad >= 4.0)

1. search for `state.name:open` should result only in tickets, which do have the state `open`.
2. (old behaviour: search for `state:open` should result only in tickets, which do have the state `open`.)
3. search for `state_id:2` should result only in tickets, which do have the state `open`.

### Actual behavior:

1. no tickets get returned.
2. some tickets with state `new`, `open`, `closed` and `pending reminder` get returned
3. some tickets with state `new`, `open`, `closed` and `pending reminder` get returned

### Steps to reproduce the behavior:

1. search for `state.name:open`
2. search for `state:open`
3. search for `state_id:2`

(same for any other `state` or `state_id`)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

Note: The referenced Zammad version you provided is **no Zammad version**.

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
