### ISSUE TITLE
Not all LDAP Users are visible under Users

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#3518]
### Infos:

* Used Zammad version: 4.0.x
* Installation method (source, package, ..): Package
* Operating system: Debian 10 (Buster)
* Database + version: Postgres 11.11
* Elasticsearch version: 7.7
* Browser + version: Google Chrome V89.0.X

### Expected behavior:

*Synced (and added) LDAP users show up under User Tab, to assign specific users certain roles.

### Actual behavior:

*Users are synced, and can login, however only a handful show up under the Users tab, and even when searching manually for a user, they don't show up, so I can't assign them roles. As shown in the image below, users are synced, as expected. I can't show the user tab, for reasons of privacy.
![zammaderror](https://user-images.githubusercontent.com/56757636/115521827-d43f3c80-a28b-11eb-9d96-9e87e2348ef2.PNG)

### Steps to reproduce the behavior:

*Install Zammad via documentation, sync with LDAP (in my case 6000+ Users).

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by Dennis1993** [comment]
I know this problem. My problem was a double mail address in some accounts. This is not possible.
