### ISSUE TITLE
Zammad doesn't honor REMOTE_USER in API Calls

### ISSUE THREAD

**Issue by JustKiddingCode** [zammad/zammad#3533]
### Infos:

* Used Zammad version: 4.0.1
* Installation method (source, package, ..): Package
* Operating system: Debian 10
* Database + version: Postgres 11
* Elasticsearch version: 
* Browser + version: Curl

### Expected behavior:

* Zammad uses REMOTE_USER set by NGINX

### Actual behavior:

* Zammad uses authorisation

### Steps to reproduce the behavior:

* Set up Zammad with Authorisation by Webserver (e.g. TLS Client Certificate)
* call any /api URL

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
