### ISSUE TITLE
Chat on iOS only shows parts after typing

### ISSUE THREAD

**Issue by cautopartes** [zammad/zammad#3534]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: iOS 14.5 Safari
* Ticket#1086495 

### Expected behavior:

* Send button and conversation should be always visible

### Actual behavior:

* Once the user starts to type some text the viewport changes drastically (Browser zoom in). Big parts of the chat window are missing 
* The user needs to zoom out to see the whole chat window

### Steps to reproduce the behavior:

* See video: 

https://user-images.githubusercontent.com/69846837/116423592-1d216300-a841-11eb-8cdd-26c5124aec46.mp4

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by bolah2009** [comment]
This issue is related to iPhone auto-zoom when an input element is less than 16px, [see here](https://css-tricks.com/16px-or-larger-text-prevents-ios-form-zoom/). When `fontSize` in https://github.com/zammad/zammad/blob/cacfb4b909938fb28e032eff7a919600a9d3b6da/public/assets/chat/views/chat.eco#L1 is set to be less than `16px`, the input element inherits this value and gets overwritten with the external style in  https://github.com/zammad/zammad/blob/cacfb4b909938fb28e032eff7a919600a9d3b6da/public/assets/chat/chat.scss#L20 Thanks to @mrflix for pointing this out.

The proposed solution would be fixing the font size to 16px, even when the font size is customized to be lesser than 16px.
