### ISSUE TITLE
Source - After Upgrade to 4.0 only blank white page appear

### ISSUE THREAD

**Issue by Itay-Sharoni-zz** [zammad/zammad#3537]
### Infos:

* Used Zammad version: 4.0
* Installation method (source, package, ..): Source
* Operating system: Debian 9
* Database + version: Mysql8
* Elasticsearch version: 7.12
* Browser + version: any

### Expected behavior:

when upgrading from 3.6.0 to 4.0 I had multiple issues

1. the latest GZ file have different structure, when extracting, all new files goes to  /opt/zammad/zammad-latest instead of /opt/zammad

so upgrade process do not see any new files and finish in one second, and version remain 3.6.0

I had to copy /opt/zammad/zammad-latest content to /opt/zammad/ and run upgrade process again, this time I could see it upgrading

2. after upgrade process is complete + Elasticsearch re-index when all services are running, any page show up as white blank (any page, even login page)

from browser console I see many errors:

![image](https://user-images.githubusercontent.com/65607183/116803713-d07ca700-ab22-11eb-9dff-046088e5106d.png)

after trying troubleshooting this for many hours, I had to rollback to 3.6.0

### Actual behavior:

1. after extract
running:
gem install bundler
bundle install --without test development postgres (I use mySQL)
rake db:migrate
rake assets:precompile

this should finish the upgrade process, but instead it remains in 3.6.0

2. after upgrade is finished (using copy /opt/zammad/zammad-latest content to /opt/zammad/)
we only see blank page and app not loading

### Steps to reproduce the behavior:
upgrade from 3.6.0 to 4.0 using source + mySQL + elasticsearch

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
