### ISSUE TITLE
Reporting not displaying open/closed tickets

### ISSUE THREAD

**Issue by 0x4c6565** [zammad/zammad#3540]
### Infos:

* Used Zammad version: **4.0.0-20**
* Installation method (source, package, ..): Docker
* Operating system: CentOS 7
* Database + version: **zammad/zammad-docker-compose:zammad-postgresql-4.0.0-20**
* Elasticsearch version: **zammad/zammad-docker-compose:zammad-elasticsearch-4.0.0-20**
* Browser + version: Firefox 89.0b7

### Expected behavior:

* When attempting to view the reporting section, open/closed ticket counts should show

### Actual behavior:

* When attempting to view the reporting section, open/closed ticket counts are no longer showing since upgrading to `v4.0.0`:

![image](https://user-images.githubusercontent.com/7476213/116986284-8122ac00-acc5-11eb-88d5-b4e2f015a7bd.png)

We upgraded this on the evening of 21/04/2021, which you can see in the drop on the graph

### Steps to reproduce the behavior:

* View reporting
* Observe no open/closed ticket counts since upgrade

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
