### ISSUE TITLE
REST event streaming API functionality 

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#355]
Zammad wish of Peter Eckel:

"For the REST API, a sensible functionality would be an option to subscribe to the event stream (ticket creation, update, status change etc.) along the lines of the integration that is present in the Icinga 2 API:

http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/icinga2-api#icinga2-api-event-streams

That feature would greatly facilitate the development of integration tools, i.e. monitoring tools or other ticket management software like JIRA."

**Comment by hanneshal** [comment]
Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
[Board](https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals)


regards
Johannes
