### ISSUE TITLE
CTI: Mapping between user(object) and call log faulty/unclear

### ISSUE THREAD

**Issue by Megachip** [zammad/zammad#3560]
### Infos:

* Used Zammad version: 3.5.0-3 & 4.0.0
* Installation method (source, package, ..): package
* Operating system: 
   3.5.0: Univention Memberserver 4.4-7
   4.0.0: CentOS Linux release 7.7.1908 (Core)
* Database + version:
   3.5.0: postgres (PostgreSQL) 9.6.17
   4.0.0: postgres 9.2.24
* Elasticsearch version:
   3.5.0: Version: 7.9.1, Build: default/docker/083627f112ba94dffc1232e8b42b73492789ef91/2020-09-01T21:22:21.964974Z, JVM: 14.0.1
   4.0.0: Version: 6.8.15, Build: default/rpm/c9a8c60/2021-03-18T06:33:32.588487Z, JVM: 1.8.0_232
* Browser + version: Safari Version 14.1 (16611.1.21.161.6)

### Expected behavior:

* See Agent and Customer in Call log, if Matching

### Actual behavior:

* 4.0.0 See a bunch of maybe users and the user reported by the CTI
![image](https://user-images.githubusercontent.com/487352/118263859-1f2d2800-b4b7-11eb-8414-cdefaad4fa48.png)

* 3.5.0 See new customers and CTI users
![image](https://user-images.githubusercontent.com/487352/118264366-e0e43880-b4b7-11eb-8c07-409f1049b4d6.png)
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/487352/118265084-fd34a500-b4b8-11eb-9bd6-af9ebe430ca5.png">
 

### Steps to reproduce the behavior:

4.0.0
* Added exact matching phone number to ONE customer.

3.5.0
* Added additional attribute to user object with type phone 
<img width="176" alt="image" src="https://user-images.githubusercontent.com/487352/118264753-797ab880-b4b8-11eb-92b3-419400183cb0.png">

* getting non exact number from ldap
![image](https://user-images.githubusercontent.com/487352/118264923-bfd01780-b4b8-11eb-8a0b-fadf304d17c0.png)
In that case I wouln't expect a matching, but for sure, a regex/phonetic matching would be cool ;) 

* Adding new users directly trough call log
![image](https://user-images.githubusercontent.com/487352/118265265-2b19e980-b4b9-11eb-9c32-1650a990e7c5.png)
![image](https://user-images.githubusercontent.com/487352/118265355-5a305b00-b4b9-11eb-8d9d-d7c64de50d4c.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
