### ISSUE TITLE
Created Ticket state equivalent to closed the customer can update

### ISSUE THREAD

**Issue by sinichi19** [zammad/zammad#3564]
* Used Zammad version: tested using 3.6 and 4.0
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04
* Database + version: any
* Elasticsearch version: any
* Browser + version: latest , google chrome

### Expected behavior:

* When created new ticket state equivalent to closed the customer cant update the ticket 

### Actual behavior:

* The new ticket state equivalent to closed can update by the customer and changed to open.

### Steps to reproduce the behavior:

*1. check if the Group Settings- Follow-up Possible is configured (do not reopen Ticket but create new Ticket)
*2.Create new ticket state using the official documentation

Ticket::State.create_or_update(
     name: 'New Closed',
     state_type: Ticket::StateType.find_by(name: 'closed'),
     created_by_id: 1,
     updated_by_id: 1,
   )

--and--

attribute = ObjectManager::Attribute.get(
     object: 'Ticket',
     name: 'state_id',
   )
attribute.data_option[:filter] = Ticket::State.by_category(:viewable).pluck(:id)
attribute.screens[:create_middle]['ticket.agent'][:filter] = Ticket::State.by_category(:viewable_agent_new).pluck(:id)
attribute.screens[:create_middle]['ticket.customer'][:filter] = Ticket::State.by_category(:viewable_customer_new).pluck(:id)
attribute.screens[:edit]['ticket.agent'][:filter] = Ticket::State.by_category(:viewable_agent_edit).pluck(:id)
attribute.screens[:edit]['ticket.customer'][:filter] = Ticket::State.by_category(:viewable_customer_edit).pluck(:id)
attribute.save!

*3. Customer - created new ticket
*4.When Agent reply and update the ticket to new created ticket state equivalent to closed the customer still can update the ticket and reply

Thank You and More Power

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by sinichi19** [comment]
Thank you sir @MrGeneration  and my apologies if i posted here, and I already posted on zammad community.

I thought my concern is enhancement or a bug because on my understanding the created new ticket state equivalent to closed is same the behavior of default closed state.

thank you
