### ISSUE TITLE
LDAP user gets "Corrupted"

### ISSUE THREAD

**Issue by KleepX** [zammad/zammad#3566]
### Infos:

* Used Zammad version: 4.0.x
* Installation method (source, package, ..): package
* Operating system: CentOS 7
* Database + version:  postgresql 9.2.24
* Elasticsearch version: 7.12.0

### Expected behavior:

Login with the LDAP user like normally.

### Actual behavior:

After the first login of the user, the user gets somehow changed to something like: "6f0b2fb6d31cac5[...]"
and it isnt possible to login anymore until we delete him and ReSync the LDAP directory.

That problem exists for 6 User.
The weird thing is: Only 2 of those user are still in the company, the rest is either a User for a certain Program or already gone.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
