### ISSUE TITLE
WhatsApp

### ISSUE THREAD

**Issue by martini** [zammad/zammad#357]
Zammad wish of Marc Nilius

WhatsApp integration as Zammad channel like Twitter or Facebook

**Comment by wagnst** [comment]
I would love to see Telegram integration. Should also be much easier to implement, as its oss.

**Comment by thorsteneckel** [comment]
Hi @wagnst - thanks for your proposal. Could you please create a separate issue for this so we can discuss it there? Btw. I like it 👍

**Comment by wagnst** [comment]
Hi @thorsteneckel, done thanks #362!

**Comment by singular-error** [comment]
Telegram, Threema, What'sUp and Telephone contacts - they all have in common that they don't need a email-adress. So, what about a user-identification via one of some unique ids instead of email-adress? And of course, one user can have more ids / channels - but maybe no email.? I'd like to see this as a key feature.

**Comment by vincentfuhler** [comment]
Whatsapp is very important to us

**Comment by Johannes-GitHub** [comment]
Are there any news already?

**Comment by thorsteneckel** [comment]
It's still prohibited by Whatsapp/Facebook to use their API in any other way than their own product(s). There are implementations out there but if they are used Whatsapp might suspend the user (you) and start a legal case against the provider (us?). So until there are no changes in their policy there won't be a solution/implementation for Whatsapp without risking too much. We'll keep all subscribers updated here in case of any changes. We are interested in an integration too but can't do anything about it. 😞

**Comment by Wouter0100** [comment]
With the introduction of WhatsApp Business and their API, this could be a real thing - and would be VERY awesome. 

See https://www.whatsapp.com/business/api and https://developers.facebook.com/docs/whatsapp

Long story short: you'll have to run a Docker container which connects to WhatsApp servers and provides an API to get data from and to WhatsApp. Because the way WhatsApp is designed, something needs to be running to receive the messages - which is the Docker container.

Implementing the API in Zammad would be a real feature and a plus to implement WhatsApp without the risks of being blocked.

**Comment by petervanbeugen** [comment]
I agree very much with Wouter. Having the WA functionality available in the short term would be fantastic.
I am willing to co-sponsor this !

**Comment by java-guy** [comment]
Is there any news on the WhatsApp integration? 
We are interested in switching to zammad but WA is a must for us.

**Comment by thorsteneckel** [comment]
Hi @java-guy - cool to hear your interest in Zammad. Unfortunately the WhatsApp integration requires [an external docker service to run](https://developers.facebook.com/docs/whatsapp/guides/installation) which is quite complicated for parts of our user base. We're evaluating ways how to streamline the process. However, our current focus is on the Knowledge Base. Be sure that we will post updates here as soon as we start working on the issue.

**Comment by jozephbrasil** [comment]
Nowadays WhatsApp is really very important for any business. Some countries uses WhatsApp for almost everything. +1 for this integration.

**Comment by MrGeneration** [comment]
I'm locking the conversation for now as `+1` just causes noise on this Repository.
If you want to discuss this, please see: https://community.zammad.org/t/whatsapp-business-api/1078

**Comment by Mirtaaa** [comment]
Closed in favor of https://github.com/zammad/zammad/issues/5010
