### ISSUE TITLE
How to add a channel to start a ticket ?

### ISSUE THREAD

**Issue by hugodeco** [zammad/zammad#3576]
I developed a plugin to WhatsApp via "QuePasa" and its working very well. But, i had clone the Telegram system to do so,
How can i start a ticket or chat by this new plugin ?

There is an example code ?
How do i add this to new ticket view ?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
