### ISSUE TITLE
Multiligual content / dynamic content

### ISSUE THREAD

**Issue by martini** [zammad/zammad#358]
Suggestion for user to support multiligual content / dynamic content like https://support.zendesk.com/hc/en-us/articles/203663356-Providing-multiple-language-support-with-dynamic-content-Professional-and-Enterprise-

**Comment by rolfschmidt** [comment]
- Agents should be able to set language for new customers.
- There should be a new admin interface to configure ip ranges / domains to detect the language of the customer.
- Send notifications based on the language setting of the customer.

**Comment by klausbehnke** [comment]
I like also to see the option to assign a language directly in the invitation dialog to make sure, that the invitation email will use the selected language (and the customer have already the proper language saved in the profile.

There should be also an option to assign a language to an organization, which is used for new customers register via the same domain.

**Comment by MartinBorg** [comment]
Language selection based on IP ranges is wrong. RFC3282 is right :~) It defines an "Accept-Language:" header for email (MIME parts) and web pages.

OK, even some big web players do not accept the "Accept-Language" header. That's why one always get wrong languages from them when working abroad.

Many countries are multi-lingual anyway, so IP based language detection is not even useful when not travelling.

It would be nice, if Zammad would use the Accept-Language: header from both incoming email and from web browser.

**Comment by Mirtaaa** [comment]
Due to inactivity, currently not important. Therefore we will close this topic for now.
