### ISSUE TITLE
copy and paste bullet list entry - format error

### ISSUE THREAD

**Issue by chrklo** [zammad/zammad#3587]
### Infos:

* Used Zammad version: 4.0.0-1622547078.51bf33da
* Installation method (source, package, ..): package
* Operating system: CentOS Linux release 8.3.2011
* Database + version: postgresql-10.15-1
* Elasticsearch version: 6.8.16
* Browser + version: Google Chrome 91.0.4472.77

### Expected behavior:

* like in older zamad versions I expect that I can copy and paste bullet list entries

### Actual behavior:

* on paste a bullet list entry you get a double bullet list entry
* after shift + ctrl + l the second bullet is removes and it looks ok
* after saving the ticket entry an empty bullet list entry is inserted

### Steps to reproduce the behavior:

* generate a bullet list in a ticket with shift + ctrl + l
* copy on line with ctrl + c
* enter
* paste with ctrl + v
* remove double bullet with shift + ctrl + l
* save ticket entry

see attached screenshots
![step_1](https://user-images.githubusercontent.com/28293610/120469111-3ec2bc80-c3a2-11eb-9b29-624558de72a1.jpg)
![step_2](https://user-images.githubusercontent.com/28293610/120469124-42eeda00-c3a2-11eb-831d-76f1afb005ec.jpg)
![step_3](https://user-images.githubusercontent.com/28293610/120469126-43877080-c3a2-11eb-9d8d-fe5d6bf8e2cd.jpg)
![step_4](https://user-images.githubusercontent.com/28293610/120469128-44200700-c3a2-11eb-8b62-3c7af89f1cc9.jpg)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
sub bullets are not supported currently which is why this is not a bug. 
Sorry.

**Comment by chrklo** [comment]
the sub bullet is the problem here.

in old zammad versions copy and paste didnt make a sub bullet - just a new line

**Comment by MrGeneration** [comment]
You're copying HTML formatted code and are wondering why Zammad accepts it?
Paste the content unformatted and you're good to go.

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
