### ISSUE TITLE
LDAP-Sync broken after Renaming an Active-Directory User

### ISSUE THREAD

**Issue by jimsche2000** [zammad/zammad#3607]
### Infos:

* Used Zammad version: 4.0
* Installation method package
* Operating system: Linux Ubuntu 18.04.5 LTS
* Database + version: ?
* Elasticsearch version: ?
* Browser + version: newest Google Chrome

### Expected behavior:
After Renaming a User in Active Directory the next LDAP-Sync from Zammad renames the user in its database.
We use this functionality when a employee gets married or similar -> when someones name changed.

### Actual behavior:
After renaming a User in Microsofts Active Directory the next LDAP-Sync disables the old user and creates a new one. From now on every LDAP-Sync changes the user name of the new user with a random 2-3 digit number behind. This is spamming opur activity stream! To work around this i need to delete the new user, reactivate the old user, and delete the old user too.

That wouldn't be a big Problem - but their tickets get deleted too. And this need to be fixed!

![image](https://user-images.githubusercontent.com/12158411/121643600-49600e80-ca92-11eb-91bc-9263ef2970d1.png)
![image](https://user-images.githubusercontent.com/12158411/121643624-4fee8600-ca92-11eb-91bd-f577b721859e.png)

### Steps to reproduce the behavior:
Search for an Active-Directory-User which is already synced to Zammad (via LDAP-Sync).
Rename it in the Active Directory(all name-attributes including the username!)
Rename its exchange mail-adress (if thats important - i don’t know)
Run the ldap-sync some times.

![image](https://user-images.githubusercontent.com/12158411/121643674-60066580-ca92-11eb-9a03-979cea9dfa33.png)
![image](https://user-images.githubusercontent.com/12158411/121643688-64cb1980-ca92-11eb-91c1-483e8ab98436.png)

Thanks for any help - i've searched at github, zammad community-page and google, but can't find any similar problems.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

---


This is a local environment issue and not caused by Zammad. 
![issue3607](https://user-images.githubusercontent.com/6549061/121677658-76beb380-cab6-11eb-8503-bac655c80d07.gif)
