### ISSUE TITLE
Updating zammad db tables but nothing changes on GUI data.

### ISSUE THREAD

**Issue by donweasel** [zammad/zammad#3608]
Hello, im working on a multi app integration using direct databases connection and when updating tables on the zammad db, nothing changes on the GUI.  Thanks

* Used Zammad version:  Zammad version 4.1.x
* Installation method: package
* Operating system: CentOs7
* Database + version: (PostgreSQL) 9.2.24
* Elasticsearch version: no installed
* Browser + version: Chrome Latest

### Expected behavior:
while running querys directly against the zammad db on PostgreSQL and see the changes done in the db displayed on the GUI

### Actual behavior:

when updating any tables the GUI remain with the old data BUT if i update on the GUI it writes on the DB

### Steps to reproduce the behavior:

i tried different methods:
1. OBDC driver and add the zammad server as a MSSQL linked server
2. using pgAdmin4 
3.  on server direct queries 

on each one execute update statements then confirm data with a select statemen while nothing changes on the GUI

**Comment by mantas** [comment]
Hi @donweasel 

Writing directly to database does not clear cache :) It works as intended.

**Comment by donweasel** [comment]
Hi @mantas 
Cache from where ? the browser? already tried that, different PCs, different browsers, incognito windows  and still the same

**Comment by Dennis1993** [comment]
Cache from zammad

**Comment by donweasel** [comment]
@Dennis

> Cache from zammad

please be more specific.

**Comment by donweasel** [comment]
how do i clear zammad cache?

**Comment by Dennis1993** [comment]
I think you need to clear the cache by the following:

root@zammad:~# zammad run rails c
Loading production environment (Rails 5.1.7)
irb(main):001:0> Rails.cache.clear

**Comment by donweasel** [comment]
> I think you need to clear the cache by the following:
> 
> root@zammad:~# zammad run rails c
> Loading production environment (Rails 5.1.7)
> irb(main):001:0> Rails.cache.clear

That worked perfectly fine ! Thank you !

**Comment by dennis** [comment]
> @dennis
> 
> > Cache from zammad
> 
> please be more specific.

I could say the same, when it comes to usernames :) That is, unless you wanted to involve me.  (this is more fyi, it happens often)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
