### ISSUE TITLE
Elastics Search doesn't start.

### ISSUE THREAD

**Issue by Dirk23** [zammad/zammad#3613]
Hi,

I always keep Zammad up to date, but I didn't realize that elastic search doesn't also update it self. So now I have Zammad in lates Version 4.0.x but elasticsearch was on 5.6.16. I then updated elastic search to 7.13.2 but elasticsearch wont start. In the log file I can see:
```[2021-06-15T09:55:46,879][ERROR][o.e.b.Bootstrap          ] [zammad] Exception
java.lang.IllegalStateException: The index [zammad_zammad_production_ticket/q7t32r3wTC-P5-NJSh0giA] was created with version [5.6.16] but the minimum compatible version is [6.0.0-beta1]. It should be re-indexed in Elasticsearch 6.x before upgrading to 7.13.2.
```

How can I do that, so that elastic search will start again?

Thanks in advance!

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
