### ISSUE TITLE
Open tickets via link within the browser session

### ISSUE THREAD

**Issue by darklightmoon** [zammad/zammad#3620]
### Infos:

* Used Zammad version: 3.6
* Installation method (source, package, ..): package
* Operating system: Windows 10
* Database + version:
* Elasticsearch version: 
* Browser + version: Firefox

### Expected behavior:

* Open ticket via link (shift ctrl 3x . ) or URL Link in actual session 

### Actual behavior:

* New tab and session created
* old session paused with message box: 

![grafik](https://user-images.githubusercontent.com/59093874/122227286-0bf6e900-ceb7-11eb-8ed9-74794b906165.png)

### Steps to reproduce the behavior:

* click on ticketlink for example

 
![grafik](https://user-images.githubusercontent.com/59093874/122227199-f8e41900-ceb6-11eb-8207-5e17e42ec491.png)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
