### ISSUE TITLE
Error instalation

### ISSUE THREAD

**Issue by joaoguariglia** [zammad/zammad#3646]
Good afternoon, the product can be good and beautiful, but I tried in every way to install and I couldn't, both from debian and from the docker follow the errors:

Docker
![image](https://user-images.githubusercontent.com/23190903/124358940-87c49580-dc1a-11eb-849a-97f2c1205721.png)

Debian
![image](https://user-images.githubusercontent.com/23190903/124358903-59df5100-dc1a-11eb-8974-f38eb033ef12.png)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
