### ISSUE TITLE
Responding to forwarded mails after changing customer, still sends me e-mail 

### ISSUE THREAD

**Issue by blu-IT** [zammad/zammad#3649]
### Infos:

* Used Zammad version: 4.0.0
* Installation method: docker-compse
* Operating system: Ubuntu 18.04 LTS
* Database + version: Postgres
* Elasticsearch version: unknown 
* Browser + version: Firefox 89.02

### Expected behavior:

* When responding to mails / tickets that have been forwarded into the system **and changed/updated customer** after that zammad recognized the mail, answers **should go to the (changed) customer.**

### Actual behavior:

* When responding to an e-mail, the one who forwarded the e-mail into the system gets the answer - even the customer has been changed for that ticket.

### Steps to reproduce the behavior:

* Write an e-mail or forward an existing one to an mail-account that is fetched by zammad.
* Change the customer for that e-mail to the right one in zammad.
* Respond to the e-mail of that customer.
* Check your e-mailbox and hobe you did not receieve that response ;-)

Yes I'm sure this is a bug and no feature request or a general question.

Maybe this behavior is also affected to this issue here? https://github.com/zammad/zammad/issues/3554

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
