### ISSUE TITLE
Maximum number of connections from user+IP exceeded (mail_max_userip_connections=3)

### ISSUE THREAD

**Issue by PDK2020** [zammad/zammad#3651]
### Infos:

* Used Zammad version: 4.1.x
* Installation method (source, package, ..): docker-compose versión
* Operating system: Centos 8
* Database + version: Postgre
* Elasticsearch version: Disabled
* Browser + version: Firefox 89.0.2

### Expected behavior:
I'm trying to add a new SMTP relay on an Email, where the user and host is the same that other email souces.
*

### Actual behavior:
I'm getting this error:
Maximum number of connections from user+IP exceeded (mail_max_userip_connections=3)
*

### Steps to reproduce the behavior:
Add multiple email accounts with the same SMTP relays as the outgoing channel.
*

### Question:
Where do I configure the environment variable mail_max_userip_connections?
*

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
