### ISSUE TITLE
Waiting Time Today Dashboard Statistic Do Not Update

### ISSUE THREAD

**Issue by johnalanyoung** [zammad/zammad#3655]
### Infos:

* Used Zammad version: Zammad version 4.0.x
* Installation method (source, package, ..): Package
* Operating system: CentOS Linux 7
* Database + version: postgres (PostgreSQL) 9.2.24
* Elasticsearch version: elasticsearch-7.12.1
* Browser + version: Google Chrome. Version 91.0.4472.124 (Official Build) (64-bit)

### Expected behavior:

* On the Dashboard under "WAITING TIME TODAY"; "My handling time" and "Average" statistics to display the relevant amount of time tickets are waiting for a customer update.

### Actual behavior:

* On the Dashboard under "WAITING TIME TODAY"; "My handling time" and "Average" statistics display "0 minutes" no matter what happens with all tickets.

### Steps to reproduce the behavior:

* Deploy Zammad via package install, create tickets and interact with them in any manner. No matter what I do this Dashboard statistic do not change when all the other statistics do work as intended.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
