### ISSUE TITLE
Zammad on Oracle Linux 8 fails to install

### ISSUE THREAD

**Issue by sbrosl** [zammad/zammad#3657]
Oracle Linux 8 is one of the main successors and (almost) drop-in replacement to CentOS 8 and follows a similar release philosophy as CentOS 6-8 and is similarly downstream from RHEL.

In our experience, it has indeed been a drop-in replacement but this does not seem to be the case with the Zammad package as it expects the _epel-release_ package to be called _epel-release_, where as it was renamed _oracle-epel-release-el8_ in Oracle Linux 8. Because of this, Zammad package installation fails with a "nothing provides epel-release needed by zammad-4.1.0-1626163404.5c90a5d0.centos8.x86_64" message.

Would it be able to fix support for Oracle Linux 8 soon?
Possible solutions: could be by allowing the oracle-epel-release-el8 as an alternative to the epel-release package, or by trusting the user to install epel-release and just having the dependencies on the packages it provides instead of the repository itself?

Thanks

### Infos:

* Used Zammad version: 4.1.0 (latest at time of this issue)
* Installation method (source, package, ..): package
* Operating system: Oracle Linux 8
* Database + version: PostgreSQL 13
* Elasticsearch version: 7.13 (latest at time of this issue)
* Browser + version: not pertinent

### Expected behavior:

* Be able to install Zammad on Oracle Linux 8 as per on CentOS 8 and RHEL 8 as Oracle Linux 8 provides the same libraries and platform as CentOS 8.

### Actual behavior:

* Zammad fails to install as the epel-release repository on Oracle Linux is named oracle-epel-release-el8
* Error message: "nothing provides epel-release needed by zammad-4.1.0-1626163404.5c90a5d0.centos8.x86_64"

### Steps to reproduce the behavior:

* Install Oracle Linux 8, follow Zammad install steps for CentOS 8

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

---

The distribution you're trying to use is not supported, neither by us nor by our packager.

**Comment by sbrosl** [comment]
Ok sorry, felt like a bug in the package to me, I will head over there instead :)
Thanks!
