### ISSUE TITLE
Get list of all users in Zammad using Rest API

### ISSUE THREAD

**Issue by nastacio-roggen** [zammad/zammad#3659]
### Infos:

* Used Zammad version:
* Installation method (source, package, ..):
* Operating system:
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

When I run **curl --insecure -u "username":"password" https://zammad.mydomain.net/api/v1/users** in the command prompt, I expect to get the data for every user in the Zammad system.

### Actual behavior:

I am only getting the first 500 users in the Zammad system when I know I have more than that in there.

### Steps to reproduce the behavior:

Install curl on windows command prompt.
run **curl --insecure -u "username":"password" https://zammad.mydomain.net/api/v1/users**
parse the output into a csv file.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
