### ISSUE TITLE
New Email Account button not present

### ISSUE THREAD

**Issue by darjichirag235** [zammad/zammad#3675]
### Infos:

* Used Zammad version: 4.1.x
* Installation method (source, package, ..): package
* Operating system: Centos-7
* Database + version: PSQL-10
* Elasticsearch version: 7.9.0
* Browser + version: Chrome

### Expected behavior:

*
Actuly after add outbound command via "Rails Console" (Channel.create(area: 'Email::Account', options: { outbound: { adapter: 'sendmail' } }, active: true, preferences: { editable: false }, updated_by_id: 1, created_by_id: 1) "

In email channel section "New" email account creation button is remove from the Email channel account section.
Currantly not present "New" button in email section.

### Actual behavior:

*
![Email-account](https://user-images.githubusercontent.com/87975989/126973762-5060a574-8543-49e3-bd29-dfd36440e3a6.JPG)

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This also has been posted in the community 28 minutes ago. 
Please don't make people twice as busy with not providing these crucial base information.

https://community.zammad.org/t/email-account-showing-blank/7339

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

---


Incomplete command.

**Comment by darjichirag235** [comment]
ok
