### ISSUE TITLE
No incomming Mails after Update

### ISSUE THREAD

**Issue by funsports** [zammad/zammad#3692]
### Infos:

* Used Zammad version: 4.1.x - [4.1.0-1628189510.ad8bc927.focal amd64 [aktualisierbar von: 4.1.0-1623058318.8522a752.focal]]
* Installation method (source, package, ..):
* Operating system: Ubuntu 20.04.2 LTS
* Database + version: psql
* Elasticsearch version: 7.13.1

### Expected behavior:

*  Zammad accepts mails as usual

### Actual behavior:

* Zammad has been running with us for more than a year without any problems.
Now we have the problem who we are updating [4.1.0-1628189510.ad8bc927.focal amd64 [upgradeable from: 4.1.0-1623058318.8522a752.focal]
Incoming mails are no longer accepted by Zammad.
Mail is configured as follows:
https://admin-docs.zammad.org/de/latest/channels/email/advanced/sendmail.html
we run an exim that accepts the emails and forwards them to Zammad.
In the Exim Log, the mail is properly accepted and forwarded to Zammad.

After rollback a Snapshot, Zammad work. 
I checked Zammad-Changelogs, but i cant found anything in this way....

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

Thanks in advanced

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
