### ISSUE TITLE
Can't log in after FreshDesk Import

### ISSUE THREAD

**Issue by jeremyrnelson** [zammad/zammad#3699]
### Infos:

* Used Zammad version: 4.1.0-1628847507.5a492dca.focal
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04
* Database + version: Postgresql 12.8
* Elasticsearch version: n/a
* Browser + version: n/a

### Expected behavior:

I would expect some sort of default username and password for logging in after the initial import, or an admin account setup screen before the import starts, maybe?

### Actual behavior:

FreshDesk import completes, you come to a login screen, and you can't log in, nor can you use "forgot your password?" because I can't log in to set up email.

### Steps to reproduce the behavior:

Do any FreshDesk import and then try to log in.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Admin-Mail + Token.

---



Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by jeremyrnelson** [comment]
There's no way to set up the admin email in the first place...

**Comment by MrGeneration** [comment]
> Admin-Mail + Token.

This is as far as I can help. 
This is a technical question - sorry.

**Comment by thorsteneckel** [comment]
> Admin-Mail + Token.

I think what @MrGeneration wanted to say is that we don't have much information about the Freshdesk internal permissions available at import time. [That's why we use the User for the given API key as the Admin of the imported Zammad system.](https://github.com/zammad/zammad/blob/0402c755dea1fb2d276d798134671ef236caeb7d/lib/sequencer/unit/import/freshdesk/agent/mapping.rb#L64-L72)

In non source code terms: After the import ist completed you should be able to login with the email address of the API key user as a login and the API key itself as the password. Hope that helps. If not, please create a thread over at the [community board](http://community.zammad.org/) and refer to me.

**Comment by jeremyrnelson** [comment]
Yes, that makes perfect sense, and I spun up a new VM to confirm that info
was there on the migrate screen.  Since the import took 3 days, I totally
forgot about that.  I'd still like to advocate for the ability to use/set
up/play with the system while the import is happening, but that's an
entirely separate issue.

Please close this out.


Jeremy Nelson, President

Pinnacle Technology Solutions

260-205-8900

***@***.***
