### ISSUE TITLE
Saml login url ?

### ISSUE THREAD

**Issue by NiTRoeSE** [zammad/zammad#3700]
Hi,

we want to use a direct link to zammad so that users not landing on login page and must press the "SAML Button" to be authenticated instead we want to use a link (SAML) wich automatically logs in the user.

Unfortunately i can't find such link. 
Is there any way to do this ?

Thanks for help!

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
