### ISSUE TITLE
Rest API Ticket-Creation Error

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad#3708]
Hi! 

Maybe something is wrong!

Best Regards,
David

### Infos:

* Used Zammad version: 4.1.x
* Installation method (source, package, ..): package
* Operating system: Debian
* Database + version: postgresql 13
* Elasticsearch version: 7.14.0
* Browser + version: chrome 92

### Expected behavior:

* When i send the request to  /api/v1/tickets a ticket should be created.

### Actual behavior:

* Error 422 -> Group can't be blank

### Steps to reproduce the behavior:

* Sending following data does not work:

`{"id":null,"group":"EDV\/Alab\/Allgemein","priority_id":null,"state_id":1,"organization_id":null,"number":null,"customer":"egger.david@jacoby-gm.at","created_at":null,"updated_at":null,"updated_by_id":null,"created_by_id":null,"title":"ttest","article":{"id":null,"subject":"ttest","body":"test","from":"egger.david@jacoby-gm.at","to":null,"cc":null,"content_type":"text\/html","internal":false,"created_by_id":null,"updated_by_id":null,"created_at":null,"updated_at":null,"type_id":null,"sender":null,"type":null,"form_id":"630417273","attachments":null},"followups":null,"created_by":null}
`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
