### ISSUE TITLE
How to edit Zammad default english text for chat

### ISSUE THREAD

**Issue by zakdandachi** [zammad/zammad#3714]
Hello, 
I apologize for being newbie to this website and in general. I am trying to change the default text of zammad web chat widget. I have tried to edit chat.js and changed the text from there which I guess was not a good idea but still did not update the text.
I did reboot, rake rebuild, etc.. 

Been searching the web and documentation for hours nothing about that.. only how to translate to other languages

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
