### ISSUE TITLE
365 integration: Channel::Driver::Imap: #<Net::IMAP::ResponseParseError: unexpected token EOF

### ISSUE THREAD

**Issue by Silverstar224** [zammad/zammad#3723]
Hello,
having followed the instructions on the zammad website for Microsoft 365 I encountered following problem, displayed in the zammad 365 mask:
Can't use Channel::Driver::Imap: #<Net::IMAP::ResponseParseError: unexpected token EOF (expected CRLF)> 
ThecConfiguration in Azure and Zammad worked fine, until the afore-mentioned message.

I am using Ubuntu 20.04 and a native installation of zammad with a PostgreSQL DB. The Version shows as 4.1.x, and I am using the current version from https://dl.packager.io/srv/deb/zammad/zammad/stable/ubuntu 20.04/main amd64 Packages.
The production.log is attached

Thank you.

[production.log](https://github.com/zammad/zammad/files/7105489/production.log)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
