### ISSUE TITLE
Status of reminder tickets not refreshed in overview

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#3724]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): Your own demo
* Operating system: your own demo
* Database + version: your own demo
* Elasticsearch version: your own demo
* Browser + version: Microsoft Edge 93.X

### Expected behavior:
When the time comes, the circle should turn yellow again without having to refresh the page or switch to another overview.
*

### Actual behavior:
If you set a ticket to wait as a reminder, the black circle does not automatically turn yellow again when the time is reached. (see gif file)
*

### Steps to reproduce the behavior:
![Animation](https://user-images.githubusercontent.com/1473674/132095974-1d4c1a7a-31d0-4ce3-92cb-2d7126812d9e.gif)

*

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by Dennis1993** [comment]
Why is that not a bug?
The other way is working, the yellow dot switch to black after set a reminder?
I don‘t understand that, can you explain that, please? 😊

**Comment by MrGeneration** [comment]
That's because of how overviews are refreshed. 
Please head over to the community if you require a in depth answer.
