### ISSUE TITLE
Delete Old Microsoft 365 Account 

### ISSUE THREAD

**Issue by christian-wr** [zammad/zammad#3728]
### Infos:

* Used Zammad version: 4.1.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04
* Database + version: 
* Elasticsearch version: 
* Browser + version: Chrome (93.0.4577.63) or Firefox (91.0.2 (64-Bit))

### Actual behavior:
I cannot delete the old Microsoft 365 accounts, the following message appears:
Ich kann die alten Microsoft 365 Accounts nicht löschen, es erschein die folgende Meldung:

*
![image](https://user-images.githubusercontent.com/90287914/132415955-f01bdf87-b521-4c45-98e0-8fdbcef6e861.png)
![image](https://user-images.githubusercontent.com/90287914/132416008-78b8f8d8-8f8a-462c-a487-cdaab54d30b5.png)

Not a big problem, but ... 
Nicht das riesen Problem aber ... 

### Steps to reproduce the behavior:

*
Click Delete/Löschen 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

---

Update to latest possible stable.
