### ISSUE TITLE
Customers can create "closed" tickets (?!)

### ISSUE THREAD

**Issue by benrubson** [zammad/zammad#3735]
Hi,

### Infos:

* Used Zammad version: 4.1.0-1631024881.3edca5e9.buster amd64
* Installation method (source, package, ..): package
* Operating system: Debian 10
* Database + version: mariadb-server 10.3.29-0+deb10u1 amd64
* Elasticsearch version: 7.14.1 amd64
* Browser + version: Safari, Firefox (lastest versions)

### Expected behavior:

* Customers can create tickets through web channel only as "new" state.

### Actual behavior:

* Customers can create tickets through web channel as "closed", which does not seem to really make sense
(or I miss the use case).

![Screenshot 2021-09-10 at 17 43 42](https://user-images.githubusercontent.com/6764151/132880743-7a9f003f-73ae-49d4-bb58-7921e10de824.png)

### Steps to reproduce the behavior:

* Connect to the web channel as a "Customer", create a ticket, select "closed" state.

Many thanks 👍

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by benrubson** [comment]
Thank you for your feedback @MrGeneration.
I thought this was a bug, as it seems that "closed" ticket state should have been hidden for customers (or their tickets sent as "closed" would simply be lost).
Could we then think about re-opening this please ?
Thank you again 👍

**Comment by MrGeneration** [comment]
No this is a configuration / technical question.
This is not a bug but a feature.

**Comment by benrubson** [comment]
Found it, thank you again 👍 
https://github.com/zammad/zammad-documentation/pull/105
