### ISSUE TITLE
Closed tickets wrong report

### ISSUE THREAD

**Issue by paymanzafar1** [zammad/zammad#3745]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): package
* Operating system: CentOs
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* Reopened ticket should not be listed in the Closed tickets list in reporting section.

### Actual behavior:

* Reopened ticket is listed in closed tickets list in reporting section.
* It is not listed in the Overviews, but in the reporting section.
* The "Closed At" field of the ticket is set.

### Steps to reproduce the behavior:

* Create a ticket
* Close it
* Open it again
* In the reporting section, click -all- profile, and the "Closed" button. 
* You will see the ticket listed but its state is Open

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by paymanzafar1** [comment]
Hi,

I don’t know why you think this was a technical question.

It is a clear bug. I wrote the required steps to create this issue.

When you close a ticket, and then reopen it, it will be listed a closed ticket in the Reporting section.

Best regard,
Payman Moghadam

**Comment by MrGeneration** [comment]
Stop discussing with me please, this works as designed.
If you don't understand why, please kindly head over to the community and ask why there.
