### ISSUE TITLE
FQDN not replaced in ngnix config 

### ISSUE THREAD

**Issue by szg-mw** [zammad/zammad#3753]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): yum
* Operating system: CentOS Linux release 7.9.2009 (Core)
* Database + version: -
* Elasticsearch version: -
* Browser + version: -

### Expected behavior:

Changing the "Fully Qualified Domain Name" under Settings -> "System" should replace the FQDN in all config files.

### Actual behavior:

Changing the "Fully Qualified Domain Name" under Settings -> "System" does not change the hostname in the ngnix-config file (/etc/ngnix/conf.d/zammad.conf) so doing a http-call to your old FQDN will redirect you to the old FQDN with https.

server {
        listen 80;
        server_name oldfqdn.domain.com
        return 301 https://oldfqdn.domain.com$request_uri;

### Steps to reproduce the behavior:

Change the FQDN of Zammand via GUI, do a http-call to the old fqdn.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by szg-mw** [comment]
Hi,

does not look like a technical question to me. I´ve already fixed the issue for me so I don´t need any further assistance.

Would just let you know about the "issue". If it works as designed you can close the the issue.

**Comment by MrGeneration** [comment]
Everyone gotta discuss today huh - ask again on the community please.
