### ISSUE TITLE
Use API to find open or new tickets - doesn't find the right tickets for me

### ISSUE THREAD

**Issue by idominiki** [zammad/zammad#3764]
### Infos:

* Used Zammad version: 4.1.x
* Installation method (source, package, ..): apt Installation
* Operating system: Ubuntu 18.04.6 LTS
* Database + version: PostgreSQL 10.18
* Elasticsearch version: 7.14.2

### Expected behavior:

* When using API to retrieve tickets, it would give me tickets list in JSON format with all open or new tickets

### Actual behavior:

* It shows only three tickets, which are closed

With ..../search?query=state_id%3A1%20OR%20state_id%3A2 I get this output: "tickets":[61,60,12],"tickets_count":3 ....}

In the web I see this: 
<img width="274" alt="image" src="https://user-images.githubusercontent.com/62521486/134350696-402b8dc1-f798-440d-9bb3-463570c5cef6.png">

If I search for the mentioned tickets above, the ticket status is 4 = closed:
{"id":60,"group_id":1,"priority_id":2,"state_id":4, .... }

If I search an open ticket like 88 then I get the right output: {"id":88,"group_id":1,"priority_id":2,"state_id":2," .... }

### Steps to reproduce the behavior:

* see "Actual behavior" section.

Yes I'm sure this is a bug and no feature request or a general question.

Would be great If someone can help me here!

Greets from Germany
Dominik

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
