### ISSUE TITLE
Triggers excluding 2 emails

### ISSUE THREAD

**Issue by dbschema-pro** [zammad/zammad#3767]
Hello,

On Zammad 3.6, I want to create a trigger that excludes two emails. I couldn't do this. After adding the first email contains not, it is no more allowed to add another record with similar content.
I need to add two emails to be excluded from the trigger.

![image](https://user-images.githubusercontent.com/60284259/134646172-3bb2406e-23e3-4688-a6b7-314172a6e603.png)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
