### ISSUE TITLE
Autoresponder on Mailsize doesnt set Auto-Submitted-Header

### ISSUE THREAD

**Issue by b90g** [zammad/zammad#3770]
### Infos:

* Used Zammad version: 4.1.0
* Installation method (source, package, ..): package
* Operating system: debian bullseye
* Database + version: package recommendet
* Elasticsearch version: latest
* Browser + version: any

### Expected behavior:

* Emails which are rejected for having to many MB  dont seem to Set the Header `Auto-Submitted` which leads to zammad rejecting mailinglists mails on the mailinglist...

### Actual behavior:

* Header is set and mailinglist-Server recognizes to not send it via mailinglist

### Steps to reproduce the behavior:

* Sent a Mail which is to large and check header for `Auto-Submitted`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
That's a feature not a bug.

Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
