### ISSUE TITLE
Force users to reload after system migration

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#3776]
### Infos:

* Used Zammad version: 5.0
* Installation method (source, package, ..): all
* Operating system: all
* Database + version: all
* Elasticsearch version: all
* Browser + version: all
* Ticket#1093505

### Expected behavior:

* Online users should get a reload in browser after updating of the system.

### Actual behavior:

* Users who are never shutting down their systems will never get the updated UI and have temporarily problems.

### Steps to reproduce the behavior:

* Open browser with zammad
* Update zammad from 4.1 to 5.0
* Session will be still available and user is still running old javascript code

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Theoretically this should happen automatically already due to Zammad restarting.
However, in rare race conditions (I had myself as well), the UI may loose the websocket connection and also fail trying to reconnect proper. In this situation the agent bareely notice any negative side effects.

This even allows temporary use of a second tab of the same Zammad session because the connection broke that bad.

**Comment by rolfschmidt** [comment]
We should have at least a reload to make sure the new javascript is running.

**Comment by MrGeneration** [comment]
> We should have at least a reload to make sure the new javascript is running.

Usually Zammad does exactly that after loosing the connection to the application server.
This happens during restarting the application server as well (which is caused by updates)

**Comment by rolfschmidt** [comment]
hmm I'm not deep enough into the topic. The customer said he had his system in standby mode overnight which could be a forcing point here...

**Comment by MrGeneration** [comment]
Yes and standby is exactly what **can** cause above mentioned connection check to go berserk and die.

**Comment by rolfschmidt** [comment]
If i remember correctly we didnt want to exchange versions between frontend and backend because of security reasons. But maybe we could give the websocket server a random ID on startup and if the client already have one and it is different then it reloads the browser. So it would restart on every restart of the websocket server which should not happen to often right? 

After standby it would try to reconnect and see that the ID is different and reload.

**Comment by MrGeneration** [comment]
The problem is the app loosing the websocket connection which would break your fix attempt. My opinion though.
The Ajax fallback also doesn't kick in.

**Comment by rolfschmidt** [comment]
> 
> 
> The problem is the app loosing the websocket connection which would break your fix attempt. My opinion though.

Ah i did not check for the reconnect ... But there is code which is retrying the connect of the websocket server? Are you really sure? Ajax fallback should kick in at least. Yeah it is maybe too theoritical here, we need to reproduce it and see forward then. But standby could be a good way to reproduce it i guess.

**Comment by MrGeneration** [comment]
That's Martin E.'s and my theory, yes.
This happens fairly rarely and actually is hard to reproduce. I failed at it which is why we had to ignore it up to now.

**Comment by martini** [comment]
Proposal:

```
AppVersion.set(true, 'app_version')
```

The same as we did earlier https://github.com/zammad/zammad/blob/develop/db/migrate/20170214000001_reload_online_browser_after_cors_csrf_changes.rb

If a websocket connection is reconnected the websocket connection is checking if `app_version` is still the same, if not a reload is forced.

Note: There are variants where there is no websocket reconnect (e. g. as Marcel mentioned), but unfortunately I could not find out how to reproduce this.

**Comment by MrGeneration** [comment]
~~We should never communicate application versions to unauthenticated users or customers.~~
~~This is a potentially security issue.~~

~~Especially because we have WAY TOO MANY users having so lax update rules that they're running several security versions behind. Please don't expose those users even more than they do them selfes already.~~

Turns out I absolutely misunderstood the way this works.
This technically allows me to find out when the last configuration change (e.g. for objects) has taken place. 
So in theory I could find out how old an instance *might* be and thus I could have less stress testing.

Any way, we never provide the app version to the user but an timestamp instead.
