### ISSUE TITLE
Broken logo

### ISSUE THREAD

**Issue by mzch** [zammad/zammad#3778]
### Infos:

* Used Zammad version: commit a57b65aee3a409622ab2bcdbe668335e3f0c0208
* Installation method (source, package, ..): source
* Operating system: Debian 11.0
* Database + version: PostgreSQL 13.4
* Elasticsearch version: 7.155
* Browser + version: Chrome 

### Expected behavior:

* Show zammad logo

### Actual behavior:

* Broken. See below:
![ScreenShot](https://user-images.githubusercontent.com/621178/135260398-84bde1eb-b0b6-4fba-bfd2-35ef2885a1c4.png)

Yes, `/assets/images/0fe8d5213617493a8a9e9857adacac52.png` doesn't exist.

### Steps to reproduce the behavior:

* Access login page.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mantas** [comment]
@mzch does the logo show up when you go to Settings -> Branding ?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by MrGeneration** [comment]
I'm betting that this has been a migration.

**Comment by mzch** [comment]
Oh, sorry. This is my fault. Thanks!
