### ISSUE TITLE
Possibility to use tags for scheduler actions

### ISSUE THREAD

**Issue by ntinti** [zammad/zammad#378]
Hi

I want to delete all "Spam" tickets. But it is not possible to take this tag ore another tag as a condition for a ticket.

**Comment by MrGeneration** [comment]
Sorry for not getting back to you in this topic.

This already has been implemented and works (Just tested it to make sure)
I'll take Milestone 2.5 because I know that it was inside there for sure. :)

![image](https://user-images.githubusercontent.com/6549061/44040059-cd7204b8-9f1a-11e8-9fb1-f66e43124d5f.png)

Closing now. :)
