### ISSUE TITLE
Zammad with port other than 80 or 443 (FQDN)

### ISSUE THREAD

**Issue by bm1-phillip** [zammad/zammad#3785]
Hello,

we have Zammad running on another port something like zammad.domain.org:12345

When I enter the Port as FQDN, I can't send mails because my mail provider can't handle the port. Apart from that the port has not lost with the FQDN.

If I leave out the port, then the URLs, which are e.g. in Mail, are not correct.

How do I do that correctly or is that simply not possible?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
