### ISSUE TITLE
Till label not assigned to corresponding input fields in calendar edit view

### ISSUE THREAD

**Issue by saz** [zammad/zammad#3793]
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): source
* Operating system: Ubuntu 18.04
* Database + version: Postgresql 9.6
* Elasticsearch version: 7.15.0
* Browser + version: Google Chrome 92.0.4515.131

### Expected behavior:

* Clicking on a `Till` label in the calendar edit view activates the corresponding input field

### Actual behavior:

* Clicking on a `Till` label in the calendar edit view activates the `Monday` input field in all cases
![image](https://user-images.githubusercontent.com/402629/136366373-1453e9a5-7eb0-49c0-838b-12d03dc8034c.png)

### Steps to reproduce the behavior:

* Clicking on a `Till` label

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Can't reproduce, seems to be a local issue.
Please ensure you've run all required steps during the upgrade / installation as per documentation.

If that doesn't help and still persists, please consult the community: https://community.zammad.org

**Comment by regiohelden-dev** [comment]
Weird... Because it's *in* the code:
https://github.com/zammad/zammad/blob/73cb552846d66162471f1591b3763f07696f84c4/app/assets/javascripts/app/views/generic/business_hours.jst.eco#L23

**Comment by saz** [comment]
@MrGeneration Mind reopening this bug report?

**Comment by MrGeneration** [comment]
I agree on the label being invalid (since 2015):
![image](https://user-images.githubusercontent.com/6549061/136383383-c85a71b5-11e6-4310-a306-1b5e9872ac5f.png)


However, I cannot reprodce Chrome v94 using mondays till on all other values - neither on updating nor on creating:
![image](https://user-images.githubusercontent.com/6549061/136383472-1010f247-631f-4e95-a54b-e028eed45376.png)
![image](https://user-images.githubusercontent.com/6549061/136383491-88f47ecb-dd3f-422d-b091-90529bcd5a81.png)
![image](https://user-images.githubusercontent.com/6549061/136384232-448231a7-7895-4022-921d-75d7e888cfa2.png)


I'm also not seeing mentioned console errors:
![image](https://user-images.githubusercontent.com/6549061/136383590-4d772688-584a-41af-938c-f9eebd87c1b6.png)


The last two parts are the reason why the issue has been flagged with `can't reproduce`.
Please ensure that this is not a browser addon feature striking into the UI.

I did verify this on:
- (clean) hosted environment
- (clean) package installation

I also did ensure Cache of Zammad being cleared and even went through the trouble to recompile the assets.
I also double tab above comments on Firefox v92.

So as for the functionality described I can't reproduce this and thus currently have to expect local issues (combinations of things). However, do agree on the label needing a proper fix which -under the hood- probably will fix your "local" issue as well.

**Comment by saz** [comment]
Interestingly enough, I'm not getting this message in the console, but the HTML is still wrong.
If you're clicking on any of the words `TILL` the time input field below this word will be focused?

**Comment by MrGeneration** [comment]
You're right, when clicking on `till` the wrong field is highlighted. So that's definitely an issue.
