### ISSUE TITLE
No possible to update ticket status. Core Workflows page doesn't work

### ISSUE THREAD

**Issue by cantwintt** [zammad/zammad#3804]
### Infos:

* Used Zammad version: 5.0/develop
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

1)Ticket status changing 
2)Core Workflows chaning

### Actual behavior:

1)There is no possible to close,change status and etc of ticket. Inside the ticket and with group opperations
2) Core workflows page doesn't, "loading" and nothing more 

### Steps to reproduce the behavior:

Go to Tickets and try to change status or just try to close ticket
Go To Settings-System-Core Workflows
![Z1](https://user-images.githubusercontent.com/92361537/136916530-6d5935c7-a26d-47b4-82e1-fd22b313570b.JPG)
![Z2](https://user-images.githubusercontent.com/92361537/136916535-def7dae0-3ebf-4e0b-b315-a66a125f5fa1.JPG)
[Z3.zip](https://github.com/zammad/zammad/files/7328093/Z3.zip)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Please provide your logfiles traceback of the moment this is failing.
Also share the core workflow configuration if applicable.

**Comment by cantwintt** [comment]
[z_log.txt](https://github.com/zammad/zammad/files/7328273/z_log.txt)
Log attached
Better use Notepad++
Workflow page doesn't work correctly, so i can't show you workflow

**Comment by MrGeneration** [comment]
```
E, [2021-10-12T11:25:58.780147 #591-188620] ERROR -- : PG::UndefinedTable: ОШИБКА:  отношение "core_workflows" не существует
LINE 8:  WHERE a.attrelid = '"core_workflows"'::regclass
                            ^
 (ActiveRecord::StatementInvalid)

```


----


Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
