### ISSUE TITLE
found organizations do not expand on ticket creation

### ISSUE THREAD

**Issue by kgoldinger** [zammad/zammad#3812]
### Infos:

* Used Zammad version: 5.0.1
* Installation method (source, package, ..): RPM Package
* Operating system: RockyLinux 8.4
* Database + version: Postgresql 10.4
* Elasticsearch version: 7.15.1
* Browser + version: Edge 94.0.992.50 / Firefox 91.0.1

### Expected behavior:

* On the user selection/ search while creating a Ticket, a click on found organizations should expand all users of this organization

### Actual behavior:

* a click on some organizations does nothing at all.
Until now, I wasn't able to find a reason why some orgas are affected while others aren't, in a first place I've thought that the size/ usercount of the organization matters, but that doesn't seem to be the relevant factor.

### Steps to reproduce the behavior:

* create a new ticket
* search for a customer (organization)
* klick on the organization to expand the related users

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by MrGeneration** [comment]
Duplicate of #3815
