### ISSUE TITLE
Condition with is set or is not set doesn't work with CoreWorkflow

### ISSUE THREAD

**Issue by cscicarus** [zammad/zammad#3813]
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..):
* Operating system: Ubuntu
* Database + version:
* Elasticsearch version:
* Browser + version: Chrome

### Expected behavior:
I have one Object "Repo"sitory with a list of different Repositories, one marked as standard.
I have a second Object "GitNo" where I can place an issue no.
(In combination of Repo and GitNo I'm generating a link to a related Git-issue)
These Object information are optional on a ticket.

With CoreWorkflows I would like to blank the GitNo Object if the Repo is "-" so not set.

So there should be following working option:

a)
Early workflow: GitNo "ausblenden"
Late workflow: If Repo "is set" "einblenden"
b)
Workflow: If Repo "is not set" "ausblenden"
c)
Early workflow: GitNo "ausblenden"
Late workflow: If Repo "is" <selection of the possible choices for Repo> "einblenden"
d)
Workflow: If Repo "is not" <selection of the possible choices for Repo> "ausblenden"
...

### Actual behavior:

I did try the behavior in the "new Ticket" dialog.
Non of the approaches does work. The GitNo is either blanked or displayed but never depeding on the selection in Repo

### Steps to reproduce the behavior:

Sorry.
See Expected behavior

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by cscicarus** [comment]
it is a bug and no technical question

**Comment by MrGeneration** [comment]
I'm not here to discuss. Apart from your really bad description, it is a technical question.
Kindly RTFM: https://admin-docs.zammad.org/en/latest/system/core-workflows/how-do-they-work.html#action

I didn't put weeks of work into it so you can tell us about bugs which are clear technical questions just because you either didn't read or didn't try the correct options.
