### ISSUE TITLE
Periodical error “Channel: Email::Notification out Can’t use Channel::Driver::Sendmail: #<Errno::EPIPE: Broken pipe>“.

### ISSUE THREAD

**Issue by bo0ts** [zammad/zammad#3833]
### Infos:

* Docker Image: `zammad/zammad-docker-compose:zammad-5.0.2-1`
* Installation method: Helm Chart zammad-helm 6.0.1
* OKD 4.7

We have an outbound email notification setup with sendmail. This works fine, but periodically the error `Channel: Email::Notification out Can’t use Channel::Driver::Sendmail: #<Errno::EPIPE: Broken pipe>` is reported in the monitoring endpoint.

Simply reconfiguring the notification (clicking `Edit` and `Continue`) fixes the problem.

### Expected behavior:

* This error should not happen.

### Actual behavior:

* The error happens from time to time.

### Steps to reproduce the behavior:

* Unfortunately we cannot reproduce this behaviour on demand.

Yes, I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by bo0ts** [comment]
@MrGeneration I'm not sure. I've had another look at our instance and the `Manage > Channels > Email` screen lists three outbound email notifications configured for `sendmail` which we did never add and which we cannot remove through the UI. That seems like a bug to me.

I've attached a screenshot to show the issue.

![image](https://user-images.githubusercontent.com/76102/141755712-3c290ea8-15b4-41ec-977c-ec72d3f31c98.png)

**Comment by bo0ts** [comment]
@MrGeneration Another indicator that this is indeed a bug: After deleting the notifications via the rails console and recreating them with another configuration, three boxes appear again.

**Comment by MrGeneration** [comment]
Again, this is not a bug.
It's a technical question, please consult the community or, if you need commercial grade support consider getting a support contract.

As for "several notification channels" this is a administration issue and not a bug.
