### ISSUE TITLE
Problems after migration from OTRS 6 CE to Zammad

### ISSUE THREAD

**Issue by tthomasb** [zammad/zammad#3838]
Hello all, 

I have done a migration from OTRS 6 CE to Zammad (current version). After the migration, where the "First Steps" should come, a login screen now appears, although I have not yet created an organization. For test purposes, I tried to log in with my OTRS account, which did not work either. Any suggestions for solutions or experience with this problem? 

Have a nice rest of the weekend and best regards

Thomas

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
