### ISSUE TITLE
No signature on new ticket if email is default message type

### ISSUE THREAD

**Issue by maxstoyanov** [zammad/zammad#3844]
### Infos:

* Used Zammad version: 5.0.2-1636525426.86ded716.focal
* Installation method (source, package, ..): package
* Operating system: Ubuntu
* Database + version: postgresql 12+214ubuntu0.1 
* Elasticsearch version: 7.15.1
* Browser + version: Chrome 95.0.4638.69

### Expected behavior:

* Create new ticket with the green plus button.
* Default signature should be visible

### Actual behavior:

* No signature visible.
* Workaround: Switch to phone inbound (or outbound) and back to email

### Steps to reproduce the behavior:

* Set signature in group
* Set email as default new ticket type
* Create new ticket

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Works on my machine™

![issue3844](https://user-images.githubusercontent.com/6549061/141115665-24d8278b-a320-45c2-9396-7855bd936ddf.gif)


Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by maxstoyanov** [comment]
In your screencast I see that you have several groups. On my installation we only have the default group "Users".

Please have a look at this video.

https://user-images.githubusercontent.com/1681823/141325333-f052325c-4a61-4bbf-85fd-e949c6992bd8.mov

**Comment by MrGeneration** [comment]
A crucial information are important. :-)

**Comment by rolfschmidt** [comment]
regression of https://github.com/zammad/zammad/commit/52aa34bb2068c7c3850a04ab3e3ea91ac491ae68
