### ISSUE TITLE
Wrong DateTime in Ticket Calendars

### ISSUE THREAD

**Issue by Klaservice** [zammad/zammad#3854]
I'm facing a problem with the calendar event generation from the tickets.

It seems that the generated DTSTART and DTEND Variables reports the right day but the wrong time of the event.

i would also ask: where this two variables are taken from the created Ticket?

BEGIN:VCALENDAR
VERSION:2.0
PRODID:icalendar-ruby
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP:20211116T122330Z
UID:1dd012fe-2230-4868-8b10-ce21417ddbc2
DTSTART;TZID=Europe/Rome:20211116T000000
DTEND;TZID=Europe/Rome:20211116T000000
CLASS:PRIVATE
DESCRIPTION:T#27028
SUMMARY:aperto ticket: 'test'
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20211116T122330Z
UID:77587080-2e8a-4794-85eb-2ae8af6c5e4a
DTSTART;TZID=Europe/Rome:20211116T000000
DTEND;TZID=Europe/Rome:20211116T000000
CLASS:PRIVATE
DESCRIPTION:T#27035
SUMMARY:aperto ticket: 'test'
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20211116T122330Z
UID:009deaf1-a510-45c7-9612-ea2339edcd5f
DTSTART;TZID=Europe/Rome:20211116T000000
DTEND;TZID=Europe/Rome:20211116T000000
CLASS:PRIVATE
DESCRIPTION:T#27032
SUMMARY:aperto ticket: 'Configurazione NExtcloud su Zadara'
END:VEVENT
END:VCALENDAR

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
