### ISSUE TITLE
how to chat channel

### ISSUE THREAD

**Issue by kushalsharma2** [zammad/zammad#3856]
### Infos:

* Used Zammad version:
* Installation method (source, package, ..):
* Operating system:
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

*

### Actual behavior:

*

### Steps to reproduce the behavior:

*

Yes I'm sure this is a bug and no feature request or a general question.

Hii
I wanted to know how to use chat feature of zammad

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
