### ISSUE TITLE
client detection, avoiding spam

### ISSUE THREAD

**Issue by dna-i** [zammad/zammad#3858]
Hi,
Is there an update on this subject? 
https://github.com/zammad/zammad/issues/1207 
It's an old thread, but not sure if it's been closed or discontinued not having a solution
We are lately experiencing a quite annoying problem related to the client detection and spam. Did anyone implement a solution like the recaptcha or the hidden functionality? What would be the best solution did you find?

d

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
