### ISSUE TITLE
System send actors unpleased email when there is a new ticket

### ISSUE THREAD

**Issue by vhmsec** [zammad/zammad#3874]
Actual behavior:
The System send actors an email when there is a new ticket. This is not pleased.
The text look like:

"Hallo X,
es wurde ein neues Ticket (Test) von "Y" erstellt.
Gruppe: Vertrieb
Besitzer: -
Status: neu"

How can I fix that?
Thank you for your help

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
