### ISSUE TITLE
2 question - new project and add new status

### ISSUE THREAD

**Issue by camrader** [zammad/zammad#3882]
well, nihao all people
i have a question
may be a qustion is from dummy, but

 #questions:

1.how i can create a another one project in my instance zammad ? 
that's, i have a two sectors of support - technikal supports and CRM support. And i need is separated all tasks from user and delegate to my agent beside tech support and CRM.
HOW ?

2. to add a new status in field - only in consol ?

thanks and sorry for my english

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by camrader** [comment]
oh, sorry
thanks
