### ISSUE TITLE
Follow-up detection does not work for the body of plain text mails

### ISSUE THREAD

**Issue by bastian-299** [zammad/zammad#3894]
### Infos:

* Used Zammad version: 5.0.1
* Installation method (source, package, ..): source
* Operating system: Ubuntu
* Database + version: mysql 8.0.27
* Elasticsearch version: 7.16.1
* Browser + version: firefox 91.3.0esr 

Follow-Up detection settings: Body, References

### Expected behavior:
All mails with <system hook><ticket number> in the body text of an email should be attached to corresponding ticket.

### Actual behavior:
Only RTF or HTML mails are detected by follow-up detection. Plain text mails are not merged, instead of merging a new ticket is created

### Steps to reproduce the behavior:
Enable Follow-Up detection to "Body"
Send a plain-text mail to the Zammad system with an existing <system hook><ticket number> in the body of the mail. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Reference detection in bodies do neither work for HTML nor plain text.

**Comment by fliebe92** [comment]
Hey @MrGeneration,

do you have an example for us which we can use for reproducing the reported behavior?

In a local Zammad development system, it works fine with a plain text mail and a HTML mail.

Thanks for your support!

**Comment by MrGeneration** [comment]
I had to go through verification stuff again because 6 months is a too long time for my brain.
During this I had to discover that the follow up for plain text mails *does* work in only one specific situation:

You have to use the exact ticket slug `Ticket#12345`. That's unexpected - on earlier Zammad versions you could also just use a ticket number. This lead to false positives (sometimes) due to matching phone numbers. It doesn't seem to matter if it's the increment of date number style.

This is also why the documentation is hinting to that
![image](https://user-images.githubusercontent.com/6549061/171645080-18c0bedd-ed91-49c7-a8ae-d562a40f734a.png)

I can't reproduce the original issue any more. If I provide the one correct format though.

**Comment by fliebe92** [comment]
Thanks for your answer! Do we then have some kind of a mismatch between documentation and the follow-up detection? Do you have any suggestion what we should do here?

**Comment by MrGeneration** [comment]
> Do we then have some kind of a mismatch between documentation and the follow-up detection?

As I said. To me this behavior is unexpected.
It wouldn't be the first time that devs change behavior and forget to tell the documentation guy.

In my opinion the first check should be if something changed to determine if it's a documentation issue, a bug or whatever.

**Comment by bastian-299** [comment]
I can still reproduce the behavior with Zammad 5.1.1.
But in our environment the Ticket Hook is not something like "XXX#", but "XXX-".
So maybe the body-follow-up detection expects Ticket# and ignores the configured ticket hook?

**Comment by fliebe92** [comment]
Thanks @bastian-299 for your feedback, after some more tests, we were able to reproduce the issue.

@MrGeneration, we checked the used regular expression for finding ticket numbers in the body of the mail. The ticket hook was always present, even in prior versions. Feel free to get in touch with us to discuss this in more detail. :)
