### ISSUE TITLE
a new request that has no owner, the ticket header is deleted

### ISSUE THREAD

**Issue by tncrclk** [zammad/zammad#3896]
When I update the ticket after assigning a user to a new request that has no owner, the ticket header is deleted. The ticket title looks like a "-" sign. how can it be fixed?

version 5.0.x

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
