### ISSUE TITLE
Chosen role setup disappeared

### ISSUE THREAD

**Issue by darc-ev** [zammad/zammad#3898]
### Infos:

* Used Zammad version: 4.1.1
* Installation method (source, package, ..): Rpm Repository
* Operating system: CentOS 7
* Database + version: 9.2.24
* Elasticsearch version: 7.16.1
* Browser + version: Microsoft Edge 96.0.1054.43 & Mozilla Firefox 91.3.0esr

### Expected behavior:

* Chosen role will be saved permanently in agent setup

### Actual behavior:

* After some time, the chosen role is unchosen in the agent view

### Steps to reproduce the behavior:

* We created a new role, picked up some agents, checked the checkbox (new role) and saved the setup. The agents are able to work with the tickets (depending the new role). Even after Logoff in Re-Login. After some time, the role setup is gone. The checkbox is unchecked.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
