### ISSUE TITLE
GitLab third-party login leads to unprocessed template strings on 422 error

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#3912]
### Infos:

* Browser + version: Firefox latest

### Expected behavior:

* properly processed template

### Actual behavior:

![422 Unprocessable Entity_20220109011220](https://user-images.githubusercontent.com/59403389/148665345-fb139da1-be29-4b3d-8c95-7b256a7dd564.png)

### Steps to reproduce the behavior:

* try to logging-in with gitlab on https://help.revolt.chat/#login

- [x]  Yes I'm sure this is a bug and no feature request or a general question.

**Comment by ice9exe** [comment]
we also have the same problem but there is still no solution. it works very well in localhost I do not understand why is not working.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by MrGeneration** [comment]
Apologies, no technical question.
However I'm locking this issue to contributors to silence "me too" comments that don't help any one.

**Comment by dominikklein** [comment]
@dym-sh Maybe you are able to provide some production log information so that we can check this for related error messages?

**Comment by ghost** [comment]
(im not the one running zammad instance, but i was the first one to file this issue, after interaction with revolt team on github)

i'll tag people from @revoltchat, maybe someone of them may help with production log:
@fatalerrorcoded, @infi, @insertish, @janderedev, @Rexogamer, @TaiAurori, @wait-what, @Zomatree

**Comment by Rexogamer** [comment]
Thanks for letting us know 😅 - Insert should be able to provide logs at some point, although from what I can tell they're fairly busy at the moment so it might be a bit before they're available

**Comment by dominikklein** [comment]
Thanks for the input :-) Maybe one additional question, on which environment is Zammad running?

**Comment by t-shehab** [comment]
No feedback received. Closing for now.
