### ISSUE TITLE
Debian 11 dropped libapache2-mod-auth-kerb package (required for SSO)

### ISSUE THREAD

**Issue by nuokh** [zammad/zammad#3914]
### Infos:

* Used Zammad version: 5.0.3
* Installation method (source, package, ..): package
* Operating system: Debian 11

### Expected behavior:
* Following the [https://docs.zammad.org/en/latest/appendix/single-sign-on.html]("Install further Apache dependencies" docs to set up SSO) using Debian 11 installs needed dependencies.

### Actual behavior:
* Debian can't find installation candidate for libapache2-mod-auth-kerb. Looks like it got removed.

### Steps to reproduce the behavior:
1. Set up fresh Debian 11 server
2. Try "apt install krb5-user libapache2-mod-auth-kerb" (from SSO docs)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by prigaux** [comment]
For info, libapache2-mod-auth-gssapi replaces libapache2-mod-auth-kerb
