### ISSUE TITLE
TicketID is not the URL ID

### ISSUE THREAD

**Issue by DoktorAerzt** [zammad/zammad#3916]
### Infos:

* Used Zammad version: 5.0.3-1641822517.3413a290.bionic
* Installation method (source, package, ..): package
* Operating system: Ubuntu 18.04 LTS
* Database + version: Postgres 10.19-0ubuntu0.18.04.1
* Elasticsearch version: 6.8.22
* Browser + version: Not relevant

### Expected behavior:

The URL ID and the Ticket ID should be the same.
example.org/#ticket/zoom/4274
TicketID = 4274

### Actual behavior:

The URL ID is one number higher asthe Ticket ID.
example.org/#ticket/zoom/4275
TicketID = 4274

### Steps to reproduce the behavior:

We are unsure when this problem happens but now we always get a false URL ID. 
The api is also not more working correctly because your need to work with the URL ID and not the ticket id. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by marcungeschikts** [comment]
Following forum discussion(https://community.zammad.org/t/ticketid-is-not-the-url-id/8490), do you still consider it as a technical question and not a bug?

**Comment by MrGeneration** [comment]
Its still is a technical question yes. I'm locking this issue to contributors only to reduce unneeded bumping.
