### ISSUE TITLE
Restore: DB is not created

### ISSUE THREAD

**Issue by altesockensuppe** [zammad/zammad#3929]
### Infos:

* Used Zammad version: 5.0.3-1642408445.bf5cb0a5.bullseye
* Installation method (source, package, ..): package
* Operating system: Debian 11
* Database + version: postgresql 13.5-0+deb11u1
* Elasticsearch version: 7.16.3
* Browser + version: not affected

### Expected behavior:

* Reason: I created a new VM and installed Zammad on it. Now I wanted to restore the DP and file backup with the supplied bash scripts.
* During the Zammad restore `./zammad_restore.sh` the database should be dropped and then created
The affected lines in the `functions` script are these (line 195 - 223)

```
    if command -v zammad > /dev/null; then
      zammad config:set DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      zammad run rake db:drop
      zammad config:set DISABLE_DATABASE_ENVIRONMENT_CHECK=0
    else
      DISABLE_DATABASE_ENVIRONMENT_CHECK=1 ${ZAMMAD_DIR}/bin/rake db:drop
    fi

    echo "# ... Creating database ${DB_NAME} for owner ${DB_USER}"
    if command -v zammad > /dev/null; then
      # We'll skip this part for docker installations
      su -c "psql -c \"CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};\"" postgres
    else
      ${ZAMMAD_DIR}/bin/rake db:create
    fi
```

### Actual behavior:

* The database is dropped but not recreated
* As workarround the database was created with the command `su -c "psql -c \"CREATE DATABASE zammad OWNER zammad;\"" postgres` on the CLI and the lines `199 + 208` were commented out in the file `functions`.

### Steps to reproduce the behavior:

* Zammad backup with `zammad_backup.sh`
* Create a new system, install Zammad via package manager
* Copy the dump to the new system
* become user zammad `su zammad`
* restore zammad with 
  * `zammad~$ cd /opt/zammad/contrib/backup`
  * `zammad~$ ./zammad_restore.sh`.
* At `echo "# Restoring PostgreSQL DB"` the fatal error appears that the database `zammad` does not exist
  * If you open a second shell and display the databases in postgresql with the user `postgres`, you see that `zammad` is missing
* And the output of the script is `Zammad restored successfully`

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
