### ISSUE TITLE
Tag selection refresh the sidebar and show field for a second

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#3932]
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): your demo on mydemo.zammad.com, I don't know
* Operating system: your demo on mydemo.zammad.com, I don't know
* Database + version: your demo on mydemo.zammad.com, I don't know
* Elasticsearch version: your demo on mydemo.zammad.com, I don't know
* Browser + version: Microsoft Edge 97.0.1072.69

### Expected behavior:
If I select a tag the sidebar shouldn't reload
*

### Actual behavior:
If I select a tag and changed before e.g. the status of a ticket, the sidebar reloads after some seconds and show the field GRUPPE for a second. In some cases (I don't know in which case) the status value are lost or the Besitzer is changed. If I find it out I post it.
*

### Steps to reproduce the behavior:
1. set status to closed
2. select a tag
3. Move with TAB to another field and wait 2-3 seconds
4. the sidebar reloads
*

Here is a GIF-Animation is the problem in your own demo to be sure thats not a wrong configuration in my installation:
![Animation](https://user-images.githubusercontent.com/1473674/150683588-993e08f2-e3c4-4c35-a71f-2a72c28f6ee6.gif)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by Dennis1993** [comment]
Can you explain why?
Your standard text is not helpful for all users… 🙄
Why the field is popped in and out? Thats normal? Why?
