### ISSUE TITLE
Startup of Zammad does not synchronize the custom branding logo

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#3933]
### Infos:

* Used Zammad version: any (at least with Zammad 4.0 and higher)
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Zammad synchronizes the current branding logo from database to to file system upon startup.

### Actual behavior:

Synchronizing branding logos from database to file system does not happen during start up.
This potentially causes issues upon specific restoration processes.

### Steps to reproduce the behavior:

* Upload a custom logo (via branding) and submit
* Stop Zammad
* Remove the custom logo from file system (find all of them: 
  `find /opt/zammad/public/assets/images/ -type f -regextype sed -regex ".*/[0-9a-f]\{32\}\.png"`)
* Start Zammad
* check `public/assets/images/` listings

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by martini** [comment]
The problem is this line. If I comment this out everything is working nice.

https://github.com/zammad/zammad/blob/develop/config/initializers/logo.rb#L5

Got introduced with https://github.com/zammad/zammad/commit/5745fa46bd86ab9ad8966d9bd7555cce0f007fd1#diff-b4a195f23c3174ac126a32ea1daba32f7b246899846171aea397de5f6c95e054R1

**Comment by martini** [comment]
As site note, the origin of the issue is coming from changed rake behavior in Rails 5.2, see https://github.com/rails/rails/issues/32870
