### ISSUE TITLE
Backup script failing when using PostgreSQL

### ISSUE THREAD

**Issue by shakalandy** [zammad/zammad#3949]
### Infos:

* Used Zammad version: 5.0.3-1643280981.141dc0ca.focal
* Installation method (source, package, ..): debian package
* Operating system: Ubuntu 20.04 LTS
* Database + version: postgresql-12 (12.9.0)
* Elasticsearch version: 7.16.3
* Browser + version: bash :)

### Expected behavior:

* Backup Script should work when using "peer" authentication without a password.
* At least, it should, or did I miss something? Using local/peer authentication should be considered safe, or not?

### Actual behavior:

* backup script is failing with "# ERROR - Found an empty database password ..."

### Steps to reproduce the behavior:

* Version was upgraded several times, so could also be an "older" issue.
* Backup worked normally with package version 5.0.3-1641822517.3413a290.focal
* backup stopped working with upgrade to 5.0.3-1642755691.7ff7be80.focal
* related to the major backup change in #3865 
* workaround possible by commenting "#check_empty_password"
* possible solution: Introduce variable/check for local/peer auth when using postgresql?

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
