### ISSUE TITLE
MySQL / MariaDB utf8mb4 support

### ISSUE THREAD

**Issue by danir-de** [zammad/zammad#3980]
Zammad currently supports MySQL and PostgreSQL as database backends.

When paired with MySQL or MariaDB, Zammad looses the ability to save or process uncommon UTF-8 icons due to the lack of utf8mb4 support, as documented [here](https://community.zammad.org/t/emojis-or-icons-in-overview-title/5166) and [here](https://github.com/zammad/zammad/issues/1824) (#1824).

The only solution that was proposed till now was https://github.com/zammad/zammad-documentation/commit/8974151bdbe49223b2ac9ef7135cd65c3c085277 by adding a note to the documentation that proper UTF-8 suppoer by using utf8mb4 is broken in Zammad.

This issue serves more as a bug report then a feature request, because the expected behaviour of any application would be for proper utf8mb4 support, letting users make full use of UTF-8, leaving users with broken installs or incomplete UTF-8 capabilities. 
That's why: Yes I'm sure this is a bug and no feature request or a general question.

### Installation Info:
* Database version: MariaDB 10.7 (utf8mb4)
* Zammad version: latest (5.0.3)

### Expected behavior:
* Use MySQL utf8mb4 as DB backend

### Actual behavior:
* SQL Errors (#1824)

**Comment by MrGeneration** [comment]
This is a feature request and more of a upsteam issue - the reason is here:
https://github.com/zammad/zammad/issues/1824#issuecomment-365321856

So that's why:
Sorry, but this seems to be a feature request.
Please note that this repository is the wrong place for feature requests.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case the community provides enough votes (hearts on the first article, so feels the same way like you), we will move the feature request to this repository.

If you require a feature *now* or want to sponsor functions, please feel free to contact our sales team: sales [at] zammad [dot] com.

**Comment by danir-de** [comment]
I don't agree with this being a feature request since it breaks with MySQL/MariaDB support and introduces [potential security issues](https://mathiasbynens.be/notes/mysql-utf8mb4) and continuing data loss for customers and operators.

Nethertheless I've created an [additional topic in the feature request part of the Zammad forums](https://community.zammad.org/t/mysql-mariadb-utf8mb4-support/9322).
