### ISSUE TITLE
ERROR -- : Can't use Channel::Driver::Smtp: #<EOFError: end of file reached>

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#3993]
### Infos:

* Used Zammad version: 4.1.x
* Installation method (source, package, ..): Package
* Operating system: Debian GNU/Linux 10 (buster)
* Database + version: (PostgreSQL) 11.14 (Debian 11.14-0+deb10u1)
* Elasticsearch version: 7.x
* Browser + version: MS Edge, Chrome, Firefox newest versions

### Expected behavior:

* We created an automation task that will send an close notification e-mail to the customer of the ticket. 
* We expected that Zammad will send E-Mails to all customers of alle closed tickets.

### Actual behavior:

* Zammad system shows following error message: 
* ERROR -- : Can't use Channel::Driver::Smtp: #<EOFError: end of file reached>

### Steps to reproduce the behavior:

* Create an automation task that will send E-Mails to the customer if the ticket is closed.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
