### ISSUE TITLE
Reference other text modules from a text module (e.g. shared variables for canned responses)

### ISSUE THREAD

**Issue by trent823** [zammad/zammad#4001]
Is it possible to reference text module within another text module.
For example we have canned responses that we use to reply to customer enquiries.
Some of these canned responses have common text like information about our FAQs, or common groups of questions we require for different types of questions.

The issue is that we regularly changes these common elements and it requires us to update all our text modules we are using for canned responses. Instead if we could have a text module that contained the common text that we could reference in other text modules then we could just update one text module to update all of them

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
