### ISSUE TITLE
Trigger actions seems to be short a few fields

### ISSUE THREAD

**Issue by No15pecial** [zammad/zammad#4013]
### Infos:

* Used Zammad version: 5.0.x
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20 
* Database + version: MariaDB
* Elasticsearch version: Not sure how to check 
* Browser + version: Firefox 98

### Expected behavior:

*
Adding a trigger on Users to make the field Organization mandatory. That field is not present in the Action list. Also missing are Address and Note

### Actual behavior:

* The fields Organization, Address, and Note are missing from the action section. 

### Steps to reproduce the behavior:

* Add a trigger for Users and try to make Organization mandatory

No  I'm NOT sure this is a bug. I asked on the forum but I have not received a reply

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by No15pecial** [comment]
@MrGeneration  I submitted this to the   Zammad community over at: https://community.zammad.org/   No answer. I figured if the fields are missing then it must be a bug.   OK I'll hope someone replies in the forum.

I'm still in eval mode but if this turns out to be viable I my look into a support contract.

**Comment by MrGeneration** [comment]
You've waited two whopping hours.
If you require business grade response times consider buying support.

**Comment by No15pecial** [comment]
Huh?

OH I see I waited 2 hours since I posted in the forum. I'm sorry I jumped the gun I thought I found a bug. I actually posted a similar (well the same)  question yesterday. I'm still learning the ropes and making a bunch of mistakes (probably evident from a couple of my other posts in the form).  I'm not sure what the norm is or what is customary.  I must learn patience is a virtue.

Again apologies
