### ISSUE TITLE
Failed to run background job #1 'TicketArticleCommunicateEmailJob'  - Error SMTP

### ISSUE THREAD

**Issue by RobsonMaxsuel** [zammad/zammad#4014]
### Infos:

* Used Zammad version: 4.1
* Installation method (source, package, ..): Package
* Operating system: Ubuntu 20.04
* Database + version: - Mariadb 10.3.34
* Elasticsearch version: - 8.7.0
* Browser + version: Chrome 99

### Expected behavior:

* sending emails correctly of notification

### Actual behavior:

* Error of SMTP

### Steps to reproduce the behavior:

* 
![image](https://user-images.githubusercontent.com/65795360/158611091-77de4d5a-9a96-4c5a-8329-c285fc4f46e4.png)

Failed to run background job #1 'TicketArticleCommunicateEmailJob' 3 time(s) with 7 attempt(s).

![image](https://user-images.githubusercontent.com/65795360/158611330-93d8b2f3-8f42-4e4c-8bf3-6d5223c841bc.png)

I didn't identify error messages in the log /opt/zammad/log/production.log, but if I need it I can send it.

We are using Locaweb's email server - email-ssl.com.br

Anyone have an idea?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by RobsonMaxsuel** [comment]
ok, I will create the topic at: https://community.zammad.org or check if it already exists.
