### ISSUE TITLE
Searches display all groups and owners on bulk selections

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4054]
### Infos:

* Used Zammad version: 5.1.0.
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: Microsoft Edge, 99.0.1150.46
* Ticket: 10104944 

### Expected behavior:

* If I open my overview and select several tickets at once, the dropdowns will also appear at the bottom, but only with the available options for which my user is authorized. In addition, I can select a user in the "Owner" dropdown here without resetting the fields and could thus take over this user via the button.

### Actual behavior:

*I am logged into the system with a user who is not authorized for all existing groups in the system, and I perform a search, then after selecting several tickets in the search results in the dropdown "Group" and "Owner" I can see all system-wide created groups and users. If I now select a corresponding user from the list in the "Owner" dropdown, all dropdowns reset and I can no longer select a user, the only option visible is the  "-". 

### Steps to reproduce the behavior:

* Enter a subject in the search field --> select multiple tickets --> now select a corresponding user from the list in the dropdown "Owner" --> after that all dropdowns reset and you can't select a user anymore, only "-".

![Unbenannt](https://user-images.githubusercontent.com/101350124/162994884-2b705590-77f3-4a40-a261-8d9fa9ffed94.jpg)

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by martini** [comment]
JFI: I verified this issue on a fresh `stable` installation.

![search-bulk-action](https://user-images.githubusercontent.com/110226/163389133-77ee13c5-1268-44d6-882d-66104eedc942.gif)
