### ISSUE TITLE
Invalid byte sequence in utf-8

### ISSUE THREAD

**Issue by localghost91** [zammad/zammad#4075]
Hi there Zammad Community, 

Actual behavior:

   I've installed Zammad recentily and I want to import some User-Data, but the "invalid byte sequence in utf-8" error message    
   appears. When trying to configurate S/mime i get the same error message :/

   I'm not too expirienced but i think it has to do with a locale configuration. 

Expected behavior:

    Import User Data via CSV

root@h123455:~# locale -a
C
C.UTF-8
de_DE.utf8
POSIX

###Infos:

    Used Zammad version: 5.1.x
    Installation method (source, package, ..): package
    Operating system: Debian 10
    Database + version: postgresql 13
    Elasticsearch version: elasticsearch 7.14 
    Browser + version: Firefox99.0.1

Is there something missing? I appreciate every hint you can give me to solve this problem :)

**Comment by mantas** [comment]
Seems to be either encoding issue in user data you're trying to import or a bug in Zammad that prevents this specific data from being imported.

Please tell which what exactly you're importing. It'd be great if you could share anonymized sample data.

**Comment by localghost91** [comment]
[User_Import_Zammad - Kopie.csv](https://github.com/zammad/zammad/files/8609604/User_Import_Zammad.-.Kopie.csv)

Thanks for the fast reply. I attached sample data.

**Comment by mantas** [comment]
Looks like there's something wrong with your CSV file. File itself pretends to be UTF-8. But if I open it as such, `König` is not recognized correctly. Looks like actual contents are Windows-1252. Thus importer gets confused.

**Comment by localghost91** [comment]
Okay, thanks for the hint! I will try to fix it and I let you know if it worked. Greetings

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
