### ISSUE TITLE
Search results are implicitely limited to 50 results

### ISSUE THREAD

**Issue by freesteph** [zammad/zammad#4084]
### Infos:

* Used Zammad version: latest
* Installation method (source, package, ..): zammad-docker-compose
* Operating system: Mac OS
* Database + version: N/R
* Elasticsearch version: N/R
* Browser + version: all

### Expected behavior:

* When I search for something (in my particular instance: tags), I would like to see all of the results, paginated if necessary, because on large production volumes there are sometimes way more than 50 tickets with a certain tag.

### Actual behavior:

*  I only get shown 50 results and cannot paginate or customise the resultset.

### Steps to reproduce the behavior:

* Have 50+ tickets with a tag. Try to browse all the tickets with this tag.

Yes I'm sure this is a bug and no feature request or a general question.

### Solution :

This patch fixes the issue:

```diff
From 9f3cd061aa731f35aa71149c9e7f33a99e6bc149 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?St=C3=A9phane=20Maniaci?= <stephane.maniaci@gmail.com>
Date: Thu, 12 May 2022 15:52:56 +0200
Subject: [PATCH] Feature: Don't limit search results to 50.

---
 app/assets/javascripts/app/controllers/search.coffee | 1 -
 1 file changed, 1 deletion(-)

diff --git a/app/assets/javascripts/app/controllers/search.coffee b/app/assets/javascripts/app/controllers/search.coffee
index 1ec5781c4..ae1f5dcdb 100644
--- a/app/assets/javascripts/app/controllers/search.coffee
+++ b/app/assets/javascripts/app/controllers/search.coffee
@@ -26,7 +26,6 @@ class App.Search extends App.Controller
 
     @globalSearch = new App.GlobalSearch(
       render: @renderResult
-      limit: 50
     )
 
     @render()
-- 
2.32.0 (Apple Git-132)
```

Let me know if this is a viable option. If it isn't I'll happily receive pointers towards a solution allowing a limited search with pagination.

**Comment by freesteph** [comment]
Duplicates https://github.com/zammad/zammad/issues/2142, my bad.

**Comment by freesteph** [comment]
And re-opening because the other issues are locked and don't address tag-based searches. Sorry about the noise.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by freesteph** [comment]
Hello Marcel

I'm not sure it's a question; the search is limited to 50 results, which isn't configurable by any means. That's what the code reads, and it is perceived as a bug/limitation for our teams using Zammad on multiple large-volumes websites. Apologies if I missed something, and thank you for your quick reply.

**Comment by MrGeneration** [comment]
This is a hard limit. There is an existing issue for that.
Adding more issues with the same topic brings nobody forward and also doesn't speed up the solving if applicable.

Technical question because you've also put questions into the post.
We're in general not answering questions on Github. If you do have further questions, please consult the Community.
