### ISSUE TITLE
it's a joke... 

### ISSUE THREAD

**Issue by ice9exe** [zammad/zammad#4085]
it's a joke if you avoid the "me too" to solve the problem. no. https://github.com/zammad/zammad/issues/3912

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
