### ISSUE TITLE
Pop-Up Warning for missing attachments with text containing "attached" or related only appears on english terms (not translated)

### ISSUE THREAD

**Issue by Koppishop** [zammad/zammad#4096]
### Infos:

* Used Zammad version: 5.1
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

* pop-up warning on text containing "attached", "attachment", "enclosed", etc. should also work in other languages.

### Actual behavior:

* pop-up warning on text containing "attached", "attachment", "enclosed", etc. only work in english.

### Steps to reproduce the behavior:

* setup new instance
* update user profile language to german (or others) 
* respond to ticket by mail using "anbei" "in der Anlage"
* press "submit" and no warning pop-up appear
* respond to ticket by mail using "attached" "attachment"
* press "submit" and warning pop-up appears

Yes I'm sure this is a bug and no feature request or a general question.

MarkUp for translatable strings are missing here: https://github.com/zammad/zammad/blob/9bccb2d2d2782f327952e6c076169b98eb1bae3e/app/assets/javascripts/app/lib/app_post/utils.coffee#L951

**Comment by mgruner** [comment]
@rolfschmidt @dominikklein this should perhaps go to PM first, and I would also consider this a feature request.

Just marking strings as translatable would probably not be sufficient:

- the language of the mail being written might differ from the agent's UI language
- for different languages, different words might be relevant, so that a 1:1 translation might not be sufficient
- would we want to check for all configured strings in all languages when looking at an email (since we currently don't know which language it is written in)?

**Comment by rolfschmidt** [comment]
I don't think so. This is a regression of the i18n replacement. There is already a loop to translate the words and it was used before. The old behaviour should be brought back. If you prefer a new way for the translation then this should be done in an enhancement issue because it needs to be specified.

https://github.com/zammad/zammad/blob/d07c69fcf040f975bec83aa9ded21c05fb3825c8/app/assets/javascripts/app/lib/app_post/utils.coffee#L952-L960

**Comment by mgruner** [comment]
@rolfschmidt thanks for the clarification. Then we can proceed with the fix, and PM can check if they want to improve something later or not.

**Comment by Marco-Total** [comment]
In the actual version  6.4.1-1741933941.0923b150.focal the popup warning is missing again.

**Comment by fliebe92** [comment]
Hi @Marco-Total. Please open a new report with clear steps on how to reproduce this behavior. Thanks!
