### ISSUE TITLE
Placeholder for client first article

### ISSUE THREAD

**Issue by PFialkowskiAGH** [zammad/zammad#4115]
Hi,
I need to get first article written by client and put this on notifications and trigger.
I've seen, that something like that is planning in zammad:
https://github.com/zammad/zammad/issues/905#issuecomment-290708600
But I can't find it.
Is this currently implemented in the system?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
