### ISSUE TITLE
Imap Bug in Ruby 2.7 to connect imap server grommunio-imap

### ISSUE THREAD

**Issue by hdnhdn** [zammad/zammad#4116]
Hello, 
when i will change my mail server in e-mail settings to the new grommunio server. it doesnt work.
the problem, when i will save the imap settings i get an error:

![image](https://user-images.githubusercontent.com/13570292/172769656-a9e5601a-c5a7-4715-b7de-07bfd0220858.png)

Unexpected token LPAR (expected QUOTED or LITERAL)

on testing und searching i will see there is an rubby 2.7 probleme, that have a bugfix. but i cannot update rubby to version 3.x
happend only on new grommunio-imap mail server. old server and other work.

i have make an ticket on grommunio, that also use zammad as ticketsystem, but the have not the problem.
i have make a ticket nand community entry there. but no solution.

we only find this:
https://bugs.ruby-lang.org/attachments/8560

next i have test an change settings in imap.rb but nothing helped.

the log in mailserver only show this:

Jun 09 07:19:34 m1 imap[1420]: < LOGIN ****: ret=6a9h code=1705
Jun 09 07:19:34 m1 imap[1420]: < RUBY0002 SELECT INBOX: ret=0h code=0
Jun 09 07:19:34 m1 imap[1420]: < RUBY0003 SORT (DATE) US-ASCII ALL: ret=0h code=0
Jun 09 07:19:34 m1 imap[1420]: < RUBY0004 SEARCH ALL: ret=2000000h code=0
Jun 09 07:19:34 m1 imap[1420]: < RUBY0005 FETCH 1 (RFC822.HEADER: ret=2000000h code=0

so i need support here..
ist the problem on mailserver or on zammads used version ruby?
or ist the problem on ruby package at the grommunio server.

zammad ruby:
Ubuntu 20.04
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

grommunio ruby:
Suse grommunio appliance
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux-gnu]

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question. Also the issue template completely has been ignored.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
