### ISSUE TITLE
Un-able to see see the ticket flow report 

### ISSUE THREAD

**Issue by nemanivks** [zammad/zammad#4120]
![image](https://user-images.githubusercontent.com/107258222/173068027-33b0de73-14c6-4965-90d1-bdec408cf72d.png)
Un-able to see see the ticket flow report

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
