### ISSUE TITLE
No error message is shown if the mandatory role field is missing during creating/updating overviews

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#4140]
### Infos:

* Used Zammad version: 5.1.x
* Installation method (source, package, ..): your own demo
* Operating system: your own demo
* Database + version: your own demo
* Elasticsearch version: your own demo
* Browser + version: Edge 102

### Expected behavior:
Output a visual error when the required role field is missing during the creating and updating of overviews.

### Actual behavior:
No visible error message when the required role field is missing during the creation and update of overviews.

### Steps to reproduce the behavior:
- Go to manage overview screen
- Try to update or create an overview without a role
- See that there is no visible error message and only an error in the console log.

![Animation](https://user-images.githubusercontent.com/1473674/174860802-27f544ad-358f-4485-9f4a-17294ac0d1ea.gif)

**Comment by dominikklein** [comment]
@Dennis1993 I think you need to select a role, because this is a required field, but sure the error handling seems not good in this situation.

**Comment by martini** [comment]
I agree. If you press "submit", is there a message on top of the modal screen?

**Comment by dominikklein** [comment]
> I agree. If you press "submit", is there a message on top of the modal screen?

When I saw it correctly there is currently no visible error message in the dialog. But it's not related to 5.2, it was already in the past.
I will improve the issue description.

**Comment by MrGeneration** [comment]
Zammad 5.2 stable does not provide an error message any longer - only within the developer console which is very bad:
![image](https://user-images.githubusercontent.com/6549061/174979509-373b3b1c-235d-409d-83d8-2edf74afc7f0.png)
![image](https://user-images.githubusercontent.com/6549061/174979531-f08a2c74-c015-4464-828e-6b99da655f66.png)

I've checked back to 4.1 where this issue is already present
![image](https://user-images.githubusercontent.com/6549061/174980486-57a2659d-472a-4495-844a-5cb2739a2540.png)
