### ISSUE TITLE
Invalid filter syntax in LDAP

### ISSUE THREAD

**Issue by Dennis1993** [zammad/zammad#4145]
### Infos:

* Used Zammad version: 5.2.0 (patchlevel from today)
* Installation method (source, package, ..): source
* Operating system: Ubuntu 20.04
* Database + version: Postgres
* Elasticsearch version: latest
* Browser + version: Edge 103

### Expected behavior:
If I want to sync only active users from out LDAP the filter for that should be work in zammad
`(&(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2))`

### Actual behavior:
Since the version 5.2 Zammad says every sync, that a systemmailbox has a problem. In all versions before no problems detected:
![image](https://user-images.githubusercontent.com/1473674/175828413-2c9c9d26-16e8-469b-8d21-ffd223822280.png)

Because this error I want to sync only active users because the systemmailbox-objects are from the Exchange as default accounts.

If I put now a LDAP user filter for only activated users zammad says, that the filter is invalid. In powershell the filter works perfectly:
`(&(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2))`

### Steps to reproduce the behavior:
Insert the filter for a LDAP conection:
`(&(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2))`

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by Dennis1993** [comment]
Have you read my post?
Why is that not a bug?
It is not possible to save the LDAP filter:

![image](https://user-images.githubusercontent.com/1473674/175829675-f2a82fff-1714-4cf1-9074-736a8d7fcb34.png)

**Comment by MrGeneration** [comment]
> Have you read my post?

No I'm in general throwing dice and if it's a 6 you get through. /s

> It is not possible to save the LDAP filter:

Which part of "invalid ldap filter syntax" did you not understand?
The syntax is **invalid** which is not a bug but your fuck up.

Now please either open a support ticket if you're a paying customer or move on to the community.
This is a friendly warning as behaving this way is not the first time.
