### ISSUE TITLE
The conversation history is not displayed.

### ISSUE THREAD

**Issue by mdncom** [zammad/zammad#4150]
Hey,

our Zammad system is linked to an O365 Acc, if I answer via Zammad on mails that works. But the recipient of my answer DOES NOT see what I have answered.
In short: The conversation history is not displayed.

Greetings
KM

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
