### ISSUE TITLE
Custom objects cannot be set in filters

### ISSUE THREAD

**Issue by sbrunecker** [zammad/zammad#4154]
### Infos:

* Used Zammad version: 5.2.0-9
* Installation method (source, package, ..): docker-compose
* Operating system: Docker
* Database + version: Zammad Postgres 5.2.0-9
* Elasticsearch version: 5.2.0-9
* Browser + version: Chrome 102.0.5005.115

### Expected behavior:

* Object value is set according to filter action (#394)

### Actual behavior:

* Object value is set to default value

### Steps to reproduce the behavior:

* Create an object `autoreply`
![image](https://user-images.githubusercontent.com/33121464/176500442-f2a826eb-e9fc-438b-bef2-4abfae7ba294.png)
* Update the database and restart zammad
* Create an email filter 
![image](https://user-images.githubusercontent.com/33121464/176501221-6d28e685-51e2-4464-848a-c4c4a99a59f6.png)
* Send an email from the email in the filter configuration to an inbound email account
* Observe that the scheduler logs show

```
I, [2022-06-29T17:34:23.109831 #1-110300]  INFO -- : fetching imap (mail.company.com/my-company@company.com port=993,ssl=true,starttls=false,folder=INBOX,keep_on_server=true,auth_type=LOGIN)
I, [2022-06-29T17:34:23.316989 #1-110300]  INFO -- :  - message 1/1
I, [2022-06-29T17:34:23.374086 #1-110300]  INFO -- : Process email with msgid '<xxxxxxx@company.com>'
I, [2022-06-29T17:34:23.383090 #1-110300]  INFO -- :   matching content 'from' contains some-email@abc.com
I, [2022-06-29T17:34:23.388653 #1-110300]  INFO -- : set_attributes_by_x_headers header x-zammad-ticket-priority_id found. Assign priority_id=3
I, [2022-06-29T17:34:23.388690 #1-110300]  INFO -- : set_attributes_by_x_headers header x-zammad-ticket-customer_id found. Assign customer_id=54
I, [2022-06-29T17:34:23.408136 #1-110300]  INFO -- : set_attributes_by_x_headers header x-zammad-article-preferences found. Assign preferences={"send-auto-response"=>true, "is-auto-response"=>false}
I, [2022-06-29T17:34:23.448708 #1-110300]  INFO -- : Execute trigger (auto reply (on new tickets)/1) for this object (Ticket:1484/Loop:1)
```

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
