### ISSUE TITLE
tickets.id and tickets.number are not matching

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#4160]
### Infos:

* Used Zammad version: 5.2.0 and 5.2.1
* Installation method (source, package, ..): package
* Operating system: Ubuntu 20.04.4 LTS
* Database + version: postgresql-12
* Elasticsearch version: 7.17.5
* Browser + version: MS Edge Version 103.0.1264.37

### Expected behavior:

Ticket Number and ID are matching.

### Actual behavior:

In our system the id 532 was skipped but not the number "4200532".

Used sql statement:
```
select
    id as ID,
    number as number
from tickets t
where t.id >= '531'
order by t.number;
```
Output:
```
 id  | number
-----+---------
 531 | 4200531
 533 | 4200532
 534 | 4200533
 535 | 4200534
 536 | 4200535
 537 | 4200536
 538 | 4200537
 539 | 4200538
 540 | 4200539
...
```

In the GUI:
![image](https://user-images.githubusercontent.com/65536211/177320889-aebcad5f-2a45-4ae1-be8b-9b331e57936e.png)

### Steps to reproduce the behavior:

Create a ticket via portal or mail.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
