### ISSUE TITLE
Firewall blocking Elasticsearch Indexing

### ISSUE THREAD

**Issue by horninfo** [zammad/zammad#4187]
### Infos:

* Used Zammad version: 5.2.1
* Installation method (source, package, ..): package
* Operating system: Debian
* Database + version:
* Elasticsearch version:
* Browser + version:

### Expected behavior:

* zammad run rake zammad:searchindex:rebuild builds searchindex

### Actual behavior:

* command aborts at version check
* Internal Elasticsearch port is dropped by firewall rule

### Steps to reproduce the behavior:

* us nftables as shown in Documentation for Debian

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
