### ISSUE TITLE
Request - Where to disable MX Validation for forms Zammad v5.2.x

### ISSUE THREAD

**Issue by LPJon** [zammad/zammad#4194]
I need to know how to disable MX lookups for email validation on forms for Zammad v5.2.x. I have a situation where the email server i host is on the same network as Zammad. It can"t perform MX validation because it is proxied through a webserver which also handles dns for public IP's behind a NAT. Please provide me a way to disable the MX checks only.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
