### ISSUE TITLE
Slack integration ignores custom Icon-URL

### ISSUE THREAD

**Issue by Mintux** [zammad/zammad#4196]
### Infos:

* Used Zammad version: 5.2.1
* Installation method (source, package, ..): source
* Operating system: Debian 11 Bullseye
* Database + version: MariaDB 10.5.15
* Elasticsearch version: 7.17.5
* Browser + version: Firefox 103.0

### Expected behavior:

Zammad should use the custom Icon-URL for the Slack Integration like described in the documentation.

### Actual behavior:

Zammad ignores the custom Icon-URL and always uses the fallback which is https://zammad.com/assets/images/logo-200x200.png. 

### Steps to reproduce the behavior:

Activate the Slack Integration and set a custom Icon-URL. Create a new ticket and see the wrong Icon in Slack.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by asaglam76** [comment]
Yep, that's right. Have same issue with Rocket.Chat
I didn't focused more this, thought it is a failure from my side, but now, I think also it a bug.

**Comment by cautopartes** [comment]
I used Mattermost via Slack integration to verify this. So far, I can confirm that the setting for Icon-URL has no effect.

**Comment by dominikklein** [comment]
Should be fixed in the "old" Slack integration with this commit: https://github.com/zammad/zammad/commit/ac4c7404400349ec75cc85c2a36c046cbc37703e

In general, Slack no longer supports this Icon-URL in the new suggested way of creating such an incoming webhook:

```
You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.
```
(https://api.slack.com/messaging/webhooks)

RocketChat and Mattermost are still supporting this, but in the future we are going in a different direction with the new pre-defined webhook feature: https://github.com/zammad/zammad/issues/4482
