### ISSUE TITLE
Accounted time not transfered on ticket merge

### ISSUE THREAD

**Issue by Jaykju** [zammad/zammad#4201]
### Infos:

* Used Zammad version: 5.2.1
* Installation method: package
* Operating system: Ubuntu 20.04.4
* Database + version: PostgreSQL 12.11
* Elasticsearch version: 6.8.23
* Browser + version: Chrome Linux 103.0.5060.134

### Expected behavior:

When two tickets are merged the accounted times should be removed from the "source"-ticket and added to the "target"-ticket.

### Actual behavior:

All articles are moved to the "target"-ticket but the accounted time is not transfered.

This results in a ticket with status merged and only one article "merged" but still including the accounted time.

### Steps to reproduce the behavior:

1. Create two tickets and track some time in each of them.
2. Merge the two tickets and check the accounted times.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
