### ISSUE TITLE
Over 100 kB downloaded for login page

### ISSUE THREAD

**Issue by paulmenzel** [zammad/zammad#4204]
Visiting https://support.hifis.net/#login, only a login page is shown, but 3.46 MB are transferred. The biggest offender is the (uncompressed) 2.78 MB Zammad JavaScript file https://support.hifis.net/assets/application-c2ebfe8c786c6b9db7c86af18be477d99e3b743970f29e3b6554830d772eb792.js, and (uncompressed) 321 kB [Bootstrap](https://getbootstrap.com/) CSS file https://support.hifis.net/assets/application-0dff4740f40f18c3dd3a1a2d278781ee823c40e81140a6a1e817d15d7f7c8041.css.

[Google PageSpeed Insights gives a score of 32/100 on mobile, and 71/100 on desktop.](https://pagespeed.web.dev/report?url=https%3A%2F%2Fsupport.hifis.net%2F%23login&form_factor=desktop)

**Comment by dominikklein** [comment]
@paulmenzel The assets pipeline will always create an uncompressed and compressed version. Looks to me the webserver is not correctly configured (https://docs.zammad.org/en/latest/getting-started/configure-webserver.html#configure-the-webserver - `contrib/nginx/zammad.conf`)

Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
If you're paying customer already, please consult your Zammad support for assistance! :-)

**Comment by paulmenzel** [comment]
Thank you for the answer.

Do you have a correctly set up Zammad instance, where the page size can be verified to be below 100 kB?

**Comment by Dennis1993** [comment]
Try the demo: https://zammad.com/de/loslegen

all other questions please post on the community.

**Comment by MrGeneration** [comment]
The issue is that you don't understand that Zammad is not a website but an application.
You'll of course not hit 100kb or less as all relevant assets are loaded before you're logging in.

Works as designed. A vanilla instance transfers roughly 1MB of data without any customization.
