### ISSUE TITLE
Each posting to a linked Facebook page creates a ticket in the Helpdesk

### ISSUE THREAD

**Issue by jacotec** [zammad/zammad#421]
Hi,

I've linked Zammad to our Facebook page, so user posts become tickets in the help desk. That works quite well, also answers are commented back to Facebook.

But each time my Facebook app posts on the "main page" (not "Besucherbeiträge") - which is done automatically when someone writes an article on our homepage by a Wordpress plugin, a ticket gets created in Zammad with just the name of my facebook page. The ticket is closed by default when it arrives in Zammad:

![image](https://cloud.githubusercontent.com/assets/3321655/20309713/51705f84-ab49-11e6-85d2-6385130c86d8.png)

That's a bit annoying ;-)

**Comment by thorsteneckel** [comment]
Hi @jacotec  - This is the new standard behavior discussed here: https://github.com/zammad/zammad/issues/251

We do this to be able to handle responses to that post. Otherwise there would be no ticket and the response/comment will be lost. The ticket contains only the name of your page since it's the text of the post:
![bildschirmfoto 2016-11-15 um 16 07 19](https://cloud.githubusercontent.com/assets/3873515/20310924/0ac91d0a-ab4e-11e6-86d6-b4d79254dc07.png)

But we think that's a bug to not include the link in the Zammad ticket. We will fix that.

I'm totally with you that this is annoying but the text of the post is out of our scope.

**Comment by jacotec** [comment]
Hi @thorsteneckel 

thanks ... I fully understand and agree to create a ticket here! I was just wondering where this comes from, but that makes sense! :-) Did not know that also main page posts can be commented, not only "Besucherbeiträge" ;-)

I've changed my plugin to use an excerpt of the post and now it's much better (and Zammad can differ between posts, I guess *g*). Including the link would be appreciated.

**Comment by monotek** [comment]
Hmmm... Wasn’t this already changed, that posts of siteadmins  are created with closed state and only reopened when somebody comments the post?

https://github.com/zammad/zammad/issues/251

**Comment by jacotec** [comment]
@martini  Just thinking if it wouldn't make sense to disable the email notification to the group where the closed tickt belongs to. Nobody cares and it's a load to the staff. It's starting to get interesting once a comment opens it ...

**Comment by jacotec** [comment]
@martini @thorsteneckel 
Any comments to my last post (disabling the email notification to the agents for the created but closed ticket)?

It's somehow annoying for them to always get mails from the helpdesk for tickets which absolutely need no attention.

**Comment by thorsteneckel** [comment]
Hi @jacotec - Is this issue still present? We are (still) not able to reproduce it. Please provide a step by step instruction.

**Comment by MrGeneration** [comment]
I, I can reproduce this problem. New Posts on the facebook page (with content) will be created directly as "closed", but appear directly as closed. I will try what happens if I reopen the ticket automatically with a filter/trigger.

I am missing a history in that case, because I cannot see if it is directly triggered as "closed" or it will get closed right after creating. Users receive a E-Mail-Notification (in case agent wants to) and also it will get  the information from the activity stream.

Also the information that zammad is not able to track the post if it's open is not correct. I manually reopened the ticket and posted a test afterwards (it will be appended to the ticket):

![image](https://user-images.githubusercontent.com/6549061/35293724-e006769e-0074-11e8-8fe6-8a2d62f6a3bf.png)


How I configured zammad:

* Created a facebook App as described in documentation
* added API-Key and secret
* added account and configured only the desired facebook page to redirect the posts in the wanted group
* post a new post as page on the facebook page
* wait a bit to zammad grab the change ...
* zammad notices change and creates a new ticket (with notification) and closes the ticket

Configuration:
![image](https://user-images.githubusercontent.com/6549061/35293910-7550135e-0075-11e8-86ed-790e0699769a.png)

**Comment by thorsteneckel** [comment]
Zammad also creates tickets for your own post. This is necessary to receive replies to these posts. Since in principle no action is necessary for your own post, the ticket is created as closed. Notifications should not be sent here. The ticket history shows that the ticket has been created as closed. If a reply/comment is created under a post, it will be received and attached to the ticket as an article. The status changes to `open` because it is an (external) customer article.

Where does the process in your scenario differ?

**Comment by MrGeneration** [comment]
Hey @thorsteneckel ,

it is different exactly at the last point " The status changes to open because it is an (external) customer article."

The ticket will not be reopened automatically. I had to do this manually on my own.

![image](https://user-images.githubusercontent.com/6549061/35325818-24bd2410-00f5-11e8-99a9-a894fe988ab2.png)

Since this is a official facebook page I have limited options to test those problems. But I can create a temporary page if needed.

**Comment by thorsteneckel** [comment]
Thanks for your feedback. Can you please create writeups in new issues since this is closed quite a while and had a different origin. Please create one issue for the `open` part and one for the wrong customer. We will address it. Thanks!
