### ISSUE TITLE
Possibility to handle shared organization information in more granular way

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4218]
### Infos:

Infos:
Used Zammad version: 5.2.x
Installation method (source, package, ..): any
Operating system: any
Database + version: any
Elasticsearch version: any
Browser + version: Microsoft Edge, Version 104.0.1293.54 (Official Build) (64-Bit)
Ticket: #10113309, #10113271

### Expected behavior:

* It should be possible to set the shared organization flag in a more granular way. So that only specific customer users have the possibility to see all tickets from the organization.
* This could maybe be on the user level or role level.

### Actual behavior:

 * At the moment it's only possible to set the shared organization flag on the organization level. When the shard organization is activated, all users in this organization will have access to all organization tickets.

**Comment by KoJie** [comment]
the issue of ticket permissions on the customer side would be a fundamental modification of the Zammad structure. Due to this, a simple solution is currently not possible here. However, we know that there are several use cases that are valid to approach this topic and find a global solution in the future. For this, however, we need some analysis and, above all, use cases to guide us. 
Therefore, we close the topic here, but would like to refer to our community to discuss scenarios and solution ideas: https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6.
