### ISSUE TITLE
EOF reached in getting started

### ISSUE THREAD

**Issue by enzofoucaud** [zammad/zammad#4226]
### Infos:

* Used Zammad version: latest
* Installation method (source, package, ..): [Step 4](https://docs.zammad.org/en/latest/install/docker-compose.html)
* Operating system: WSL2
* Database + version: latest in [zammad-docker-compose](https://github.com/zammad/zammad-docker-compose)
* Elasticsearch version: latest in [zammad-docker-compose](https://github.com/zammad/zammad-docker-compose)
* Browser + version: latest in [zammad-docker-compose](https://github.com/zammad/zammad-docker-compose)

### Expected behavior:
* Go to the next step

### Actual behavior:
![image](https://user-images.githubusercontent.com/15039645/186437636-8ea890a8-a213-4edb-8c4c-51c5d8756255.png)

### Steps to reproduce the behavior:
* Getting start

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
