### ISSUE TITLE
Zammad Form integration into vue3 TypeScript project

### ISSUE THREAD

**Issue by SebastianOpriel** [zammad/zammad#4230]
Hi!
We currently try to integrate zammad form feature (https://COMPANY.zammad.com/#channels/form) into a vue3/TypeScript project with Composition API. Has anyone already integrated the form and may provide some code examples as the provided code example is working with JavaScript only? 

Thanks!
Best Regards,
Sebastian

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
