### ISSUE TITLE
The documentation does not state information on permissions needed for the Elasticsearch user used to connect to Elasticsearch server

### ISSUE THREAD

**Issue by oussjarrousse** [zammad/zammad#4232]
While attempting to connect my zammad installation with an elasticsearch that I am hosting on another device. I created a special Elsaticsearch user for Zammad. I did not want to give too much permissions to the zammad ES user. However I did not find in the documentation the list of permissions required for a successful integration of EL and Zammad. https://docs.zammad.org/en/latest/install/elasticsearch.html 

Eventually I ended up using the following solution:

Define a new EL role with the following permissions:
- Cluster privileges: monitor, manage_ingest_pipelines
- Index privileges: 
  - indices: Zammad_*
  - privileges: create_index, create_doc, create, read

I think this info should be added to the documentation exactly here:
https://docs.zammad.org/en/latest/install/elasticsearch.html

**Comment by MrGeneration** [comment]
Wrong repo.

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
