### ISSUE TITLE
How does token generation works in zammad for users that were on boarded to zammad via Microsoft account ? Whats the grant type?

### ISSUE THREAD

**Issue by sanasz91mdev** [zammad/zammad#4235]
Hello,

To onboard all Microsoft Azure AD users to zammad, i have successfully completed integration with Microsoft. I am even able to sign up / login with Microsoft via zammad web interface.

I am creating a Microsoft Teams Bot application that uses Zammad Rest APIs .. **I can see no possibility** of generating tokens for users that were on boarded to zamamd using Microsoft account ... 

I have seen 2 ways of token generation that is,

1) user-access-token (it requires user password in API request Headers - **_how will i provide it for users that were on boarded using Microsoft account?_**)
2) generating token on settings in zammad Admin panel

Is there really no possibility for using Zammad Rest APIs without knowing user password?

I want to build a flow in which my Bot shows a zammad login dialog and on clicking Microsoft, a token is returned to Bot application, which uses the received token for calling Zammad Rest APIs. Is this possible, If yes then how?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
