### ISSUE TITLE
Email notification not working

### ISSUE THREAD

**Issue by Hyphaed** [zammad/zammad#4237]
Email notification is not working

I've configured Google Email SMTP suing app pass (not working)

I tried to manually add gmail account to sendmail (not working)

* months ago was wokring, the virutal machine has enough free space, enough ram, enough CPU

I've checked documentation and other posts of people with similar issue, but still with the problem

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
