### ISSUE TITLE
Separate M365 OAUTH user and mail integration

### ISSUE THREAD

**Issue by hennibadger16** [zammad/zammad#4253]
### Infos:

* Used Zammad version: 5.2.1-7
* Installation method (source, package, ..): Docker
* Operating system: Alpine Linux
* Database + version: Postgres 5.2.1-7
* Elasticsearch version: 5.2.1-7
* Browser + version: Chrome 105

### Expected behavior:

* Different Azure enterprise applications for user authentication and mail integrations for scoping neccessary API permissions

### Actual behavior:

* It only seems possible to register a single Azure application. So permission on users' mailboxes are getting applied which are not needed.

### Steps to reproduce the behavior:

* Integrate Azure mailbox and user authentication.

I'm not sure if it's more of feature request or even possible to integrate as I guess it would need two separate Azure app integrations?

Thank you.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
