### ISSUE TITLE
SSL_connect returned=1 errno=0  state=error: unsupported protocol

### ISSUE THREAD

**Issue by if20b034** [zammad/zammad#4267]
### Infos:
Used Zammad version: 5.2.2
Installation method (docker): Hosted
Operating system: any
Database + version: any
Elasticsearch version: any
Browser + version: Chrome

### Expected behavior:
When setting up an outgoing email, no error should be thrown and the email should be added. 

### Actual behavior:
The error: "SSL_connect returned=1 errno=0  state=error: unsupported protocol" is shown right after inserting the data for the email setup. Works on Zammad.com (The 30 days free trial verison) with the same settings and no problems at all.

### Steps to reproduce the behavior:
Follow the tutorial for Docker. Open up localhost:8080. Try to set up an outgoing email.

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
