### ISSUE TITLE
Export does not show body of ticket

### ISSUE THREAD

**Issue by Biopack-Alain** [zammad/zammad#4270]
Hy,

i want to export the body of the tickets to a excel file or other file i only find the excel export , and this show me not the body is there a way or a tool to get to full ticket data including the body ? 

### Infos:

* Used Zammad version:
* Installation method Package
* Operating system: Debian
* Database + version: Mysql
* Browser + version: chrome

### Expected behavior:

Export all ticket data 

### Actual behavior:

Export contains limited data

### Steps to reproduce the behavior:

Zammad > Reporting > Select Year > Export

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by Biopack-Alain** [comment]
Hi @MrGeneration 

sorry i will go to the community and ask it there sorry for the disturbance.
