### ISSUE TITLE
Customer sees agent mechanisms

### ISSUE THREAD

**Issue by KamilTancula** [zammad/zammad#4271]
### Infos:

* Used Zammad version: 5.2.x
* Installation method (source, package, ..): source
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

*A regular user sees a basic "new ticket" window.
Not expanded as in the case of users with agent privileges.  

### Actual behavior:

*Customer when creating a "New Ticket" sees the same panel for the request as a user with Agent privileges , namely Recaivede Call, Outbound Call and Send Email. 
In addition, the user can see the statistics of the agents. 

### Steps to reproduce the behavior:

*CLogging in as a normal user and additionally trying to create a new ticket

Yes I'm sure this is a bug and no feature request or a general question.

![zammad1](https://user-images.githubusercontent.com/72379678/192280159-1102ec52-71af-4006-89e6-6cdb6857c6cd.JPG)
![zammad2](https://user-images.githubusercontent.com/72379678/192280167-4145e1bb-f789-4992-8a12-fe99f81d099b.jpg)
![zammad3](https://user-images.githubusercontent.com/72379678/192280169-816a77f7-0b28-4501-a8f7-051c200789d7.jpg)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by KamilTancula** [comment]
Hello,

This is not a technical question. 
In version 5.1, an ordinary user after logging in had a default window for reporting new tickets. 
After upgrading to 5.2, the same user (as well as the other 100 users) sees the new ticket submission system as a user with agent privileges - that is, extended. 
In addition, the unfastening of the upra
So this is 100% a bug and not a problem with the settings.

**Comment by MrGeneration** [comment]
I can't reproduce it with the supplied information.
Consult the community if you have further questions about this.
