### ISSUE TITLE
After upgrading to 5.2, customers have "limited" agent privileges. 

### ISSUE THREAD

**Issue by KamilTancula** [zammad/zammad#4272]
### Infos:

* Used Zammad version: 5.2.x
* Installation method (source, package, ..): source
* Operating system:any
* Database + version:any
* Elasticsearch version:any
* Browser + version:any

### Expected behavior:

*After upgrading to 5.2, customers have "limited" agent privileges. 

So that a "regular" customer can only see the basics of the new ticket submission panel as it was in version 5.1 and not the extended version as seen by a user with agent privileges, and additionally, so that they do not have access to the agent dashboard

### Actual behavior:

*"Ordinary" customer after logging into the system sees dashbord user with agent privileges (reports, statistics, etc.). 
In addition, when creating a new ticket (via web), he does not see the basic window only the extended one i.e. with options "Recaivede Call, Outbound Call and Send Email."
Attached are the old and new windows for the same user who only has a basic customer. 

### Steps to reproduce the behavior:

*Upgrade the system from 5.1 to 5.2 and log in with a user that already existed. 
He or she should suddenly see things that an agent should see, as well as the agent view when trying to set up a new ticket. 

It seems to be related to this notification because the user has the same problems : 
https://github.com/zammad/zammad/issues/4272

Yes I'm sure this is a bug and no feature request or a general question.

![zammad_old](https://user-images.githubusercontent.com/72379678/192286101-3e2da9a1-4dc2-46bd-9e40-aa823e824e30.jpeg)
![zammad_new](https://user-images.githubusercontent.com/72379678/192286103-bf3214cf-a300-4366-81ee-8829daa8df03.JPG)

**Comment by MrGeneration** [comment]
WARNING:
Please stop opening duplicate issues. The answer will not differ.

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by KamilTancula** [comment]
Hello,

I see the ticket has a status of closed but I also see an entry that the problem has been verified and the problem is classified as a bug. @rolfschmidt 
I would like to know if something will be done about this issue or however I should restore the system from before the update .

**Comment by MrGeneration** [comment]
> I would like to know if something will be done about this issue or however I should restore the system from before the update

Restore if applicable (and possible) and re-run the update. The issue will no longer appear.

For any further question regarding this, please consult the community.

**Comment by rolfschmidt** [comment]
> Hello,
> 
> I see the ticket has a status of closed but I also see an entry that the problem has been verified and the problem is classified as a bug. @rolfschmidt I would like to know if something will be done about this issue or however I should restore the system from before the update .

Hi @KamilTancula ,

If you can't rollback then go into your admin -> roles and remove the `ticket.agent` permission flag in all customer roles. You are right this is a bug and we fixed it with a follow up in https://github.com/zammad/zammad/issues/4243. 

It was a bug which happend for system with wrong permission configurations. So if you had a customer role with ticket groups configured (which only agents can have normally) then this role got accidentally the ticket.agent permissions by the migration. 

We fixed the migration a couple days ago (https://github.com/zammad/zammad/commit/53ca85439269f3beef5d2a87e9b10efbc1b32647) to remove the groups if no ticket.agent permission is given.  It was a inconsistent state which allowed potential security risks because a customer should not have group permissions. So we improved the dialog to reduce the wrong configurations as well.  Unfortunately you were one of the few users which upgraded in the short period where the migration was broken.

I'm sorry for the harsh answers in the beginning but my colleagues did not know about the situation. Thank you very much for your issues :)
