### ISSUE TITLE
Send Ticket Id in a http request to a specific url

### ISSUE THREAD

**Issue by AhmedElmehalawi** [zammad/zammad#4273]
I created a new attribute for ticket called "goTo"
I tried to make this field like a clickable url or a button but I couldn't manage to do so.
Workaround for this issue I tried to make its format text field with link template and in the link template I put the url I wanna redirect to

The question is how to send the ticket ID to this url

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
