### ISSUE TITLE
Problem syncing via Red Hat Satellite / Pulp3

### ISSUE THREAD

**Issue by SchnabeJ** [zammad/zammad#4280]
### Infos:

* Used Zammad version: 5.X
* Installation method (source, package, ..): rpm via yum/dnf from on-premise Red Hat Satellite server 
* Operating system: rhel 8
* Database + version: -
* Elasticsearch version: - 
* Browser + version: -

### Expected behavior:

* The Zammad Enterprise Linux repository (https://dl.packager.io/srv/rpm/zammad/zammad/stable/el/8/x86_64) should be mirrored/synced to our on-premise Red Hat Satellite server via Pulp 3 following a schedule. 

### Actual behavior:

* Pulp 3 is not able to sync the repo due to a problem with the metadata. 
* "Package id from primary metadata does not match package id from filelists, other metadata"
* The Red Hat support looked into the issue together with Pulp developers and found that pulp3 is trying to match the first pkgid from primary.xml.gz with the first pkgid from filelists.xml.gz  which will always fail so that this error makes sense.

### Steps to reproduce the behavior:

* Try syncing the Zammad repository via Red Hat Satellite / Pulp3

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
This is not an application issue or anything we have control of.

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
