### ISSUE TITLE
 Problem! No Entries on time accounting (Zammad)

### ISSUE THREAD

**Issue by ncaaaa** [zammad/zammad#4284]
Infos:

    Used Zammad version: 5.2.x
    Used Zammad installation type: (source, package)
    Operating system: CentOS Stream 8

Expected behavior:

    data ( Activity, Ticket, Customer, Organization) entered in time accounting

Actual behavior:
![gambar](https://user-images.githubusercontent.com/114985895/193771877-85505563-1686-46ca-a5f0-4ae1defb2f09.png)
![gambar](https://user-images.githubusercontent.com/114985895/193772004-b0783c6c-1b06-4b61-a7b2-5b6921834951.png)

**Comment by dominikklein** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer to the Zammad community over at: https://community.zammad.org/ .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
If you're paying customer already, please consult your Zammad support for assistance! :-)
