### ISSUE TITLE
 Problem! Time Accounting  no data entries available (Technical questions)

### ISSUE THREAD

**Issue by ncaaaa** [zammad/zammad#4288]
please help with this problem https://community.zammad.org/ .
Infos:

    Used Zammad version: 5.2.x
    Used Zammad installation type: (source, package, docker-compose, …)
    Operating system: CentOS Stream 8

Expected behavior:

    data ( Activity, Ticket, Customer, Organization) entered in time accounting

Actual behavior:

    No Entries
![gambar](https://user-images.githubusercontent.com/114985895/194260273-b97ed03f-d523-4f72-9ab9-5be7df597213.png)
![gambar](https://user-images.githubusercontent.com/114985895/194260334-c31b3740-252c-4038-b317-97f4a7b62792.png)

please help with this problem https://community.zammad.org/ .

**Comment by MrGeneration** [comment]
Warning: Stop posting the same technical question several times on this repo. You're abusing it.

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
