### ISSUE TITLE
Updating group settings causes huge numbers of delayed jobs

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4306]
### Infos:

* Used Zammad version:  develop / 5.3
* Installation method (source, package, ..): any
* Operating system: any 
* Database + version: any
* Elasticsearch version: any
* Browser + version: any

### Expected behavior:

Updating group settings like e.g. follow up settings do not cause a reindex of all Tickets of said group.

### Actual behavior:

Updating group settings like e.g. follow up settings cause a reindex of all Tickets of said group.

### Steps to reproduce the behavior:

* have a lot of tickets
* update any option from any group (I chose follow up setting and set the timeframe option)
* have a look at delayed jobs

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by rolfschmidt** [comment]
The reason for this is that the search index for each tickets contains data of related objects. The core problem here is that the ticket index excludes data (https://github.com/zammad/zammad/blob/ed8a6921ff15236a1605bdbce9a04d914f276d0b/app/models/concerns/has_search_index_backend.rb#L84) and because of that it can't be updated with one bulk update statement.

This is why it has to loop over all tickets related to the changed object (here group) to update each ticket object with one job (https://github.com/zammad/zammad/blob/ed8a6921ff15236a1605bdbce9a04d914f276d0b/app/models/concerns/has_search_index_backend.rb#L88).

One workaround would be to think about to remove the group that totally from the ticket search index. This would allow to skip the job creation. The question is do people search for tickets by group. However in long term the search index needs to be fixed in the way so that we can do bulk updates for ticket objects faster then now.

I have the same issue currently with another customer (Ticket#10114725) which is updating organizations heavily.

**Comment by MrGeneration** [comment]
I personally think that the group information is important, especially possible custom fields and its name. However, indexing the groups options on a per ticket basis is just extremely heavy if you want to adjust the settings due to a new option becoming available like with 5.3.

**Comment by rolfschmidt** [comment]
> I personally think that the group information is important, especially possible custom fields and its name. However, indexing the groups options on a per ticket basis is just extremely heavy if you want to adjust the settings due to a new option becoming available like with 5.3.

Yeah I think so too, it is also bad if we want to improve search features in the future, like a clickable search UI or something... 

We need to find a new way of updating tickets fast in the ticket search index or we need to think about including article attachments again:

https://github.com/zammad/zammad/blob/ed8a6921ff15236a1605bdbce9a04d914f276d0b/lib/search_index_backend.rb#L1086-L1089

If we would include the article attachments again in the search index, then it would be possible to use the existing bulk updating code to update tickets much faster without a high amount of jobs.

Downside would be that we need more space for the ES and it would be probably slower on `rake searchindex:rebuild`. But the slower argument is kinda fake because now you need 10k jobs every time if something changes which does not even work if you have more than 10k tickets and is also very slow.

If I remember correctly saving space was the initial reason for the exclude (correct me if I am wrong @martini)

**Comment by MrGeneration** [comment]
The reason why attachments might be excluded (even through they are searchable....) might be the payload size which is connected to that. Payloads have a limited size they may have on ES side - big tickets will likely fail due to this.

**Comment by rolfschmidt** [comment]
> The reason why attachments might be excluded (even through they are searchable....) might be the payload size which is connected to that. Payloads have a limited size they may have on ES side - big tickets will likely fail due to this.

My understanding of the exclude is the following:

I think the exclude is for the storage of the data. So e.g. the ticket will get indexed. The request will include the article attachments. Then I guess the ingest plugin will create a kind of shadow data which makes the attachments searchable of the ticket. Afterwards the data of the attachments get dropped.

If we now do a bulk update on the ticket index then the ticket data will not know it's attachments and loose the searchable attachment data of the ingest plugin on the bulk update. This would not happen without the exclude.

It has been a while since I debugged the situation last time. ES is pumping out a lot of releases, there might be a different solution which we not know of yet.

**Comment by shagr4th** [comment]
Hi !
With latest stable, I just noticed that each ticket creation will force the indexation of all the organization's tickets. Seems to be related to [this line](https://github.com/zammad/zammad/blob/stable/app/models/ticket/touches_associations.rb#L8), which triggers a touch at the end: it compares saved_changes[0] (which is empty), and saved_changes [1] (which is the new ticket's organization)

Is there a reason to trigger a touch at creation time ? To me the organization has not "changed" because it's the first time it is inserted in the tickets table

**Comment by rolfschmidt** [comment]
> Hi ! With latest stable, I just noticed that each ticket creation will force the indexation of all the organization's tickets. Seems to be related to [this line](https://github.com/zammad/zammad/blob/stable/app/models/ticket/touches_associations.rb#L8), which triggers a touch at the end: it compares saved_changes[0] (which is empty), and saved_changes [1] (which is the new ticket's organization)
> 
> Is there a reason to trigger a touch at creation time ? To me the organization has not "changed" because it's the first time it is inserted in the tickets table

The issue was there before, but because of some bug fixes it happens more often now. We are currently evaluating the new solution which will remove the potential creation of 1 job each organization ticket down to 1 job per organization update.

If you have bad performance issues and no time to wait for the upcoming release 5.3, and you want to help to test the optimized solution:

1. Update to latest stable zammad
2. `zammad run rails r "Setting.set('es_excludes', false)"`
3. `zammad run rake searchindex:rebuild`

If you do not want to take any risk, please be patient. We will have the problem fixed soon.

**Comment by shagr4th** [comment]
Thanks for the quick reply ! No bad performance issue right now (even if it's constantly indexing) but I'll try this solution
