### ISSUE TITLE
ldap integration Error

### ISSUE THREAD

**Issue by ticktostick** [zammad/zammad#4313]
* Used Zammad version:5.2.3
* Installation method (source, package, ..):package
* Operating system:ubuntu 20.04

### Expected behavior:
ldap source not showing 
start LDAP sync

### Actual behavior:
Error
PG::UndefinedTable: ERROR: relation "ldap_sources" does not exist LINE 8: WHERE a.attrelid = '"ldap_sources"'::regclass ^

### Steps to reproduce the behavior:

hit start new in ldap integration

also hit new source and create it again gives the same error

Then after signing out I cannot sign again

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
