### ISSUE TITLE
Ticket templates don't allow editing if obsolete attribtues are selected

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad#4316]
### Infos:

* Used Zammad version: develop 5.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: verified on current Firefox (Win)

### Expected behavior:

Ticket templates can be opened for editing to e.g. correct invalid selections.

### Actual behavior:

If a ticket template contains invalid values which are (no longer) available, Zammad does not allow to open them. This forces admins to remove said template and re-add it. This also affects cloning.

![image](https://user-images.githubusercontent.com/6549061/197801359-07264ec5-e382-447d-b6be-1731681cd7a0.png)

### Steps to reproduce the behavior:

* create e.g. a new field (select as example)
* use said field in your ticket template
* nuke the field
* try to edit your template

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by dvuckovic** [comment]
@MrGeneration I wasn't able to reproduce the reported behavior exactly, even though I followed the steps to the letter.

For me, the obsolete field does not prevent the edit modal from opening up, but I do get an empty select field where you would expect the old attribute to show up. This is also a bug, for sure, and we can handle it, but I never got the console error you reported for some reason.

Am I missing something?

**Comment by MrGeneration** [comment]
I cannot open several old migrated templates on our support instance at all.
I'm using Firefox on Windows and do receive above mentioned error when I'm trying to open it.

I did assume it's old values. Possibly also missing attributes. I don't know.

I did not expect to see the old value and am fine with an empty attribute.

**Comment by dvuckovic** [comment]
After some deeper digging, the root cause was identified as coming from some obsolete date and/or datetime fields with `nil` values in stored templates. For example, a quick template reproduction sample would be:

```
#<Template:0x000000000b925d78
 id: 41,
 name: "test me 1",
 options: {"ticket.title"=>{"value"=>"some title"}, "ticket.may_still_exist_but_is_an_empty_date_field"=>nil},
 updated_by_id: 3,
 created_by_id: 3,
 created_at: Wed, 02 Nov 2022 09:44:59.383064000 UTC +00:00,
 updated_at: Wed, 02 Nov 2022 09:47:55.773944156 UTC +00:00>
```

Normally, this would be caused by historical values only, as it is not possible anymore to save such a field via new management screen.

Additionally, a couple of related issues were identified:

* Last template migration results in an intermediate state which is a bit different than the expected one and can lead to problems. All attribute values must be in a form of `{ value: any }`, and not primitive or direct values. Auto-complete fields are also expecting an additional key in this structure under the name `value_completion`, instead of a separate `#{field}_completion` attribute.

* All stored unknown template attributes are still displayed as an empty line, which can quickly get out of hand. It would be better to simply skip rendering them in the GUI all together.

* Applying _falsy_ values via template like `0` or `''` might fail by coallescing to a string `[object Object]` in the GUI.

We will be handling this shortly, stay tuned.
