### ISSUE TITLE
CSRF token verification failed CAPROVER 

### ISSUE THREAD

**Issue by walderfranco** [zammad/zammad#4340]
Hi, I have caprover and zammad installed on AWS. since I placed the SSL to Zammad I can no longer log in to the app from the domain connected in caprover.

example:
subdomaincaprover.caprover.mypersonalsite.com - I can login as I am not logged out.

but if i go to added domain in caprover that has SSL.
zammad.mypersonalsite.com - I can't log in.

What have I done?
Modify the zammad_ssl.conf file as some tutorials say but I haven't been able to solve anything.

I need help.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
