### ISSUE TITLE
Telegram bot trigger

### ISSUE THREAD

**Issue by Stalker1995** [zammad/zammad#4344]
### Infos:

* Used Zammad version: 5.2.3

I'm trying to create a trigger to respond to a telegram request using the email example, but I can't select telegram send to the action

How it is possible to implement it, by means of triggers or it is not possible?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
