### ISSUE TITLE
Can't use Channel::Driver::Imap: #<Net::IMAP::NoResponseError: LOGIN failed.>

### ISSUE THREAD

**Issue by Bence98007** [zammad/zammad#4346]
### Infos:

* Used Zammad version: 5.2.3 latest
* Installation method (source, package, ..):
* Operating system: Debian 11
* Database + version: latest
* Elasticsearch version: latest
* Browser + version: not applicable

### Expected behavior:

IMAP continue to work with O365

### Actual behavior:

Hello there,
2 weeks ago, (probably when I updated to 5.2.3 open-source) IMAP disconnected and never received any more email tickets.
In the configuration, I've tried to login again, thrown error: `LOGIN failed.`
At the email settings I can see this error message:
`Can't use Channel::Driver::Imap: #<Net::IMAP::NoResponseError: LOGIN failed.>
`

Searched through the forums, and found that it was a bug in older version:
https://github.com/zammad/zammad/issues/3346
https://community.zammad.org/t/zammad-e-mail-setup-shows-login-failed/6101/8

Is this bug back again, or I'm doing something wrong?

**Comment by Bence98007** [comment]
I've tried to set up Microsoft 365 account, but it requires public callback URL, but my setup is a local instance with no incoming access from public internet.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
