### ISSUE TITLE
Missing localized translation for "is required/mandatory" error message for fields

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4378]
### Infos:

* Used Zammad version: 5.2.x
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket#10115919, #10134157

### Expected behaviour:

* When I don't enter a mandatory ticket field, the error message is localized.

### Actual behaviour:

* When I choose (e.g.) a pending state and don't fill the "pending till"-field, the error message is not localized:

![grafik](https://user-images.githubusercontent.com/97293098/203074214-ad6d6483-a7dc-474b-a3b4-a5cc307894ef.png)

### Steps to reproduce the behaviour:

* Use Zammad in another language than English. Choose "pending reminder" as the status and don't set a "pending till"-value.

Yes, I'm sure this is a bug and no feature request or general question.

**Comment by cautopartes** [comment]
Heads up: 
On a given occasion, we did some tests and noticed that those error messages seem to be tied to your operating systems' language settings. 

A customer wanted to change these messages back to English, because they were shown in German language. We could reproduce the situation with English and German localization settings on operating system level. The error messages corresponded to the configured language.

**Comment by mgruner** [comment]
@cautopartes this seems to be unrelated to the error that @YetAnotherGerrit describes here. For the pending time field, native browser field validation errors are *not* used. A fix is on the way.
