### ISSUE TITLE
Elasticsearch Rebuild extremely slow

### ISSUE THREAD

**Issue by XDjackieXD** [zammad/zammad#4379]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): docker-compose
* Operating system: Ubuntu 20.04.5 LTS
* Database + version: Postgresql 15.0
* Elasticsearch version: 8.5.0
* Browser + version: Firefox 106.0.5

### Expected behavior:

* After update run search index rebuild
* Have it finish rather quickly

### Actual behavior:

* Run search index rebuild
* Have it take over an hour for ~27000 tickets while the hardware is almost idle

### Steps to reproduce the behavior:

* Run `docker-compose exec zammad-railsserver rake zammad:searchindex:rebuild` on a Zammad instance with a good amount of tickets.

Yes I'm sure this is a bug and no feature request or a general question.

At least I would consider this a bug as it will lead to search being unavailable potentially for a day or more on large instances after version upgrades. We use this in a small company and just started using Zammad so we expect to run into this problem sooner or later, especially as our scheduled downtime for upgrades is limited.

As far as I can tell this is caused by sending an HTTP request to Elasticsearch for every single ticket instead of doing bulk inserts or even just persistent HTTP connections.
Our hardware is bored but the latency between the two docker containers (running on the same host) seemingly is enough to slow this down to "really slow".

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by XDjackieXD** [comment]
Imo this definitely is not a question.
I identified the root cause, possible fixes and it actively hinders larger deployements.
I did not ask a single question...

**Comment by MrGeneration** [comment]
It's a technical question or environment problem not a bug.
The more tickets you have the long you wait. Normal process.
