### ISSUE TITLE
Triggers don't fire when customer organization set to secondary org

### ISSUE THREAD

**Issue by t-shehab** [zammad/zammad#4394]
### Infos:

* Used Zammad version: 5.3
* Installation method (source, package, ..): any
* Operating system: any
* Database + version: any
* Elasticsearch version: any
* Browser + version: any
* Ticket#10118985

### Expected behavior:

* A trigger fires normally when the setting "Customer Orgainzation is specific organization" is set to a customer's secondary organization.

### Actual behavior:

* A trigger does NOT fire when the setting "Customer Orgainzation is specific organization" is set to a customer's secondary organization.

### Steps to reproduce the behavior:

* Configure a trigger like so (make sure to choose the Organization option under "Customer"):

![image](https://user-images.githubusercontent.com/114283486/203978656-5870e774-f7ed-48db-b22c-52c4f731c7d6.png)
* Open a ticket whose secondary organization is "secondary-test".

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by mgruner** [comment]
@t-shehab thank you very much for the report. With the exact same steps, the Trigger worked just fine for me locally. It probably was fixed in the meantime, even though I cannot say when.

Please feel free to reopen with more information if you can show that it is still not working in a more recent version of Zammad.
