### ISSUE TITLE
Trigger with State=Closed&Action=Updated conditions does not work

### ISSUE THREAD

**Issue by igodsewer** [zammad/zammad#4399]
### Infos:

* Used Zammad version: 5.2.3
* Installation method (source, package, ..): Package
* Operating system: Ubuntu Server 22.04
* Database + version: Postgres 12.12
* Elasticsearch version: 7.17.0
* Browser + version: Chrome 107.0.5304.121

### Expected behavior:

When a Customer replies to a closed ticket, he should be emailed with a warning, ticket status changed to "Opened" and its priority raised.

### Actual behavior:

Ticket is only reopened, seems like not by the trigger but rather with follow-up settings of its ticket group. That said, follow-up actions are applied before ticket action is checked against triggers, which seems like a bug.

### Steps to reproduce the behavior:

Create a trigger with:

State is closed
Action is updated
Sender is Customer
Type is email

![image](https://user-images.githubusercontent.com/5046970/204808877-23bf13c3-2026-4da3-8db5-1ffcd6cf218b.png)
![image](https://user-images.githubusercontent.com/5046970/204809004-44690cd9-ba42-4e46-ae27-347c2f483dab.png)

Email Zammad to create a ticket, then close the ticket. 
When its closed, reply to ticket from email to re-open it. 

Yes I'm sure this is a bug and no feature request or a general question.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
