### ISSUE TITLE
Overview grouping does not work with multi_tree_select

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4408]
### Used Zammad Version

5.3

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When you have a multi_tree_select-attribute and select more than one option the order in which you select them is relevant for the grouping in overviews.

![image](https://user-images.githubusercontent.com/5445062/216607687-24c751d4-c039-4365-8cf1-62e9486c9c7c.png)

### Expected behaviour

When you have a multi_tree_select-attribute and select more than one option the order in which you select them is **not** relevant for the grouping in overviews.

![image](https://user-images.githubusercontent.com/5445062/216607726-177b1df9-23fe-4f6b-80d4-780ca39ae8c7.png)

### Steps to reproduce the behaviour

Create a multi_tree_select-attribute.
Select at least two options in Ticket#A and select **the same** options in Ticket#B but in another order.
Create an overview with this multi_tree_select-attribute as "group by".
Ticket#A and Ticket#B are not grouped together even though they have exactly the same options selected.

### Support Ticket

Ticket#10111842

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
## EDIT: This was another approach but since there is already an existing grouping logic this makes no sense anymore. See further down.

---

### Current behavior

![image](https://user-images.githubusercontent.com/5445062/216556538-ecfd97c2-0b1c-4ce8-90b5-e1cffdc9250b.png)

### Expected behavior

I would say it would need to look like this right?

![image](https://user-images.githubusercontent.com/5445062/216556909-c3650769-b819-4c86-bc08-fb339868db3a.png)

### Problems

This might to lead to new issues because you basically have tickets shown multiple times. Bulk actions, Drag & Drop and sorting could be affected and definitely need to be tested afterward. Also not sure if the table implementation will support this properly. There might be a lot of rabbit holes on the way to the solution.

---

Are there more questions open to this @dominikklein / @KoJie ?

**Comment by YetAnotherGerrit** [comment]
The problem is actually if two tickets have both categories "B" and "B::B1", they **should** be grouped together. Regardless of what categories are selected first. But in reality, if you have Ticket X, which has categories "B, B::B1" and Ticket y, which has categories "B::B1, B" they will not be grouped together:

![grafik](https://user-images.githubusercontent.com/97293098/216601204-24170642-797c-4fa9-a7c1-5ee809534e7f.png)

For the grouping, it should not be relevant in what timely order you've selected the options.

**Comment by rolfschmidt** [comment]
> The problem is actually if two tickets have both categories "B" and "B::B1", they **should** be grouped together. Regardless of what categories are selected first. But in reality, if you have Ticket X, which has categories "B, B::B1" and Ticket y, which has categories "B::B1, B" they will not be grouped together:
> 
> ![grafik](https://user-images.githubusercontent.com/97293098/216601204-24170642-797c-4fa9-a7c1-5ee809534e7f.png)
> 
> For the grouping, it should not be relevant in what timely order you've selected the options.



That's the other way. So you would expect this outcome? I guess this way would be even easier

**Comment by rolfschmidt** [comment]
I will make a mockup for this approach as well... sec

**Comment by rolfschmidt** [comment]
@YetAnotherGerrit funny. So the grouping is actually already working kinda, but in some cases the sorting before is just missing so some values are dropping out? That would make the issue really simple:

![image](https://user-images.githubusercontent.com/5445062/216603199-73951733-ba3a-4d9e-a11c-bb8dbe618a38.png)

In my case it works. So if it would work always like this the issue would be solved for you @YetAnotherGerrit  ?

**Comment by YetAnotherGerrit** [comment]
Yes, I think it should be sorted before grouping. If this solves the issue.

**Comment by rolfschmidt** [comment]
After talking to @YetAnotherGerrit: There is already an existing grouping logic which is just a little broken.

Attached a good screenshot example in the top article: https://github.com/zammad/zammad/issues/4408#issue-1472950862

This removes the specification requirement because there is already an existing logic. The target of the issue is then to fix the existing logic, which means to check that the values are grouped properly even if they are selected in a different order in the ticket zoom. This is also the expected behaviour of the customer.
