### ISSUE TITLE
New ticket information is not visually displayed in the overviews as it is in the left sidebar

### ISSUE THREAD

**Issue by Suhopoljac** [zammad/zammad#4430]
### Used Zammad Version

5.3.0

### Environment

- Installation method: [e.g. source, package] any
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04] any
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3] any 
- Elasticsearch version: [e.g. 7.17] any 
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] - MS Edge, Version 108.0.1462.46 (Official Build) (64-bit)

### Actual behaviour

When a ticket has been updated in the left sidebar, the blinking circle to the left of the ticket title indicates new information. The same ticket displayed in the overviews has no such visual representation indicating the new information. 

### Expected behaviour

After receiving a new information in the ticket, I would expect the same visual representation with the coloured circle in the overviews. 

### Steps to reproduce the behaviour

Create a ticket --> reply to it and leave the tab in the sidebar --> while waiting for the reply, open the overview containing the before mentioned ticket --> after receiving the ticket update, 
compare the representation of the coloured circles on the left side. 

![Test1](https://user-images.githubusercontent.com/101350124/207858109-789ebb08-8c9a-4af9-8c6a-225f82e35fb4.jpg)

### Support Ticket

Ticket#10120533

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
