### ISSUE TITLE
SLA Escalation reminde e-mail sent on midnight rather than service times

### ISSUE THREAD

**Issue by xeruf** [zammad/zammad#4432]
### Used Zammad Version

5.0

### Environment

- Installation method: Debian package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian

### Actual behaviour

Similar to in https://github.com/zammad/zammad/issues/2157, wenn a ticket escalates through an SLA I get reminder e-mails at midnight CET and even on weekends, despite service times being set to Mo-Fr 9-17.

### Expected behaviour

Escalation reminders come during work hours

### Steps to reproduce the behaviour

Define an SLA, let a ticket escalate

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by xeruf** [comment]
Interestingly, I got no notification on Sunday

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by xeruf** [comment]
It is not a technical question, I am pretty sure this is a malfunction.

**Comment by MrGeneration** [comment]
Sorry I'm not here to discuss.
It's working as designed. Just because it behaves unexpected to you it doesn't make it a bug.
