### ISSUE TITLE
Zammad adopts white/light gray font color when copying a text in dark mode

### ISSUE THREAD

**Issue by MustafaTongul** [zammad/zammad#4445]
### Used Zammad Version

5.3.x

### Environment

- Installation method: Any
- Operating system Any
- Database + version:  Any
- Elasticsearch version: Any
- Browser + version: Chrome Version 108.0.5359.125 (Mac, Win & Linux)

### Actual behaviour

If a text is copied in Zammad within a ticket while the dark mode is active and the copied text is pasted into a new article and the ticket is updated, Zammad takes over the font color from the dark mode. If you now switch from dark mode to light mode, the new article is difficult to read, with a light gray font color on a white background.

https://user-images.githubusercontent.com/76220675/209126391-07138ad4-a904-477f-890d-8806e61a2f24.mp4

```
rails r 'pp Ticket::Article.find(404)' 

$ zammad run rails r 'pp Ticket::Article.find(404)' 
#<Ticket::Article:0x0000563e258bbcf8
 id: 404,
 ticket_id: 154,
 type_id: 5,
 sender_id: 1,
 from: "Anna Smith",
 to: "Bob Smith <bob@example.com>",
 cc: nil,
 subject: nil,
 reply_to: nil,
 message_id: nil,
 message_id_md5: nil,
 in_reply_to: nil,
 content_type: "text/html",
 references: nil,
 body: "This is a black font colour with white background",
 internal: false,
 preferences: {},
 updated_by_id: 3,
 created_by_id: 3,
 origin_by_id: nil,
 created_at: Wed, 21 Dec 2022 16:26:56.763000000 UTC +00:00,
 updated_at: Wed, 21 Dec 2022 16:26:56.763000000 UTC +00:00>
$
```

### Expected behaviour

If a text is copied in Zammad within a ticket while the dark mode is active and the copied text is pasted into a new article and the ticket is updated, Zammad ignores the font color from the dark mode. If you now switch from dark mode to light mode, the new article is legible with black font color on a white background.

### Steps to reproduce the behaviour

Copy an existing text within a ticket in Zammad while darkmode is active and paste it into a new article. Now switch to light mode.

https://user-images.githubusercontent.com/76220675/209126774-8fea5d12-fa8b-4aee-9e50-e1c443a5b19c.mp4

### Support Ticket

Ticket#10120769, #10120947,#10120386, #10121447, #10121615, #10121799, #10123059, #10123606

### I'm sure this is a bug and no feature request or a general question.

yes

### ToDo

- [x] Check current behaviour about copying the styles (also about the dark mode implementation) and also the usage of the reply/forward and the possibility to stripe styles during the copy.
- [x] Implement a clarified solution.
- [x] Testing

**Comment by dvuckovic** [comment]
This issue is specific to Chrome (not even Webkit-based Safari exhibits the reported behavior). Apparently, the computed style (text color in this case) is included in the clipboard HTML content and preserved when pasted in the richtext editor.

What was very strange (for me, at least) is that with the "dark" mode turned off, pasted text didn't contain the computed style with the dark gray text color, even though it was present in the clipboard. Further investigation identified the culprit: there is some extensive cleanup of the HTML happening during the paste action, and the dark gray text color value was simply part of the block list.

The most straightforward fix would be to include the new white/light gray color in the block list too.
