### ISSUE TITLE
Monospace Workaround not work anymore.

### ISSUE THREAD

**Issue by paulsen-it** [zammad/zammad#4446]
### Used Zammad Version

5.3

### Environment

- Installation method: zammad-docker-composer
- Database + version:  postgresql 10
- Browser + version: chrome 108

### Actual behaviour

Ticket #1055 says we must copy Monospace Text from LibreOffice to the Knowledge Base article to get Monospace text, because the Editor cannot do that. But this doesn't work anymore. This is very bad, we use the Knowledge Base also for Commands and short code snippets. Without Monospace Text, we cannot read the code. Please insert the Monospace feature in the Text Editor. It's so simple, but helps much people.

### Expected behaviour

mark text, and press a shortcut, and the Text shows with Monospace Font.

### Steps to reproduce the behaviour

Go to libreOffice, write Text, give the Text a monospace font, copy & paste the text to Knowledge Base. Monospace text is removed. Text is with normal font.

### Support Ticket

-

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Monospace in the editor and sanitizer still do work.

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
