### ISSUE TITLE
The X-Forwaded-For address is not used as session location inside docker containers

### ISSUE THREAD

**Issue by moritz-makandra** [zammad/zammad#4462]
### Used Zammad Version

5.3.0

### Environment

- Installation method: docker
- Operating system: ubuntu 20.04
- Database + version: 15.1-alpine
- Elasticsearch version: bitnami/elasticsearch:8.5.1
- Browser + version: chrome 109

### Actual behaviour

As location of the sessions the ip address of the nginx reverse proxy inside the docker container is displayed.

### Expected behaviour

The location should show the actual ip address of the user. This information is derived from the `X-Forwarded-For` header. 

### Steps to reproduce the behaviour

* Get the docker compose file form [zammad/zammad-docker-compse](https://github.com/zammad/zammad-docker-compose)
* Spin up the stack
* log in to zammad
* check the session location

### Support Ticket

123

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by moritz-makandra** [comment]
Looks like the `X-Forwarded-For` header is not used, because of the settings in `Rails.config.action_dispatch.trusted_proxies`.

The default here is set in the [docker-entrypoint.sh](https://github.com/zammad/zammad/blob/76e0e6fae53647e7e5465f34cc24378a30209c92/contrib/docker/docker-entrypoint.sh#L24) script to localhost only.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
