### ISSUE TITLE
Trigger condition does not allow to use a field twice – possible regression

### ISSUE THREAD

**Issue by Signum** [zammad/zammad#4491]
### Used Zammad Version

5.3.1-1675806064.85c9455d.bullseye

### Environment

- Installation method: Debian Package
- Operating system: Debian 11
- Database + version:  PostgreSQL 13
- Elasticsearch version: 7.17.6
- Browser + version: Chromium 109.0.5414.119

### Actual behaviour

A field can only be used once as a trigger condition. After using it in one condition it is grayed out and can not be used in another condition.

### Expected behaviour

Allow a field to be used in multiple conditions. Current example:

- field1 has changed
- field1 is XYZ

So the trigger only fires when the field1 has changed and its new value is XYZ.

### Steps to reproduce the behaviour

- Create a new trigger
- Add a condition "Title – has changed"
- Add another condition "Title …"
- Realize that the "Title" field cannot be chosen because it is grayed out.

This might be a regression from #2185

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by MrGeneration** [comment]
AND/OR is scheduled for 5.4 which is not yet released.

**Comment by Signum** [comment]
Thanks for the swift reply. Seems I misunderstood #2185
