### ISSUE TITLE
Note not saved gets added to answer

### ISSUE THREAD

**Issue by cottton** [zammad/zammad#4496]
### Used Zammad Version

5.3.1

### Environment

- Installation method: docker
- Operating system (if you're unsure: `cat /etc/os-release` ): NA
- Database + version:  irrelevant
- Elasticsearch version: irrelevant
- Browser + version: latest google chrome on different machines. Also safari.

### Actual behaviour

When writing into the internal note -box
but not saving changes yet
and then clicking on answer to a previous post (article?)
then the internal note -text gets added to the answer.

When now saving changes the internal note will be sent to the customer. _(I tested this.)_

See screenshots.
![1](https://user-images.githubusercontent.com/13582504/218865332-1651ad73-2fea-4a06-8a62-e6fda8fd0d50.png)
![2](https://user-images.githubusercontent.com/13582504/218865335-34fa87e9-011d-4287-b5a1-a6370db6c218.png)

### Expected behaviour

Expected to NOT add internal text into the answer.

### Steps to reproduce the behaviour

See actual behaviour.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
