### ISSUE TITLE
CentOS installer should accept Plesk nginx package

### ISSUE THREAD

**Issue by mjh1709muc** [zammad/zammad#4500]
### Used Zammad Version

5.3

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): AlmaLinux 8.7 + Plesk 18.0.50
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

CentOS installer aborts with:

```
Problem: problem with installed package sw-nginx-1.20.2.1-2.redhat.8+p18.0.50.2+t230213.1226.x86_64
  - package sw-nginx-1.20.2.1-2.redhat.8+p18.0.50.2+t230213.1226.x86_64 conflicts with nginx provided by nginx-1:1.14.1-9.module_el8.3.0+2165+af250afe.alma.x86_64
  - package zammad-5.3.1-1675259950.8ebe3877.centos7.x86_64 requires nginx, but none of the providers can be installed
  - cannot install the best candidate for the job
  - package nginx-1:1.16.1-2.module_el8.4.0+2470+68135136.1.alma.x86_64 is filtered out by modular filtering
  - package nginx-1:1.18.0-3.module_el8.4.0+2472+f736ed63.1.alma.x86_64 is filtered out by modular filtering
  - package nginx-1:1.20.1-1.module_el8.6.0+2782+a022aca3.alma.x86_64 is filtered out by modular filtering
```

Plesk is installed on the system, so nginx package got replaced with the Plesk package sw-nginx-xxx.

### Expected behaviour

Should also accept sw-nginx-1.20.2.1-2.redhat.8+p18.0.50.2+t230213.1226.x86_64 package.

### Steps to reproduce the behaviour

clean install.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
I'm gonna close this as technical question, because this most likely is an issue with your package manager which might be related to Plesk doing things as well. We clearly demand nginx as dependency - nothing more and nothing less.
https://github.com/zammad/zammad/blob/develop/.pkgr.yml#L25

If your package manager doesn't resolve that cleanly, that's very much out of our control.
I wouldn't suggest anyone to install Zammad on a Plesk host or similar because these tools fiddle a lot and very deep in your system and may actually cause down times to broken environments.

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
