### ISSUE TITLE
Writing into the text area at the bottom of a ticket creates a note instead of sending a reply email.

### ISSUE THREAD

**Issue by mak-dunkelziffer** [zammad/zammad#4537]
### Used Zammad Version

5.3

### Environment

irrelevant

### Actual behaviour

Writing into the text area at the bottom of a ticket **CREATES A NOTE**.

This is the worst UI possible. You accidentally create a note instead of sending a reply and then close the ticket, thinking you are done. Your customer will think you are the worst, most unreliable company for not responding to them.

**This UI flaw undermines the base purpose of the software. Therefore I categorize this UI flaw as a bug.**

### Expected behaviour

The text area should SEND AN EMAIL REPLY.

Or even better: give us two buttons:
- a tiny outline button (https://getbootstrap.com/docs/4.0/components/buttons/#outline-buttons)  for taking a note
- a huge colored primary button for sending a reply

Both then open a text area.

### Steps to reproduce the behaviour

see "Actual behaviour"

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by mak-dunkelziffer** [comment]
LOL

**Comment by Dennis1993** [comment]
If you click on REPLY on the first post (it is below of the box/content) you can send an email and close the ticket if you want?! 😂
What is the problem?
