### ISSUE TITLE
Install incompatibility with Elasticsearch

### ISSUE THREAD

**Issue by vmunene** [zammad/zammad#4549]
### Used Zammad Version

5.4

### Environment

- Installation method: Package and Source
- Operating system: ubuntu 20.04
- Database + version: postgresql 12
- Elasticsearch version: 7.17
- Browser + version: firefox 111

### Actual behaviour

zammad run rake zammad:searchindex:rebuild Fails with 
zammad Unable to process put request to elasticsearch URL 'http://localhost:9200/_production_chat_session'

### Expected behaviour

run rake should process indexes

### Steps to reproduce the behaviour

Install elasticsearch and zammad.
run "zammad run rake zammad:searchindex:rebuild"

Note the problem is on Fresh install, upgrade from previous version works fine

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
