### ISSUE TITLE
Usage of articles in webhooks payload

### ISSUE THREAD

**Issue by fliebe92** [zammad/zammad#4565]
Webhooks are using articles in the payload.

It should be possible to decide in the webhook itself if the payload includes the article or not.

Use Case: 

* The article content contains confidential data.
* The article content is very long.

#### Implementation

It could be a new dropdown field in the webhook form, where it can be selected if the article should be present or not.

When the article should not be present, it needs to be set to empty, so that it will not be present in the default payload and also not in any used article variable from the custom payload (and also inside the used notifications).

**Comment by dominikklein** [comment]
When we make the custom payload field not readonly inside a predefined webhook, this change here is maybe not needed, because the current use case is about the notifications and then this can be edited during the creation inside the custom payload field.

Or is there for example a use case that the default payload should not include article data and always only the ticket data?

**Comment by mantas** [comment]
Closing as no longer relevant. Admins can achieve the same by using custom payload.

**Comment by mantas** [comment]
related MR with discussion https://git.zammad.com/zammad/zammad/-/merge_requests/5618
