### ISSUE TITLE
Chat fails to automatically generate host for WebSocket

### ISSUE THREAD

**Issue by cubehrends** [zammad/zammad#4566]
### Used Zammad Version

5.4.0

### Environment

- Installation method: none (subdomain.zammad.com)
- Operating system (if you're unsure: `cat /etc/os-release` ): Linux Mint 20.3 (Una)
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version:Google Chrome 112.0.5615.49 (Official Build) (64-bit)

### Actual behaviour

When loading additional scripts with https://subdomain.zammad.com/assets/chat/chat.min.js an error occurs while creating a WebSocket:
![image](https://user-images.githubusercontent.com/19872314/230363889-545eee1f-4a13-431c-8cac-dfd93c91c38d.png)
Passing the "host" param like mentioned here does not help either.
![image](https://user-images.githubusercontent.com/19872314/230364320-82fb8958-60f6-400a-af4c-bf972d198e57.png)

### Expected behaviour

We expect the Chat to work when additional scripts are loaded externally.

### Steps to reproduce the behaviour

1. Correctly Implement Chat into WordPress-Website
2. Load additional scripts (like https://app.ewebinar.com/widget.js)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
I'm leaving this to the one that verifies the issue. From my opinion this technically is a question because this most likely is a configuration or combination issue with the website in question.

**Comment by dominikklein** [comment]
Hi @cubehrends 

I could not reproduce the problem. This seems to be a technical question.

Did you already check that it's working without the additional script? 

Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org/ .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
If you're paying customer already, please consult your Zammad support for assistance! :-)

**Comment by cubehrends** [comment]
Hi @dominikklein 

we've verified this to be a reproducible bug. You can check the issue yourself at https://www.kim-bewertung.de/ via privacy settings:

Essential Cookies Only (additional external scripts blocked): Zammad-Chat working as expected
External Media Consented (additional external scripts loaded): 
![image](https://user-images.githubusercontent.com/19872314/233007688-5a7586b0-4c82-4a5d-bd46-fc766fcc6ba9.png)

I hope this bug report will help you in bettering your software.
