### ISSUE TITLE
disabled user can create ticket with telegram bot

### ISSUE THREAD

**Issue by EBII** [zammad/zammad#4572]
### Used Zammad Version

5.4

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

after censor user with (close & spam) the user can still use the telegram channel. 

### Expected behaviour

not ticket create or completed 
may be uncensored it for new access

### Steps to reproduce the behaviour

new user create ticket in telegram channel, 
Close & spam (the user is censored )
user can still use telegram channel

![image](https://user-images.githubusercontent.com/4985100/232023764-e60ffd9e-dd69-4919-96c3-54d22a6a9fa9.png)

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
