### ISSUE TITLE
CSRF token verification failed!

### ISSUE THREAD

**Issue by BacNTb** [zammad/zammad#4587]
### Used Zammad Version

5.4.1

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

I have successfully installed and changed a little bit of configuration in the information system like Fully Qualified Domain Name and HTTP type and changed the logo, and the organization name can't log in anymore, an error occurs. CSRF token verification failed!. I don't know what is going wrong. Help

### Expected behaviour

a

### Steps to reproduce the behaviour

a

### Support Ticket

Ticket#123

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
