### ISSUE TITLE
Reauthenticating an existing Microsoft365 channel with the wrong email account changes the used email address

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#4607]
### Used Zammad Version

5.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

I have set up a Microsoft 365 email account in Zammad, and re-authenticate the email account with a different Microsoft 365 email account. The re-authenticate works as expected, but when I email the second Mocrosoft 365 account, Zammad opens a ticket from that email. Even if the second account is not setup in Zammad.

### Expected behaviour

Expected behavior would be that Zamamd block the second mail account completely, since it is not setup in Zammad. 

### Steps to reproduce the behaviour

- Add a Microsoft 365 email account to your Zamamd, example: support@yrczf.onmicrosoft.com
- go to admin > channels > Microsoft 365 > click on re-authenticate support@yrczf.onmicrosoft.com
- use a different mail account when performing the re-authenticate, example: adelev@yrczf.onmicrosoft.com
- send an email to adelev@yrczf.onmicrosoft.com, Zammad will fetch all email from this account now! *DANGER*

for more detail, please see following screencast:
[Screen Recording (12.05.2023 14-22-06).wmv.zip](https://github.com/zammad/zammad/files/11463835/Screen.Recording.12.05.2023.14-22-06.wmv.zip)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
We would like to understand why this is labeled as `data loss`. Any opinion on that?

Furthermore, how to fix this properly? Should we simply not update the channel with the changed mail address or should we show a modal dialog explaining that the reauthenticate was not successful due to a not matching mail address?

Thanks for your input :)

**Comment by MrGeneration** [comment]
> We would like to understand why this is labeled as data loss. Any opinion on that?

Because you loose another accounts mail data if e.g. the channel is configured to "keep messages on server = false".
This means a user accidentally might clear another mailbox due to re-authenticate not ensuring the same account is being used for that process.

Even worse: Setting an channel to inactive if you notice will still cause Zammad to fetch email until the scheduler reloads / comes to the security threshold. This means this action is not immediate (unless you can kill the scheduler process which e.g. in SaaS is not possible for customers). 

> Furthermore, how to fix this properly? Should we simply not update the channel with the changed mail address or should we show a modal dialog explaining that the reauthenticate was not successful due to a not matching mail address?

You could make this a warning like "we noticed your email account seems to differ from what you want to re-authenticate. Are you *certain that you're using the right mailbox to authenticate??"

With options like [yes proceed](danger) and [cancel]

**Comment by fliebe92** [comment]
Thanks, @MrGeneration, I was thinking in the same direction, just wanted to be on the same page.

**Comment by fliebe92** [comment]
@KoJie, @martini> We need to discuss the solution for this issue report in the team.

**Comment by martini** [comment]
> @KoJie, @martini> We need to discuss the solution for this issue report in the team.

Yes. My proposal is just show a error message if re-authenticate is done with wrong/different user.

**Comment by fliebe92** [comment]
We would like to show a modal if a different user was used for the re-authentication and abort the re-authentication process in Zammad.
