### ISSUE TITLE
Zammad: _core_workflow: error

### ISSUE THREAD

**Issue by forgeOneHQ** [zammad/zammad#4633]
### Used Zammad Version

5.4.1-1685652268.d074a0f4.jammy

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): ubuntu 22.04.1
- Database + version:  14.8-0ubuntu0.22.04.1
- Elasticsearch version: 7.17.10
- Browser + version: Brave v1.52.117

### Actual behaviour

Cannot update tickets, always requests a reminder date and time.

```
application-ad05a57d…10eadeeeb1894.js:23 App.i(error)                   | update 
{_core_workflow: {…}}
_core_workflow
: 
controllerForm
: 
i {formGen: ƒ, html: ƒ, hideAlert: ƒ, showAlert: ƒ, dispatchHandlers: ƒ, …}
target
: 
span
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__
: 
(...)
get __proto__
: 
ƒ __proto__()
set __proto__
: 
ƒ __proto__()
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__
: 
(...)
get __proto__
: 
ƒ __proto__()
set __proto__
: 
ƒ __proto__()
````

### Expected behaviour

Update tickets without error or requesting date and time set, when it is not set to "waiting for closing/reminder".

### Steps to reproduce the behaviour

Just updated from previews build of 5.4.1

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by fliebe92** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org/ .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
If you're paying customer already, please consult your Zammad support for assistance! :-)
