### ISSUE TITLE
 Issue with capturing responses in mobile view after Version 6 update

### ISSUE THREAD

**Issue by projektug24** [zammad/zammad#4639]
### Used Zammad Version

6.0

### Environment

Package Installer
Debian 11.7
10.5.19-MariaDB-0+deb11u2
Chrome (iOS), Safari (iOS), Firefox (iOS), Chrome  113.0.5672.129 (Web)

### Actual behaviour

Dear community,

After updating to version 6, I'm facing an issue where no responses can be recorded under the mobile view. The page doesn't load, and shortly after, the message "The connection to the server was lost" appears.

In the zammad.conf file located at /etc/apache2/sites-enabled, I have added the following:

ProxyPass /cable ws://127.0.0.1:3000/cable

And Redis Server is running.
![lost_connection](https://github.com/zammad/zammad/assets/55640523/69d9774d-abb1-46f9-9706-2558bb74384b)

### Expected behaviour

that it works :)

### Steps to reproduce the behaviour

[config.txt](https://github.com/zammad/zammad/files/11668108/config.txt)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
The order of directives usually is very important in many scenarious.
You may want to adapt to the contrib version:

https://github.com/zammad/zammad/blob/develop/contrib/apache2/zammad_ssl.conf#L48-L52

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
