### ISSUE TITLE
zammad upgrade to 6.0

### ISSUE THREAD

**Issue by dno-digiserv** [zammad/zammad#4642]
### Used Zammad Version

6.0

### Environment

- Installation method: Package
- Operating system: Centos 8
- Database + version:  PostgreSQL 14.8
- Elasticsearch version: 7.17.10-1
- Browser + version: mobile, any

### Actual behaviour

when opening ticket on mobile I get the following:

`
We're sorry, but something went wrong. Received message: undefined method `name' for #<EmailAddress id: 3, channel_id: 5, realname: "Kundesupport", email: "support@******.no", active: true, note: "", preferences: nil, updated_by_id: 12, created_by_id: 12, created_at: "2023-02-09 19:03:03.238000000 +0000", updated_at: "2023-02-09 19:10:03.536000000 +0000">
`

this only happens when on new mobile view, not on desktop ui.

### Expected behaviour

ticket opens when tapped.

### Steps to reproduce the behaviour

upgrade to 6.0 and open a ticket on mobile

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dno-digiserv** [comment]
this might not be relevant, but for others, seems this didn't fire:

/opt/zammad/contrib/packager.io/postinstall.sh

if it's a manual step I probably missed it in the docs, but have double checked and from what I can tell they are not specified in the update pages.

**Comment by fliebe92** [comment]
Hi @dno-digiserv,

the issue you reported is caused by an incomplete migration to Zammad 6.0. I guess you updated all packages on your server and by doing this, e.g. PostgreSQL was updated as well and this caused the Zammad migration to fail. It would be sufficient to execute the migration again (`zammad run rake db:migrate`), then everything should be fine.

Files located in `contrib/packager.io` is just there because we're using packager.io to create official packages of Zammad :)

**Comment by dno-digiserv** [comment]
thank you for the heads up and better solution.

Found a comment on an unrelated issue on the forum that referenced the postinstall script, but the db:migrate would have been better :)

**Comment by MrGeneration** [comment]
> Found a comment on an unrelated issue on the forum that referenced the postinstall script, but the db:migrate would have been better :)

The postinstall gets references by me all the time because most of the times users don't provide the log output of their update. So you don't know where it died. The postinstall ensures that all update procedures are run - including the db migration.

> if it's a manual step I probably missed it in the docs, but have double checked and from what I can tell they are not specified in the update pages.

It's part of the update installation and called automatically by your package manager. If the documentation is followed correctly -and- did not throw any error, this manual step is not needed at all.
