### ISSUE TITLE
Creating Ticket is not working

### ISSUE THREAD

**Issue by amirburi** [zammad/zammad#4650]
### Used Zammad Version

6.0.x.2cdc3c3e7.saas

### Environment

- Installation method: [e.g. source, package] saas
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: Chrome 114.0.5745.61/Android

### Actual behaviour

Unable to create new ticket

### Expected behaviour

Be able to create new ticket. Spinner is shown all the time.

<img width="516" alt="Screenshot 2023-06-12 at 15 45 20" src="https://github.com/zammad/zammad/assets/100340766/c159958e-0ccf-43bb-aaf1-de10f1f5fc45">

### Steps to reproduce the behaviour

Try to create a ticket

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by amirburi** [comment]
> If you're paying customer already, please consult your Zammad support for assistance! :-)

I pay. Your software is not working! Fuck!

**Comment by amirburi** [comment]
I WANT TO REPOPEN THIS ISSUE! ITS YOUR BUG!

**Comment by MrGeneration** [comment]
> I pay. Your software is not working! Fuck!

As I said: If you're a paying customer, kindly contact SaaS support.
We cannot help you with public issues. I cannot investigate this issue if I don't have a ticket to it (an issue is no ticket).

If you don't know how to contact Zammad, see:
https://zammad.com/en/company/contact

**Comment by amirburi** [comment]
I just want to point out errors to you but my effort is not appreciated. I pay. But why do I have to write privately. It is open source! Then I let it stay.

**Comment by MrGeneration** [comment]
> I just want to point out errors to you but my effort is not appreciated. I pay. But why do I have to write privately. It is open source!

You just don't understand that it's not a bug but either infrastructural (your end) or a configuration issue on our end.
I cannot help you without identifying you. For this, please create a support ticket!

**Comment by dominikklein** [comment]
@amirburi I think nobody is saying that we will not create a public issue when there is really a bug and that your effort is not appreciated. But first, it needs to be clarified with the support what could be the root cause of the problem for your single system, because we didn't see it before. When afterward there is a clear bug visible, we will create a public issue about this :-)
