### ISSUE TITLE
Make path of auto_wizard.json configurable

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#4671]
Currently auto_wizard.json has to be copied into zammads root dir to use it.

That can be problematic in container setups, where the container filesystem is set to read only.

Therefore it would be nice if the file could be used from another path, so a volume mount can be used to write the file there.

Path could be set via env var for example or maybe even the entire file could be read from env.

**Comment by mgruner** [comment]
@monotek what about checking first in `var/`, before checking in Zammad's root directory? Then we don't need any additionial `ENV`s.

**Comment by monotek** [comment]
That would work too :)

By the way. 
What happens if the file is still there on a restart (because /var would be persisted), if it was already applied?

**Comment by mgruner** [comment]
Well the AutoWizard should remove the file after it ran, so that it would be gone again, unless that the containers create it again. That would seem appropriate in `var/` IMHO.

It does also have safeguards against being executed on an already configured system. And it's started from the browser only, right. So do you see any issues there?

**Comment by monotek** [comment]
No, just wanted to get sure thats no problem :)

**Comment by mgruner** [comment]
So we actually went with a new ENV variable `AUTOWIZARD_RELATIVE_PATH` that can be used to set a path other than Zammad's root directory. Backport will arrive soon.

**Comment by monotek** [comment]
Thanks a lot! :)
