### ISSUE TITLE
Cannot change organisation of ticket

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#4744]
### Used Zammad Version

6-develop

### Environment

SaaS
- Browser + version: Edge 115.0.1901.188 (Offizielles Build) (64-Bit)

### Actual behaviour

When trying to change the customer of a ticket (more specifically the organisation), the modal dialogue does not react to the "submit"-click.

![image](https://github.com/zammad/zammad/assets/97293098/c43b34b3-7a3d-44f9-aac7-570a9c8b76dc)

```
E, [2023-08-09T09:38:21.667538#7756-5660] ERROR -- : Error performing Core Workflow engine.
E, [2023-08-09T09:38:21.667580#7756-5660] ERROR -- : undefined method `id' for nil:NilClass

    user.group_access?(record.group.id, access)
                                   ^^^ (NoMethodError)
app/policies/ticket_policy.rb:87:in `agent_access?'
app/policies/ticket_policy.rb:57:in `agent_update_access?'
app/models/core_workflow/custom/ticket_time_accounting_check.rb:21:in `available_for_user?'
app/models/core_workflow/custom/ticket_time_accounting_check.rb:17:in `enabled?'
app/models/core_workflow/custom/ticket_time_accounting_check.rb:5:in `saved_attribute_match?'
app/models/core_workflow/condition/match_all_modules.rb:13:in `block (2 levels) in match'
app/models/core_workflow/condition/match_all_modules.rb:10:in `each'

```

### Expected behaviour

I can change the organisation of a ticket.

### Steps to reproduce the behaviour

- Activate the time accounting feature
- Go inside an existing ticket
- Try to change the customer

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by Koppishop** [comment]
Used Zammad Version
6-develop

Environment
SaaS

Browser + version: Chrome Version 115.0.5790.171 (Offizieller Build) **(64-Bit)**

Actual behaviour
When trying to change the customer of a ticket, the organization selector appears (even if no secondary organization is available). It is possible to select the organization, but changes can not be saved. At the end, no ticket.customer can be changed anymore

Expected behaviour
I can change the customer/organisation of a ticket.

Steps to reproduce the behaviour
Try to change the ticket.customer of a ticket in SaaS - develop branch.
Changed the ticket.customer and/or ticket.organization works in any other hosted test instance
