### ISSUE TITLE
Core workflow "is"/"is not" conditions are not working for custom select fields

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad#4752]
### Used Zammad Version

6.0.1

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When I use the "is"/"is not" conditions with a custom object attribute from type "select" in core workflow it's not working correctly. Only when I use a fixed field like type it's working like expected.

https://community.zammad.org/t/bug-core-workflow-set-to-not-considering-previously-worked-with-objects

### Expected behaviour

It should be possible to use the "is"/"is not" conditions with a custom object attribute from type "select" in core workflow.

### Steps to reproduce the behaviour

- Create two object attributes from type select with some options (e.g. service and incident type).
- Create following core workflows (activate the type field or use only the custom field inside the conditions):

![Bildschirmfoto 2023-08-09 um 13 34 22](https://github.com/zammad/zammad/assets/5445094/6e768464-d2a0-47a7-bb65-f6248294644b)
![Bildschirmfoto 2023-08-09 um 13 34 09](https://github.com/zammad/zammad/assets/5445094/4fd65691-f516-4f7b-a1a7-3e0cc025c674)

- Go to the ticket create screen and see that the "Incident Type" field will not be visible after the conditions should match.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by bahusafoo** [comment]
So I found something in addition to the custom select fields that may be contributing to my specific case.

Context: Each org in my environment will have 4 groups: Information Technology, Maintenance, Materials Management, Human Resources - we don’t want other orgs’ groups showing for end-users outside those orgs - in theory this should all work well.

I have a workflow early (priority 1) on that removes all groups from the group selection, and another (priority 2) that adds specific ones back later on based on the user’s organization (The specific named groups mentioned above that are named after their specific org).

In my testing, it appears that once a group is removed and added back, its value is no longer considered in core workflow logic in later workflows down the line of priority. Removing the step that removes them, and changing the org specific filtered workflow to instead remove all other groups vs adding back the org’s specific groups allows it to work, as the group is never removed and then added back.

I hope this makes sense.

**Comment by fliebe92** [comment]
Hi @bahusafoo.

> In my testing, it appears that once a group is removed and added back, its value is no longer considered in core workflow logic in later workflows down the line of priority. Removing the step that removes them, and changing the org specific filtered workflow to instead remove all other groups vs adding back the org’s specific groups allows it to work, as the group is never removed and then added back.

Could you please share a screenshot of the mentioned Core Workflows? Thanks a lot.

**Comment by rolfschmidt** [comment]
@dominikklein + @bahusafoo:
please provide more information how to reproduce this. I tested this on stable and it works fine. Maybe you just forgot to adjust the priority of core workflows so the hide one runs last or your list is not alphabetically if the priority is the same, I can't tell from the screenshots because they are cut. Please provide FULL screenshots of your field configuration and your core workflows to make this reproducible. Btw. The part with the add_option makes logically no sense, just that you know.

[screen-recorder-tue-aug-15-2023-09-27-51.webm](https://github.com/zammad/zammad/assets/5445062/94f7fffe-756c-4d02-b8d8-78f0480c2394)

**Comment by bahusafoo** [comment]
@rolfschmidt @fliebe92 Hello - I created a video outlining this - I think it's easier to just demonstrate what's going on.  I did figure out the issue occurs when removing an option from an object using the "remove option" in a core workflow and then adding it back using the "add option" action in a later core workflow - this happens for both the built-in objects as well as custom objects (I show this all in this video).  The issue is not with priorities - I clearly have them set in the right order.

As a workaround, we can use a method where instead of removing everything up front and adding what the user should see as we go, we remove everything we don't want them to see as we go.  This works currently, but this is not ideal, as it's harder to maintain this way - I'd rather add options I want as I add them than have to remember to go remove any new options we may add later on from every core workflow.  

So a simplified recreation of this: 

1. add a text object "test input" 
2. add a single select object "test selection" with values a b c d e f g
3. in core workflows make a priority 1 workflow that removes all those options from the obect
4. in another workflow priority 2 add b d f back to the object
5. add a priority 3 core workflow that displays "test input"  if "test selection" is b or d.  
6. Test this as a customer (it won't ever show "test input"). 
7. Now go back, change the priority 1 core workflow to instead only remove only a c e g (instead of all options) - now go try it again, it will now display "test input" correctly.
Something about an option being removed prevents it from being considered in "is/is not" logic even if it's re-added before that logic occurs.

https://www.youtube.com/watch?v=xGeXrh4_RZ8

**Comment by rolfschmidt** [comment]
> @rolfschmidt @fliebe92 Hello - I created a video outlining this - I think it's easier to just demonstrate what's going on. I did figure out the issue occurs when removing an option from an object using the "remove option" in a core workflow and then adding it back using the "add option" action in a later core workflow - this happens for both the built-in objects as well as custom objects (I show this all in this video). The issue is not with priorities - I clearly have them set in the right order.
> 
> As a workaround, we can use a method where instead of removing everything up front and adding what the user should see as we go, we remove everything we don't want them to see as we go. This works currently, but this is not ideal, as it's harder to maintain this way - I'd rather add options I want as I add them than have to remember to go remove any new options we may add later on from every core workflow.
> 
> So a simplified recreation of this:
> 
> 1. add a text object "test input"
> 2. add a single select object "test selection" with values a b c d e f g
> 3. in core workflows make a priority 1 workflow that removes all those options from the obect
> 4. in another workflow priority 2 add b d f back to the object
> 5. add a priority 3 core workflow that displays "test input"  if "test selection" is b or d.
> 6. Test this as a customer (it won't ever show "test input").
> 7. Now go back, change the priority 1 core workflow to instead only remove only a c e g (instead of all options) - now go try it again, it will now display "test input" correctly.
>    Something about an option being removed prevents it from being considered in "is/is not" logic even if it's re-added before that logic occurs.
> 
> https://www.youtube.com/watch?v=xGeXrh4_RZ8

@bahusafoo I verified this and created a new Issue (https://github.com/zammad/zammad/issues/4763). 

Not sure what to do with this issue (https://github.com/zammad/zammad/issues/4752). In my opinion, it is not reproducible and should be closed.
