### ISSUE TITLE
Upvoting #330 is not possible

### ISSUE THREAD

**Issue by sleuny** [zammad/zammad#4765]
Hey, its not possible to upvote in #330 as suggested.

_Originally posted by @MrGeneration in https://github.com/zammad/zammad/issues/330#issuecomment-447055502_

**Comment by MrGeneration** [comment]
That's because it has been bumped too much.

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
