### ISSUE TITLE
Security type selector overlaps label

### ISSUE THREAD

**Issue by sheremet-va** [zammad/zammad#4770]
### Used Zammad Version

6.1

### Environment

- Installation method: source
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

The selector between "PGP" and "S/MIME" overlaps"Security" label (in the example security is long, but it happens regardless of the length) .

![Screenshot 2023-08-21 at 11 49 13](https://github.com/zammad/zammad/assets/16173870/bbbcfdff-9693-4c06-9553-870e3e13829c)

### Expected behaviour

Buttons don't overlap.

### Steps to reproduce the behaviour

- Have both PGP and S/MIME configured
- See the overlap

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by gwingend** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail.
Ich bin nicht im Büro.
Ihre Mail wurde weder gelesen noch weitergeleitet.

Bitte wenden Sie sich in dringenden Fällen an den EDV-Helpdesk ***@***.***).


Mit freundlichen Grüßen
Gerhard Wingender
Amt für IT

>>> zammad-sync ***@***.***> 22.8.23 08:18 >>>

Closed #4770 as completed via 566fe287a52bd06a66127a4690d4efb65a89f99e.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/zammad/zammad/issues/4770#event-10153687218
You are receiving this because you are subscribed to this thread.

Message ID: ***@***.***>
-- 
Diese E-Mail wurde von Sophos UTM auf Viren überprüft.

Besuchen Sie uns im Internet unter: www.neuwied.de
oder bei Facebook @neuwied.de
und Instagram @deichstadt_neuwied

Eine E-Mail unterliegt dem Kommunikationsgeheimnis und ist nur für den Empfänger bestimmt. Der Inhalt ist grundsätzlich als vertraulich zu betrachten und nicht für Dritte zugänglich. Eine Weiterleitung bedarf daher der Zustimmung des Verfassers. Diese E-Mail darf zu dienstlichen Zwecken innerhalb der Stadtverwaltung weitergeleitet werden.

Sparen Sie pro Seite ca. 200 ml Wasser, 2 g CO2 und 2 g Holz: Drucken Sie daher bitte nur, wenn es wirklich notwendig ist!
