### ISSUE TITLE
Replacing an ObjectAttribute's data_option (key and display) does not update the Object if that data_option was selected

### ISSUE THREAD

**Issue by t-shehab** [zammad/zammad#4794]
### Used Zammad Version

6.0

### Environment

- Installation method: any
- Operating system: any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

Replacing an ```ObjectAttribute```'s ```data_option``` does not update the Object if that ```data_option``` was selected.

### Expected behaviour

Replacing an ```ObjectAttribute```'s ```data_option``` should update the Object if that ```data_option``` was selected. If a ```key``` and ```display``` of a single-select or multi-select ```ObjectAttribute``` is changed, the affected ```Objects``` should reflect this change.

If you have an ```ObjectAttribute```'s ```data_option``` that is set on many ```Objects```,  clicking through potentially hundreds or thousands of them every time you want to replace a ```data_option```, is not viable.

Either the ```key```-part of the ```data_option``` needs to be greyed out once it is set for the first time (like the ```NAME``` of the ```ObjectAttribute``` itself). Or an automated loop over every Object that uses the given ```data_option``` should be performed upon a user replacing it, to update it to the new values.

### Steps to reproduce the behaviour

[screencast.webm](https://github.com/zammad/zammad/assets/114283486/9c151295-8b9f-47a1-90f4-9973cb45a3f0)

### Support Ticket

Ticket#10138497

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@t-shehab This works as designed. When the internal value is changed in an object attribute this is not reflected in the existing data. For this situation, the historical data shows the "old" value.

@rolfschmidt please correct me, when I'm wrong.

**Comment by t-shehab** [comment]
It may work as designed, but it is still a major problem when Zammad allows its users to replace ```key``` and ```display``` values of potentially thousands of occurrences of these values in the system. This is forcing the user to manually click through thousands of dropdown menus.

Therfore, in my opinion, a solution should be found here.

**Comment by rolfschmidt** [comment]
**context data_option**

```
key => stored value in the database
display value => display text in the frontend for the stored value
```

---

@dominikklein ++

@t-shehab this is consulting task. Normally the admin should not do something like that. If you remove option keys and want to migrate that to one of the existing or a new option keys then you need to execute rails code. I also don't think this will change in the future because it might not even possible to handle this automatically.

At least for tickets the migration might be possible without rails code:

1. Create the new option in the object manager attributes.

2. Add a new scheduler which migrates the old value to the new value.

3. Remove the old value from the object manager attributes.

But I agree that we should provide some help for it. It might make sense that we provide a rails code migration example for the Users and Organizations in the admin documentation. For this you should create a new issue there (https://github.com/zammad/zammad-admin-documentation/issues) and then @ralf401 can ask developers for support on implementing/documenting it.

**Comment by rolfschmidt** [comment]
Maybe one note more. If we add documentation for it then it also makes sense to create a hidden helper function in the backend which is used for the case so the code is as simple as possible.

**Comment by rolfschmidt** [comment]
@dominikklein I think an UI for this would be to error-prone right? I could imagine that you could run into issues while migrating and then your system is in an incosinstent state or even broken. If we do it via documentation then we could at least warn him to make a backup first I guess.

**Comment by dominikklein** [comment]
For sure there are improvement options, but it's always a decision for the current situation. @t-shehab I think you should create an "idea" entry in the community when something like that is needed.

@rolfschmidt Yes someone should maybe create a documentation issue, for some improvements in this direction.
