### ISSUE TITLE
Group levels

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#48]
If a group is created i miss a field for "is subgroup of".

If a group is subgroup of another group the subgroup should inherit all options of the topgroup.

**Comment by monotek** [comment]
Is this still an issue?
Maybe there is already some devider I didn't know of?
"::" Seems not to work.

**Comment by martini** [comment]
For me the question is, there are still may queues/groups needed? In the past many installations reduced the queue/group/count from many to very low count (because it was to annoying to used queues/groups not only to assign it to a certain team/department).

Using tags or categories is now very common.

**Comment by monotek** [comment]
We have more than 750 Queues in OTRS, with up to 3 Subqueues, which look like: 

"Department::Language::Product::Version"

Tags could be an option but at the moment there’s no such feature and therefore we can't use Zammad. When we're talking about tags its maybe also good to reconsider a language tag attached to a group: https://github.com/zammad/zammad/issues/53 

As long we don't have tags the queue sublevels would be needed to work around. 
By the way... How is the migrator handling subqueues?

**Comment by thorsteneckel** [comment]
The OTRS migrator creates groups with the same name as the queue name was, e.g. "Department::Language::Product::Version". There is nothing like a parent ID or so due to the flat group structure.

**Comment by monotek** [comment]
Uuuuhhh... So i guess an import would look realy bad in our case :D

**Comment by hanneshal** [comment]
Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals

regards
Johannes
