### ISSUE TITLE
Technical Questions / Bug?

### ISSUE THREAD

**Issue by UBA-NE** [zammad/zammad#4913]
### Used Zammad Version

6.1.0-1698142833.c4a2d029.buster 

### Environment

- apt-get
- Debian GNU/Linux 12 (bookworm)
- postgresql psql (PostgreSQL) 15.3 (Debian 15.3-0+deb12u1)
- Elasticsearch: 7.17.14
- Browser: firefox 118.0.2 (64-Bit)

### Actual behaviour

When I press Ctrl+F5, I get the following Error in my console. With the JS error, the page stops working. If I only press F5 or Control + R, the Page reloads and works as expected. This error can be reproduced on all pages in the application.

> executeSingel task: Ticket-4264 TypeError: $.fn.datepicker is undefined

![grafik](https://github.com/zammad/zammad/assets/6997013/80e291a1-682a-43c1-9558-26c60ba957b1)

![grafik](https://github.com/zammad/zammad/assets/6997013/b39fdb56-2df7-4d48-a832-fd30414395c5)

### Expected behaviour

I would expect the page reload normally.

### Steps to reproduce the behaviour

Pressing press Ctrl+F5.

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by dominikklein** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

Also see our documentation: https://admin-docs.zammad.org/en/latest/channels/email/accounts/email-notification.html

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
