### ISSUE TITLE
[BUG] Zammad stopped working in chromium based browsers. firefox still works.

### ISSUE THREAD

**Issue by tracure1337** [zammad/zammad#4934]
### Used Zammad Version

6.1.0

### Environment

ELASTICSEARCH_VERSION=8.10.2
#IMAGE_REPO=docker.io/zammad/zammad
IMAGE_REPO=ghcr.io/zammad/zammad
MEMCACHE_SERVERS=zammad-memcached:11211
MEMCACHE_VERSION=1.6.21-alpine
POSTGRES_DB=zammad_production
POSTGRES_PASS=zammad
POSTGRES_USER=zammad
POSTGRES_HOST=zammad-postgresql
POSTGRES_PORT=5432
POSTGRES_VERSION=15.3-alpine
REDIS_URL=redis://zammad-redis:6379
REDIS_VERSION=7.0.5-alpine
RESTART=unless-stopped
VERSION=6.1.0
ZAMMAD_HTTP_TYPE=http

### Actual behaviour

Chrome, Chromium, Thorium all show the quick loading logo and then nothing. No errors in the console either.

![image](https://github.com/zammad/zammad/assets/43231640/8510c7af-04bb-45ac-a540-a16df93abaec)

Firefox works.

### Expected behaviour

The Login screen appears.

### Steps to reproduce the behaviour

Not sure. I am able to reproduce it with various chromium based browsers. Clean state, no extensions.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
I'm unable to reproduce that on any current chromium based browser with the latest version of Zammad 6.1.
Please provide a proper description on how to reproduce this, other wise this might be a technical question I'm afraid.

**Comment by tracure1337** [comment]
Totally willing to share the URL for you to test an see for yourself. As well as the docker-compose.yml etc.

How can I send it to you  in Private?

thanks for looking into this. This also happens on other computers and other locations.

**Comment by MrGeneration** [comment]
Sorry we cannot qualify personal settings in the scope of bug reports.

---

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by tracure1337** [comment]
This is NOT a  personal setting. This is precisely the way it is setup according to your docs. And it happened from one day to the other.
I highly recommend looking into this .

**Comment by MrGeneration** [comment]
I cannot reproduce this and having a personal look just for you would be support and thus a) not belong on this issue tracker and b) be unfair to others.
