### ISSUE TITLE
Download Zammad Debian packages from packager.io not possible

### ISSUE THREAD

**Issue by WalterHof** [zammad/zammad#4974]
### Used Zammad Version

6.2.0

### Environment

Zammad installed as Debian package
OS: Debian 12
The Debian repository string is: `deb [signed-by=/etc/apt/trusted.gpg.d/pkgr-zammad.gpg] https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 12 main`

Is packager.io broken? 
Walter

### Actual behaviour

`apt update works` without errors

```
# apt update
Hit:1 http://security.debian.org/debian-security bookworm-security InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 https://artifacts.elastic.co/packages/7.x/apt stable InRelease
Hit:5 https://download.sep.de/linux/repositories/debian bookworm InRelease
Get:6 https://dl.packager.io/srv/deb/zammad/zammad/stable/debian 12 InRelease [1,845 B]
Fetched 1,845 B in 1s (1,796 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
```

Unfortunately a reinstallation is not possible, the package is not found:
```
# apt install --reinstall zammad
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reinstallation of zammad is not possible, it cannot be downloaded.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Last check, with Chrome browser I tried to download the Zammad package from `packager.io`, `https://dl.packager.io/srv/deb/zammad/zammad/stable/debian` but I get this error: `[packager.io] 404 - Resource not found.` 

### Expected behaviour

Download an reinstall Zammad.

### Steps to reproduce the behaviour

`apt install --reinstall zammad` and I see the error:
`Reinstallation of zammad is not possible, it cannot be downloaded.`

With Chrome browser I tried to download the Zammad package from `packager.io`, `https://dl.packager.io/srv/deb/zammad/zammad/stable/debian` but I get this error: `[packager.io] 404 - Resource not found.` 

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
I'm afraid I am unable to reproduce this. I verified fresh installation and upgrade installation on both Debian 11 and 12 without issues.

If you still experience issues and need help, please use the community thread you've created as well.

---


Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
