### ISSUE TITLE
The sidebar area in the ticket is very wide in RTL

### ISSUE THREAD

**Issue by YosefAdPro** [zammad/zammad#4975]
### Used Zammad Version

6.2

### Environment

- Installation method: [e.g. source, package] package
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04] ubuntu 20.04
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3] postgresql 
- Elasticsearch version: [e.g. 7.17] 
- Browser + version: [e.g. chrome 83, safari 14, firefox 105] Chrome 120

### Actual behaviour

When using the RTL language, the sidebar area in the ticket is very wide, and there is a scroll bar at the bottom. After upgrading from 6.1 to 6.2
![image](https://github.com/zammad/zammad/assets/11810187/d2ff45ed-fdeb-4a6b-b5fb-1ec4e7d317d0)

![image](https://github.com/zammad/zammad/assets/11810187/7cca3526-3359-496b-a28a-f2f4397e6e14)

### Expected behaviour

Normal width without a scroll bar like in the English language
![image](https://github.com/zammad/zammad/assets/11810187/46569e2b-67ac-412a-8e6b-576f0e7d12e9)

### Steps to reproduce the behaviour

Change language to Hebrew. Open any ticket You may also need to add a Single tree selection field

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@YosefAdPro Thanks for the report, it seems to be the problem was already present before the last release, but because of the increase of the sidebar, it's more visible.

**Comment by gwingend** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail.
Ich bin nicht im Büro.
Ihre Mail wurde weder gelesen noch weitergeleitet.

Bitte wenden Sie sich in dringenden Fällen an den EDV-Helpdesk ***@***.***).


Mit freundlichen Grüßen
Gerhard Wingender
Amt für IT

>>> Dominik Klein ***@***.***> 11.12.23 08:32 >>>

@YosefAdPro Thanks for the report, it seems to be the problem was already present before the last release, but because of the increase of the sidebar, it's more visible.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/zammad/zammad/issues/4975#issuecomment-1849470840
You are receiving this because you are subscribed to this thread.

Message ID: ***@***.***>
-- 
Diese E-Mail wurde von Sophos UTM auf Viren überprüft.

Besuchen Sie uns im Internet unter: www.neuwied.de
oder bei Facebook @neuwied.de
und Instagram @deichstadt_neuwied

Eine E-Mail unterliegt dem Kommunikationsgeheimnis und ist nur für den Empfänger bestimmt. Der Inhalt ist grundsätzlich als vertraulich zu betrachten und nicht für Dritte zugänglich. Eine Weiterleitung bedarf daher der Zustimmung des Verfassers. Diese E-Mail darf zu dienstlichen Zwecken innerhalb der Stadtverwaltung weitergeleitet werden.

Sparen Sie pro Seite ca. 200 ml Wasser, 2 g CO2 und 2 g Holz: Drucken Sie daher bitte nur, wenn es wirklich notwendig ist!

**Comment by YosefAdPro** [comment]
It seems you're right, it exists before 6.2 too, but we probably didn't notice it.
