### ISSUE TITLE
Predefined-Webhook and custom payload Webhook not working 

### ISSUE THREAD

**Issue by nodwatt** [zammad/zammad#4984]
### Used Zammad Version

6.1.0 and 6.1.0-1 and develop

### Environment

- Installation method: Docker and package
- Operating system: Debian GNU/Linux 12 (bookworm)
- Database + version:   postgresql 15.3
- Elasticsearch version: 8.8.0
- Browser + version: firefox 120

### Actual behaviour

Hello,

I tried to setup Predefined-webhook and standard webhook with custom payload, but nothing appens in the UI. So I take a look into Scheduler logs and the following is what I've found.

I tried to test with zammad docker in version 6.2.0, 6.2.0-1 and develop with docker and package installation but the result remains the same.

I tried many options in webhook config. The issue still appens even if I use Mattermost predefined webook with predefined settings. 

```
ERROR -- : 2023-12-14T17:28:15+0000: [Worker(host:64498d13f07f pid:1)] Job TriggerWebhookJob [bc88f77d-d70e-4a04-815a-4fca02df8165] from DelayedJob(default) with arguments: [{"_aj_globalid"=>"gid://zammad/Trigger/1"}, {"_aj_globalid"=>"gid://zammad/Ticket/2"}, {"_aj_globalid"=>"gid://zammad/Ticket::Article/2"}, {"changes"=>{"_aj_symbol_keys"=>[]}, "user_id"=>3, "execution_type"=>"trigger", "event_type"=>"create", "_aj_ruby2_keywords"=>["changes", "user_id", "execution_type", "event_type"]}] (id=36) (queue=default) FAILED (0 prior attempts) with NoMethodError: undefined method `[]' for nil:NilClass

        message: match[:message].presence || '',
                      ^^^^^^^^^^
E, 

[2023-12-14T17:28:15.284521#1-142340] ERROR -- : 2023-12-14T17:28:15+0000: [Worker(host:64498d13f07f pid:1)] Job TriggerWebhookJob [bc88f77d-d70e-4a04-815a-4fca02df8165] from DelayedJob(default) with arguments: [{"_aj_globalid"=>"gid://zammad/Trigger/1"}, {"_aj_globalid"=>"gid://zammad/Ticket/2"}, {"_aj_globalid"=>"gid://zammad/Ticket::Article/2"}, {"changes"=>{"_aj_symbol_keys"=>[]}, "user_id"=>3, "execution_type"=>"trigger", "event_type"=>"create", "_aj_ruby2_keywords"=>["changes", "user_id", "execution_type", "event_type"]}] (id=36) (queue=default) FAILED permanently because of 1 consecutive failures
```

Can you help me ?

Thanks for your great work on this product !

### Expected behaviour

Webhook sent and log append in webhook logs

### Steps to reproduce the behaviour

Basic install -> setup predefined webhook or custom payload

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@nodwatt Difficult to say what is happening, did you change something inside the mailer Templates below `app/views/mailer`?
For which trigger action/condition is the webhook triggered (e.g. is it only failing with/with out an article?)?

**Comment by nodwatt** [comment]
@dominikklein I didn't change anything. The issue is comming on basic install off zammad. The webhook is trigger by One or many trigger as the default one (auto-reply (new-tickets)) for exemple.

Here is a simple exemple that is not working.
![image](https://github.com/zammad/zammad/assets/129776478/b8d73f05-8410-426e-8c8c-6a1f4652dc13)

**Comment by dominikklein** [comment]
In the end, this could only be related to some article content, is it always happening or only when an article is present during the update of the ticket?

(e.g. in your example Screenshot the action is "created" which means it is always an article present)

But it's difficult to say what happens here without debugging the situation. Also when we would improve the code here, so that it's not failing, the functionality in general would not be working correctly. We would need the content that breaks this "check" (regex).

**Comment by geraudloup** [comment]
Hi, same issue there, stock install with docker compose...

All data I could provide:

Running `docker logs zammad-docker-compose-zammad-scheduler-1`, I get the same error

```

E, [2024-01-22T22:49:39.232539#1-142120] ERROR -- : 2024-01-22T22:49:39+0000: [Worker(host:a99e5a18381a pid:1)] Job TriggerWebhookJob [4054979d-cbbf-44e3-a301-e390f1e050cf] from DelayedJob(default) with arguments: [{"_aj_globalid"=>"gid://zammad/Trigger/8"}, {"_aj_globalid"=>"gid://zammad/Ticket/170"}, {"_aj_globalid"=>"gid://zammad/Ticket::Article/379"}, {"changes"=>{"_aj_symbol_keys"=>[]}, "user_id"=>3, "execution_type"=>"trigger", "event_type"=>"update", "_aj_ruby2_keywords"=>["changes", "user_id", "execution_type", "event_type"]}] (id=1737) (queue=default) FAILED (0 prior attempts) with NoMethodError: undefined method `[]' for nil:NilClass

        message: match[:message].presence || '',

```

Here is a screenshot of my settings:
![image](https://github.com/zammad/zammad/assets/47665233/b3f9eaaa-3c9e-4b2a-a203-aebac6df3c52)
this setting won't trigger the webhook...

If I disable custom paylod, it will be triggered however:
![image](https://github.com/zammad/zammad/assets/47665233/ab007f6a-9dba-4c5a-80eb-f16fd97572c6)

For information, the trigger used:
![image](https://github.com/zammad/zammad/assets/47665233/dd59cf39-36e3-4c02-a595-e1a13ceb5199)

It fails for any king of webhook payload, I have tried using the pre-defined webhooks, none would work (no trigger)... So for 
exemple, I have used the Slack Notifications and just put my dummy adress and it would not trigger again.
 
 This issue is super easy to reproduce, just install with docker compose and try to make a webhook with custom payload (pre-defined or not) => You won't succeed!

**Comment by geraudloup** [comment]
By the way, I am using the 6.2 version, as shipped in https://github.com/zammad/zammad-docker-compose

**Comment by jeffersonrios17** [comment]
We are also on version 6.2 and we are unable to use it, the same error in the logs as shown in the printout of the prompt.

If you don't pass any custom body, then you get another authentication error and the trigger fired.

Changing a Call Status, Setting it to Closed, all without success.

**Comment by wagneripjr** [comment]
I'm with the same error.
Custom payload is 
{
  "text": "test google chat 1"
}

The trigger always works when the ticket is created, but when we update the ticket nothing happens, and the zammad-scheduler logs shows:

[2024-01-23T14:00:53.018194#1-142220] ERROR -- : 2024-01-23T14:00:53+0000: [Worker(host:zammad-0 pid:1)] Job TriggerWebhookJob [b2c01ae3-b133-4b40-a2ed-33e1b90b37bc] from DelayedJob(default) with arguments: [{"_aj_globalid"=>"gid://zammad/Trigger/8"}, {"_aj_globalid"=>"gid://zammad/Ticket/105"}, {"_aj_globalid"=>"gid://zammad/Ticket::Article/218"}, {"changes"=>{"State"=>["fechado", "aberto"], "_aj_symbol_keys"=>[]}, "user_id"=>13, "execution_type"=>"trigger", "event_type"=>"update", "_aj_ruby2_keywords"=>["changes", "user_id", "execution_type", "event_type"]}] (id=23976) (queue=default) FAILED (0 prior attempts) with NoMethodError: undefined method `[]' for nil:NilClass

        message: match[:message].presence || '',
                      ^^^^^^^^^^
E, [2024-01-23T14:00:53.018283#1-142220] ERROR -- : 2024-01-23T14:00:53+0000: [Worker(host:zammad-0 pid:1)] Job TriggerWebhookJob [b2c01ae3-b133-4b40-a2ed-33e1b90b37bc] from DelayedJob(default) with arguments: [{"_aj_globalid"=>"gid://zammad/Trigger/8"}, {"_aj_globalid"=>"gid://zammad/Ticket/105"}, {"_aj_globalid"=>"gid://zammad/Ticket::Article/218"}, {"changes"=>{"State"=>["fechado", "aberto"], "_aj_symbol_keys"=>[]}, "user_id"=>13, "execution_type"=>"trigger", "event_type"=>"update", "_aj_ruby2_keywords"=>["changes", "user_id", "execution_type", "event_type"]}] (id=23976) (queue=default) FAILED permanently because of 1 consecutive failures
