### ISSUE TITLE
Inconsistent link/merge dialog for web/mobile views

### ISSUE THREAD

**Issue by rephlex** [zammad/zammad#4987]
### Used Zammad Version

 6.0.0

### Environment

- Installation method: package
- Operating system debian 12
- Database + version:  some postgresql
- Elasticsearch version: something
- Browser + version: Chrome 120.0

### Actual behaviour

When using a phone, the link and merge ticket dialog has me search a ticket using a search box. Using a computer, i need to select from a list of most recent tickets.

### Expected behaviour

Mobile and web workflows should be similar / the same. Have both show full text search, or have both display most recent tickets.
Opinion: Search is better, because it allows access to ALL tickets, not just the recent ones.

### Steps to reproduce the behaviour

Try merging or linking any ticket using a smartphone, then try the same action using a computer or laptop

### I'm sure this is a bug and no feature request or a general question.

yes
Note, this is not a request for a new feature, but the **current** interface is inconsistent and therefore broken.

**Comment by dominikklein** [comment]
@rephlex Thanks for your request, but this is currently by design. The desktop app and the new mobile view have different sets of functionalities (btw: linking tickets is currently not implemented in the mobile view) and also the solutions are different.
In the long run, we will rewrite the desktop app to a new desktop view, here we will also improve some of the functionalities (and it could be that the described situation will then be more aligned again).
