### ISSUE TITLE
Scheduler - wrong count for the "has processed" column

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#5063]
### Used Zammad Version

6.2

### Environment

- Installation method: [e.g. source, package]
- Operating system (if you're unsure: `cat /etc/os-release` ): [e.g. debian 10.4, ubuntu 20.04]
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

The count **has processed** will show the total count of the matching objects instead of the processed count tickets.

![image](https://github.com/zammad/zammad/assets/5445062/5fcdcf2a-c7a7-4060-84ae-54e1736f2d02)

### Expected behaviour

The count should show 2000 or less.

`[object_count, 2000].min`

### Steps to reproduce the behaviour

- Create a system with a scheduler which processes more than 10k tickets

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
/cc @t-shehab @mantas 

Looks like mantas fixed this already for develop: https://github.com/zammad/zammad/commit/bbe92d05c42d8d317c603b13b12266dc01c20d9b

**Comment by MrGeneration** [comment]
I believe I also reported this several yesrs ago. Might be a duplicate to close. :)On 22. Feb 2024, at 10:54, Rolf Schmidt ***@***.***> wrote:﻿
Used Zammad Version
6.2
Environment

Installation method: [e.g. source, package]
Operating system (if you're unsure: cat /etc/os-release ): [e.g. debian 10.4, ubuntu 20.04]
Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
Elasticsearch version: [e.g. 7.17]
Browser + version: [e.g. chrome 83, safari 14, firefox 105]

Actual behaviour
The count has processed will show the total count of the matching objects instead of the processed count tickets.
image.png (view on web)
Expected behaviour
The count should show 2000 or less.
[object_count, 2000].min
Steps to reproduce the behaviour

Create a system with a scheduler which processes more than 10k tickets

Support Ticket
No response
I'm sure this is a bug and no feature request or a general question.
yes
