### ISSUE TITLE
Trying to create a new customer freezes UI

### ISSUE THREAD

**Issue by vBenTec** [zammad/zammad#5066]
Used Zammad Version: 6.3.x (develop)

**Environment:**

Installation method: Source
Operating system: MacOS (if you're unsure: cat /etc/os-release)
Database + version: Any
Elasticsearch version: Any
Browser + version: Any
Actual Behavior:
When a user creates a new ticket and tries to add a new customer in the third step of the form, the UI blocks.

**Expected Behavior:**
After clicking "Customer" and then the icon for creating a new user, the user should see a form with user credentials.

**Steps to Reproduce the Behavior:**

1. Click the "+" button to create a new ticket.
2. Insert values into form fields and continue.
3. Click the first item "Customer."
4. In the header, click the user plus icon.
5. 💥 (UI blocks)

Support Ticket: No response

I am certain this is a bug and not a feature request or a general question.

**Comment by dvuckovic** [comment]
Reproducible only in the dev mode, the error is not fatal in prod/test.

**Comment by gwingend** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail.
Ich bin nicht im Büro.
Ihre Mail wurde weder gelesen noch weitergeleitet.

Bitte wenden Sie sich in dringenden Fällen an den EDV-Helpdesk ***@***.***).


Mit freundlichen Grüßen
Gerhard Wingender
Amt für IT

>>> Dusan Vuckovic ***@***.***> 28.2.24 08:46 >>>

Reproducible only in the dev mode, the error is not fatal in prod/test.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/zammad/zammad/issues/5066#issuecomment-1968407116
You are receiving this because you are subscribed to this thread.

Message ID: ***@***.***>
-- 
Diese E-Mail wurde von Sophos UTM auf Viren überprüft.

Besuchen Sie uns im Internet unter: www.neuwied.de
oder bei Facebook @neuwied.de
und Instagram @deichstadt_neuwied

Eine E-Mail unterliegt dem Kommunikationsgeheimnis und ist nur für den Empfänger bestimmt. Der Inhalt ist grundsätzlich als vertraulich zu betrachten und nicht für Dritte zugänglich. Eine Weiterleitung bedarf daher der Zustimmung des Verfassers. Diese E-Mail darf zu dienstlichen Zwecken innerhalb der Stadtverwaltung weitergeleitet werden.

Sparen Sie pro Seite ca. 200 ml Wasser, 2 g CO2 und 2 g Holz: Drucken Sie daher bitte nur, wenn es wirklich notwendig ist!
