### ISSUE TITLE
New created boolean ticket attribute does not work if "No" is set as default 

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#5075]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  [any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

I created a boolean field, and set "No" as default.
When I want to work on an existing ticket, my boolean field is set to "yes" as unsaved change, and I can not abandon the unsaved change.

### Expected behaviour

I would expect that the boolean attribut is set to "No" or "-"

### Steps to reproduce the behaviour

Create a Boolean ticket attribute. Admin > System > Objects
![2024-03-04 16_24_04-Window](https://github.com/zammad/zammad/assets/94919964/848d70ed-21c5-4342-bb70-d5b8b7c9da0c)

Try to work on an existing ticket:
![2024-03-04 16_28_21-](https://github.com/zammad/zammad/assets/94919964/3e0aaefd-9b49-4413-87e3-776b489fafd9)

### Support Ticket

Ticket#10151924

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
Hi @Bozo0511,

I researched here a little bit and I think we can not fix that. The boolean field does not have a nulloption ("-") which means it forces the user to a selection. We can't really fix this behaviour because it would change the behaviour for all systems.

If you don't want this behaviour, then you just need to create the field as a **single select** with the same values. The **single select** does have a nulloption and will not force the user to a selection even if no value is set for the ticket.

**Comment by HJoost** [comment]
Hi @rolfschmidt ,

a boolean should not have a null option in most cases. So you set the default to false. I expect then that all old tickets have this default. Nothing else happens in a database when you a non nullable column with a default value.

**Comment by rolfschmidt** [comment]
> Hi @rolfschmidt ,
> 
> a boolean should not have a null option in most cases. So you set the default to false. I expect then that all old tickets have this default. Nothing else happens in a database when you a non nullable column with a default value.

Hi @HJoost, I see your point, maybe this idea would be something to think about. I need to discuss this with others, there will be no quick solution, but to have a migration which prevents the null state for the boolean for existing data sounds like a good idea.

**Comment by rolfschmidt** [comment]
Current thoughts:

- Missing Rails.cache.clear solves the ticket state and should be done on attribute creation.
- Default should be mandatory on the creation of a boolean field.

**Comment by rolfschmidt** [comment]
UPDATED

The following changes are needed:

- We need a Rails.cache.clear on the creation of the attribute, because else we have old caches with nil values.
- The default option in the admin interface for the boolean field should be mandatory.
- We need some kind of trigger which is clearing the frontend cache for the users, since it also has wrong values.
