### ISSUE TITLE
The usage of text modules removes one row beneath the text module

### ISSUE THREAD

**Issue by Bozo0511** [zammad/zammad#5125]
### Used Zammad Version

6.2

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

When I write a message and use a text module, the row beneath the text module is removed.
Which result sometime in mixing text together.

### Expected behaviour

The use of the text module should not remove any rows at the end of the text module.

### Steps to reproduce the behaviour

- Create a ticket
- Write an email 
- use s text module

[Screen Recording (15.04.2024 14-34-05).wmv.zip](https://github.com/zammad/zammad/files/14979000/Screen.Recording.15.04.2024.14-34-05.wmv.zip)

### Support Ticket

Ticket#10153835, #10154488

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
@Bozo0511 This looks not like a reproduction description for me. Maybe It could be more clear?

**Comment by Suhopoljac** [comment]
This one is quite tricky to catch as it does not occur every time text modules are used. But when it happens, e.g. when a text module is inserted before a line break, it results in the module moving down a line (in most cases). 

In my case, this most often happens when I insert the “Yours sincerely/Kind regards” before the signature. When inserting such text modules in the row above the signature, the text gets positioned in the same line as the name:

Expected result
Dear Mr. Jones,
 
[Agent message]
 
[Text block]
 
Yours sincerely
Agent
 
-----------------------
Current result
 
Dear Mr. Jones
 
[Agent message]
 
[text block]Yours sincerely
Agent
 
-----------------------

**Comment by dominikklein** [comment]
This is fixed with the new editor in the new tech stack. Can already be tested in the ticket creation of the new desktop view.
