### ISSUE TITLE
Email channels fails with Zoho mail

### ISSUE THREAD

**Issue by ahmedelakkad** [zammad/zammad#5154]
### Used Zammad Version

 6.3

### Environment

- Installation method: Docker
- Operating system: ubuntu 22.04
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

Setting up SMTP with Zoho fails and produces End of File with no other errors explaining what's wrong, it can reach the host because when the password is wrong is says "Authentication failed". This has been brought up multiple times but all tickets get closed with no solution. SMTP testers work fine with the same exact config. Please advise.

![image](https://github.com/zammad/zammad/assets/36191649/618b3d1c-bef3-42ca-a82d-fbeecd191843)

### Expected behaviour

Connecting and authenticating with zoho mail server successfully 

### Steps to reproduce the behaviour

1. Add inbound email 
2. Configure host, account and password of zoho account
3. Submit

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
