### ISSUE TITLE
Tickets overview not updated after upgrade to 6.3

### ISSUE THREAD

**Issue by Trapulo** [zammad/zammad#5162]
### Used Zammad Version

6.3

### Environment

- Installation method: docker
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 12
- Database + version:  postgres 15.3
- Elasticsearch version: 8.8
- Browser + version: any

### Actual behaviour

After the update, the list isn’t updated (eg. I see the ticket as “open”). But if you have a ticket "open" in sidebar, and any other user closes it, your sidebar is updated with green icon. The overview list still is not updated.

### Expected behaviour

Before Zammad update, when a ticket was updated (eg. is closed), the overview list was also updated in a few seconds.

### Steps to reproduce the behaviour

1. enter overview → open tickets → open a ticket. Close it.
2. go to overview again: the ticket results still “open”

The browser’s console does not report any error or failed connection

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by Trapulo** [comment]
If Zammad doesn't update a view, I suspect a BUG.
Why are sure is not a bug without any investigation?

**Comment by MrGeneration** [comment]
It would affect hundreds of installations. It is just you, it is a technical question. I can tell with my 6 years Zammad experience without deep diving it. Community, please.
