### ISSUE TITLE
Ticket with custom state not visible as customer

### ISSUE THREAD

**Issue by slplss** [zammad/zammad#5169]
### Used Zammad Version

6.3

### Environment

- Installation method: package
- Operating system ubuntu 20.04
- Database + version:  postgresql  12.18
- Elasticsearch version: 7.17.21
- Browser + version: Edge 124.0.2478.97

### Actual behaviour

After adding a new custom ticket state, the state is shown in the agent screen for ticket editing and in the agents overview.

![image](https://github.com/zammad/zammad/assets/126397826/f624fc79-ce89-4b6a-a033-0c4461b83aa8)

The new ticket with custom state is not visible when a customer is logged in and looking at his overview, when switching back to a standard state like 'open' the ticket reappears under the customers overview.
The ticket is correctly assigned to him.

It does not matter which type of state we create, this happens with all states.

### Expected behaviour

Tickets with a custom state should also be visible when a customer is logged in via the web portal.

### Steps to reproduce the behaviour

Create custom state
Assign custom state to ticket and customer
login as customer
ticket is not visible

as soon as a standard state is used the ticket reappears

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
