### ISSUE TITLE
Information about remote images is lost/not displayed in Zammad

### ISSUE THREAD

**Issue by martini** [zammad/zammad#5193]
### Used Zammad Version

6.3.1.3ff82009e.saas

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version: any
- Elasticsearch version: any
- Browser + version: any

### Actual behaviour

If an incoming e-mail contains information about an embedded remote image, for example, this information is "removed" by Zammad and no reference is made to this removed user information.

### Expected behaviour

If an incoming e-mail contains information, e.g. about an embedded remote image, Zammad should (even if the image is not displayed) display information to the agents that the message contains a remote image, but that this is not displayed for security reasons, for example.

The agent can then decide for themselves whether they want to view the email in the "original format" (link in the footer of the article).

### Steps to reproduce the behaviour

* Process an html email which contains an external image like `<img src="https://host/test.jpg">`
* Verify the new created article, you can't see any information about it

### Support Ticket

Ticket#10155348

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment]
Proposal for the warning message in the affected/sanitized articles.

* Desktop App ([Figma](https://www.figma.com/design/P3sOAIFK20RQVrx7TdURXA/Zammad-Desktop-App?node-id=725-8934&t=ZhvFk3OCAxZTArZE-1))
  <a href="https://github.com/zammad/zammad/assets/6049445/2ef09835-d834-4479-87c2-0b44efd65c2d"><img width="256" alt="Collapsed" src="https://github.com/zammad/zammad/assets/6049445/2ef09835-d834-4479-87c2-0b44efd65c2d"></a> <a href="https://github.com/zammad/zammad/assets/6049445/a2b79075-797d-4a2e-b69d-a37690ee8fd1"><img width="256" alt="Expanded" src="https://github.com/zammad/zammad/assets/6049445/a2b79075-797d-4a2e-b69d-a37690ee8fd1"></a>

* Mobile View
  <a href="https://github.com/zammad/zammad/assets/6049445/910c3e71-77a7-4aaa-8110-a608106ab9e9"><img width="96" alt="Button" src="https://github.com/zammad/zammad/assets/6049445/910c3e71-77a7-4aaa-8110-a608106ab9e9"></a> <a href="https://github.com/zammad/zammad/assets/6049445/311ed157-68e0-4e7b-b8d4-47da14559774"><img width="96" alt="Dialog" src="https://github.com/zammad/zammad/assets/6049445/311ed157-68e0-4e7b-b8d4-47da14559774"></a>

**Comment by hdk** [comment]
Looks cool!
Last thing: Now give us an option to open that "original format" directly in a new browser tab (as people will just click on the downloaded html-file an open it in the same browser anyway).

**Comment by MrGeneration** [comment]
@hdk Please post feature requests on our community board, in case it doesn't exist yet:
https://community.zammad.org/c/stuff-you-like-zammad-to-have-feel-free-to-discuss-and-add-proposals/6/none

**Comment by dvuckovic** [comment]
We are reopening this issue for an improvement to the text and styling of the alert: the message will be toned down and moved to the bottom of the article in desktop app, since it turned out to be too intrusive. Mobile view stays mostly as before, since it was already at the bottom and hidden behind a button.

<a href="https://github.com/zammad/zammad/assets/6049445/ca3eaf19-7631-4562-8219-9766e88323eb" target="_blank"><img width="256" src="https://github.com/zammad/zammad/assets/6049445/ca3eaf19-7631-4562-8219-9766e88323eb"></a>

<a href="https://github.com/zammad/zammad/assets/6049445/5adfb86f-3273-47ae-b975-e1917e07495f" target="_blank"><img width="96" src="https://github.com/zammad/zammad/assets/6049445/5adfb86f-3273-47ae-b975-e1917e07495f"></a>
