### ISSUE TITLE
API 301 redirection when accessing through HTTP

### ISSUE THREAD

**Issue by AnaelMobilia** [zammad/zammad#5211]
### Used Zammad Version

6.3.1

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 12
- Database + version:  postgresql 15.6
- Elasticsearch version: 8.13
- Browser + version: n/a

### Actual behaviour

When calling an API endpoint through HTTP (not HTTP**S**), we got a 301 redirection on which the starting "/" is missing
![image](https://github.com/zammad/zammad/assets/6187125/7af9844b-83cc-43be-ac70-441c347e7c44)

### Expected behaviour

Got a 301 to https://example.com**/**api/... (with a "/" on the begin of the path)

### Steps to reproduce the behaviour

Make an API call to http://example.com/api/v1/organizations/911

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by AnaelMobilia** [comment]
Hey @MrGeneration 

It's an issue on server side (missing an initial "/"), not an usage / configuration issue.

Please, reopen the issue as #5212 is submitted in order to fix the configuration file on the zammad repo ;-).

Bests regards,
Anael

**Comment by MrGeneration** [comment]
Fair point. Your issue didn't let shine through that you identified the vhost as culprit, sorry.
