### ISSUE TITLE
Cannot create ticket if ticket attribute called "scope" is used

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5221]
### Used Zammad Version

6.3.1

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian 12
- Database + version:  psql
- Elasticsearch version: 7.x
- Browser + version: Edge + Chrome

### Actual behaviour

When creating a ticket and a ticket attribute "scope" is used (and set), the ticket cannot be created. "No Route To [...]".

### Expected behaviour

When creating a ticket and a ticket attribute "scope" is used, the ticket can be created.

OR

A tricket attribute "scope" cannot be created.

### Steps to reproduce the behaviour

Create a ticket attribute "scope".
Create a ticket and fill out a value in the field "scope".

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by binsky08** [comment]
Not yet sure about how to fix it, but that's my more technical description of the problem:

Adding a zammad object to a ticket will add/load the object's name as a ticket (Ticket object) parameter: https://github.com/binsky08/zammad/blob/57201144ddfbbf5cb4b24d270d695313eda705e6/app/assets/javascripts/app/controllers/agent_ticket_create.coffee#L729

Let's assume that `scope` is our custom named zammad object and `params.scope = 'foobert'` during ticket creation.

The `ticket.load(params)` call will load the content of params into the ticket object. So after that ticket.scope = params.scope.

When trying to save the ticket with `ticket.save`, a spine ajax request is being built, including that call:
https://github.com/spine/spine/blob/2d3bf2345e39b1adf96576423876e824aeeea888/src/ajax.coffee#L17

Since `object.scope` is our `ticket.scope`, the entered scope value will be prepended to the ajax request url, which ends in a failing request like that:

![image](https://github.com/user-attachments/assets/d1907bb4-a535-4edc-9088-2e0ffbe7151a)

<hr>

If we take the idea further, it is therefore possible to overwrite any attribute of the models to which own zammad objects can be applied. (Ticket, User, Organization, Group).

Let's try if we can overwrite the Ticket constructor:

![image](https://github.com/user-attachments/assets/04f7dd58-7787-47d3-9f95-1942834f1f21)

...

Nice, works. We successfully broke the complete zammad frontend (more or less everything that loads a Ticket instance).

<details>
  <summary>Click me to open the trace</summary>
  
   ![image](https://github.com/user-attachments/assets/72fb4bda-d85b-4410-8977-a223ba8f7104)
</details>



Is this a security issue as well?
- maybe somehow
- since it needs an administrator creating a "malicious" zammad object the risk of breaking things isn't too high

How could we fix it?
- deny all spine model class names and keywords to be a zammad object name
- use something like `model.custom_attributes` to store custom zammad objects instead of merging them into the models "root scope"

**Comment by mantas** [comment]
Potential fix - `scope` could be added to reserved words that can’t be used to create attributes list.

**Comment by binsky08** [comment]
> Potential fix - `scope` could be added to reserved words that can’t be used to create attributes list.

cool, thanks for the hint

![image](https://github.com/user-attachments/assets/45d05f82-91f4-4325-bffe-c68b1cb7e690)
