### ISSUE TITLE
Searching and filtering tags

### ISSUE THREAD

**Issue by driebe** [zammad/zammad#524]
Hi everyone,

trying out the tag functionality yielded two issues/suggestions I encountered. For one, searching for tags does not yield any results. The tag-label does not seem to be included in the search functionality (though I am running a Zammad installation without elastic-search, so I am unsure whether this is an issue on my end).

However, secondly, since Zammad applies the tag functionality for the labeling of spam, I feel that it should be possible to filter the views in regards to the tags. I tagged a number of tickets as spam and have no possibility of hiding them for the user, which leads to clutter in the "closed tickets" view.

Regards
Daniel

**Comment by martini** [comment]
Hi @driebe 

it's right. If you use Zammad without elasticsearch, the search is *really* limited.

 -=> Since elasticsearch is really easy to integrate and so powerful, we did not implement full featured search via SQL.

If we get many requests to improve search by SQL, we will work on it (currently we do not have feedback about this needs - once you have tried elasticsearch you will never miss it).


Second topic, searching for tags in overview/trigger/... and so on is already here https://github.com/zammad/zammad/issues/245 

Any feedback is welcome!

 -Martin

**Comment by monotek** [comment]
That search is not the same on SQL & Elastic is imho kind of bad.
If there is no info about this there should be some detailed info whats the differences.

I expected SQL search is just slower but has the same features.
This not being the case elasticsearch should be dependency also in the DEB & RPM packages.

**Comment by martini** [comment]
Closing for now. Feel free to reopen if needed.
