### ISSUE TITLE
Create new ticket based of telegram user

### ISSUE THREAD

**Issue by zgurea1** [zammad/zammad#5275]
### Used Zammad Version

6.3.1

### Environment

- Latest Docker Version

### Actual behaviour

When i create new ticket i only have 3 option to chose, but if the client is from telegram, i can not create a ticket to responde in telegram. Also if i split the ticket is the same behavior.

<img width="770" alt="image" src="https://github.com/user-attachments/assets/0677df48-d063-45e6-8752-f39fa6c1b95b">

### Expected behaviour

When create a ticket or split the ticket you have option to communicate with client form the source he reached.

### Steps to reproduce the behaviour

1. Integrate Telegram.
2. Create a ticket and closed
3. From zammad create new ticket or split the ticket
4. You dont have option to chose from the source that your client reached

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
