### ISSUE TITLE
Problem with database.yml in versions 6.1.0 and later

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#5277]
### Used Zammad Version

6.1.0 and later

### Environment

Zammad 6.1.0 and later, regardless of another environment

### Actual behaviour

The config directory contains the database.yml file (config/database.yml), which is needed to work on the command line "rails c". Before version 6.1.0, this file was automatically modified by the script docker-entrypoint.sh (contrib/docker/docker-entrypoint.sh). Starting with version 6.1.0, this file is no longer modified automatically, so the console behaves unexpected.

### Expected behaviour

Script "docker-entrypoint.sh " automatically modifies the file "config/database.yml". Need to put back the sed command.

### Steps to reproduce the behaviour

See for example line 55 of docker-entrypoint.sh 6.0.0 or 60 line of docker-entrypoint.sh 6.1.0-alpha version. It contains sed command to modify database.yml. 6.1.0 and later doesn’t contains this string.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
