### ISSUE TITLE
multilanguage support via language tags in groups

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#53]
To avoid dublication of groups when more than one support language is used, a language tag for groups would be very usefull.

At the moment my OTRS queues look like:

Support::German::Programm
Support::French::Programm
Support::English::Programm

It would be much cooler to have just one zammad group "Support::Programm" which could get one or more language tags. These tags needs to be also set for agents which should see the language.

I think this would make administration of many languages in one system a lot easier.

What do you think?

**Comment by hanneshal** [comment]
Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals

regards
Johannes

https://community.zammad.org/t/multilanguage-support-via-language-tags-in-groups/25
