### ISSUE TITLE
Microsoft 365 channel does not work while trying to send email after password change

### ISSUE THREAD

**Issue by javlin69** [zammad/zammad#5302]
### Used Zammad Version

6.3.1

### Environment

- Installation method: source
- Operating system (if you're unsure: `cat /etc/os-release` ): Ubuntu 24.04 (arm64)
- Database + version:  PostgreSQL 12
- Elasticsearch version: Not installed
- Browser + version: Chrome 127.0.6533.100 (Official Build) (arm64)

### Actual behaviour

The password is changed, but the UI shows error No such file or directory - /usr/sbin/sendmail.  Email channel is not configured as Microsoft 365 channel is already configured successfully and expected to work as the default outbound channel.  On a quick review of the source code (6.3.1) it seems problem lies with lib/notification_factory/mailer.rb (line 165).  Probably it should not use a hard coded value 'Email::Notification' for the area parameter.  One quick fix can be use an environment variable and then use a fallback value.  
e.g.
set env variable EMAIL_OUTBOUND_CHANNEL_AREA=Microsoft365::Account
mailer.rb
# get active Email::Outbound Channel and send
channel_area = ENV['EMAIL_OUTBOUND_CHANNEL_AREA'] || 'Email::Notification'
channel = Channel.find_by(area:  channel_area, active: true)

### Expected behaviour

The email should be sent using the Microsoft 365 Channel and should not try to use local sendmail instead

### Steps to reproduce the behaviour

- Install from source
- Skip SMTP setup in the browser setup flow
- Login as admin and configure Microsoft 365 channel
- Try changing password for the user

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
