### ISSUE TITLE
Variables in text modules don't work within links

### ISSUE THREAD

**Issue by herzkerl** [zammad/zammad#5303]
### Used Zammad Version

6.3.1-1722340033.fc8bee39.bullseye

### Environment

- Installation method: package
- Operating system: Debian 11
- Database + version: psql (PostgreSQL) 13.15 (Debian 13.15-0+deb11u1)
- Elasticsearch version: newest
- Browser + version: not relevant

### Actual behaviour

- The first # is attributed to the link, hence the first variable is not executed
- Also, only the first part, including the #, is linked: `https://booking.domain.tld/#`
- The rest of is just text: `{user.firstname}.Doe/meeting`

### Expected behaviour

The variables should work correctly when used within a link, example below.

`https://booking.domain.tld/#{user.firstname}#{user.lastname}/meeting` should resolve to a link like: `https://booking.domain.tld/John.Doe/meeting`

### Steps to reproduce the behaviour

- Create a text module with the following text: `https://booking.domain.tld/#{user.firstname}#{user.lastname}/meeting`
- Use the text module in a new or existing ticket

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by herzkerl** [comment]
The content of the text module seems to be automatically converted to a link (stopping at the first #) _before_ writing to the database.

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*

**Comment by fliebe92** [comment]
Hi @herzkerl. It really matters how you insert the link.

I just wrote the following snippet in VSCode: `https://booking.domain.tld/#{ticket.owner.firstname}#{ticket.owner.lastname}/meeting`

When I copy & paste it into a text module, then it works fine. Manual inserting of a link is not working fine.
