### ISSUE TITLE
Elasticsearch: Too many buckets [Docker-compose]

### ISSUE THREAD

**Issue by merlinwoff** [zammad/zammad#5306]
### Used Zammad Version

6.3.1-95 (Elasticsearch: 8.14.3)

### Environment

- Installation method: official docker-compose
- Operating system (if you're unsure: `cat /etc/os-release` ): debian 12, but using Docker
- Database + version:  postgresql 15.7-alpine
- Elasticsearch version: 8.14.3
- Browser + version: Chrome 83

### Actual behaviour

In the docker logs of the elasticsearch container, it is always printing the following line:
2024-08-19T13:48:19.291700880Z [2024-08-19T13:48:19,291][WARN ][o.e.s.a.M.MultiBucketConsumer] [0711fcfffaef] Too many buckets (max [65536], count [66627])

We experienced some strange behavior, which we think could be related to this log: Some tickets are not searchable using Elasticsearch (over the Zammad Search Filters regarding the Ticket Titles).

### Expected behaviour

This warning shall not occur.

### Steps to reproduce the behaviour

Using Zammad with the official docker-compose.yaml and having more then 10k Tickets in the database.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by rolfschmidt** [comment]
Hi @merlinwoff,

1. Can you try to re-index the ticket you are missing? Does it work? Can you find the ticket afterwards? Else provide some error output

```
root> zammad run rails c
rails> Ticket.find(1).search_index_update_backend
```

The ticket ID can be found at the end of the ticket URL.

2. Please also search for related errors about the Elasticsearch in your production.log:

```
cd /opt/zammad
cat log/production.log | grep ERROR -A10
```

Would be interesting if you can find the bucket warning there and some traceback or something.

Without any way to reproduce the error, we can really help you. 10k tickets is a small and not the root of the issue. It could be tho that the issue is docker related, which we do not support (https://docs.zammad.org/en/latest/install/docker-compose.html).

I am also not sure if the bucket warning is really the issue of your problem.

**Comment by rolfschmidt** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer to the Zammad community over at: https://community.zammad.org/ .

In case this turns out to be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
If you're a paying customer already, please consult your Zammad support for assistance! :-)
