### ISSUE TITLE
Marking text is not possible anymore with shift+left

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad#5337]
### Used Zammad Version

6.4

### Environment

- Installation method: any
- Operating system (if you're unsure: `cat /etc/os-release` ): any
- Database + version:  any
- Elasticsearch version: any
- Browser + version: Edge

### Actual behaviour

When writing an article or modifying a text field, you can mark text with `shift`+`right arrow`, but not with `shift`+`left arrow`.

If more than one ticket tab is opened, it changes the tab instead, if this is the only ticket, it ignores the shortcut instead.

### Expected behaviour

When writing an article or modifying a text field, you can mark text with `shift`+`right arrow` and `shift`+`left arrow`.

### Steps to reproduce the behaviour

Start writing anything. Ticket title, ticket attribute, article. Try to mark text (e.g. for copy & paste) with `shift` and `left arrow`/`right arrow`. One works, the other doesn't.

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dvuckovic** [comment]
Another (related) combination that does not work anymore is `shift + alt + arrows` (expanding selection by whole words).

**Comment by dvuckovic** [comment]
Additional conflict [was identified](https://community.zammad.org/t/shift-enter-vs-enter/15480): `shift+Enter` in rich text editor is now submitting the form/dialog, but previously it was inserting a forced line break.

Normally, the expected behavior of the editor should be as follows:

* plain `Enter` inserts a new paragraph (e.g. `<div></div>` markup)
* `shift+Enter` inserts a forced line break (e.g. `<br>` markup)

Recommendation is to switch ~~back to require browser hotkeys for submitting the form/dialog, so it would now again be `shift+ctrl+Enter` (`ctrl+option+Enter` on MacOS).~~ to `ctrl+Enter` for confirming/submitting the dialog, as its simple enough and we noticed no further conflicts.
