### ISSUE TITLE
Different error in BE for the name field than in FE for the same field

### ISSUE THREAD

**Issue by kingmanfri** [zammad/zammad#5355]
### Used Zammad Version

6.3

### Environment

- Installation method: helm charts
- Database + version:  [e.g. postgresql 9.3, mysql 5.7, mariadb 10.3]
- Elasticsearch version: [e.g. 7.17]
- Browser + version: [e.g. chrome 83, safari 14, firefox 105]

### Actual behaviour

Why is the text in the error message referring to the 'article body' field? This might be the field name in BE, but in FE the field name is 'Text'.
![image](https://github.com/user-attachments/assets/5f9dc14e-d865-425f-8c58-15a153af73be)

### Expected behaviour

I would expect to see 'Title missing' or 'Text missing'.

### Steps to reproduce the behaviour

1) Open Zammad

2) Create Ticket
3) Add Title

4) Add Group

5) Add Problem

6) Click button Create

7)Check error message

### I'm sure this is a bug and no feature request or a general question.

no

**Comment by t-shehab** [comment]
Hi @kingmanfri,

thanks for opening this issue. Since this is technically not a bug, I invite you to open a thread in our [community](https://community.zammad.org).

Please note that issues are for bug reporting only.

**Comment by dvuckovic** [comment]
This issue is caused by the validation happening too late in the process (on the article model level, not the frontend controller). We already improved this situation immensely in the Desktop Rewrite project, and now this error will bubble up and be shown contextually, as part of the form field. Might be too late to try to fix this in the legacy desktop app, though. It's an architectural issue with the validation stack.

**Comment by dominikklein** [comment]
https://github.com/zammad/zammad/issues/5028

**Comment by kingmanfri** [comment]
@dvuckovic: Do you have an estimated release date for the new desktop version?

**Comment by dvuckovic** [comment]
> @dvuckovic: Do you have an estimated release date for the new desktop version?

Sorry, I don't have such information at this time. I would kindly ask for your patience.
