### ISSUE TITLE
Date field is automatically filled in with the current date.

### ISSUE THREAD

**Issue by MarkusHeld** [zammad/zammad#5370]
### Used Zammad Version

6.3

### Environment

- Installation method: Any, SaaS

### Actual behaviour

When a Date field object is only displayed in the customer edit mask, then the actual date is automatically inserted, when a ticket from the customer is created.

![Bildschirmfoto 2024-10-08 um 18 31 28](https://github.com/user-attachments/assets/a28f2e30-5f8a-47a1-b5c1-86fe52534e86)

https://github.com/user-attachments/assets/594fcab7-96f6-4688-aa22-5f6ee43f0e28

When the object is shown in the creation mask, this doesn't happen.

### Expected behaviour

That not the actual date is inserted automaticly in the object field, the field should be empty.

### Steps to reproduce the behaviour

1. Create a new Date field object, like in the screenshot above
2. Create a new ticket as a customer and leave the object field empty

### Support Ticket

Ticket#10159431

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by dominikklein** [comment]
First it's not related to date fields, it's about the general object attribute default value handling.

Current behavior (creation of object):

1. When an attribute is not present inside the object hash during the creation the default from the object attribute configuration is used (when something was configured).
2. When an attribute is present the default will be completely ignored.

Besides this technical handling in the backend, the frontend is prefilling the visible fields inside the form. It's possible to remove the prefilled default value. Because the field is in this situation always present in the payload, also on the backend side the default will be ignored (e.g. an empty text field means that no default is automatically on the backend side).

This means related to this reported problem. Whenever the field is completely not shown in the form the default value handling from the backend will set a possible configured default value.

I think currently this is the expected behavior. Workaround could be to set a default value with core workflow in a more specific way, but at least for the date field example this is currently not supported inside core workflow.

The next step would be to clarify if this is not the expected behaviour for the product. When no decision is needed, it will lead to a breaking change.
@YetAnotherGerrit

**Comment by YetAnotherGerrit** [comment]
I don't understand, why you expect it not to set a default value, when you specified it should.

This one does not set a default value:
---
![image](https://github.com/user-attachments/assets/5938469d-9700-4d19-8bc0-b007559c06fe)
---

This one does:
---
![image](https://github.com/user-attachments/assets/0955b568-411b-468d-8b6a-5ffe0de67939)
---

As you can see here:
---
![image](https://github.com/user-attachments/assets/e9b70bad-33a8-4c59-aa35-6c227761b84b)
---

**Comment by YetAnotherGerrit** [comment]
Talked with @MarkusHeld - this solved the problem. Issue closed.
