### ISSUE TITLE
Users can see all tickets (because they are Agents and Customer), although only authorized to one group

### ISSUE THREAD

**Issue by ghost** [zammad/zammad#5447]
Users have the role of customer and agent (for a specific internal group, we have several). Since they open tickets for all groups as a customer, but are only allowed to edit and view the tickets of their own group as an agent, and of course the customer tickets they have created themselves (for their own user).

The problem is that as soon as the customer authorization (tickets.customer) and the agent authorization (ticket.agent) are assigned, the user can see all (!) tickets in the system (even those to which he is not actually authorized via the group). All tickets can then be viewed, especially via the search.

Is this a known or desired behavior, or is it a bug?

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
