### ISSUE TITLE
Search query `create_article_type:email` doesn't return any results

### ISSUE THREAD

**Issue by herbetom** [zammad/zammad#5450]
### Used Zammad Version

6.4.1-1734476180.a187f3a5.bullseye

### Environment

- Installation method: package
- Operating system (if you're unsure: `cat /etc/os-release` ): Debian 11.11
- Database + version: postgresql 13+225+deb11u1
- Elasticsearch version: 7.17.26
- Browser + version: chromium 131.0.6778.139

### Actual behaviour

I get an empty result.

### Expected behaviour

I would expect to get all Tickets that started via an email.

### Steps to reproduce the behaviour

1. Visit https://tickets.example.org/#search/create_article_type%3Aemail

(Of course replace tickets.example.org with an zammad instanc ;) )

I found that attribute here: https://user-docs.zammad.org/en/latest/advanced/search.html#ticket-attributes

Maybe i'm just missunderstanding or missusing it. If so that would be of source also good to know. But as of know i would assume it's at least an issue with the documentation. :)

### I'm sure this is a bug and no feature request or a general question.

yes

**Comment by mantas** [comment]
Hi @herbetom 

This looks like a technical question (and inconsistent documentation) rather than a bug. Please use community forums to ask such questions next time. Technically `create_article_type` is a verbose attribute with a metadata hash rather than just a string. Correct search string would be `create_article_type.name:email` :)

@ralf401 just a heads up that there may be some issues with documentation page linked above ;) 

Closing now.
