### ISSUE TITLE
SLA description only available in english

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad#556]
As discussed in #551 with @abendrob we found out that the SLA description is only available in german. Maybe @rkaldung can help us out here?

Source:  https://github.com/zammad/zammad/blob/7df285d9dfc9299afc5b276db4a27b20ef395f87/app/assets/javascripts/app/models/sla.coffee#L21

**Comment by pradorocchi** [comment]
@description = '''
** Service Level Agreements **, abbreviated ** SLAs **, help you to meet certain customers' time-related responses. Thus, for example, you can say customers should always get a response from you after 8 hours at the latest. In the event of an imminent violation or a breach, Zammad will alert you to such events.

It can be ** response time ** (time between the creation of a ticket and the first reaction of an agent), ** update time ** (time between a customer's request and an agent's reaction) and ** solution time ** (time between creation and closing a ticket ) To be defined.

Any threatening violations or violations are displayed in a separate view in the overviews. You can also configure ** e-mail notifications **.
'''

**Comment by thorsteneckel** [comment]
Daaamn! Thats great. I'll add this asap.

**Comment by thorsteneckel** [comment]
As discussed with @martini we changed the text to english. Currently there is no satisfying solution for translating long formatted strings like these. We will implement a proper solution for this.

**Comment by pradorocchi** [comment]
Good morning, 
yesterday I worked on the Brazilian Portuguese translation and already completed 51% of it (I expect to complete 100% until this weekend) and while working on it I found other 3 German text-explanations around the system. I'm sending them for you here translated in English.

I did some interpretation to fit better in english because German sometimes is too "dry". And I checked the explanation by following it and navigating to the system to verify if the explanation is valid for the present system version (i checked with the developer version here). 
Feel free to read and adapt it better if needed.

The translation follows (sorry for not sending it via pull request)


______________________________
Manage - > Organization -> Description:

Mit Organisationen können Sie Kunden gruppieren. Dies hat u. a. zwei bedeutende Vorteile.
1. Als Agent haben Sie nicht nur die Übersicht über die Tickets eines Kunden sondern zusätzlich die Übersicht über die gesamte Organisation. Z. B. über die Suchen nach der Organisation, diese per einfachen klick öffnen.
2. Als Kunde können Sie die Tickets ihrer Kollegen mit einsehen und bearbeiten (sofern die Organisation eine "teilende" ist, dies können Sie je Organisation als Parameter einstellen).


Organizations allows you to group customers. This gives you two important advantages.
1. As an agent, you have not only the overview of the customer's tickets, but also an overview of the entire organization. For example, search around the organization.
2. As a customer, you can view and revise your colleagues' tickets (if the organization is in "shared" mode). You can set this parameter for each organization.



______________________________
Manage -> Overview -> Description

Übersichten können Sie Ihren Agenten und Kunden bereitstellen. Sie dienen als eine Art Arbeitslisten von Aufgaben welche der Agent abarbeiten soll.
Sie können auch individuelle Übersichten für einzelne Agenten oder agenten Gruppen erstellen.

Overviews gives you visibility of your agents and customers. It is a sort of list or aggroupment of tasks, showing details about the agents work.You can also create custom overviews for individual agents or agent groups.



______________________________
Manage -> Calendar -> Description

Ein Kalender wird benötigt um Eskalationen oder Auswertungen anhand von Geschäftszeiten zu berechnen.
Definieren Sie einen "Standard"-Kalender welcher Systemweit gültig ist. Nur in den angegebenen Geschäftszeiten werden Eskalations-Benachrichtigungen an Agenten versendet.
Haben Sie Kunden für welche Sie unterschiedliche Geschäftszeiten einhalten müssen, so können Sie mehrere Kalender anlegen. Die Zuweisung zu den Kunden-Tickets geschieht über die SLAs.


A calendar is required to calculate escalations or evaluations based on Business Hours.
Define a "standard" calendar which is valid throughout the system. Escalation notifications are sent to agents only in the specified calendar business hours.
If you have customers for which you need to work with different business times, you can create several calendars. The allocation of the customer's tickets is done via the SLAs rules.

**Comment by martini** [comment]
by the way, @pradorocchi thanks for your wonderful work! ❤️ 👍🏻

**Comment by mgruner** [comment]
This will be fixed with the migration to Weblate in Zammad 5.1, which is able to handle multi line strings.
