### ISSUE TITLE
Add tagging to bulk action

### ISSUE THREAD

**Issue by tisar** [zammad/zammad#56]
As an agent I want to be able to tag more than one ticket at a time. 

Depending on configuration it should be possible or not to add tags to closed tickets.

**Comment by monotek** [comment]
Still not possible...

**Comment by dschuette** [comment]
+1 
Not implemented yet. The possibility to bulk-tag tickets would have been helpful in order to tag tickets as "legacy" when we had imported hundreds of older mails from an existing Google mailbox.

**Comment by hanneshal** [comment]
Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals

regards
Johannes 
https://community.zammad.org/t/tags-in-bulk-action/24
