### ISSUE TITLE
Original e-mail inclusion at the bottom of sent e-mails

### ISSUE THREAD

**Issue by juliocjulio** [zammad/zammad#571]
### Infos:

* Used Zammad version: Latest version
* Operating system:  Ubuntu Server 16.10
* Browser + version: Chrome 55.0.2883.87

### Question:

Hello, me and my colleagues are testing Zammad and we are expecting to enter production as it satisfy our needs.
My only issue is that when we use Zammad to answer our Support Department e-mails, we don't have any option to show the original e-mail from the Customer at the bottom of our response. Just like any e-mail client would do.

Is this a known request feature? Thank you very much, you guys are great.

**Comment by martini** [comment]
Hi @juliocjulio 

we decided to do not blow up emails by full quotes. We implemented a smart way to quote related content by selecting and pressing "reply". See the attached gif.

![reply_and_quote](https://cloud.githubusercontent.com/assets/110226/21523978/e964f8aa-cd12-11e6-9733-1b32bdc33da0.gif)
 
Any feedback is welcome!

 -Martin

**Comment by olivergrahl** [comment]
I understand the idea behind that decision. Still, I would as well prefer an (optional) full quote of the whole conversation at the end of each email sent. Some reasons:

- I totally dislike that quote-answer-quote-answer-quote-answer communication style. I prefer to reply in full sentences and refer to the original inquiry in text form, often summarizing a problem in a short sentence, instead of quoting the lengthy original inquiry. In many cases, this even helps the inquiring party to understand their real problem.

- Without the ability to scroll down to read the whole story, on a longer conversation more and more information gets lost on each reply, and I would be forcing the customer to log in to the web interface to understand the whole story, something they rarely will or want to do. 

- I want to communicate with them as if I would just have replied to their email. They don't need to bother with the technical fact that I'm using a ticket system. 

- When dealing with teams, the person reviewing your reply may not be the person who raized the question. It helps them getting up to date as quick as possible, when they can review the whole conversation. Everybody's used to those long quote bodies. Like them or dislike them - they work.

The only counter argument I see are the wasted bytes storing all that redundant information. And that should be my problem, not my customer's.

Just my 2ct. :-)

**Comment by martini** [comment]
@juliocjulio you also want a config option for blown full quotes? 🤔

**Comment by martini** [comment]
@juliocjulio 

> On another topic, I tried emulating the designation drop zone but couldn't get it to work, do I need to open a new issue?

I can't follow what your goal is (a dummy screenshot would be fine). Yes, a new issue would be fine!

**Comment by juliocjulio** [comment]
@olivergrahl This is exactly our issue. We are a Video Management Software development company and many of our problems require lots of e-mailing to understand, gather information and then choose the right analyst to solve the problem. Currently there's no Helpdesk Suite that fully satisfy our needs but Zammad is very close, the more I use it the more I find ways of exploring it's potential.

@martini Yes, I would really like to have that option. :) I don't really feel like I should be asking this as it's free and open source. This is my first ever interaction with this kind of project so if you guys need any help I can provide, please let me contribute.

**Comment by olivergrahl** [comment]
I guess it would be fine to strip the signature part from each article in the full quote, so it would just be the same content we initially see in Zammad.

**Comment by lilltiger** [comment]
This is indeed a needed feature, for us not having this is a deal killer, way to much extra work for our help desk to copy in the whole conversation all the time.

I need it to look just like a regular e-mail conversation to our customers.

**Comment by ktwe** [comment]
+1

A combination of a changeable default behavior and some shortcut to include/exclude the full quote within the ticket view would be very nice.

**Comment by MartinBorg** [comment]
I very much hate full quotes and TOFU.
Unfortunately, many people in my working environment disagree.
+1 for shortcut.
Default to current behaviour is OK for me.

**Comment by pedrogui** [comment]
+1

is there any development on this one?

**Comment by martini** [comment]
How about this propose? 

![full-quote](https://user-images.githubusercontent.com/110226/28157204-091c223e-67b6-11e7-9604-c0673d21e239.gif)

**Comment by ktwe** [comment]
So when just clicking on Reply, a full quote is attached to the bottom of the mail?

**Comment by martini** [comment]
> So when just clicking on Reply, a full quote is attached to the bottom of the mail?

Exactly.

**Comment by olivergrahl** [comment]
Full quote means all the conversation, or just the last message from above?

**Comment by martini** [comment]
> Full quote means all the conversation, or just the last message from above?

Full quote as it is in a normal email client. -> Always adding the last full message (article) where you press reply - to the bottom the new email. You can still change content in there (like in an normal email client).

**Comment by olivergrahl** [comment]
This would be a great addition!

Our previous ticket system adds the conversation's full history to the bottom of all outgoing emails. A cleaned up view that does not include any quotes. Similar to the view you get within the ticket system. 

It does that "under the hood" when sending out those emails. So, the quotes don't get stored with the reply.

I always liked that approach. The customer always has the full history, no matter what. But a quote feature just like in an email client solves most of what I need, as well!

**Comment by juliocjulio** [comment]
Hi @martini 
The proposed quote would work wonders for us!

As @olivergrahl pointed, there are rooms for improvement, but again, it also solves most of what we need here too.

We are looking foward to have this new feature and I'm sure many people will like it too. Is it expected to launch with the next version?

**Comment by martini** [comment]
@juliocjulio @olivergrahl thanks for all your wonderful feedback!

I close this issue for now (because IMO the subject got implemented). I can understand the feature of @olivergrahl - this is fine if you have a 1:1 conversation with the customer. If you involve other people like providers or vendors it would not be possible to generate it automatically. However in certain use cases it would be great (in case - a new feature issue would be fine). 

@juliocjulio If you want to use the feature now you could upgrade to master until next stable is out. We work on next release/stable hard (it's going to be a new major version - will come soon).

**Comment by olivergrahl** [comment]
Perfect! :-) Already super excited about 2.0, can't wait!! :-)

**Comment by ondrejgazda** [comment]
Hi, I'm not able to find this feature (full quote) in 2.1 - was it removed? Thanks.

**Comment by IQNeoXen** [comment]
> How about this propose?

This looks like exactly what I need - however, Zammad is not quoting the whole ticket by default when just clicking "reply".
I can't find any options to enable it. Am I just blind or is it hidden somewhere?

Thank you very much in advance, sorry for opening this again..

**Comment by martini** [comment]
@IQNeoXen this is the wrong place to ask, please follow https://community.zammad.org (hint -> ticket zoom -> settings icon -> Email - full quote)

**Comment by JsBergbau** [comment]
For those who find via Google here, https://community.zammad.org/t/how-to-setting-full-quote-original-e-mail-content/615 is the Community Link how to edit setting
