### ISSUE TITLE
email forward of article (like regular email client forward - e. g. forward customers message to third party contact)

### ISSUE THREAD

**Issue by Johannes-GitHub** [zammad/zammad#573]
### Infos:

* Used Zammad version: 1.1.1
* Operating system: Ubuntu 
* Browser + version: Firefox

### Expected behavior:

Hi @ all, 
we want to move ticket´s forward via eMail, incl. Attachments and Text. 
Can you please take a look? 

### Actual behavior:
Actually we can only answer via eMail, or do it with split the ticket. 

### Steps to reproduce the behavior:
Open Zammad ;) .

**Comment by Johannes-GitHub** [comment]
Hi Update: 
Found following, when i copy (ctrl +c) Text an klick at answer, 
the text will add in my answer. But the files are missing.

**Comment by thorsteneckel** [comment]
#581 requests something similar. I'll flag this here as an duplicate since the other issues provides some more feature requests regarding the same functionality.

**Comment by martini** [comment]
@thorsteneckel JFI #581 is different. This only means the regular "forward" like in an email client.

**Comment by fantaaaaaa** [comment]
Hi Martin,

as discussed, we would also welcome this feature. What's important in forwards is making sure that the forwarded conversation and the original conversation do not interfere and that you can not accidentaly mix up the conversations and let the recipients see stuff from the other conversation.

also it should be possible to forward the attachment of a conversation or the message too and be able to modify the forwarded text during editing and before sending the message.

Thanks!

**Comment by markum** [comment]
Ich think we should talk use cases here. We - Locomore - would like to have this feature too. I would help us very much in the sense of structuring communication. 
Use case one would not have the danger of mixing up things:
- We sometimes receive mails in support which are not handled by the support team, but rather by e.g. marketing or press. These departments do not use zammad and won't do it in future. In those cases 2 variations would make sense. First: Forwarding of the original mail with unmodified sender. Second: Forwarding of the mail with a comment (then with the individual email of the supporter, not the generic support address). In both cases there would not be a followup in zammad. So no mixup could happen because the further handling will happen outside of zammad and answers wont even land there.
Use case two
- There is a question about a support mail which can not be handled by the support team. So the support team forwards externally from Zammad within the company and the supporter awaits the reply so that he or she can formulate the answer. The easy solution to avoid a mix up could be to have a variation of usecase one second usecase: The forward contains the ticket#, but since the sender is the personal email of the supporter, the answer is received outside in the normal emailprogramm. With ticket number the supporter can easily connect ticket and the answer. An improvement could be creating a new ticket which is linked to the old ticket. So that the above feared mixup can be avoided and it is also easier to follow what happened.
Usecase two may be more complicated to impliment. Usecase one would be a big improvement for us.

**Comment by fantaaaaaa** [comment]
@markum We can absolutely relate to your usecases and would love "linked forwards" to enable a separate conversation for a third level support or an external partner. When the issue in the forwarded conversation is resolved, we can easily switch back to the original "parent"-conversation and give feedback to the customer!

**Comment by martini** [comment]
Thanks, it's Christmas soon!
