### ISSUE TITLE
Change Ruby Port

### ISSUE THREAD

**Issue by factor200x** [zammad/zammad#592]
Hello,

I have the problem that I have to change the port of the WebServer after installation from now 3000 to 3001. Can someone tell me where I must make the setting?

Thank you very very much
Olaf

**Comment by factor200x** [comment]
Hello, 

Has done, found it.

bye
Olaf

**Comment by martini** [comment]
Thanks for feedback!

**Comment by ikolubr** [comment]
I know the issue is closed... but how did you change it?

Thank you

**Comment by odit** [comment]
@ikolubr 
shell> rails s -p 3001 &

in production, you need change /etc/nginx/sites-enabled/zammad.conf:
upstream zammad {
    server localhost:3001;
}

**Comment by ikolubr** [comment]
I'm using Debian 8. if I type zammad run rails s -p 3001 it works, but how do I make that change define.
Sorry man.. I never played with Rails before. Is there a file I can change and the service will work from now on on the port 3001?

Thank you,

**Comment by odit** [comment]
in config/puma.rb add one line:
port 3001

Enjoy.

**Comment by ikolubr** [comment]
Here is my config/puma.rb but it didn't work. Still port 3000.
`workers Integer(ENV['WEB_CONCURRENCY'] || 0)
threads_count_min = Integer(ENV['MIN_THREADS'] || 5)
threads_count_max = Integer(ENV['MAX_THREADS'] || 30)
threads threads_count_min, threads_count_max

preload_app!

on_worker_boot do
  ActiveRecord::Base.establish_connection
end
port 3001`

**Comment by odit** [comment]
Sorry, I fixed this file:
`workers Integer(ENV['WEB_CONCURRENCY'] || 0)
threads_count_min = Integer(ENV['MIN_THREADS'] || 5)
threads_count_max = Integer(ENV['MAX_THREADS'] || 30)
threads threads_count_min, threads_count_max
port 3001

preload_app!

on_worker_boot do
  ActiveRecord::Base.establish_connection
end`

**Comment by ikolubr** [comment]
@odit thanks you for your help... but no deal..
I edit the file as you requested.. what now?! I do a service zammad restart, I even rebooted the server but no deal... still listening on port 3000.

**Comment by hamzehmohammadnia** [comment]
Im struggling with Zammad process too. Im trying to make RPM installation of Zammad to work with MySQL and Apache.Due to applying some changes on Zammad (installing MySQL) and working on Centos 7 (using RPM version of Zammad), the process that initiates the listening port is deactivated... I can see that when I look at the listening port.

I dunno how I can fix it... If any suggestion, I'd appreciate it @odit  
In my case, "zammad run rails s -p 3000 & "solves the problem and web front gets initiated but it looks not very stable since if i close the console, webfront crashes down. I need to fix it to work with services rather than manual command line.

The status of Zammad processes:




systemctl status zammad
● zammad.service
   Loaded: loaded (/etc/systemd/system/zammad.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-06-12 12:27:01 UTC; 2min 17s ago
 Main PID: 27719 (sleep)
   CGroup: /system.slice/zammad.service
           └─27719 /bin/sleep infinity

Jun 12 12:27:01 ...[1]: Started zammad.service.
Jun 12 12:27:01...[1]: Starting zammad.service...



 systemctl status postgresql
● postgresql.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql.service; disabled; vendor preset: disabled)
   Active: inactive (dead)


systemctl status mysqld
● mysqld.service - MySQL Server
   Loaded: loaded (/usr/lib/systemd/system/mysqld.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-06-12 12:26:56 UTC; 4min 11s ago
     Docs: man:mysqld(8)
           http://dev.mysql.com/doc/refman/en/using-systemd.html
  Process: 27535 ExecStart=/usr/sbin/mysqld --daemonize --pid-file=/var/run/mysqld/mysqld.pid $MYSQLD_OPTS (code=exited, status=0/SUCCESS)
  Process: 27429 ExecStartPre=/usr/bin/mysqld_pre_systemd (code=exited, status=0/SUCCESS)
 Main PID: 27539 (mysqld)
   CGroup: /system.slice/mysqld.service
           └─27539 /usr/sbin/mysqld --daemonize --pid-file=/var/run/mysqld/mysqld.pid

Jun 12 12:26:37 ...[1]: Starting MySQL Server...
Jun 12 12:26:56 ...[1]: Started MySQL Server.



systemctl status httpd
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-06-08 16:14:06 UTC; 3 days ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 4413 ExecReload=/usr/sbin/httpd $OPTIONS -k graceful (code=exited, status=0/SUCCESS)
 Main PID: 8430 (httpd)
   Status: "Total requests: 0; Current requests/sec: 0; Current traffic:   0 B/sec"
   CGroup: /system.slice/httpd.service
           ├─ 4415 /usr/sbin/httpd -DFOREGROUND
           ├─ 4416 /usr/sbin/httpd -DFOREGROUND
           ├─ 4417 /usr/sbin/httpd -DFOREGROUND
           ├─ 4418 /usr/sbin/httpd -DFOREGROUND
           ├─ 4419 /usr/sbin/httpd -DFOREGROUND
           ├─ 8430 /usr/sbin/httpd -DFOREGROUND
           └─29337 /usr/sbin/httpd -DFOREGROUND

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

systemctl status zammad-web
● zammad-web.service
   Loaded: loaded (/etc/systemd/system/zammad-web.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-06-12 12:27:04 UTC; 5min ago
 Main PID: 27847 (sleep)
   CGroup: /system.slice/zammad-web.service
           └─27847 /bin/sleep infinity

Jun 12 12:27:04 ...[1]: Started zammad-web.service.
Jun 12 12:27:04 ...[1]: Starting zammad-web.service...

BUT:

systemctl status zammad-web-1 -l
systemctl status zammad-web-1 -l
● zammad-web-1.service
   Loaded: loaded (/etc/systemd/system/zammad-web-1.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-06-12 12:33:11 UTC; 5s ago
 Main PID: 30964 (ruby)
   CGroup: /system.slice/zammad-web-1.service
           └─30964 /opt/zammad/vendor/ruby-2.3.1/bin/ruby bin/rails s -p 3000

Jun 12 12:33:11 ... systemd[1]: zammad-web-1.service holdoff time over, scheduling restart.
Jun 12 12:33:11 ... systemd[1]: Started zammad-web-1.service.
Jun 12 12:33:11 ... systemd[1]: Starting zammad-web-1.service...
Jun 12 12:33:12 ... zammad-web-1.service[30964]: /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/zammad/bin in PATH, mode 040777
Jun 12 12:33:14 zammad-ansiblever zammad-web-1.service[30964]: /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/zammad/vendor/bundle/ruby/2.3.0/bin in PATH, mode 040777
Jun 12 12:33:16 zammad-ansiblever zammad-web-1.service[30964]: /opt/zammad/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /opt/zammad/vendor/bundle/ruby/2.3.0/bin in PATH, mode 040777



Thank you in advance,
