### ISSUE TITLE
Configurable ticket prioritys

### ISSUE THREAD

**Issue by monotek** [zammad/zammad#61]
We need configurable ticket prioritys.

I would suggest 10 levels. 5 was not enoug for us. 

Levels should be configurable and every level should have another backround color or some other kind of visaul feature.

Levels (amount an color) should be configurable.

**Comment by hanneshal** [comment]
Since november 15th we handle such requests at our community board. [Board](https://community.zammad.org/t/major-change-regarding-github-issues-community-board/21)

If you like to see this in Zammad feel free to start a topic at:
https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals

regards
Johannes
