### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by kernbrand** [zammad/zammad#637]
new installation of zammad on debian (installed from source, not the deb)
the dashboard shows 

StatusCode: 500
{"error":"Input/output error @ io_write - \u003cSTDOUT\u003e"}

after login. 

i assume that this is caused by

zammad@1484294723-1:~$ script/websocket-server.rb start
/opt/zammad/config/environments/development.rb:37:in `block in <top (required)>': uninitialized constant Rack::LiveReload (NameError)
 from /opt/zammad/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `instance_eval'
        from /opt/zammad/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/railtie.rb:210:in `configure'
        from /opt/zammad/config/environments/development.rb:1:in `<top (required)>'
...

any ideas how to fix this?

**Comment by thorsteneckel** [comment]
Hi @kernbrand - seems your startup is done in the `development` rails environment which is default. Try to export `export RAILS_ENV=production` before you start your server and the services should start fine.

Nevertheless it's highly recommended to use the Zammad Debian package since it makes updating Zammad a breeze. 🤓

**Comment by kernbrand** [comment]
hi thorsteneckel,

thanks :) yes, i forgot to call "export RAILS_ENV=production". 

i tried the deb installation, but unfortunately it doesn't work for me. i was not able to start the scheduler (don't ask for the error, i forgot it immediately).
