### ISSUE TITLE
Ticket were shown twice

### ISSUE THREAD

**Issue by rkaldung** [zammad/zammad#655]
### Infos:

* Used Zammad version: latest
* Operating system: CentOS 7
* Browser + version: Google Chrome latest + macOS

### Expected behavior:

* Recent viewed tickets were unique.

### Actual behavior:

* Tickets were shown twice in the link dialog under recent viewed tickets.

### Steps to reproduce the behavior:

* Twice pen a ticket and close the tab, then open the link dialog in anther ticket.

![image](https://cloud.githubusercontent.com/assets/378324/22142663/68a430a4-def7-11e6-8583-1c2b4e5e533a.png)

**Comment by rolfschmidt** [comment]
Hi @rkaldung 
should be fixed now in develop branch.

-Rolf

**Comment by rkaldung** [comment]
I recommend to remove the open ticket from the list too ;-)

**Comment by rolfschmidt** [comment]
Hi @rkaldung 

* Open ticket got removed from the list of related tickets
* z-index for the error messages in the modal dialog got fixed by @mrflix 

![grafik](https://cloud.githubusercontent.com/assets/5445062/25478384/28edc22c-2b41-11e7-8aab-1564aca1cd66.png)

Should be fine now in develop branch ;-)
