### ISSUE TITLE
Shortcuts in different keyboard layout

### ISSUE THREAD

**Issue by tojaskiba** [zammad/zammad#656]
* Used Zammad version: 1.2.0
* Operating system: Windows 7 Proffesional
* Browser + version: Chromium 57
* Ticket-ID: #1048406, #1076974, #1081532, #10106475, #10115149

When using Polish keyboard, using special character like ę with alt+e triggers logout shortcut.
Maybe zammad should use ctrl + shift?

**Comment by skibson** [comment]
What is the best way to turn off shortcuts system wide? Maybe such option should appear also in every user's profile settings menu?

**Comment by maege** [comment]
Same Problem by typing @ in swiss german layout -> (Ctrl + Alt + 2) will result in h2 title.

**Comment by skibson** [comment]
i fixed this in our installation by changing line 127 in app/assets/javascripts/app/lib/base/jquery.contenteditable.js
from e.altKey to e.shiftKey

**Comment by martini** [comment]
The current idea is to move to different shortcuts for windows/mac:

mac: ctrl+alt
windows: ctrl+shift

Any feedback about this? @johan12345

**Comment by johan12345** [comment]
Yeah, changing to Ctrl+Shift would probably be more conflict-free solution than the current one. Some shortcuts could even be done just with ctrl (for example, Ctrl+B, Ctrl+U, Ctrl+I are quite common for text formatting, and the same thing on Mac with Cmd+B, Cmd+U, Cmd+I).

The most flexible way would of course be to make the shortcuts user-configurable, but that's also more time-consuming to implement.

**Comment by monotek** [comment]
@martini 
Why not "ctrl + shift" everywhere?

**Comment by martini** [comment]
> for example, Ctrl+B, Ctrl+U, Ctrl+I are quite common for text formatting, and the same thing on Mac with Cmd+B, Cmd+U, Cmd+I

Thanks a good idea! Done.

> Why not "ctrl + shift" everywhere?

There are some native mac shortcuts on mac with ctrl+shift which conflict then.

Shortcuts are now dependent on OS (in develop branch). Feedback if there are still conflicts would be good!

Mac:
<img width="746" alt="screen shot 2017-04-10 at 00 01 45" src="https://cloud.githubusercontent.com/assets/110226/24841283/722263c6-1d81-11e7-8b19-a8b1ef014dd2.png">

Win:
<img width="757" alt="screen shot 2017-04-09 at 23 53 04" src="https://cloud.githubusercontent.com/assets/110226/24841284/7d3c2bca-1d81-11e7-922c-fc6b07c829c5.png">

**Comment by zabarabab** [comment]
ctrl-shift-w closes firefox on linux ;-(

**Comment by skibson** [comment]
Right, ctrl+shift is base of many browser shortcuts

**Comment by maege** [comment]
Hi
We have no issues with the new shortcuts. Thank you :-)
I think a other nice shortcut is: Ctrl + Enter for sending E-Mail or Article like Outlook:
![image](https://cloud.githubusercontent.com/assets/25299891/25797430/776f9480-33dd-11e7-9b7f-15b999c284fd.png)
Outlook prevents accidental sending with the the sending with the warning above (you can just press enter to accept the warning and send the mail)

**Comment by AND51** [comment]
Dear all,
Dear rolfschmidt,

According to rolfschmidt in #1052, I would like to express my opinion here. I consider "shortcut issues" a difficult topic, because of all these github issues regarding that topic. Also, I apologize in advance, if sombody has already said what I want to say now.

I mainly use two browsers, Firefox and Vivaldi. I work with Zendesk a lot and – it's a miracle – Zendesk hardly collides with browser-shortcuts. I don't know why :-D
However, the combination of Firefox/Zammad and especially Vivaldi/Zammad is quite different.

I like the way you can configure the shortcuts in Vivaldi. I think, this is also a reasonable way for Zammad. Plus, the Zammad-team can deliver Zammad with a collection of "best practice shortcuts". People may configure other shortcuts (globally or per account), if they need to.

Here is what the shortcut screen looks like in Vivaldi, but I'm sure you have already seen this in other applications, too:

![image](https://cloud.githubusercontent.com/assets/26226303/26496758/0e5388bc-4229-11e7-9023-45fb7cdaa2f6.png)

**Comment by thorsteneckel** [comment]
> I like the way you can configure the shortcuts in Vivaldi. I think, this is also a reasonable way for Zammad. Plus, the Zammad-team can deliver Zammad with a collection of "best practice shortcuts". People may configure other shortcuts (globally or per account), if they need to.

++

**Comment by abckas** [comment]
Since my ticket got closed while it's not mentioned here... Pressing "Shift + Ctrl + N" opens a new private window in google chrome

**Comment by pinscher** [comment]
It makes no sense to use shift+ctrl on windows because shift+ctrl  is used already by many browser shortcuts (chrome, firefox). Zendesk is using on windows Strg+Alt instead. This is much better cause there are no browser shortscuts existing for Strg+Alt. 

Also thre must be a shortcut to change the state, e.g. like in Zendesk:
![image](https://user-images.githubusercontent.com/415306/50970179-f6f51f00-14e0-11e9-9fdb-87b02f6679a4.png)

**Comment by blizzz** [comment]
I accidentally triggered the "update as closed" function several times when I only wanted to copy text. Ctrl+Shift+C is copying on terminal. Of course I am in the browser now, yet muscle memory comes into play.

**Comment by ekafaton** [comment]
Is there any news regarding this issue? I have to re-write long responses on a regular basis because I use CTRL+T a lot which deletes everything written inside the textbox. Of course this is very frustrating, we don't even need the zammad shortcuts.
Allowing us to disable the shortcut globally would be a fantastic workaround until a solution is found.

**Comment by MrGeneration** [comment]
This is currently in feature backlog and doesn't have an ETA.
As soon as this moves in any direction we will update it accordingly.

Please stop bumping issues in this repository, because it creates noise, distraction and doesn't speed up the process at any point.

I'm thus limitting the conversation to contributors only. I hope you can understand this.

**Comment by thorsteneckel** [comment]
JFI: It's not possible to enter the translation mode in some scenarios. As a workaround you can activate it by pasting these values in the console of your browser:

```js
App.Config.set('translation_inline', true)
App.Event.trigger('ui:rerender')
```

Once you're done make sure to leave the mode again by pasting these lines into your browser console:

```js
App.Config.set('translation_inline', false)
App.Event.trigger('ui:rerender')
```

**Comment by Mirtaaa** [comment]
Closed and new opened for structuring reasons:
https://github.com/zammad/zammad/issues/4870
