### ISSUE TITLE
Who assigned a Ticket to the Agent

### ISSUE THREAD

**Issue by AdiosOnline** [zammad/zammad#669]
Hi,

It would be awesome to see, who has assigned a Ticket to the current Agent. A little Note like the "Email sent" Notifications between the Ticket Notes, would be enough to keep an eye on the previous way of the Ticket.

Regards Jorrit

**Comment by thorsteneckel** [comment]
Hi @AdiosOnline - you can see this information in the ticket history. Our goal is to keep Zammad slim and simple. Therefore we cluster all functionalities into respective views (e.g. history). Since the agent information is not necessary in the detail view we won't add it (yet). If there are enough requests we may come back to it.

**Comment by AdiosOnline** [comment]
Hi @thorsteneckel ,
This is exactly what I need but not found... So there is no reason to relay on this Issue. Please close it as Solved!  Sorry for this unnecessary Issue posting..

Thanks Jorrit

**Comment by thorsteneckel** [comment]
No problem - that's why we are here 🤓
