### ISSUE TITLE
Set individual organizations per ticket

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#676]
Currently there is already an information about the organization at the ticket (tickets.organization_id). There is a possibility needed to set the organization based on the ticket individual and not customer based.

This will create the opportunity to have a customer with multiple organization relations and the agent can decide which organization he wants to relate the ticket to.

**Comment by dritier** [comment]
Hello together... is this somehow on track or can I help somehow getting this integrated?

**Comment by rolfschmidt** [comment]
dup of https://github.com/zammad/zammad/issues/1573

**Comment by gduprey** [comment]
It really does not seem like a duplicate of 1573.  That issue is about assigning a user to multiple organizations.

This issue is about assigning which organization is applicable to a specific ticket.

Case in point: Ticket is opened by a customer/user who has a primary organization and several secondary.  That user services multiple organizations.  As such, they can open a ticket for any of them, but currently, the ticket is only classified as being in the primary organization.  

Perfectly sane default, of course, but if there was a drop-down in the Ticket pane that allowed selecting a different organization, even if limited to primary/secondary organizations for the user/customer who opened the ticket, it would help a great deal in tracking tickets by the actual requesting organization
