### ISSUE TITLE
Disallow creation of new tickets if customer is inactive

### ISSUE THREAD

**Issue by madd86** [zammad/zammad#721]
Right now, if customer is inactive, you can still create tickets.

How can we block that from happening?

**Comment by martini** [comment]
Hi @madd86 

you mean you still can create tickets via email?

 -Martin

**Comment by madd86** [comment]
I can still create any kind of ticket. Inbound phone call, outbount as well as e-mail.

That shouldn't be the case. A cheap solutions would be to remove it from listing when searching for the name, but a better one would be to warn the user is inactive and prevent creation of a new ticket.

**Comment by thorsteneckel** [comment]
@muhammadn - This might be tricky. Please wait for QA after my vacation. Thanks!

**Comment by tswaehn** [comment]
This seems to be still open. We deactivate non existent users, but the user can still create tickets.

**Comment by SummerStorm** [comment]
We are adding the ability to delete users soon (issue #2074), and a deleted user cannot create tickets. So that new feature will get you guys exactly what you want.

In the meanwhile, the inactive flag is purely a visual indicator that carries no restrictions on what that user can do. An inactive user is still allowed to create and respond to tickets. 

For more information please see this [community board post](https://community.zammad.org/t/clarification-about-the-active-flag/963).
