### ISSUE TITLE
Long living tickets get confusing

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad#737]
User recommendation:
It would be great to have a addional compressed article list in the ticket zoom to have more overview. This would help in long living tickets with much articles. I liked the compressed article overview in OTRS an it would be great to have something similar in Zammad.

**Comment by thorsteneckel** [comment]
IMHO this sounds like a solution for a problem that is not clearly specified. Ok, long living tickets get confusing. But isn't it caused by to much text and a missing summary? I would like to hear what is it what makes this long living tickets so confusing and what actions take long and are not satisfying.

**Comment by rolfschmidt** [comment]
Ticket# 101667

**Comment by hanneshal** [comment]
Closed. Due incomplete spec + age
