### ISSUE TITLE
Pagination missing / broken

### ISSUE THREAD

**Issue by nidico** [zammad/zammad#787]
If I understand correctly, an overview shows the first 500 entries by default (since c8f329d9c0e31435abfcd27c0f26818c816167c9). However there doesn't seem to be any way to get to the next pages.

This is particularly critical if reordering is used, as in the following example:

- Say we have 600 open issues
- An overview "open issues, oldest first" shows the oldest 500 issues
- Resorting to "newest first" by clicking on the `created_at` table sorter now resorts the same (oldest) 500 issues, instead of the expected behavior - showing the newest 500 open issues.

### Infos:

* Used Zammad version: 1.3.0
* Operating system: Ubuntu 16.04
* Browser + version: Chromium 55

**Comment by MrGeneration** [comment]
I'm not quite sure on what topic we are here - I suspect we're talking about overviews.
This is working by now, which is why I'm closing this issue.

If you feel this is a mistake, please let us know why exactly, to understand it better.
![overview-sorting](https://user-images.githubusercontent.com/6549061/59345623-c7a54100-8d10-11e9-9459-c090349c70a0.gif)
