### ISSUE TITLE
Descriptions Languages

### ISSUE THREAD

**Issue by Toucan-Sam** [zammad/zammad#812]
### Infos:
* Used Zammad version: 1.3.0
* Operating system: CentOS 7
* Browser + version: All

When clicking on "Description" at the top of a section, the language should match the base install. There are still a few sections that have German (fixed) descriptions. There is a similar issue with #556 but only covers SLAs (which looks finished). Remaining areas to translate are:

Organizations
Overviews
Calendars

**Comment by em-ex** [comment]
BTW, as of 2.0.0 descriptions for Organizations, Overviews and Calendars are still shown in German, despite what language is set in browser.

**Comment by thorsteneckel** [comment]
#556 is a duplicate / related issue to this.

The cause is that there is currently no performant way of translating these texts without sending all translations to the client despite only one is needed. This would (currently) slow down the initial startup time and the application in general because it will hold all translations in memory.
We have to find a proper solution for this but this might take some time 😖
