### ISSUE TITLE
Ticket Attachments

### ISSUE THREAD

**Issue by ThePatzen** [zammad/zammad#846]
Hi!

Is there a way to show image-attachments insight the Ticket? (No need for downloading?)

It would also be nice to open Attachments like html and pdf in the browser and not as download.

### Infos:

* Used Zammad version: 1.3.x
* Operating system: Ubuntu 16.04
* Browser + version: Chrome 56

Thanks for your time!
Best regards from austria!
- David

**Comment by martini** [comment]
Hi @ThePatzen 

1) forcing of downloading attachments is for security reasons (otherwise an attacher could execute code in your browser and act as you)

2) If you use inline images (for example copy an image to clipboard and insert it via ctrl+v in you text area), the image will be shown inline.

Note: Upcoming Zammad release supports also showing images for html emails.

For later we work on preview mode of attached attachments. But this is not available for now.

 -Martin

**Comment by ThePatzen** [comment]
Hi @martini 
Thank you for your quick response!
So i'm looking forward to this preview feature! 

David
