### ISSUE TITLE
Indistiguable Owner on multi-group customer

### ISSUE THREAD

**Issue by gpkvt** [zammad/zammad#863]
### Infos:

* Used Zammad version: latest docker-compose (reports 1.3, should be 1.4)

### Actual behavior:

* When you have two groups (2 different incoming mail accounts) and one customer submits tickets to both of them. Any Agent with proper access rights is listed twice in the owner drop down menu on ticket view.

### Expected behavior:

* The agent should be listed only once, or the group name should be listed after the agent name as well.

### Steps to reproduce the behavior:

* Create a new group
* Create a new incoming mail account
* Grant Agent access rights to at least two groups
* Create first ticket with CustomerA in Group A
* Create second ticket with Customer A in Group B
* View first ticket an select Owner
* Agent is listed twice

**Comment by martini** [comment]
Hi @gpkvt 

wow. I can't reproduce this. Can you add a screenshots?

Thanks!

 -Martin

**Comment by gpkvt** [comment]
Hi @martini 

sure.

Add two incoming Mailaccounts (support and test):

![1](https://cloud.githubusercontent.com/assets/296982/24219583/9ae3621c-0f47-11e7-8aaa-5d3d524687be.png)

Create a new group and assign test-mailaddress (support already was assigned to a different group during setup):

![2](https://cloud.githubusercontent.com/assets/296982/24219591/a28c99ac-0f47-11e7-93f7-e786fb54aaa0.png)

Have the same customer write to test- and support-mailadress at least once, open any ticket of this customer and have a look at the Owner-Drop Down-Menu:

![3](https://cloud.githubusercontent.com/assets/296982/24219594/a8f856a0-0f47-11e7-984a-f0b2ee37786e.png)

Hope that helps. Let me know if you need more informations. 

Thanks!

**Comment by gpkvt** [comment]
It is working without problems if no "Role" is added.

**Comment by rolfschmidt** [comment]
Hi @gpkvt ,
i tried to reproduce the problem but i was not able to reproduce it on our test systems with 2 mail accounts and multiple groups. Please check if the issue is still existing on the newest versions of zammad. You also can use our test systems to help us to reproduce the problem on our hosted systems (if you have some mail test accounts):

https://zammad.com/getting-started

Please reopen the issue if you are able to reproduce the problem on a actual version of zammad.

Best regards,
Rolf
