### ISSUE TITLE
Inline images within A tags don't display

### ISSUE THREAD

**Issue by olivergrahl** [zammad/zammad#872]
Firstly, thank you so much for implementing #343 (show inline images), much appreciated!

### Infos:

* Used Zammad version: 1.4.0
* Operating system: ubuntu:16.04
* Browser + version: FF 51

### Expected behavior:

* Display inline images no matter what

### Actual behavior:

* Inline images don't display when nested within a link (`<a>`) tag.

### Steps to reproduce the behavior:

While this inline image displays nicely:
`<img src="cid:part1.36125BD4.8C34B81F@foo.com">
`
This one doesn't display at all:
`<a href="http://www.zammad.org"><img src="cid:part1.36125BD4.8C34B81F@foo.com"></a>
`
It displays the linked URL instead:
`http://www.zammad.org
`

**Comment by martini** [comment]
Hi @olivergrahl 

currently this works as designed. In our tests we only found spam emails which contains images with links. User added images normally have no links (because the user normally only want's to show the image).

So currently we just replace images with the link.

Maybe you have a different use case where this doesn't fit?

 -Martin

**Comment by olivergrahl** [comment]
My use case was my very own email signature which has our logo in it, linked to our website. I could assume I'm not the only one having it set up like this. But in the end I don't care too much about not seeing images in signatures. It was just the first thing I tried to try the new feature. So you can probably close this issue.

**Comment by martini** [comment]
Thanks for feedback.

Indeed I just had incoming emails in mind. 🙈
