### ISSUE TITLE
Rocket.Chat

### ISSUE THREAD

**Issue by mcmenkes** [zammad/zammad#878]
Hi there, 

as a feature request i would like to promote a Rocket.Chat (https://rocket.chat/) integration as additional channel. RC is an opensource replacement for slack. 

We would like to add this as an internal channel, because Twitter, Facebook, Telegram and Slack doesn't match our requirements regarding security, privacy and costs. Most of our internal communication is going through our internal Rocket.Chat servers, which is a really (!) great piece of software like zammad is too. 

EDIT: The process should be that users can submit tickets from Rocket.Chat --> zammad and these can be replied by zammad as well. Therefore we have to define incoming & outgoing webhooks on both sides. 

Maybe there is an integration code for Rocket.Chat already and appreciate sharing howto get started. 

Thanks & Best regards, 
MC

**Comment by Hermsi1337** [comment]
Any news on this? A Rocket.Chat integration would be awesome.

**Comment by thorsteneckel** [comment]
Locking conversation. There is no new input. +1 and requesting comments create noise and distraction. We are working hard on the next upcoming/most requested features. If you want to state your interest in the feature and give valuable input please give the initial post a 👍 reaction and we are able to evaluate it. We will lock all distracting issues from now on. Thanks for your understanding.

**Comment by hanneshal** [comment]
Please see additional information for the REST API.

https://github.com/zammad/zammad/issues/1432

**Comment by thorsteneckel** [comment]
Hey there! It's been a while. I was reviewing the PR #2761 and talked to my colleagues about it. While doing so we found out that Zammad is actually perfectly capable of integrating RocketChat without any changes needed via the Slack integration. This comes from the fact that RocketChat is API compatible with Slack. However, this isn't very clear in the Zammad UI. Therefore we will enhance the text on the integration view (in Zammad), the documentation and our new feature browser over at https://zammad.com. Thanks for filling the gap @osallou !

**Comment by MrGeneration** [comment]
A small follow up on this topic as Andrew brought this to our attention.
OP has edited the first article some years ago and added the technical possibility to create tickets via slack / rocket chat directly.

This is a part that slipped through our fingers which is why we explicitly state it here now:
- ticket creation via rocket chat / slack is **not** possible
- this is currently not a planned functionality in our opinion

If you feel that this is a functionality you really need and want you have two options from this point:
- either you can contact our sales team for a custom development -OR-
- you can open a feature request on the community for voting if not existing already 
   ( https://community.zammad.org/c/Stuff-you-like-Zammad-to-have-Feel-free-to-discuss-and-add-proposals/6 )

We apologize for the confusion from our end.
