### ISSUE TITLE
Imported states from OTRS are not correctly mapped to Zammad states

### ISSUE THREAD

**Issue by ktwe** [zammad/zammad#890]
### Infos:

* Used Zammad version: 1.4.0
* Operating system: Ubuntu 16.04 LTS
* Browser + version: Google Chrome latest

### Expected behavior:

* Zammad should correctly map imported states to its own default states when importing from OTRS.
* E..g. Overview "open tickets" should show open tickets, not closed ones.

### Actual behavior:

* After importing from our OTRS 4 instance, the "Open" overview shows closed instead of open tickets. A deeper look into the definition of the Open overview showed up, that the filter is set to show all tickets having states "closed successful", "closed unsuccessful" and "new". (See attached screenshot).

### Steps to reproduce the behavior:

* Attached CSV file contains the content of our ticket_states and ticket_state_types table.

### Questions:
* Is it safe to just change the filters of the predefined overviews or are there more places in Zammad where states might be handled wrong?
* Is there any good workaround? E.g. changing the states to the Zammad default within the SQL database?
![2017-03-25 10_40_00-zammad helpdesk - overviews](https://cloud.githubusercontent.com/assets/7195773/24321320/dfd4bf34-1149-11e7-93f0-900f4f60c070.png)

**Comment by thorsteneckel** [comment]
Hi @ktwe - I have a theory for this:

Since we have to keep up the relations between different objects (like ticket and state) we keep using the OTRS object IDs. This may lead to the following scenario:

OTRS state "open" has the ID 4, Zammad state "closed" has the ID 4. So the import will update the Zammad state to be the new "open" state. Which is kind of bad since other settings (like e.g. the overview) are using rightfully the ID to store the states which now have other names (and so meanings) which cause this trouble.

I have to verify this first. I'll let you know.

Since I'm not fully aware of all cases which are affected by this I can't give you a workaround or solution yet.

**Comment by hiaz** [comment]
Hi,

First: Really cool product - All the "little things" I did not like in otrs are solved sooo pretty in zammad ;).

I've the same problem here. @ktwe I think it is not safe just to change the filters because some states have different functionality. E.g. "pending"-state shows a "pending till" field which is mapped to "closed unsuccessful" in my case.

**Comment by martini** [comment]
@thorsteneckel I did something in this direction: https://github.com/zammad/zammad/commit/55f17a226b39b71f087221e440d1b5186856c5f4

In other words, you need to "re-execute" the overview create to get the states in overviews with the correct values updated.

**Comment by ktwe** [comment]
Many thanks for your fast responses! How can I re-execute the overview creation?

**Comment by thorsteneckel** [comment]
Hi @ktwe - I think @martini hint was just from a technical nature. As @hiaz stated there are other side effects of this wrong state renaming stuff. I'm currently working on a fix for this but currently there is no workaround which wont cause other functions to fail. I'll let you know as soon as a fix is ready! Sorry for the circumstances.

**Comment by hiaz** [comment]
@thorsteneckel No reason to say sorry. This is a jung opensource project and you reacted as fast as possible even though most people involved did not sign a subscription, I guess (yet ;).

Back to the topic: Please also keep in mind that it is possible to create your own custom ticket states in OTRS. The good thing is that they have a defined type which can not be changed (in the gui at least). So it would be fine if you could migrate them as well in a proper way.

**Comment by thorsteneckel** [comment]
Hi @hiaz - This is fixed with the commit above in the 1.6 release of Zammad. Feedback would be great! Closing now.
