### ISSUE TITLE
OTRS Importer: more options for debug

### ISSUE THREAD

**Issue by hiaz** [zammad/zammad#895]
### Infos:

* Used Zammad version: 1.4
* Operating system: Ubuntu 16.4 LTS
* Browser + version: Chrome 56

### Scenario:

Import much data from OTRS (about 1/4 million articles). Sometimes the importer fails without a "meaningful" ERROR message. This is really hard to debug because on the one hand you don't know exactly which thread caused the error and on the other hand you always have to restart the import from the beginning and wait (in my case up to one hour) until you can see if the problem is fixed. 

### Solution

Maybe it would be a good idea to have two more options for the importer (maybe they already exists):

Offset: Zammad fetches data from OTRS in batches. There seems to be an offset for every batch wich starts with 0 for the first run. Maybe a user can predefine the first offset to save roundtrip time in a debug scenario.

Single-Thread: Sometimes it is really hard to see witch thread forced the importer to fail. Maybe a "single-thread" option is a good idea for debug.

**Comment by martini** [comment]
I also had some issue where OTRS did not server the requested data, because database was busy or there was a network issue and the http request did not return successful. 

This means the whole import stopped and I needed to restart the whole import again.

So Offset option would be very good.

Also a "re-try" count of http request would be useful to prevent stopping caused by temp. network or database issue would be fine.
