### ISSUE TITLE
Twitter DMs: long messages shown as link

### ISSUE THREAD

**Issue by derN3rd** [zammad/zammad#912]
### Infos:

* Used Zammad version: 1.4.0
* Operating system: Ubuntu 16.04
* Browser + version: Google Chrome 57.0.2987.110 (Official Build) (64-bit)

### Expected behavior:

* Twitter (Direct) Messages should be imported as normal message

### Actual behavior:

* Long dms are cut of and a t.co link is shown, which refers to the message on twitter.com
* Messages from Twitter are sorted randomly, not by time

### Steps to reproduce the behavior:

* Integrate support via twitter dm
* Send a very long message from another account
* Wait 'til zammad fetches newest dms

**Comment by derN3rd** [comment]
I think it is because of the changes on Twitter:
https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

Like said on this page, we only have to add tweet_mode=extended to the Rest request.
But I can't find the request in the code. (Also I'm new to ruby)

**Comment by thorsteneckel** [comment]
I'll have a look. Thanks for the report and the 'extended' hint. For the ref: https://github.com/sferik/twitter/issues/813

**Comment by thorsteneckel** [comment]
Hi @derN3rd - this is fixed in the upcoming release down to stable 1.3 with the commits above. The actual parameter was `full_text=true` instead of `tweet_mode=extended` for direct messages. Please don't ask why 🤓 Closing for now.

**Comment by GreXXL** [comment]
@thorsteneckel a quick question about this: for me it's "t.co" links everywhere. Is this the expected behaviour or should I be able to see the full tweet within zammad. It's quite strange as it is currently as you can never read a whole tween in zammad.

<img width="848" alt="bildschirmfoto 2018-04-21 um 14 40 03" src="https://user-images.githubusercontent.com/1630413/39084220-f894ce44-4571-11e8-9c61-9cc7b361322c.png">

**Comment by thorsteneckel** [comment]
@GreXXL - please create a new issue and fill out the issue template. Make sure you are using the latest version of Zammad. We will have a look as we find the time 👍
