### ISSUE TITLE
User/Customer management only show up 40 entries 

### ISSUE THREAD

**Issue by mensachan** [zammad/zammad#921]
### Infos:

* Used Zammad version: 1.4.0
* Operating system: Debian 8.7
* Browser + version: Chrome 57 (checked on FF as well)

### Expected behavior:

* User Management view in settings should show all existing Users or split them in Pages

### Actual behavior:

* Displays only 40 Users. Missing users can only be found via search box in this view or in global search

### Steps to reproduce the behavior:

* See Customer view in Settings

**Comment by sthag** [comment]
There 52 in the users management list but it is of course the same issue.
Would be great to have an overview over the total users to compare and edit them.
Would be also nice to have the possibility to group edit and select multiple users.

**Comment by MrGeneration** [comment]
I'm closing this issue as a duplicate in favor for issue https://github.com/zammad/zammad/issues/2214 .
Sorry, during the issue creation earlier from my end it slipped through my fingers.
Issue 2214 however has more details than this issue - which is why I believe it's the better issue to keep open.
