### ISSUE TITLE
HTML Table in email being re-formatted

### ISSUE THREAD

**Issue by abenrob** [zammad/zammad#930]
### Infos:

* Used Zammad version: 1.4
* Operating system: xenial + docker-compose (server OS...)
* Browser + version: Chrome for Ubuntu Version 57.0.2987.133 (64-bit)

### Expected behavior:

* HTML email able to be fully viewed

### Actual behavior:

* Zammad is converting HTML table (used in lieu of ul/li for email compatibility) into `<br>` + text

### Steps to reproduce the behavior:

* Send email containing HTML table to email channel, view message in Zammad

More details:
The original message contains a table like this;
```
<table cellpadding="2" cellspacing="2" border="0">
<tbody><tr>
<td valign="top">•</td>
<td>Use description: Do neat stuff</td>
</tr>
<tr>
<td valign="top">•</td>
<td>Regions: not defined</td>
</tr>
</tbody></table>
```
In zammad, this same content (when viewing source, is formatted:
```
<br>
 " • "
<br>
 " • "
```
Important to note that not only is the format changed, but the content is missing as well...

If I open the attached message.html, the formatting is intact, as it was in the original message, so this seems to be in the ticket view only.

**Comment by MartinBorg** [comment]
Zammad: 1.5.0-1492777259.6e8905
OS: Debian 8 Jessie
Browser: Firefox 52 on Debian 9 Stretch

The table is really messed up. I sent the table from
https://www.w3schools.com/html/html_tables.asp

|Company|Contact|Country|
|---|---|---|
|Alfreds Futterkiste|Maria Anders|Germany|
|...|...|...|

and Zammad changes it to:

Company Contact Country
Alfreds Futterkiste Germany

i.e. it removes the content of the middle column, but not its title.

Unfortunately, many people seem to think that sending (simple) tables in problem reports is a good idea.

**Comment by abenrob** [comment]
[If there’s only one thing you to know about coding email, it’s that tables rule the day.](https://templates.mailchimp.com/development/html/)
Inability to support tables in emails is a :-1:

**Comment by MartinBorg** [comment]
IMHO, the worst thing is, that parts of the table contents are removed. This is worse than not supporting tables at all, because it can lead to bad misunderstandings.

Shouldn't this ticket #930 be tagged as "bug", at least?

**Comment by martini** [comment]
> Shouldn't this ticket #930 be tagged as "bug", at least?

Yes. It's a bug. I tagged it.

**Comment by martini** [comment]
Hi,

in current development there is a view support for html tables (it's currently only in development because of many changes for html sanitizer).

Feedback is welcome!

 -Martin

Simple Table Example 1:
<img width="439" alt="screen shot 2017-04-28 at 11 24 55" src="https://cloud.githubusercontent.com/assets/110226/25523371/b24c75ca-2c06-11e7-93ec-5fd3c76d3565.png">

Simple Spam Table Example 2:
<img width="588" alt="screen shot 2017-04-28 at 11 10 25" src="https://cloud.githubusercontent.com/assets/110226/25523372/b274f824-2c06-11e7-98c7-a4b175bc2d29.png">

Complex Spam Table Example 3:
<img width="610" alt="screen shot 2017-04-28 at 11 10 43" src="https://cloud.githubusercontent.com/assets/110226/25523373/b2756ae8-2c06-11e7-85dd-c4e87864acd1.png">
