### ISSUE TITLE
Don't allow reopen a closed ticket over the gui

### ISSUE THREAD

**Issue by embeddedprojects** [zammad/zammad#933]
### Infos:

* Used Zammad version: newest
* Operating system: debian
* Browser + version: firefox

### Expected behavior:

* when a ticket is closed we won't that customer can reopen ticket over the web gui. Is there planed anything?

### Actual behavior:

* 

### Steps to reproduce the behavior:

*

**Comment by martini** [comment]
@embeddedprojects for me this is an bug (reopen is already prevented via email follow up). So it should have the same behaviour via web.

**Comment by embeddedprojects** [comment]
can you tell me on which place we have to fix it in the source?

or how we can easy disable the select field

**Comment by thorsteneckel** [comment]
There is an option called `follow_up_possible` on the group:

https://github.com/zammad/zammad/blob/e353e89c6df5e88d7f3bd43df96c7b6594358565/db/seeds/object_manager_attributes.rb#L1459

Which is evaluated for incoming emails:

https://github.com/zammad/zammad/blob/e353e89c6df5e88d7f3bd43df96c7b6594358565/app/models/channel/filter/follow_up_possible_check.rb#L13

But not considered in the frontend App or for direct API calls. This check is missing. Therefor there are two tasks at hand:

1.) Add API check:
There should be an `before_action :follow_up_possible_check, only: :update` check for the [ticket controller](https://github.com/zammad/zammad/blob/e353e89c6df5e88d7f3bd43df96c7b6594358565/app/controllers/tickets_controller.rb). This should check for a current state of the type `closed` and the `follow_up_possible` group option of the Ticket. If the Ticket is a closed type state and the `follow_up_possible` option is false the request should be canceled via an `Exceptions::UnprocessableEntity` (HTTP status code `422`) with an explaining error message.

2.) Disable form
The whole form should be disabled for non `@permissionCheck('ticket.agent')` (and `@permissionCheck('admin')` ?). Otherwise it will be irritating for customers if they can change the attributes but can't submit them. To prevent frustrations there should be a notification text that changes to this closed Ticket are not possible and a new Ticket should get created.
Please ask for implementation details to prevent unneeded actions.

Thanks for your support <3

**Comment by muhammadn** [comment]
@embeddedprojects this is improved in commit https://github.com/zammad/zammad/commit/4c38d7a719362a99122119624a338ea4ffba0925

You will need to set your Group in "follow up possible" to "do not reopen ticket but close ticket"
