### ISSUE TITLE
Title editing not so intuitive

### ISSUE THREAD

**Issue by AND51** [zammad/zammad#954]
### Infos:

* Used Zammad version: 1.4.x
* Operating system: hosted at zammad.com
* Browser + version: Vivaldi 1.8

### Expected behavior:

* Of course, you can edit the title of a ticket. But this is not advertised, because the title input field is not highlighted when hovering it with the mouse cursor. Even if the input field gets the focus, then it feels like "typing in midair".
* Please, add a visual effect for CSS pseudo classes :hover and :focus

### Actual behavior:

* The field is fully editable, but this is not visualized by a graphical effect. This might be related to #719 where @jacotec said, "it was not visible to me".

### Steps to reproduce the behavior:

* Edit the title of a ticket.

Zammad:
![screenshot-2017-04-15-224554](https://cloud.githubusercontent.com/assets/26226303/25067021/8cb0f60c-2237-11e7-823e-01c841e7a9ca.png)

Compare this to GitHub (when submitting an issue ;-) or to Zendesk.

Zendesk :hover
![screenshot-2017-04-15-234957](https://cloud.githubusercontent.com/assets/26226303/25067023/a8df6638-2237-11e7-9dcc-d200790c0561.png)

Zendesk :focus
![screenshot-2017-04-15-235014](https://cloud.githubusercontent.com/assets/26226303/25067029/b164d5e0-2237-11e7-984c-9b54d901faac.png)

**Comment by mrflix** [comment]
Good point André! Funny thing is: the effect is already there but its invisible because the background it changes too is the general background color. So the effect is only visible when its on a different color like in these cases where you might have see it before:
![screen shot 2017-04-27 at 11 29 29](https://cloud.githubusercontent.com/assets/60777/25477188/f76aaf7a-2b3c-11e7-966c-90ab29deab8b.png)
![screen shot 2017-04-27 at 11 29 36](https://cloud.githubusercontent.com/assets/60777/25477189/f76c026c-2b3c-11e7-9eee-a5f6a1dd20ec.png)
I darkened the background for this case. Thanks for reporting it!
