### ISSUE TITLE
Searching symbol

### ISSUE THREAD

**Issue by tobibe** [zammad/zammad#984]
### Infos:

* Used Zammad version: 1.4.0
* Operating system: Ubuntu 16.04.02
* Browser + version: Firefox + Chrome

![grafik](https://cloud.githubusercontent.com/assets/9305993/25334112/8b89fcbc-28ed-11e7-9b5b-74da236a88bb.png)

If I type something in the searchbar, sometimes it last a little bit and I feel a little uncertain if the search is finished and nothing found or if I have to wait a little more. And if you search for something not existing, you'll never get a response, that the search has finished, because the screen doesn't change in any way.

Maybe you could display a litte waiting symbol, while the search is running. And if there's nothing found, you could write that there is nothing found or the waiting symbol just disappears.

Greetings
tobibe

**Comment by dennykorsukewitz** [comment]
Hi @tobibe ,

this issue is solved: https://github.com/zammad/zammad/commit/0db8c28bd5

While the search is running you see this loading icon:
![issue984](https://user-images.githubusercontent.com/3249687/61126133-ee8b9a00-a4ab-11e9-875d-53e05968f4d4.gif)

If nothing was found then this will be displayed:

<img width="264" alt="Zammad_Helpdesk_-_Dashboard_und_Schreibtisch" src="https://user-images.githubusercontent.com/3249687/61126185-17ac2a80-a4ac-11e9-96d6-de7895ad83b3.png">

**Comment by thorsteneckel** [comment]
Fixed by: https://github.com/zammad/zammad/commit/0db8c28bd57b7cad7deb8d96e08c618dd34b8692

There was another issue of which this is a duplicate but I can't find it.
